### ISSUE TITLE
BTCPayServer can't connect to Azure Postgres.

### ISSUE THREAD

**Issue by monaka** [btcpayserver/btcpayserver#1101]
**Describe the problem/bug**

It becomes unable to connect My Postgres on Azure. Please see the log follows.
It was run with no issue before.

**Your environment**
* Version of BTCPay Server: btcpayserver/btcpayserver:1.0.3.135-amd64 (docker image)
* Deployment method: Helm chart (my original not released yet)
* Other relevant environment details:

**Logs (if applicable)**

Sensitive information was replaced to `{censored}`.

```
info: Configuration:  Postgres DB used (Server={censored}.postgres.database.azure.com;Database={censored};Port=5432;User Id={censored}@{censored};Password={censored};Ssl Mode=Require;)
fail: PayServer:      Error on the MigrationStartupTask
System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)

   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
```

**To Reproduce**
1. Bootups the container from `btcpayserver/btcpayserver:1.0.3.135-amd64`.
2. Watches the log.

**Expected behavior**

BTCPayServer boots up.

**Actual behavior**

Failed to boot it.

**Screenshots/Links**

None.

**Additional context**

I've already start trying to resolve it. I suspect this is a certification issue.

**Comment by monaka** [comment]
I can connect to Azure Postgres instance from the instance of `btcpayserver/btcpayserver:1.0.3.135-amd64` like logs. So certificates in /etc/ssl/ca-certificates will be sane.

```
/app # apk add postgres
/app # apk add postgresql
(1/11) Installing ncurses-terminfo-base (6.0_p20171125-r1)
(2/11) Installing ncurses-terminfo (6.0_p20171125-r1)
(3/11) Installing ncurses-libs (6.0_p20171125-r1)
(4/11) Installing libedit (20170329.3.1-r3)
(5/11) Installing db (5.3.28-r0)
(6/11) Installing libsasl (2.1.26-r11)
(7/11) Installing libldap (2.4.48-r0)
(8/11) Installing libpq (10.10-r0)
(9/11) Installing postgresql-client (10.10-r0)
(10/11) Installing libxml2 (2.9.8-r1)
(11/11) Installing postgresql (10.10-r0)
Executing busybox-1.27.2-r11.trigger
OK: 70 MiB in 40 packages
/app # psql 'host={censored}.postgres.database.azure.com dbname={censored} port=5432; user={censored}@{censored} password={censored} sslmode=require'
psql (10.10, server 9.6.15)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

{censored}=> 
```

**Comment by NicolasDorier** [comment]
there is nothing I can do here. Maybe you need the `ca-certificates` package on your distro.

**Comment by monaka** [comment]
@NicolasDorier Thank you for the response.
As I use your official image, `ca-certificates` was installed.
I supporse I can't connect to the server with `psql` if `ca-certificates` were broken.

**Comment by NicolasDorier** [comment]
Can you post an issue on https://github.com/npgsql/efcore.pg ?

The version we are using is `2.1.2`.

**Comment by monaka** [comment]
@NicolasDorier Finally I found an workaround.
My BTCPaySever boots up after adding `Trust Server Certificate=true` to the connection string.
It's weird but it works. This may the issue in Azure side, imo.
I close this as resolved.

I'll post to efcore if I got some more information about this issue.
Thank you for your kind support.

**Comment by NicolasDorier** [comment]
@monaka unsure what this flag does. But I fear that it exposes you to MitM attack.

**Comment by monaka** [comment]
@NicolasDorier thanks for your kind comment. Generally speaking, I agree it is risky. But just in my case, all components are in Azure VPC. So the risk is acceptable to me. :-)
