### ISSUE TITLE
BitPay Node.JS Client Library incompatibility

### ISSUE THREAD

**Issue by brunoaduarte** [btcpayserver/btcpayserver#113]
I tried to use the BitPay official Node.JS client with BTCPayServer but there seems to be some SSL incompatibility

https://support.bitpay.com/hc/en-us/articles/115003025486-How-do-I-configure-and-use-the-BitPay-Node-JS-Client-Library-

Here it works with "bitpay.com"

```
root@ubuntu:/home/ubuntu# bitpay config -u prod
root@ubuntu:/home/ubuntu# bitpay config -p
{ apiHost: 'bitpay.com', apiPort: 443, forceSSL: true }
root@ubuntu:/home/ubuntu# bitpay pair
Do you have a pairing code?
no

Okay, we can get a pairing code, please choose a facade:
  1) Point of Sale
  2) Merchant
  : 1

 Your token information:

 Client ID:     Tf9xifPzN..................................us3o7Ci
 Pairing Code:  Q.......k
 Label:         node-bitpay-client-ubuntu
 Facade:        pos


 Your pairing code will be available until: Thu Apr 12 2018 16:40:18 GMT-0300 (-03)


 Pair this client with another organization by giving an administrator this pairing code:
 Q.......k

 Pair this client with your organization:
 https://bitpay.com/api-access-request?pairingCode=Q.......k
```

Then i point the config settings to my local BTCPayServer (that is running perfectly)

```
root@ubuntu:/home/ubuntu# bitpay config -u BTCPayServer
root@ubuntu:/home/ubuntu# bitpay config -p
{ apiHost: '0.0.0.0', apiPort: '23000', forceSSL: 'false' }
```

But i get this error when trying to pair it
```
root@ubuntu:/home/ubuntu# bitpay pair
Do you have a pairing code?
no

Okay, we can get a pairing code, please choose a facade:
  1) Point of Sale
  2) Merchant
  : 1
Error: { Error: write EPROTO 140046275798848:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

    at _errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:880:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }
```

**Same problem when creating a simple custom NodeJS module "pay.js"**

```
var fs    = require("fs");
var bitpay = require('bitpay');
var privkey = fs.readFileSync('/root/.bitpay/api.key');
var client = bitpay.createClient(privkey);

client.on('ready', function() {
 client.get('invoices', function(err, invoices) {
 console.log(err || invoices);
 });
});

client.get('invoices', function(err, invoices) {
 if(invoices == undefined) {
   console.log('No invoices');
   return;
 };
 invoices[0].get('refunds', function(err, refunds) {
 console.log(err || refunds);
 });
});
```
**BitPay**
```
root@ubuntu:/home/ubuntu# bitpay config -u prod
root@ubuntu:/home/ubuntu# bitpay config -p
{ apiHost: 'bitpay.com', apiPort: 443, forceSSL: true }
root@ubuntu:/home/ubuntu# node pay.js
No invoices
events.js:188
      throw err;
      ^

Error: Unhandled "error" event. ([object Object])
    at RESTClient.emit (events.js:186:19)
    at /home/ubuntu/node_modules/bitpay/lib/rest-client.js:82:26
    at Request._callback (/home/ubuntu/node_modules/bitpay/lib/rest-client.js:173:40)
    at Request.self.callback (/home/ubuntu/node_modules/bitpay/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/ubuntu/node_modules/bitpay/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/ubuntu/node_modules/bitpay/node_modules/request/request.js:1085:12)
```

**BTCPayServer**
```
root@ubuntu:/home/ubuntu# bitpay config -u BTCPayServer
root@ubuntu:/home/ubuntu# bitpay config -p
{ apiHost: '0.0.0.0', apiPort: '23000', forceSSL: 'false' }
root@ubuntu:/home/ubuntu# node pay.js
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write EPROTO 139634823096128:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

    at _errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:880:14)
```

**Comment by brunoaduarte** [comment]
Problem solved, seems there's a "bug?" on node-bitpay-client "rest-client.js" on this portion of the code.

```
124    var useSSL       = (self.apiPort === 443 || self.options.config.forceSSL);
125    var protocol     = useSSL ? 'https:' : 'http:';
```

Even though i can debug and confirm "self.apiPort" is 23000, self.options.config.forceSSL is FALSE and consequentialy "useSSL" is FALSE. "protocol" always ended up as "HTTPS" (???). So i just hardcoded it to "http". 

Now it works.

**Comment by NicolasDorier** [comment]
So this is a bug only for HTTP server?
