### ISSUE TITLE
Invoices Screen not loading.  

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcpayserver#1166]
I loaded up v1.0.3.138 on my docker install, however the invoices screen for one of my stores now no longer loads. 

I believe it's related to adding Newtonsoft.Json.Linq based on the error message. 

https://github.com/btcpayserver/btcpayserver/commit/eb87d7cadc136271fe93789913cd3606cbb42286

Attached log output:

> 2019-11-16 20:09:00.197 +00:00 [ERR] Connection id "0HLRAPI43TDL8", Request id "0HLRAPI43TDL8:00000001": An unhandled exception was thrown by the application.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: 1. Path 'receivedTime', line 3, position 19.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsDateTimeOffset()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at BTCPayServer.Services.Invoices.InvoiceRepository.<>c__DisplayClass28_0.<ToEntity>b__0(PaymentData p) in /source/BTCPayServer/Services/Invoices/InvoiceRepository.cs:line 462
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at BTCPayServer.Services.Invoices.InvoiceRepository.ToEntity(InvoiceData invoice) in /source/BTCPayServer/Services/Invoices/InvoiceRepository.cs:line 450
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BTCPayServer.Services.Invoices.InvoiceRepository.GetInvoices(InvoiceQuery queryObject)
   at BTCPayServer.Controllers.InvoiceControllerAPI.GetInvoices(String token, Nullable`1 dateStart, Nullable`1 dateEnd, String orderId, String itemCode, String status, Nullable`1 limit, Nullable`1 offset) in /source/BTCPayServer/Controllers/InvoiceController.API.cs:line 78
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 56
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 31
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by bolatovumar** [comment]
Looks like the underlying JSON for your invoices got into malformed state somehow. Specifically, this error is caused by line [462](https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Services/Invoices/InvoiceRepository.cs#L462) in `InvoiceRepository.cs` where it attempts to deserialize a JSON string.

Not sure how it could get into this state.

**Comment by astupidmoose** [comment]
Fixed in v1.0.3.139

https://github.com/btcpayserver/btcpayserver/commit/27af96662fa23fd9ef633bb2366fb776cfa1089e
