### ISSUE TITLE
 RPC Error while broadcasting: RPC_TRANSACTION_ERROR General error during transaction submission Missing inputs

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1205]
**Describe the problem/bug**
When trying to spend from Ledger S with Vault I get the following error when trying to broadcast:
` RPC Error while broadcasting: RPC_TRANSACTION_ERROR General error during transaction submission Missing inputs`

I'm able to export as PSBT (Will provide PSBT files in private on request if needed) and there are no logs in console whatsoever. Since we moved Vault to Avalonia, I am not familiar where the logs are located.

**Your environment**
* Version of BTCPay Server: v1.0.3.144
* Deployment method: Docker
* Other relevant environment details: Ledger Nano S (Bitcoin App 1.3.16, Secure Element 1.6.0, Microconroller 1.11), Vault 0.0.9

**Logs (if applicable)**
```
### NBX
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HLRLP8HMP23C", Request id "0HLRLP8HMP23C:0002CEC0": An unhandled exception was thrown by the application.
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at NBitcoin.RPC.RPCClient.SendCommandAsyncCore(RPCRequest request, Boolean throwIfRPCError)
   at NBitcoin.RPC.RPCClient.SendCommandAsync(RPCRequest request, Boolean throwIfRPCError)
   at NBXplorer.RPCClientExtensions.GetBlockchainInfoAsyncEx(RPCClient client) in /source/NBXplorer/RPCClientExtensions.cs:line 80
   at NBXplorer.Controllers.MainController.GetStatus(String cryptoCode) in /source/NBXplorer/Controllers/MainController.cs:line 278
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Screenshots/Links**
![Screenshot 2019-12-02 at 21 37 39](https://user-images.githubusercontent.com/36959754/69993731-b49b5d00-154c-11ea-9685-006e5370ec72.png)

Could be related to #1170 but I doubt.

**Comment by pavlenex** [comment]
Could be related to [this](https://github.com/MetacoSA/NBitcoin/issues/520) as I trashed my bitcoind due to the [error with c-lightning](https://github.com/ElementsProject/lightning/issues/3302) and then re-synced with FastSync from scratch.

No idea how to solve this besides trying another wallet/server.

**Comment by NicolasDorier** [comment]
this error basically mean you are double spending a coin.

**Comment by pavlenex** [comment]
This was fixed by re-scanning the wallet on another btcpay server and signing. It seems the server I tried this to, has not fetched the UTXO.

Thanks for the help Nicolas. 👍

**Comment by NicolasDorier** [comment]
Closing this the workaround was to restore the wallet via rescan on another btpcayserver and get the money out.

**Comment by NicolasDorier** [comment]
The error probably happened because the scan was done on an old UTXO set when the node was not fully synched.
