### ISSUE TITLE
[Vault] UX - Provide better warrning messages when device is asleep (app not opened)

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1208]
**Describe the problem/bug**

When users try to sign with vault, we immediately assume their device will be ready to sign. For some wallets like Ledger Nano S, users have to open Bitcoin app, and we can't expect them to do that. 

Now unless the device is awake, we give people 4-5 seconds before we invalidate it, without providing any sort of indicator what they need to do. ` An unexpected error happened. ` is not a user-friendly message. When this happens:

```
TCPayServer.Hwi.HwiException: Device is asleep
   at BTCPayServer.Hwi.HwiClient.SendCommandCoreAsync(DeviceSelector deviceSelector, IEnumerable`1 options, Nullable`1 command, String[] commandArguments, CancellationToken cancellationToken)
   at BTCPayServer.Hwi.HwiClient.SendCommandAsync(DeviceSelector deviceSelector, IEnumerable`1 options, Nullable`1 command, String[] commandArguments, CancellationToken cancel)
   at BTCPayServer.Hwi.HwiClient.SendCommandAsync(DeviceSelector deviceSelector, IEnumerable`1 options, Nullable`1 command, String[] commandArguments, CancellationToken cancel)
   at BTCPayServer.Hwi.HwiDeviceClient.GetXPubAsync(KeyPath keyPath, CancellationToken cancellationToken)
   at BTCPayServer.Controllers.VaultController.VaultBridgeConnection(String cryptoCode, WalletId walletId) in /source/BTCPayServer/Controllers/VaultController.cs:line 114 vaultbridge.ui.js:95:37
```

We give this:

![Screenshot 2019-12-02 at 22 24 19](https://user-images.githubusercontent.com/36959754/69996567-9e909b00-1552-11ea-9a89-1faaacac058c.png)

**Your environment**
* Version of BTCPay Server: v1.0.3.144
*  Deployment method: Docker
* Other relevant environment details: Vault 0.0.9, MacOS

I propose that we:
1. Give people more time before we invalidate the submission. 
2. Provide message what is expected from them to do 
3. Provide message in case of an error
4. Refresh that page on error somehow, since right now if the user tries to enter anything, he has to manually refresh the page in order submission to be valid.

**Comment by NicolasDorier** [comment]
Can you give a try? It will still put unknown error but more details.

**Comment by pavlenex** [comment]
Yes, definitely looks better now, we'll see the users feedback and can work on perfecting the error messages, but imo this one is clear enough for now, thanks.
