### ISSUE TITLE
[Vault] Trezor One - This device can't sign the transaction

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1209]
**Describe the problem/bug**
This report comes from one of our community members who tried to use vault with Trezor One.

User tried multiple times, unplugged device, no luck. This happens as soon as he enters the Pin, I was unable to replicate the error on my end.

**Your environment**
* Version of BTCPay Server:  v1.0.3.144
* Deployment method: Docker
* Other relevant environment details: Chrome, Trezor One, MacOS, Vault 0.0.9

**Logs (if applicable)**
#### Console logs 
```
main-bundle.min.js?v=vYOklYYgePzdhhaFkIlfTbkWhNe3db6WL7nxg0DDmpc:39 Uncaught TypeError: Cannot read property 'jquery' of null
    at new t (main-bundle.min.js?v=vYOklYYgePzdhhaFkIlfTbkWhNe3db6WL7nxg0DDmpc:39)
    at n.f.toggle (main-bundle.min.js?v=vYOklYYgePzdhhaFkIlfTbkWhNe3db6WL7nxg0DDmpc:51)
    at HTMLButtonElement.<anonymous> (main-bundle.min.js?v=vYOklYYgePzdhhaFkIlfTbkWhNe3db6WL7nxg0DDmpc:51)
    at Function.each (main-bundle.min.js?v=vYOklYYgePzdhhaFkIlfTbkWhNe3db6WL7nxg0DDmpc:14)
    at i.fn.init.each (main-bundle.min.js?v=vYOklYYgePzdhhaFkIlfTbkWhNe3db6WL7nxg0DDmpc:14)
    at i.fn.init.n._jQueryInterface [as dropdown] (main-bundle.min.js?v=vYOklYYgePzdhhaFkIlfTbkWhNe3db6WL7nxg0DDmpc:51)
    at HTMLButtonElement.<anonymous> (main-bundle.min.js?v=vYOklYYgePzdhhaFkIlfTbkWhNe3db6WL7nxg0DDmpc:51)
    at HTMLDocument.dispatch (main-bundle.min.js?v=vYOklYYgePzdhhaFkIlfTbkWhNe3db6WL7nxg0DDmpc:14)
    at HTMLDocument.a.handle (main-bundle.min.js?v=vYOklYYgePzdhhaFkIlfTbkWhNe3db6WL7nxg0DDmpc:14)
```
#### BTCPay logs
```
at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 75
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 31
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsTContext
2019-12-02 20:59:01.781 +00:00 [ERR] Connection id "0HLRND8RUTFQB", Request id "0HLRND8RUTFQB:00000001": An unhandled exception was thrown by the application.
NBXplorer.Models.NBXplorerException: The RPC interface is currently not available.
   at NBXplorer.ExplorerClient.ParseResponseT
   at NBXplorer.ExplorerClient.SendAsyncT
   at BTCPayServer.Services.Fees.NBXplorerFeeProvider.GetFeeRateAsync(Int32 blockTarget) in /source/BTCPayServer/Services/Fees/NBxplorerFeeProvider.cs:line 43
   at BTCPayServer.Controllers.WalletsController.WalletSend(WalletId walletId, String defaultDestination, String defaultAmount) in /source/BTCPayServer/Controllers/WalletsController.cs:line 317
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
```
![Screenshot 2019-12-03 at 00 16 10](https://user-images.githubusercontent.com/36959754/70003019-2336e580-1562-11ea-9bba-dd6f12f6a29e.png)

**Comment by pavlenex** [comment]
After some more troubleshooting, the user had a non-standard derivation path m/49'/0'/4'/0/ which could be the issue here.

**Comment by NicolasDorier** [comment]
@pavlenex if he uses `m/49'/0'/4'/0` he need to set it up in the Wallet Settings.

**Comment by NicolasDorier** [comment]
argh, I tagged the wrong issue

**Comment by pavlenex** [comment]
> @pavlenex if he uses `m/49'/0'/4'/0` he need to set it up in the Wallet Settings.

How can a regular user know this? It's such a hidden thing. Why don't we just add account drop-down like we have for native Ledger integration?
