### ISSUE TITLE
NBXplorer has been stuck for a week on ltc, and btc "the node is starting"

### ISSUE THREAD

**Issue by nsx077** [btcpayserver/btcpayserver#1215]
**Describe the problem/bug**
LTC NBXplorer synchronizing on popup screen has been stuck at same block for three weeks.
BTC will say nbxplorer is at height 9 and the node is starting for hours, than eventually node will start to sync, but nbxplorer is not changing block height.

**Your environment**
* Version of BTCPay Server: 1.0.3.144
* Deployment method: docker / own hardware
* Other relevant environment details: 

**Logs (if applicable)**
019-12-05 00:02:01.193 +00:00 [ERR] BTC: NBXplorer error `Connection refused`
2019-12-05 00:02:03.525 +00:00 [ERR] LTC: NBXplorer error `Connection refused`
2019-12-05 00:02:06.653 +00:00 [INF] NBXplorer BTC: Synching => NotConnected
2019-12-05 00:02:06.653 +00:00 [INF] NBXplorer LTC: Synching => NotConnected
2019-12-05 00:02:06.657 +00:00 [ERR] BTC: NBXplorer error `Connection refused`
2019-12-05 00:02:06.658 +00:00 [ERR] LTC: NBXplorer error `Connection refused`
2019-12-05 00:03:06.664 +00:00 [ERR] BTC: NBXplorer error `Connection refused`
2019-12-05 00:03:06.666 +00:00 [ERR] LTC: NBXplorer error `Connection refused`
2019-12-05 00:03:18.367 +00:00 [INF] CssThemeManagerHostedService successfully exited...
2019-12-05 00:03:19.852 +00:00 [INF] CheckConfigurationHostedService successfully exited...
2019-12-05 00:03:20.519 +00:00 [INF] NBXplorerListener successfully exited...
2019-12-05 00:03:27.372 +00:00 [INF] LightningListener successfully exited...
2019-12-05 00:03:28.178 +00:00 [INF] Stop watching invoices
2019-12-05 00:03:29.415 +00:00 [INF] RatesHostedService successfully exited...
2019-12-05 00:03:38.310 +00:00 [INF] DynamicDnsHostedService successfully exited...
2019-12-05 00:03:38.310 +00:00 [INF] TorServicesHostedService successfully exited...
2019-12-05 00:36:06.270 +00:00 [INF] BTC: Explorer url is http://nbxplorer:32838/
2019-12-05 00:36:06.376 +00:00 [INF] BTC: Cookie file is /root/.nbxplorer/Main/.cookie
2019-12-05 00:36:06.696 +00:00 [INF] LTC: Explorer url is http://nbxplorer:32838/
2019-12-05 00:36:06.703 +00:00 [INF] LTC: Cookie file is /root/.nbxplorer/Main/.cookie
2019-12-05 00:36:08.676 +00:00 [INF] SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
2019-12-05 00:36:08.821 +00:00 [INF] Starting listening NBXplorer (BTC)
2019-12-05 00:36:09.581 +00:00 [INF] Starting listening NBXplorer (LTC)
2019-12-05 00:36:09.646 +00:00 [INF] Start watching invoices
2019-12-05 00:36:13.586 +00:00 [INF] Starting payment request expiration watcher
2019-12-05 00:36:19.220 +00:00 [INF] NBXplorer LTC: NotConnected => Synching
2019-12-05 00:36:19.240 +00:00 [INF] NBXplorer BTC: NotConnected => Synching
2019-12-05 00:36:19.375 +00:00 [INF] 0 pending payment requests being checked since last run
2019-12-05 00:36:20.925 +00:00 [INF] SSH connection succeeded
2019-12-05 00:36:22.306 +00:00 [WRN] Error while contacting poloniex: The operation has timed out.
2019-12-05 00:36:22.306 +00:00 [WRN] Error while contacting binance: The operation has timed out.
2019-12-05 00:36:22.308 +00:00 [WRN] Error while contacting bittrex: The operation has timed out.
2019-12-05 00:36:22.309 +00:00 [WRN] Error while contacting ndax: The operation has timed out.
2019-12-05 00:36:22.310 +00:00 [WRN] Error while contacting hitbtc: The operation has timed out.
2019-12-05 02:34:57.190 +00:00 [ERR] An exception occurred in the database while iterating the results of a query for context type 'BTCPayServer.Data.ApplicationDbContext'.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSectionAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSectionAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
2019-12-05 02:34:59.838 +00:00 [ERR] Connection id "0HLRP5DCSI8HD", Request id "0HLRP5DCSI8HD:00000001": An unhandled exception was thrown by the application.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSectionAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByEmailAsync(String email)
   at BTCPayServer.Controllers.AccountController.Login(LoginViewModel model, String returnUrl) in /source/BTCPayServer/Controllers/AccountController.cs:line 107
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 75
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 31
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2019-12-05 02:35:08.254 +00:00 [INF] User logged in..

![Annotation 2019-12-04 193854](https://user-images.githubusercontent.com/58539022/70199169-3e266880-16ce-11ea-8ff0-3a12ccd246c7.png)

![Annotation 2019-12-04 193955](https://user-images.githubusercontent.com/58539022/70199194-4d0d1b00-16ce-11ea-8444-da88c6d4869b.png)

**Comment by pavlenex** [comment]
Related to #904

**Comment by bolatovumar** [comment]
Sometimes restarting the server helps. I had this issue at some point as well (with BTC) and eventually it went away after a server restart.

**Comment by Eskyee** [comment]
yes rebooting the server can solve  this error, as @bolatovumar said above

**Comment by Eskyee** [comment]
btcpay-restart.sh , not always fix the problem, but a reboot does I find. @NicolasDorier

**Comment by morphologics** [comment]
I have the same problem. 
Rebooted server numerous times but same result.
NBXplorer reports: "The node is not in a connected state" 
blockinfo block_height is showing the node is fully synced.
`
Dec 14 04:59:13 ubuntu18 run.sh[1347]: info: Configuration:  BTC: Testing RPC connection to http://localhost:8332/
Dec 14 04:59:13 ubuntu18 run.sh[1347]: info: Configuration:  BTC: RPC connection successful
Dec 14 04:59:13 ubuntu18 run.sh[1347]: info: Configuration:  BTC: Full node version detected: 180000
Dec 14 04:59:13 ubuntu18 run.sh[1347]: info: Configuration:  BTC: Loading chain from cache...
Dec 14 04:59:14 ubuntu18 run.sh[1347]: info: Configuration:  BTC: Height: 604889
Dec 14 04:59:14 ubuntu18 run.sh[1347]: info: Configuration:  BTC: Trying to connect via the P2P protocol to trusted node (127.0.0.1:8333)...
Dec 14 04:59:14 ubuntu18 run.sh[1347]: info: Explorer:       BTC: TCP Connection succeed, handshaking...
Dec 14 04:59:14 ubuntu18 run.sh[1347]: fail: Configuration:  BTC: Unhandled in Waiter loop
Dec 14 04:59:14 ubuntu18 run.sh[1347]: System.OperationCanceledException: Loading the chain from the node timed out
Dec 14 04:59:14 ubuntu18 run.sh[1347]:  ---> System.InvalidOperationException: The node is not in a connected state
`

**Comment by NicolasDorier** [comment]
@morphologics given the error, I would suspect you have not whitelisted nbxplorer to your node.

**Comment by morphologics** [comment]
didn't change my bitcoin.conf which as the localhost whitelisted:

mainnet=1
server=1                              # need RPC for btcpay.
rpcbind=127.0.0.1                     # loopback is default for 0.18.0 but no harm making sure.
whitelist=127.0.0.1                   # for nbxplorer.
rpcallowip=127.0.0.1/32               # loopback is default but again no harm.
disablewallet=1                       # btcpay does not host a bitcoin wallet.
zmqpubrawblock=tcp://127.0.0.1:28332  # needed for lightning.
zmqpubrawtx=tcp://127.0.0.1:28333     # needed for lightning.


# [network]
# Maintain at most N connections to peers.
maxconnections=8
# Tries to keep outbound traffic under the given target (in MiB per 24h), 0 = no limit.
maxuploadtarget=1200

**Comment by NicolasDorier** [comment]
@morphologics mmh I have no idea, nothing in debug logs of bitcoind? you tried to add verbose logs there?

**Comment by morphologics** [comment]
I mistakenly upgraded .NET to 3.1.100 on that server and see that MS made some breaking changes related to OAuth etc.. (see https://docs.microsoft.com/en-us/dotnet/core/compatibility/2.2-3.1)

But i thought apps would specify which .NET version to use so thought it wouldn't break anything.  
Not sure if it's related but i noticed build.sh for btcpayserver issues warnings which i had ignored: 
`): warning NETSDK1071: A PackageReference to 'Microsoft.AspNetCore.App' specified a Version of `2.1.14`. Specifying the version of this package is not recommended. For more information, see https://aka.ms/sdkimplicitrefs [/home/vma/src/btcpayserver/BTCPayServer.Common/BTCPayServer.Common.csproj]`

Could it be a version compatibility issue?
I don't yet know how to downgrade or force NBXplorer to run on version 2.2,
and maybe this is irrelevant anyway?

**Comment by Kukks** [comment]
AFAIK nbx is already upgraded to 3.1. That warning is nothing serious

**Comment by NicolasDorier** [comment]
You can ignore the warning.

**Comment by NicolasDorier** [comment]
I should have fixed that on nbxplorer weeks ago. Can you update?

**Comment by NicolasDorier** [comment]
Marking for closing as it should be fixed by now, if you don't come back in 7 days, will close

**Comment by morphologics** [comment]
I discovered the sync failure in my case was dependant on the upload bandwidth throttling parameter I added to bitcoin.conf: 

`maxuploadtarget=1200`

That has the desired effect in bitcoind but a side effect is that it causes RPC auth to fail when NBXplorer attempts set up it's connection. 

I didn't investigate why that happens and simply opted to remove the upload limit parameter to get btcpay working. It means my Azure bill goes back up $20 per month for upload bandwidth which i had successfully avoided by using that throttling value. The BTC node was syncing fine for 3 weeks using that restricted upload but NBXplorer couldn't sync. Appears to be a weird bug in bitcoind related but this combination of settings and RPC auth? (but I don't know anything about bitcoind)

I think error logging in NBXplorer should be improved to clearly show the authentication failure. It isn't obvious. 

see BitcoinDWaiter.cs line 439+

`								try
								{
									Logs.Explorer.LogInformation($"{Network.CryptoCode}: TCP Connection succeed, handshaking...");
									node.VersionHandshake(handshakeTimeout.Token);
									Logs.Explorer.LogInformation($"{Network.CryptoCode}: Handshaked");
								}
								catch (OperationCanceledException) when (handshakeTimeout.IsCancellationRequested)
								{
									Logs.Explorer.LogWarning($"{Network.CryptoCode}: NBXplorer could not complete the handshake with the remote node. This is probably because NBXplorer is not whitelisted by your node.{Environment.NewLine}" +
										$"You can use \"whitebind\" or \"whitelist\" in your node configuration. (typically whitelist=127.0.0.1 if NBXplorer and the node are on the same machine.){Environment.NewLine}" +
										$"This issue can also happen because NBXplorer do not manage to connect to the P2P port of your node at all.");
									throw;
								}
								handshaked = true;
`

The auth fails without logging the warning "NBXplorer could not complete the handshake with the remote node. "

btcoind did issue a one word inline log snippet about failure but that is easily overlooked in this scenario. 

The code doesn't reach 
`Logs.Explorer.LogInformation($"{Network.CryptoCode}: Handshaked");`
and also doesn't issue the error.

**Comment by NicolasDorier** [comment]
@morphologics I advise you against hosting bitcoin core and nbxplorer on different machine. Also exposing Bitcoin RPC on internet is dangerous.

If you host nbx and bitcoin core on the same machine, this would solve completely the problem.

That said, most of the traffic in bitcoind is transaction propagation, which you can control by limiting the number of connection (by default 8). If you set that to 4, you should have twice less traffic. I don't remember the command line arg.

**Comment by NicolasDorier** [comment]
Made this commit https://github.com/dgarage/NBXplorer/commit/6bd8e6f210af0c800cc5447dcbd7ac3ce503bc5e?w=1

**Comment by morphologics** [comment]
It's all running on one machine.
Just now applied your updated and 
PR from yesterday with upgrade to error logging and tested with the bitcoind bandwidth throttling enabled.
NBXplorer now connects fine without errors.
Cool!
and much love...

**Comment by NicolasDorier** [comment]
Closing this issue then
