### ISSUE TITLE
Failed build on Ubuntu 19.10

### ISSUE THREAD

**Issue by shawnyeager** [btcpayserver/btcpayserver#1257]
**Describe the problem/bug**
Build fails

**Your environment**
* Version of BTCPay Server: v1.0.3.146
* Deployment method: build from source on Ubuntu 19.10
* Other relevant environment details: both 2.1.x and 3.1.x (current release) .Net SDKs installed

**To Reproduce**
1. `git clone https://github.com/btcpayserver/btcpayserver.git`
2. `cd btcpayserver`
3. `sudo ./build.sh`
4. See output below

**Build output from `sudo ./build.sh`**

```
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 162.96 ms for /home/shawn/btcpayserver/BTCPayServer.Rating/BTCPayServer.Rating.csproj.
  Restore completed in 162.92 ms for /home/shawn/btcpayserver/BTCPayServer/BTCPayServer.csproj.
  Restore completed in 162.94 ms for /home/shawn/btcpayserver/BTCPayServer.Data/BTCPayServer.Data.csproj.
  Restore completed in 162.95 ms for /home/shawn/btcpayserver/BTCPayServer.Common/BTCPayServer.Common.csproj.
/usr/share/dotnet/sdk/3.1.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.DefaultItems.targets(189,5): warning NETSDK1071: A PackageReference to 'Microsoft.AspNetCore.App' specified a Version of `2.1.14`. Specifying the version of this package is not recommended. For more information, see https://aka.ms/sdkimplicitrefs [/home/shawn/btcpayserver/BTCPayServer.Rating/BTCPayServer.Rating.csproj]
/usr/share/dotnet/sdk/3.1.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.DefaultItems.targets(189,5): warning NETSDK1071: A PackageReference to 'Microsoft.AspNetCore.App' specified a Version of `2.1.14`. Specifying the version of this package is not recommended. For more information, see https://aka.ms/sdkimplicitrefs [/home/shawn/btcpayserver/BTCPayServer.Common/BTCPayServer.Common.csproj]
  BTCPayServer.Data -> /home/shawn/btcpayserver/BTCPayServer.Data/bin/Release/netcoreapp2.1/BTCPayServer.Data.dll
  BTCPayServer.Common -> /home/shawn/btcpayserver/BTCPayServer.Common/bin/Release/netcoreapp2.1/BTCPayServer.Common.dll
  BTCPayServer.Rating -> /home/shawn/btcpayserver/BTCPayServer.Rating/bin/Release/netcoreapp2.1/BTCPayServer.Rating.dll
  
  Bundler: Begin processing bundleconfig.json

Build FAILED.

/usr/share/dotnet/sdk/3.1.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.DefaultItems.targets(189,5): warning NETSDK1071: A PackageReference to 'Microsoft.AspNetCore.App' specified a Version of `2.1.14`. Specifying the version of this package is not recommended. For more information, see https://aka.ms/sdkimplicitrefs [/home/shawn/btcpayserver/BTCPayServer.Rating/BTCPayServer.Rating.csproj]
/usr/share/dotnet/sdk/3.1.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.DefaultItems.targets(189,5): warning NETSDK1071: A PackageReference to 'Microsoft.AspNetCore.App' specified a Version of `2.1.14`. Specifying the version of this package is not recommended. For more information, see https://aka.ms/sdkimplicitrefs [/home/shawn/btcpayserver/BTCPayServer.Common/BTCPayServer.Common.csproj]
    2 Warning(s)
    0 Error(s)

Time Elapsed 00:00:05.31
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: ContextID 32 should have been in the ID-to-project file mapping but wasn't!
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Object[] args)
   at Microsoft.Build.BackEnd.Logging.LoggingService.GetAndVerifyProjectFileFromContext(BuildEventContext context)
   at Microsoft.Build.BackEnd.Logging.LoggingService.LogBuildEvent(BuildEventArgs buildEvent)
   at Microsoft.Build.BackEnd.TaskHost.LogErrorEvent(BuildErrorEventArgs e)
   at Microsoft.Build.Utilities.TaskLoggingHelper.LogError(String subcategory, String errorCode, String helpKeyword, String file, Int32 lineNumber, Int32 columnNumber, Int32 endLineNumber, Int32 endColumnNumber, String message, Object[] messageArgs)
   at BundlerMinifier.BundlerBuildTask.BundleMinifier_ErrorMinifyingFile(Object sender, MinifyFileEventArgs e)
   at BundlerMinifier.BundleMinifier.OnErrorMinifyingFile(MinificationResult result)
   at BundlerMinifier.BundleMinifier.MinifyBundle(Bundle bundle)
   at BundlerMinifier.BundleFileProcessor.ProcessBundle(String baseFolder, Bundle bundle)
   at BundlerMinifier.BundleFileProcessor.Process(String fileName, IEnumerable`1 bundles)
   at BundlerMinifier.BundlerBuildTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
   at Microsoft.Build.BackEnd.TaskBuilder.InitializeAndExecuteTask(TaskLoggingContext taskLoggingContext, ItemBucket bucket, IDictionary`2 taskIdentityParameters, TaskHost taskHost, TaskExecutionMode howToExecuteTask)
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteBucket(TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask, Dictionary`2 lookupHash)
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteTask(TaskExecutionMode mode, Lookup lookup)
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteTask(TargetLoggingContext loggingContext, BuildRequestEntry requestEntry, ITargetBuilderCallback targetBuilderCallback, ProjectTargetInstanceChild taskInstance, TaskExecutionMode mode, Lookup inferLookup, Lookup executeLookup, CancellationToken cancellationToken)
   at Microsoft.Build.BackEnd.TargetEntry.ProcessBucket(ITaskBuilder taskBuilder, TargetLoggingContext targetLoggingContext, TaskExecutionMode mode, Lookup lookupForInference, Lookup lookupForExecution)
   at Microsoft.Build.BackEnd.TargetEntry.ExecuteTarget(ITaskBuilder taskBuilder, BuildRequestEntry requestEntry, ProjectLoggingContext projectLoggingContext, CancellationToken cancellationToken)
   at Microsoft.Build.BackEnd.TargetBuilder.ProcessTargetStack(ITaskBuilder taskBuilder)
   at Microsoft.Build.BackEnd.TargetBuilder.BuildTargets(ProjectLoggingContext loggingContext, BuildRequestEntry entry, IRequestBuilderCallback callback, String[] targetNames, Lookup baseLookup, CancellationToken cancellationToken)
   at Microsoft.Build.BackEnd.RequestBuilder.BuildProject()
   at Microsoft.Build.BackEnd.RequestBuilder.BuildAndReport()
   at Microsoft.Build.BackEnd.RequestBuilder.RequestThreadProc(Boolean setThreadParameters)

MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: ContextID 32 should have been in the ID-to-project file mapping but wasn't!
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, Boolean graphBuild, String[] inputResultsCaches, String outputResultsCache)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
```

**Comment by pavlenex** [comment]
19.10 does not support docker last time I tried, try a different Ubuntu, 18. or lower.

**Comment by shawnyeager** [comment]
Thanks. I’m not using Docker.

**Comment by bolatovumar** [comment]
@shawnyeager the problem seems to be that you are using .NET Core v3.1.100. BTCPay runs on .NET Core v2.1.x

**Comment by shawnyeager** [comment]
Thanks, @bolatovumar. I do have both installed, as noted in the issue. I assumed (incorrectly?) that multiple versions can co-exist, and btcpayserver should still build correctly.

**Comment by bolatovumar** [comment]
@shawnyeager multiple versions can co-exist just fine. You just need a `global.json` file which will tell BTCPay Server which version to use. See here: https://docs.microsoft.com/en-us/dotnet/core/tools/global-json

**Comment by shawnyeager** [comment]
Thanks again, @bolatovumar. I did so, and am able to build successfully. However, I see the following as output from `./run.sh`:

```
Error:
  An assembly specified in the application dependencies manifest (BTCPayServer.deps.json) was not found:
    package: 'AWSSDK.Core', version: '3.3.21.19'
    path: 'lib/netstandard1.3/AWSSDK.Core.dll'
```

**Comment by bolatovumar** [comment]
@shawnyeager not sure what that error is but it looks like it's a dependency that for some reason requires .NET Core 3.1 which BTCPay currently does not run on. Maybe @NicolasDorier can shed some light on this.

**Comment by shawnyeager** [comment]
Update: using `sudo ./run.sh` resolves the above problem.

**Comment by NicolasDorier** [comment]
Now BTCPayServer is using .NET Core 3.1.

I think your problem was that you ran `run.sh` without `build.sh`

**Comment by NicolasDorier** [comment]
or maybe a problem with an old build, which can be solved by dumping the obj and bin folders

**Comment by shawnyeager** [comment]
Thanks. New release is working for me.
