### ISSUE TITLE
Sporadic "Resource temporarily unavailable" error

### ISSUE THREAD

**Issue by AryanJ-NYC** [btcpayserver/btcpayserver#1590]
**Describe the problem/bug**
It seems very randomly that the btcpayserver shuts down due to the error stack below.

**Your environment**
* Version of BTCPay Server: v1.0.4.4
* Deployment method: btcpayserver-docker

**Logs (if applicable)**
```
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000001, 11): Resource temporarily unavailable
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.ResolveCallback(Object context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.TaskExtensions.WithCancellation[T](Task`1 task, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.ConnectorPool.AllocateLong(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at BTCPayServer.Services.DelayedTransactionBroadcaster.ProcessAll(CancellationToken cancellationToken) in /source/BTCPayServer/Services/DelayedTransactionBroadcaster.cs:line 73
   at BTCPayServer.HostedServices.DelayedTransactionBroadcasterHostedService.Rebroadcast() in /source/BTCPayServer/HostedServices/DelayedTransactionBroadcasterHostedService.cs:line 35
   at BTCPayServer.HostedServices.BaseAsyncService.CreateLoopTask(Func`1 act, String caller) in /source/BTCPayServer/HostedServices/BaseAsyncService.cs:line 43
2020-05-21 21:55:15.717 +00:00 [ERR] Error while connecting to WebSocket of NBXplorer (BTC)
System.Net.WebSockets.WebSocketException (215): The socket has been closed (NormalClosure: Close message received from the peer)
   at NBXplorer.WebsocketMessageListener.CloseSocketAndThrow(WebSocketCloseStatus status, String description, CancellationToken cancellation)
   at NBXplorer.WebsocketMessageListener.NextMessageAsync(CancellationToken cancellation)
   at BTCPayServer.Payments.Bitcoin.NBXplorerListener.Listen(BTCPayWallet wallet) in /source/BTCPayServer/Payments/Bitcoin/NBXplorerListener.cs:line 142
```

**To Reproduce**
Happens sporadically

**Expected behavior**
No error happens and btcpayserver stays up.

**Actual behavior**
btcpayserver sometimes shuts down due to this error.

**Additional context**
https://github.com/npgsql/efcore.pg/issues/619 looks very similar.

**Comment by AryanJ-NYC** [comment]
I'm now thinking https://github.com/lightningnetwork/lnd/issues/3370 is the cause.

**Comment by cfromknecht** [comment]
Seems possible that it could be related to https://github.com/btcpayserver/btcpayserver-doc/issues/716
