### ISSUE TITLE
Exception when creating Payjoin-enabled invoice

### ISSUE THREAD

**Issue by Kixunil** [btcpayserver/btcpayserver#1608]
**Describe the problem/bug**
When creating Payjoin invoice, the code throws exception and doesn't redirect/show the invoice even though the invoice looks fin in the list.

**Your environment**
* Version of BTCPay Server: 1.0.4.2
* Deployment method: [Debian repository](https://github.com/Kixunil/cryptoanarchy-deb-repo-builder) (Looks like it has nothing to do with deployment, but not sure, see the end of report)
* Other relevant environment details: latest NBXplorer version; latest Bitcoin Core, btc-rpc-proxy with all calls whitelisted (even "dangerous" ones)

**Logs (if applicable)**
Relevant parts:
```
2020-05-27 17:12:19.198 +02:00 [INF] Invoice 4eKGJThrtQwZp5ZAxADupi new event: invoice_created (1001)
2020-05-27 17:12:19.259 +02:00 [ERR] Connection id "0HM02A1C845AM", Request id "0HM02A1C845AM:00000001": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Services.Invoices.InvoiceEntity.EntityToDTO() in /home/user/cadr-build/btcpayserver-1.0.4.2/BTCPayServer/Services/Invoices/InvoiceEntity.cs:line 382
   at BTCPayServer.Controllers.InvoiceController.CreateInvoiceCore(CreateInvoiceRequest invoice, StoreData store, String serverUrl, List`1 additionalTags, CancellationToken cancellationToken) in /home/user/cadr-build/btcpayserver-1.0.4.2/BTCPayServer/Controllers/InvoiceController.cs:line 218
   at BTCPayServer.Controllers.InvoiceController.CreateInvoice(CreateInvoiceModel model, CancellationToken cancellationToken) in /home/user/cadr-build/btcpayserver-1.0.4.2/BTCPayServer/Controllers/InvoiceController.UI.cs:line 535
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /home/user/cadr-build/btcpayserver-1.0.4.2/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 77
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /home/user/cadr-build/btcpayserver-1.0.4.2/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 31
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**To Reproduce**
1. Make sure Payjoin is supported by the node
2. Create an invoice via any means
3. Observe blank page or absent popup
4. Logs contain above mentioned exception
5. The list of invoices contains correctly looking invoice

**Expected behavior**
Redirect or popup is shown without exception

**Actual behavior**
Exception occurs

**Additional context**
I tried to understand the problem myself first to rule-out the possibility of my own misconfiguration and not bother you with currently unusual setup. Unfortunately, I don't seem to know C# enough to debug this thing.

It looks like it crashes on safe assignment, so the only possible explanation is that `self` is `null`. It'd have to be passed from the caller. The caller contains these lines (comments mine)

```c#
            using (logs.Measure("Saving invoice"))
            {
                // This is the latest assignment in that function
                entity = await _InvoiceRepository.CreateInvoiceAsync(store.Id, entity);
            }
            _ = Task.Run(async () =>
            {
                try
                {
                    await fetchingAll;
                }
                catch (AggregateException ex)
                {
                    ex.Handle(e => { logs.Write($"Error while fetching rates {ex}"); return true; });
                }
                await _InvoiceRepository.AddInvoiceLogs(entity.Id, logs);
            });
            _EventAggregator.Publish(new Events.InvoiceEvent(entity, 1001, InvoiceEvent.Created));
            var resp = entity.EntityToDTO(); // The exception is thrown from this method
```

So logically `await _InvoiceRepository.CreateInvoiceAsync(store.Id, entity);` must return `null`, however, `CreateInvoiceAsync` ends with these lines:

```c#
AddToTextSearch(invoice.Id, textSearch.ToArray());
return invoice;
```

if `invoice` was `null` it'd throw an exception before returning - on attempt to access its properties.

Therefore, the problem must be in some "magic C# code in between" - here's where my lack of knowledge stopped me from continuing with analysis. :(

**Comment by Kukks** [comment]
Can you try to update to latest and see if it persists? You are two
versions behind.

**Comment by Kixunil** [comment]
Wow, that's fast, it feels like I was updating yesterday and there are already two new versions! Didn't even think about btcpay being old.

Yes, update solved my issue, sorry about bothering you!

**Comment by NicolasDorier** [comment]
well this is a new feature so problems bubble up fast and we can fix them fast.
