### ISSUE TITLE
App gives err 500

### ISSUE THREAD

**Issue by kallerosenbaum** [btcpayserver/btcpayserver#1785]
**Describe the problem/bug**
I have an old PoS app that used to work, but since some time (I don't know how long) it sends an err 500. Every operation on the app seems to generate a 500. Here's an example from when I tried to remove the app from the apps list:

```
Jul 29 10:26:45 wilfrid run.sh[1726]: #033[41m#033[30mfail#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HM1J0TVVJKEK", Request id "0HM1J0TVVJKEK:00000001": An unhandled exception was thrown by the application.
Jul 29 10:26:45 wilfrid run.sh[1726]: System.ArgumentOutOfRangeException: The UTC time represented when the offset is applied must be between year 0 and 10,000. (Parameter 'offset')
Jul 29 10:26:45 wilfrid run.sh[1726]:    at System.DateTimeOffset.ValidateDate(DateTime dateTime, TimeSpan offset)
Jul 29 10:26:45 wilfrid run.sh[1726]:    at System.DateTimeOffset..ctor(DateTime dateTime, TimeSpan offset)
Jul 29 10:26:45 wilfrid run.sh[1726]:    at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
Jul 29 10:26:45 wilfrid run.sh[1726]:    at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
Jul 29 10:26:45 wilfrid run.sh[1726]:    at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
Jul 29 10:26:45 wilfrid run.sh[1726]:    at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
Jul 29 10:26:45 wilfrid run.sh[1726]:    at BTCPayServer.Services.Apps.AppService.GetAppDataIfOwner(String userId, String appId, Nullable`1 type) in /mnt/bitcoin/btcpay/btcpayserver/BTCPayServer/Services/Apps/AppService.cs:line 423
Jul 29 10:26:45 wilfrid run.sh[1726]:    at BTCPayServer.Controllers.AppsController.DeleteApp(String appId) in /mnt/bitcoin/btcpay/btcpayserver/BTCPayServer/Controllers/AppsController.cs:line 148
Jul 29 10:26:45 wilfrid run.sh[1726]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Jul 29 10:26:45 wilfrid run.sh[1726]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Jul 29 10:26:45 wilfrid run.sh[1726]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Jul 29 10:26:45 wilfrid run.sh[1726]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Jul 29 10:26:45 wilfrid run.sh[1726]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Jul 29 10:26:45 wilfrid run.sh[1726]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
Jul 29 10:26:45 wilfrid run.sh[1726]: --- End of stack trace from previous location where exception was thrown ---
Jul 29 10:26:45 wilfrid run.sh[1726]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Jul 29 10:26:45 wilfrid run.sh[1726]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Jul 29 10:26:45 wilfrid run.sh[1726]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Jul 29 10:26:45 wilfrid run.sh[1726]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Jul 29 10:26:45 wilfrid run.sh[1726]: --- End of stack trace from previous location where exception was thrown ---
Jul 29 10:26:45 wilfrid run.sh[1726]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Jul 29 10:26:45 wilfrid run.sh[1726]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Jul 29 10:26:45 wilfrid run.sh[1726]:    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Jul 29 10:26:45 wilfrid run.sh[1726]:    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Jul 29 10:26:45 wilfrid run.sh[1726]:    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Jul 29 10:26:45 wilfrid run.sh[1726]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Jul 29 10:26:45 wilfrid run.sh[1726]:    at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /mnt/bitcoin/btcpay/btcpayserver/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 84
Jul 29 10:26:45 wilfrid run.sh[1726]:    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
Jul 29 10:26:45 wilfrid run.sh[1726]:    at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /mnt/bitcoin/btcpay/btcpayserver/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 30
Jul 29 10:26:45 wilfrid run.sh[1726]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

The same "offset" error happens on every type of use (both viewing and managing). Other apps on the same server seem to work fine.

**Your environment**
* Version of BTCPay Server: v1.0.5.3
* Deployment method: Built from source, run on bare metal ubuntu machine
* Other relevant environment details: dotnet 3.1.101

**Comment by NicolasDorier** [comment]
What database are you using?

**Comment by kallerosenbaum** [comment]
sqlite

**Comment by Kukks** [comment]
If you can, please transition to a Postgres setup. SQLite support is
deprecated since it has so many limitations.

**Comment by kallerosenbaum** [comment]
> If you can, please transition to a Postgres setup. SQLite support is deprecated since it has so many limitations.

Oh, didn't know it was deprecated. I'll setup postgresql at some time, but there's no migration script, so I'll have to start from scratch, right? No big deal since it's mostly a toy for me anyway.

**Comment by NicolasDorier** [comment]
@kallerosenbaum yes. Sorry for that, we should better put proper warning about this.

**Comment by NicolasDorier** [comment]
Actually there is a warning normally.

**Comment by NicolasDorier** [comment]
Closing this. We plan to remove SQLite support. In general avoid to make breaking change like this, but supporting it has been way too much trouble, and it is not tested at all anymore. :(
