### ISSUE TITLE
500 error on invoice with a custom currency

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#184]
I created an invoice on http://btcpay-server-testnet.azurewebsites.net using a custom currency code and when i go to the invoice checkout page([here](http://btcpay-server-testnet.azurewebsites.net/i/SuWhwXSRUDdFVTEDfv9bns)) i get a 500 error with the following:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Services.Rates.CurrencyNameTable.GetNumberFormatInfo(String currency) in D:\home\site\repository\BTCPayServer\Services\Rates\CurrencyNameTable.cs:line 49
   at BTCPayServer.Controllers.InvoiceController.FormatCurrency(Decimal price, String currency, CurrencyNameTable currencies) in D:\home\site\repository\BTCPayServer\Controllers\InvoiceController.UI.cs:line 298
   at BTCPayServer.Controllers.InvoiceController.FormatCurrency(PaymentMethod paymentMethod) in D:\home\site\repository\BTCPayServer\Controllers\InvoiceController.UI.cs:line 293
   at BTCPayServer.Controllers.InvoiceController.GetInvoiceModel(String invoiceId, String paymentMethodIdStr) in D:\home\site\repository\BTCPayServer\Controllers\InvoiceController.UI.cs:line 232
   at BTCPayServer.Controllers.InvoiceController.Checkout(String invoiceId, String id, String paymentMethodId) in D:\home\site\repository\BTCPayServer\Controllers\InvoiceController.UI.cs:line 185
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in D:\home\site\repository\BTCPayServer\Hosting\BTCpayMiddleware.cs:line 46
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by Kukks** [comment]
Ok, I can see the error comes because we try to laod the currency from a predefined list @Currencies.txt 
Can we add a fallback type to `GetNumberFormatInfo`?

**Comment by NicolasDorier** [comment]
we could, but what fallback would be acceptable? We need to know the divisibility to show clearly

**Comment by Kukks** [comment]
if no currency format is available, we could just output it as raw as possible in terms of the numeric value 
`{amount.ToString()} {currencyCode} `

**Comment by NicolasDorier** [comment]
Solved, this solve back to USD formatting.
