### ISSUE TITLE
`dotnet publish` produces defective build

### ISSUE THREAD

**Issue by erikarvstedt** [btcpayserver/btcpayserver#1894]
The build created via `dotnet publish` fails at runtime.

##### 1. Publish and run
```bash
# Add nuget and dotnet SDK to your environment.
# For nix, use nix-shell -p dotnetPackages.Nuget dotnetCorePackages.sdk_3_1
TMPDIR=/tmp/build-btcp
rm -rf $TMPDIR
mkdir -p $TMPDIR/{src,buildHome,runHome}
cd $TMPDIR/src
curl -SL https://github.com/btcpayserver/btcpayserver/archive/v1.0.5.5.tar.gz | tar xz --strip-components=1

HOME=$TMPDIR/buildHome DOTNET_CLI_TELEMETRY_OPTOUT=1 \
  dotnet publish --output publish -c Release BTCPayServer/BTCPayServer.csproj

HOME=$TMPDIR/runHome DOTNET_ROOT=$(dirname $(dirname $(type -P dotnet))) \
  publish/BTCPayServer
```

##### 2. Trigger bug
```bash
curl -L 127.0.0.1:23000
```
BTCPayServer fails with output:
```
Microsoft.AspNetCore.Server.Kestrel: Connection id "0HM2KGDSR0A9S", Request id "0HM2KGDSR0A9S:00000002": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at BundlerMinifier.FileHelpers.NormalizePath(String path)
   at BundlerMinifier.FileHelpers.TrimTrailingPathSeparatorChar(String path)
   at BundlerMinifier.FileHelpers.DemandTrailingPathSeparatorChar(String path)
   at BundlerMinifier.TagHelpers.BundleTagHelper.GetSrc(String path)
   at BundlerMinifier.TagHelpers.BundleTagHelper.Process(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.TagHelpers.TagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.RunAsync(TagHelperExecutionContext executionContext)
   at AspNetCore.Views_Shared_Header.ExecuteAsync() in /tmp/build-btcp/src/BTCPayServer/Views/Shared/Header.cshtml:line 19
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper.RenderPartialViewAsync(TextWriter writer, Object model, IView view)
   at Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
   at AspNetCore.Views_Shared__LayoutSimple.<ExecuteAsync>b__10_0()
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
   at AspNetCore.Views_Shared__LayoutSimple.ExecuteAsync() in /tmp/build-btcp/src/BTCPayServer/Views/Shared/_LayoutSimple.cshtml:line 2
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /tmp/build-btcp/src/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 83
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /tmp/build-btcp/src/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 29
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```
The same bug appears when the binary from the build phase is run:
```
HOME=$TMPDIR/runHome DOTNET_ROOT=$(dirname $(dirname $(type -P dotnet))) \
  BTCPayServer/bin/Release/netcoreapp3.1/BTCPayServer
```

I'm using the `dotnet publish` approach because I want to create BTCPayServer packages for Linux.

**Comment by pavlenex** [comment]
@NicolasDorier Any idea what's going on here?

**Comment by knocte** [comment]
> I want to create BTCPayServer packages for Linux.

What format?

**Comment by erikarvstedt** [comment]
Nixpkgs.
There's already a working release: we're using [`dotnet publish`](https://github.com/NixOS/nixpkgs/blob/54a0a400f2d1ab30764cf752dd107a86fef11ffa/pkgs/applications/blockchains/nbxplorer/default.nix#L38)  for nbxplorer and [a workaround](https://github.com/NixOS/nixpkgs/blob/54a0a400f2d1ab30764cf752dd107a86fef11ffa/pkgs/applications/blockchains/btcpayserver/default.nix#L29) for btcpayserver.

When `dotnet publish` is fixed, I'll propose an update to the [AUR package](https://aur.archlinux.org/packages/btcpayserver/)

**Comment by knocte** [comment]
Just curious (sorry for the off-topic): there are AUR (and soon Nixpkgs) packages but no snap/deb/rpm/flatpak?

**Comment by pavlenex** [comment]
@erikarvstedt were you able to resolve this or figure out the culprit?

**Comment by erikarvstedt** [comment]
No, nixpkgs is still using [this workaround](https://github.com/NixOS/nixpkgs/blob/4ecaf7ef3a65cffac09cf55235fb99b4c19befe0/pkgs/applications/blockchains/btcpayserver/default.nix#L29).

**Comment by NicolasDorier** [comment]
@erikarvstedt I think the problem is with the data directory.
We use publish ourselves in https://github.com/btcpayserver/btcpayserver/blob/master/amd64.Dockerfile

We use `dotnet blah.dll` to execute btcpay

https://github.com/btcpayserver/btcpayserver/blob/master/docker-entrypoint.sh

**Comment by NicolasDorier** [comment]
Oh, got it, you want to create a self-contianed package so the dotnet is embedded ?

**Comment by NicolasDorier** [comment]
I can't reproduce. Did it on windows, it just work :/
How do you run the app? what is the current directory?

**Comment by erikarvstedt** [comment]
It indeed works when using the build directory as the working directory.
As a daemon, btcpayserver shouldn't depend on the working directory for running correctly. Could you fix this?

**Comment by NicolasDorier** [comment]
@erikarvstedt I actually also tried with `-c Release` and inside the binary directory, and it worked as well.
Did you checked what raspiblitz do for example? Because when I look our dockerfile, we are running BTCPay from the binary directory, so that should work.

**Comment by NicolasDorier** [comment]
Look they seem to do the same https://github.com/rootzoll/raspiblitz/blob/1da0b3b59ac6b3eededd84fad935a83ed0f4b425/home.admin/config.scripts/bonus.btcpayserver.sh

**Comment by erikarvstedt** [comment]
Yes, as I said, the correct runtime operation of btcpayserver should not depend on its working directory.
Please fix this in `btcpayserver`. This bug doesn't exist in `nbxplorer`.

**Comment by NicolasDorier** [comment]
NBXplorer does not have this issue because it does not have assets to look for in directories.
Will try to see if I can do something about it.

**Comment by erikarvstedt** [comment]
> Will try to see if I can do something about it.

Great, thanks! This will help making deployments more simple and robust. It is really unusual for a service binary to assume a working dir for accessing internal data.

**Comment by erikarvstedt** [comment]
Thank you!
