### ISSUE TITLE
When c-lightning env variable is enabled, it RTL keeps restarting, causing SSL certificate issue problems due to Debounce minTimer fired

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#1956]
**Describe the bug**
Whenever I try to deploy a fresh instance with `export BTCPAYGEN_LIGHTNING="clightning"` I get SSL problems.

**To Reproduce**
1. Enable `export BTCPAYGEN_LIGHTNING="clightning"` on a fresh deployment
2. Chances are you'll have SSL problem
3. `Docker ps` to see which container is restarting
4. In my case it's always 
```
53f3e857e69f        saubyk/c-lightning-rest:0.3.0                           "./docker-entrypoint…"   7 minutes ago       Restarting (1) 16 seconds ago                                                                           generated_clightning_bitcoin_rest_1
```

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version [available in the right bottom corner of footer] v.1.0.5.6
- Deployment Method: [e.g. Docker, Manual, Third-Party-hoist] Docker, Contabo VPS

**Logs (if applicable)**
Basic logs can be found in Server Settings > Logs. More logs https://docs.btcpayserver.org/Troubleshooting/#2-looking-through-the-logs

```
--- Starting the cl-rest server ---
Generating SSL cert and key
Generating a RSA private key
........................................................+++++
...............+++++
writing new private key to './certs/key.tmp.pem'
-----
writing RSA key
Reading SSL cert and key
Generating macaroon file and key
Reading rootkey for macaroon
--- cl-rest api server is ready and listening on port: 3001 ---
--- cl-rest doc server is ready and listening on port: 4001 ---
Lightning client connection error Error: connect ECONNREFUSED /root/.lightning
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/root/.lightning'
}
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED /root/.lightning
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
Emitted 'error' event on LightningClient instance at:
    at Socket.<anonymous> (/usr/src/app/lightning-client-js.js:71:23)
    at Socket.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/root/.lightning'
}
Reading config file
cl-rest state dir: /usr/src/app
Reading config file
--- Starting the cl-rest server ---
Reading SSL cert and key
Reading rootkey for macaroon
--- cl-rest api server is ready and listening on port: 3001 ---
--- cl-rest doc server is ready and listening on port: 4001 ---
Lightning client connection error Error: connect ECONNREFUSED /root/.lightning
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/root/.lightning'
}
```
### Let's encrypt logs

```
2020/10/07 10:55:39 Received event start for container 53f3e857e69f
2020/10/07 10:55:40 Received event die for container 53f3e857e69f
2020/10/07 10:55:54 Debounce maxTimer fired
2020/10/07 10:55:54 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
2020/10/07 10:56:06 Received event start for container 53f3e857e69f
2020/10/07 10:56:07 Received event die for container 53f3e857e69f
2020/10/07 10:56:22 Debounce minTimer fired
2020/10/07 10:56:22 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
2020/10/07 10:57:00 Received event start for container 53f3e857e69f
2020/10/07 10:57:01 Received event die for container 53f3e857e69f
2020/10/07 10:57:16 Debounce minTimer fired
2020/10/07 10:57:16 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
2020/10/07 10:58:02 Received event start for container 53f3e857e69f
2020/10/07 10:58:03 Received event die for container 53f3e857e69f
2020/10/07 10:58:18 Debounce minTimer fired
2020/10/07 10:58:18 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
2020/10/07 10:59:21 Received event start for container 53f3e857e69f
2020/10/07 10:59:21 Received event die for container 53f3e857e69f```

```
2020-10-07 10:55:00,933:ERROR:simp_le:1396: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-v02.api.letsencrypt.org/acme/authz-v3/7727832427 
```

@Kukks pointed out it's `2020/10/07 10:58:18 Debounce minTimer fired`

> seems that if a container restarts too many times it cuts it off. 

Potential solution according to Kukks

> is there  a way to make the nginx companion ignore specific containers?

**Additional context**

Don't have problems like this with LDN

**Comment by pavlenex** [comment]
Weird but just tried on another deployment without lightning, and i experienced the same issue, so this does not seem related to c-lightning and have no idea how to troubleshoot further, could be host-specific issue.
