### ISSUE TITLE
Unavailable invoice details

### ISSUE THREAD

**Issue by 2ge** [btcpayserver/btcpayserver#1972]
**Describe the bug**
After update btcpayserver I am unable to access to older invoices (made before update)

**To Reproduce**
I dont know which version I was running, lets say 1-2 months old.

**Expected behavior**
Get invoice details, not 500 HTTP Error

**Your BTCPay Environment (please complete the following information):**
- BTCPayServer v1.0.5.7
- Docker
- Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36

**Logs (if applicable)**
GET /invoices/PADLKaNyZV3C8wYK4nCTX5 [500]
```
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HM3EOKO5LAU9", Request id "0HM3EOKO5LAU9:00000001": An unhandled exception was thrown by the application.
System.FormatException: Invalid PaymentMethodId
   at BTCPayServer.Payments.PaymentMethodId.Parse(String str) in /source/BTCPayServer/Payments/PaymentMethodId.cs:line 111
   at BTCPayServer.Data.AddressInvoiceDataExtensions.GetpaymentMethodId(AddressInvoiceData addressInvoiceData) in /source/BTCPayServer/Data/AddressInvoiceDataExtensions.cs:line 32
   at BTCPayServer.Services.Invoices.InvoiceRepository.<>c.<ToEntity>b__34_3(AddressInvoiceData a) in /source/BTCPayServer/Services/Invoices/InvoiceRepository.cs:line 532
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToHashSet[TSource](IEnumerable`1 source, IEqualityComparer`1 comparer)
   at BTCPayServer.Services.Invoices.InvoiceRepository.ToEntity(InvoiceData invoice)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at BTCPayServer.Services.Invoices.InvoiceRepository.GetInvoices(InvoiceQuery queryObject) in /source/BTCPayServer/Services/Invoices/InvoiceRepository.cs:line 646
   at BTCPayServer.Controllers.InvoiceController.Invoice(String invoiceId) in /source/BTCPayServer/Controllers/InvoiceController.UI.cs:line 47
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 85
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 30
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

New invoice details are working.

**Comment by Kukks** [comment]
did you have altcoins enabled and then removed them?

**Comment by 2ge** [comment]
yes, I did.

**Comment by pavlenex** [comment]
@2ge in a way this is expected behavior I believe, since we informed users about implications [here](https://blog.btcpayserver.org/btcpay-server-1-0-5-4/).

> When you switch from altcoin to bitcoin only build, all altcoin related payment data in the invoices will no longer be visible.

But then again, this should happen for the old invoices, what you reported is for the new ones if I understood correctly?

**Comment by 2ge** [comment]
I understand, very special case, didn't find anything online, so if somebody will look for error at least he will get this result and know the case. Not really need to fix it, because I think it will be very hard.
