### ISSUE TITLE
HTTP ERROR 500 when resetting user password

### ISSUE THREAD

**Issue by jodobear** [btcpayserver/btcpayserver#1986]
Trying to change password for a user gives the following error:

` btcpay.xyz.com is currently unable to handle this request. HTTP ERROR 500`

Docker logs:

```sh
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HM3FKC4IAIHS", Request id "0HM3FKC4IAIHS:00000001": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at AspNetCore.Views_Account_SetPassword.<ExecuteAsync>b__29_2() in /source/BTCPayServer/Views/Account/SetPassword.cshtml:line 36
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.GetChildContentAsync(Boolean useCachedResult, HtmlEncoder encoder)
   at Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
   at AspNetCore.Views_Account_SetPassword.ExecuteAsync() in /source/BTCPayServer/Views/Account/SetPassword.cshtml:line 16
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g_
```

Anyone face this issue before?

**Comment by NicolasDorier** [comment]
seems to work on my side.

**Comment by NicolasDorier** [comment]
I think you real problem is different, but it could not show the errors before.
ping @Kukks .

There might be another issue here, should add a test for reset password.
