### ISSUE TITLE
Importing an unsupported Wallet QR code causes a page crash

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#2098]
**Describe the bug**
When trying to import a wallet from Bluewallet, you'll get a blank page.

**To Reproduce**
1. In Bluewallet export wallet
2. In BTCPay Store > Import QR 
3. Scan

**Expected behavior**
Wallet should be imported or we should provide a proper error and not crash the page.

**Screenshots**

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version: [available in the right bottom corner of footer]  1.0.6.0
- Deployment Method: [e.g. Docker, Manual, Third-Party-host] Docker
- Browser: [e.g. Chrome, Safari] Firefox

**Logs (if applicable)**
Basic logs can be found in Server Settings > Logs. More logs https://docs.btcpayserver.org/Troubleshooting/#2-looking-through-the-logs

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.DerivationSchemeSettings.TryParseFromWalletFile(String fileContents, BTCPayNetwork network, DerivationSchemeSettings& settings) in /source/BTCPayServer/DerivationSchemeSettings.cs:line 87
   at BTCPayServer.Controllers.StoresController.AddDerivationScheme(String storeId, DerivationSchemeViewModel vm, String cryptoCode) in /source/BTCPayServer/Controllers/StoresController.BTCLike.cs:line 121
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 85
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 30
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by britttttk** [comment]
In your step1 of reproduce you mean "show wallet XPub" right? Not the export. 

It works for me this way.

**Comment by pavlenex** [comment]
Okaay so, there are two types of wallet export in blue wallet, and the one which works is xpub export, the wallet export crashes the page. Regardless, the page shouldn't crash. This is also UX problem, since people may be under impression that it's wallet seed they're importing.

**Comment by pavlenex** [comment]
@Kukks I also remember you mentioning that this should import not only xpub but also  `Master fingerprint`
`Account key path` but this is not the case through Bluewallet > show Xpub.

**Comment by Kukks** [comment]
> @Kukks I also remember you mentioning that this should import not only xpub but also `Master fingerprint`
> `Account key path` but this is not the case through Bluewallet > show Xpub.

Blue wallet doesnt export that data, other wallets like Wasabi and hardware wallets like Cobo and Coldcard do.

**Comment by Kukks** [comment]
> In your step1 of reproduce you mean "show wallet XPub" right? Not the export.
> 
> It works for me this way.

This, the other export option from BW is a seed, which we would ned more info to import (address format)

**Comment by pavlenex** [comment]
Regardless, page shouldn't crash and the way we communicate this through the UI is `Wallet Import`. I think we need to discuss and move this to the manual xpub page entry if all this does is imports xpub via QR.
