### ISSUE TITLE
API Create Invoice - Internal Server Error

### ISSUE THREAD

**Issue by yuriescl** [btcpayserver/btcpayserver#2111]
**Describe the bug**
I'm getting a `500 Internal Server Error` response when [creating an invoice through the API](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/Invoices_CreateInvoice).

**To Reproduce**
1. Call the [API endpoint to create an invoice](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/Invoices_CreateInvoice) with this request body:
```
{
    "amount": "0.0002",
    "currency": "BTC"
}
```
The response will be an Internal Server Error.

**Expected behavior**
The response should be a 400 Bad Request if the request is invalid, or contain a proper error message.

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:  v1.0.6.2
- Deployment Method: Docker
- Browser: API (no browser)

**Logs (if applicable)**
```
2020-12-07 00:04:19.827 +00:00 [INF] BTC: New block
2020-12-07 00:04:33.737 +00:00 [INF] BTC: New block
2020-12-07 00:20:30.137 +00:00 [INF] BTC: New block
2020-12-07 00:35:51.634 +00:00 [INF] BTC: New block
2020-12-07 00:35:52.101 +00:00 [INF] DelayedTransactionBroadcasterHostedService successfully exited...
2020-12-07 00:35:52.103 +00:00 [INF] Internal Socks HTTP Proxy closed
2020-12-07 00:35:52.110 +00:00 [INF] CssThemeManagerHostedService successfully exited...
2020-12-07 00:35:52.111 +00:00 [INF] CheckConfigurationHostedService successfully exited...
2020-12-07 00:35:52.113 +00:00 [INF] PullPaymentHostedService successfully exited...
2020-12-07 00:35:52.122 +00:00 [INF] Disconnected from WebSocket of NBXplorer (BTC)
2020-12-07 00:35:52.123 +00:00 [INF] NBXplorerListener successfully exited...
2020-12-07 00:35:52.127 +00:00 [INF] LightningListener successfully exited...
2020-12-07 00:35:52.132 +00:00 [INF] Stop watching invoices
2020-12-07 00:35:52.144 +00:00 [INF] RatesHostedService successfully exited...
2020-12-07 00:35:52.180 +00:00 [INF] DynamicDnsHostedService successfully exited...
2020-12-07 00:35:52.181 +00:00 [INF] TorServicesHostedService successfully exited...
2020-12-07 00:35:52.184 +00:00 [INF] NewVersionCheckerHostedService successfully exited...
2020-12-07 00:35:58.019 +00:00 [INF] BTC: Explorer url is http://nbxplorer:32838/
2020-12-07 00:35:58.080 +00:00 [INF] BTC: Cookie file is /root/.nbxplorer/TestNet/.cookie
2020-12-07 00:35:58.096 +00:00 [INF] DOGE: Explorer url is http://nbxplorer:32838/
2020-12-07 00:35:58.097 +00:00 [INF] DOGE: Cookie file is /root/.nbxplorer/TestNet/.cookie
2020-12-07 00:35:58.352 +00:00 [INF] Internal Socks HTTP Proxy listening at http://127.0.0.1:37167/
2020-12-07 00:35:58.404 +00:00 [INF] Starting listening NBXplorer (BTC)
2020-12-07 00:35:58.457 +00:00 [INF] Starting listening NBXplorer (DOGE)
2020-12-07 00:35:58.475 +00:00 [INF] Start watching invoices
2020-12-07 00:35:58.524 +00:00 [INF] NBXplorer BTC: NotConnected => Ready
2020-12-07 00:35:58.525 +00:00 [INF] NBXplorer DOGE: NotConnected => Synching
2020-12-07 00:35:58.545 +00:00 [INF] Starting payment request expiration watcher
2020-12-07 00:35:58.629 +00:00 [INF] BTC: Checking if any pending invoice got paid while offline...
2020-12-07 00:35:58.652 +00:00 [INF] BTC: 0 payments happened while offline
2020-12-07 00:35:58.652 +00:00 [INF] Connected to WebSocket of NBXplorer (BTC)
2020-12-07 00:35:58.819 +00:00 [INF] 1 pending payment requests being checked since last run
2020-12-07 00:54:12.961 +00:00 [INF] BTC: New block
2020-12-07 00:58:33.994 +00:00 [INF] BTC: New block
2020-12-07 00:59:57.348 +00:00 [INF] BTC: New block
2020-12-07 01:06:13.358 +00:00 [INF] BTC: New block
2020-12-07 01:11:02.334 +00:00 [INF] BTC: New block
2020-12-07 01:21:02.433 +00:00 [INF] BTC: New block
2020-12-07 01:21:16.723 +00:00 [INF] BTC: New block
2020-12-07 01:41:15.995 +00:00 [INF] BTC: New block
2020-12-07 01:50:19.693 +00:00 [INF] BTC: New block
2020-12-07 01:55:11.851 +00:00 [INF] BTC: New block
2020-12-07 02:13:14.721 +00:00 [INF] BTC: New block
2020-12-07 02:20:37.667 +00:00 [INF] BTC: New block
2020-12-07 02:38:42.254 +00:00 [INF] BTC: New block
2020-12-07 02:39:36.638 +00:00 [INF] BTC: New block
2020-12-07 02:57:50.738 +00:00 [INF] BTC: New block
2020-12-07 02:59:49.448 +00:00 [INF] BTC: New block
2020-12-07 03:08:49.090 +00:00 [INF] BTC: New block
2020-12-07 03:14:54.593 +00:00 [INF] BTC: New block
2020-12-07 03:34:04.405 +00:00 [INF] BTC: New block
2020-12-07 03:47:06.688 +00:00 [INF] BTC: New block
2020-12-07 04:00:52.880 +00:00 [INF] BTC: New block
2020-12-07 04:00:54.830 +00:00 [INF] BTC: New block
2020-12-07 04:11:20.082 +00:00 [INF] BTC: New block
2020-12-07 04:29:22.644 +00:00 [INF] BTC: New block
2020-12-07 04:33:59.047 +00:00 [INF] BTC: New block
2020-12-07 04:50:03.327 +00:00 [INF] BTC: New block
2020-12-07 05:04:10.037 +00:00 [INF] BTC: New block
2020-12-07 05:21:01.611 +00:00 [INF] BTC: New block
2020-12-07 05:21:26.299 +00:00 [INF] BTC: New block
2020-12-07 05:31:26.335 +00:00 [INF] BTC: New block
2020-12-07 05:35:54.999 +00:00 [INF] BTC: New block
2020-12-07 05:54:31.765 +00:00 [INF] BTC: New block
2020-12-07 06:16:21.315 +00:00 [INF] BTC: New block
2020-12-07 06:32:29.841 +00:00 [INF] BTC: New block
2020-12-07 06:50:49.993 +00:00 [INF] BTC: New block
2020-12-07 06:58:09.135 +00:00 [INF] BTC: New block
2020-12-07 07:07:18.461 +00:00 [INF] BTC: New block
2020-12-07 07:25:23.922 +00:00 [INF] BTC: New block
2020-12-07 07:32:22.655 +00:00 [INF] BTC: New block
2020-12-07 07:51:32.293 +00:00 [INF] BTC: New block
2020-12-07 08:12:04.933 +00:00 [INF] BTC: New block
2020-12-07 08:16:27.129 +00:00 [INF] BTC: New block
2020-12-07 08:16:34.976 +00:00 [INF] BTC: New block
2020-12-07 08:22:38.035 +00:00 [INF] BTC: New block
2020-12-07 08:28:55.837 +00:00 [INF] BTC: New block
2020-12-07 08:30:46.779 +00:00 [INF] BTC: New block
2020-12-07 08:49:41.939 +00:00 [INF] BTC: New block
2020-12-07 09:08:53.372 +00:00 [INF] BTC: New block
2020-12-07 09:22:07.459 +00:00 [INF] BTC: New block
2020-12-07 09:22:36.566 +00:00 [INF] BTC: New block
2020-12-07 09:40:54.542 +00:00 [INF] BTC: New block
2020-12-07 09:42:51.451 +00:00 [INF] BTC: New block
2020-12-07 10:02:37.928 +00:00 [INF] BTC: New block
2020-12-07 10:06:43.499 +00:00 [INF] BTC: New block
2020-12-07 10:15:04.500 +00:00 [INF] BTC: New block
2020-12-07 10:20:57.140 +00:00 [INF] BTC: New block
2020-12-07 10:40:16.299 +00:00 [INF] BTC: New block
2020-12-07 10:50:06.119 +00:00 [INF] BTC: New block
2020-12-07 10:57:07.371 +00:00 [INF] BTC: New block
2020-12-07 11:05:56.483 +00:00 [INF] BTC: New block
2020-12-07 11:24:29.929 +00:00 [INF] BTC: New block
2020-12-07 11:28:59.753 +00:00 [INF] BTC: New block
2020-12-07 11:37:25.239 +00:00 [INF] BTC: New block
2020-12-07 11:57:11.832 +00:00 [INF] BTC: New block
2020-12-07 11:57:35.775 +00:00 [INF] BTC: New block
2020-12-07 11:58:21.052 +00:00 [INF] BTC: New block
2020-12-07 11:59:04.709 +00:00 [INF] BTC: New block
2020-12-07 12:02:09.291 +00:00 [INF] BTC: New block
2020-12-07 12:15:01.410 +00:00 [INF] BTC: New block
2020-12-07 12:33:30.462 +00:00 [INF] BTC: New block
2020-12-07 12:43:37.676 +00:00 [INF] BTC: New block
2020-12-07 12:50:24.970 +00:00 [INF] BTC: New block
2020-12-07 12:55:42.797 +00:00 [INF] BTC: New block
2020-12-07 13:07:50.937 +00:00 [INF] BTC: New block
2020-12-07 13:24:55.475 +00:00 [INF] BTC: New block
2020-12-07 13:27:19.102 +00:00 [INF] BTC: New block
2020-12-07 13:30:38.339 +00:00 [INF] BTC: New block
2020-12-07 13:48:34.115 +00:00 [INF] BTC: New block
2020-12-07 13:51:41.245 +00:00 [INF] BTC: New block
2020-12-07 14:03:19.555 +00:00 [INF] BTC: New block
2020-12-07 14:17:06.185 +00:00 [INF] BTC: New block
2020-12-07 14:36:39.775 +00:00 [INF] BTC: New block
2020-12-07 14:41:12.683 +00:00 [INF] BTC: New block
2020-12-07 14:51:27.092 +00:00 [INF] BTC: New block
2020-12-07 14:52:13.162 +00:00 [INF] BTC: New block
2020-12-07 14:58:01.542 +00:00 [INF] BTC: New block
2020-12-07 15:17:05.641 +00:00 [INF] BTC: New block
2020-12-07 15:37:04.304 +00:00 [INF] BTC: New block
2020-12-07 15:47:20.766 +00:00 [INF] BTC: New block
2020-12-07 15:49:16.850 +00:00 [INF] BTC: New block
2020-12-07 16:01:22.214 +00:00 [INF] BTC: New block
2020-12-07 16:03:25.768 +00:00 [INF] BTC: New block
2020-12-07 16:08:26.712 +00:00 [INF] BTC: New block
2020-12-07 16:11:36.967 +00:00 [INF] BTC: New block
2020-12-07 16:17:15.653 +00:00 [INF] BTC: New block
2020-12-07 16:20:14.470 +00:00 [INF] BTC: New block
2020-12-07 16:35:51.735 +00:00 [INF] BTC: New block
2020-12-07 16:36:05.620 +00:00 [INF] BTC: New block
2020-12-07 16:42:55.119 +00:00 [INF] BTC: New block
2020-12-07 16:52:45.115 +00:00 [INF] BTC: New block
2020-12-07 16:59:31.564 +00:00 [INF] BTC: New block
2020-12-07 17:02:43.858 +00:00 [INF] BTC: New block
2020-12-07 17:21:15.179 +00:00 [INF] BTC: New block
2020-12-07 17:22:09.759 +00:00 [INF] BTC: New block
2020-12-07 17:41:47.728 +00:00 [INF] BTC: New block
2020-12-07 17:48:14.616 +00:00 [INF] BTC: New block
2020-12-07 17:56:02.746 +00:00 [INF] BTC: New block
2020-12-07 17:57:24.921 +00:00 [INF] BTC: New block
2020-12-07 18:12:44.350 +00:00 [INF] BTC: New block
2020-12-07 18:13:38.221 +00:00 [INF] BTC: New block
2020-12-07 18:22:46.087 +00:00 [INF] BTC: New block
2020-12-07 18:31:46.810 +00:00 [INF] BTC: New block
2020-12-07 18:49:20.063 +00:00 [INF] BTC: New block
2020-12-07 18:49:47.131 +00:00 [INF] User logged in.
2020-12-07 18:51:08.021 +00:00 [ERR] Connection id "0HM4QKK0V71K3", Request id "0HM4QKK0V71K3:00000001": An unhandled exception was thrown by the application.
System.ArgumentNullException: Value cannot be null. (Parameter 'code')
   at BTCPayServer.Client.Models.GreenfieldAPIError..ctor(String code, String message) in /source/BTCPayServer.Client/Models/GreenfieldAPIError.cs:line 15
   at BTCPayServer.Controllers.GreenField.GreenFieldUtils.CreateAPIError(ControllerBase controller, String errorCode, String errorMessage) in /source/BTCPayServer/Controllers/GreenField/GreenFieldUtils.cs:line 24
   at BTCPayServer.Controllers.GreenField.GreenFieldInvoiceController.CreateInvoice(String storeId, CreateInvoiceRequest request) in /source/BTCPayServer/Controllers/GreenField/InvoiceController.cs:line 153
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 85
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 30
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by NicolasDorier** [comment]
Thanks for the report, looking at it.

**Comment by NicolasDorier** [comment]
I fixed the crash, which hide the real problem. Let me check if I can tell you the real issue.

**Comment by NicolasDorier** [comment]
So the root of the issue is probably that your node is not fully synched or you did not setup the wallet of your store.

**Comment by NicolasDorier** [comment]
Or the rate source is unavailble. Will release a new release this week with several bug fixes like this one.

**Comment by yuriescl** [comment]
> So the root of the issue is probably that your node is not fully synched or you did not setup the wallet of your store.

I didn't setup the wallet, that was likely the reason.
Thanks for the quick fix!

**Comment by NicolasDorier** [comment]
1.0.6.3 is out and will give better details now!

**Comment by Delitants** [comment]
Same


2024-01-12 21:25:28.285 +00:00 [ERR] Connection id "0HN0IFTTPMDP7", Request id "0HN0IFTTPMDP7:00000001": An unhandled exception was thrown by the application.
System.ArgumentNullException: Value cannot be null. (Parameter 'o')
   at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, String parameterName)
   at Newtonsoft.Json.Linq.JToken.FromObjectInternal(Object o, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.FromObject(Object o)
   at BTCPayServer.Payments.LNURLPayPaymentType.PopulateCryptoInfo(InvoiceEntity invoice, PaymentMethod details, InvoiceCryptoInfo invoiceCryptoInfo, String serverUrl) in /source/BTCPayServer/Payments/LNURLPay/PaymentTypes.LNURL.cs:line 74
   at BTCPayServer.Services.Invoices.InvoiceEntity.EntityToDTO() in /source/BTCPayServer/Services/Invoices/InvoiceEntity.cs:line 630
   at BTCPayServer.Controllers.UIInvoiceController.GetInvoiceModel(String invoiceId, PaymentMethodId paymentMethodId, String lang) in /source/BTCPayServer/Controllers/UIInvoiceController.UI.cs:line 810
   at BTCPayServer.Controllers.UIInvoiceController.Checkout(String invoiceId, String id, String paymentMethodId, String view, String lang) in /source/BTCPayServer/Controllers/UIInvoiceController.UI.cs:line 676
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 97
   at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 30
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 29
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**© BTCPay Server v1.12.3+f23078df1 (Altcoins)**
