### ISSUE TITLE
Woocomerce: Spinner of death

### ISSUE THREAD

**Issue by snaildos** [btcpayserver/btcpayserver#2165]
**Describe the bug**
Here is what I have.
I have BTCPAYSERVER in a docker container, I then have a reverse proxy on the host machine picking up that container, and passing it (reverse proxy) to a domain.
When going to the plugin payment area, typing in my btcpay server adress, pressing pair, I get the "pairing code" and put it into the the text box on the woocemerce site. I press "Pair", It loads. And it never stops loading.
![image](https://user-images.githubusercontent.com/46210117/102956503-43da3080-4513-11eb-91e9-f4a583683560.png)

**To Reproduce the bug**
Steps to reproduce the reported bug:
Already labled.

**Expected behavior**
To load and actually pair.

**Screenshots**
![image](https://user-images.githubusercontent.com/46210117/102956648-7e43cd80-4513-11eb-8796-f61e949521a4.png)

**Your BTCPay Environment (please complete the following information):**
Connecting from Google Chrome. (Thru reverse proxy)
**Logs (if applicable)**
I found one error.
2020-12-23 02:54:34.342 +00:00 [ERR] An exception was thrown while deserializing the token.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
 ---> System.Security.Cryptography.CryptographicException: The key {cba85896-dd2d-4985-ac3d-2d3cdb126c23} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)

**Setup Parameters**

**Additional context**

**Comment by snaildos** [comment]
It's still loading to this hour.

**Comment by pavlenex** [comment]
@snaildos have you tried pairing your woocommerce with a third-party host for testing https://docs.btcpayserver.org/deployment/thirdpartyhosting ? This was you can isolate if the error is on server side or plugin/browser/woordpress.

**Comment by snaildos** [comment]
Can confirm, it is the plugin. 
![image](https://user-images.githubusercontent.com/46210117/103043779-147dff00-45b9-11eb-90b3-4763e989eb9f.png)
I used a community server.
![image](https://user-images.githubusercontent.com/46210117/103043791-1ba50d00-45b9-11eb-9678-c15285006d49.png)

**Comment by snaildos** [comment]
No matter what WP version I use, Or WOOCOMMERCE version, It will not work. At all.
This is definatly a plugin problem.

**Comment by snaildos** [comment]
I even downgraded plugin versions, IT'S STILL BROKEN!
