### ISSUE TITLE
Using the API, BTCPayserver throws an unhandled Exception

### ISSUE THREAD

**Issue by DanielAscher** [btcpayserver/btcpayserver#2212]
EDIT: i have to revert this, turns out, when i created a new store everything worked fine. i have no clue what happened.

BTCPayserver is on version 1.0.6.7

error Thrown according to the log file:

```2021-01-20 11:12:08.564 +00:00 [ERR] Connection id "0HM5T5A4U30T7", Request id "0HM5T5A4U30T7:00000001": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Controllers.InvoiceController.CreateInvoiceCoreRaw(InvoiceEntity entity, StoreData store, IPaymentFilter invoicePaymentMethodFilter, CancellationToken cancellationToken) in /source/BTCPayServer/Controllers/InvoiceController.cs:line 214
   at BTCPayServer.Controllers.InvoiceController.CreateInvoiceCoreRaw(BitpayCreateInvoiceRequest invoice, StoreData store, String serverUrl, List`1 additionalTags, CancellationToken cancellationToken) in /source/BTCPayServer/Controllers/InvoiceController.cs:line 159
   at BTCPayServer.Controllers.InvoiceController.CreateInvoiceCore(BitpayCreateInvoiceRequest invoice, StoreData store, String serverUrl, List`1 additionalTags, CancellationToken cancellationToken) in /source/BTCPayServer/Controllers/InvoiceController.cs:line 86
   at BTCPayServer.Controllers.InvoiceControllerAPI.CreateInvoice(BitpayCreateInvoiceRequest invoice, CancellationToken cancellationToken) in /source/BTCPayServer/Controllers/InvoiceController.API.cs:line 37
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 92
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 30
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)```

Request from php looks like this:

```
Creating invoice at your BTCPay Server now. Exception occured: Trying to access array offset on value of type null 

POST https://payment.mybtcfans.com:443/invoices HTTP/1.1 
Content-Type: application/json 
X-BTCPayServer-Plugin-Info: BTCPayServer PHP-Client/4.0.0 User-Agent: BTCPayServer PHP-Client/4.0.0 (PHP 7.4.13) X-Accept-Version: 2.0.0 
Content-Length: 715 
x-identity: 022cb9aec85ee03755934ebd7f8e025ceb89a5ec5673b0e14d92107a681ea1d662 x-signature: 304402206dbc4571e6f66eb7bbe26122d1d2fb1d2a61a45a665fe211d67b83627ef41603022066171227253abb6ca1b47d9dda038700c2db3faa9517559e0805acaa5247e8fb 

{"price":1.99,"currency":"USD","posData":null,"notificationURL":"https:\/\/hidden.com\/ipn_callback.php","transactionSpeed":"medium","fullNotifications":true,"extendedNotifications":false,"notificationEmail":"hidden@example.com","redirectURL":"https:\/\/hidden.com","orderID":"OrderIdFromYourSystem","itemDesc":"General Description of Item","itemCode":"skuNumber","physical":false,"buyerName":"","buyerAddress1":"","buyerAddress2":"","buyerCity":null,"buyerState":null,"buyerZip":null,"buyerCountry":null,"buyerEmail":"buyeremail@example.com","buyerPhone":null,"buyerNotify":null,"guid":"e2e68432-5d33-b5d3-f8fb-c4203e8b4072","nonce":1611141128.0288,"token":"hidden!"} HTTP/2 500 date: Wed, 20 Jan 2021 11:12:08 GMT content-length: 0 set-cookie: __cfduid=d6ad6d56df1546a3d9423bc7365cd22191611141128; expires=Fri, 19-Feb-21 11:12:08 GMT; path=/; domain=.hidden.com; HttpOnly; SameSite=Lax cf-cache-status: DYNAMIC cf-request-id: 07c117b92e00000e22baa52000000001 expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct" report-to: {"group":"cf-nel","max_age":604800,"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=rfuO0CtnM1E21mNM%2ByyGS8vquMiim6ouncp9tBKQpYN%2BozHLCU3JIfeaUDCcBfZBu%2Bpa8SKN2fND%2BE0ek9jPwNWWqX7NPDp8q9LDIdGHI9n1RHMbrV4%3D"}]} nel: {"report_to":"cf-nel","max_age":604800} server: cloudflare cf-ray: 61485bd518010e22-MXP
```

**Comment by pavlenex** [comment]
@Kukks any idea what may have happened here?

**Comment by dennisreimann** [comment]
I saw something similar while working on the wallet setup redesign. For me it was related to having deleted the onchain wallet and the `PaymentMethodCriteria` on the store blob being empty after that.
Checking the code for the error above it looks more like the derivation scheme of the onchain wallet wasn't present anymore or it has been set to disabled?

**Comment by Kukks** [comment]
I cannot see anything wrong in relations to the lines mentioned in the logs. I think we should close for now. If it happens again I'll investigate again
