### ISSUE TITLE
Altcoin implementation

### ISSUE THREAD

**Issue by Deimoscoin** [btcpayserver/btcpayserver#226]
Hello Mr Dorier, i had follow your instruction for Altcoin implementation,  NBxplorer is working perfectly fine, but when i try to integrate BTCPay using other coin as example, i can't get it to work. i get this error.

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.BTCPayNetworkProvider.InitDeimos() in /home/gitian/btcpayserver/BTCPayServer/BTCPayNetworkProvider.Deimos.cs:line 16
   at BTCPayServer.Configuration.DefaultConfiguration.CreateCommandLineApplicationCore() in /home/gitian/btcpayserver/BTCPayServer/Configuration/DefaultConfiguration.cs:line 21
   at StandardConfiguration.DefaultConfiguration.CreateCommandLineApplication()
   at StandardConfiguration.DefaultConfiguration.CreateConfiguration(String[] args)
   at BTCPayServer.Program.Main(String[] args) in /home/gitian/btcpayserver/BTCPayServer/Program.cs:line 35

thanks a lot

**Comment by NicolasDorier** [comment]
I don't know what is Line 16 of Deimos.cs.

**Comment by Deimoscoin** [comment]
oops, sorry i forgot to paste it.

This is the line 16: Add(new BTCPayNetwork()

**Comment by NicolasDorier** [comment]
and line below?

**Comment by Deimoscoin** [comment]
namespace BTCPayServer
{
    public partial class BTCPayNetworkProvider
    {
        public void InitDeimos()
        {
            var nbxplorerNetwork = NBXplorerNetworkProvider.GetFromCryptoCode("DEI");
            Add(new BTCPayNetwork()
            {
                CryptoCode = nbxplorerNetwork.CryptoCode,
                BlockExplorerLink = NetworkType == NetworkType.Mainnet ? "https://deimos.network/tx/{0}" : "https://deimos.network/tx/{0}",
                NBitcoinNetwork = nbxplorerNetwork.NBitcoinNetwork,
                NBXplorerNetwork = nbxplorerNetwork,
                UriScheme = "deimos",
                CryptoImagePath = "imlegacy/deimos.png",
                DefaultSettings = BTCPayDefaultSettings.GetDefaultSettings(NetworkType),
                CoinType = NetworkType == NetworkType.Mainnet ? new KeyPath("31'") : new KeyPath("1'")
            });
        }
    }
}

**Comment by Deimoscoin** [comment]
I did the NBitcoin and NBxplorer and that part work fine, i am checking now the BTCpayServer the libraries, thanks

**Comment by Deimoscoin** [comment]
Thanks a lot @NicolasDorier now everything is working like a charm.  i am so happy, thank you so so much.
