### ISSUE TITLE
Cannot login into RTL

### ISSUE THREAD

**Issue by vega113** [btcpayserver/btcpayserver#2584]
when clicking on the server settings->services->LND (Ride the Lightning server)->See information->clicking here
expected: the window with RTL is opened
actual: I get an error 401 Single Sign On Failed!

When checking the log there's the following exception

```2021-06-20 08:59:08.400 +00:00 [WRN] InitializeTasks failed
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at BTCPayServer.Services.Rates.CoinAverageRateProvider.GetExchangeTickersAsync() in /source/BTCPayServer.Rating/Providers/CoinAverageRateProvider.cs:line 212
   at BTCPayServer.HostedServices.RatesHostedService.RefreshCoinAverageSupportedExchanges() in /source/BTCPayServer/HostedServices/RatesHostedService.cs:line 70
   at BTCPayServer.HostedServices.BaseAsyncService.CreateLoopTask(Func`1 act, String caller) in /source/BTCPayServer/HostedServices/BaseAsyncService.cs:line 43
2021-06-20 08:59:13.925 +00:00 [WRN] Error while contacting coinaverage: Unauthorized access to the API, premium plan needed
2021-06-20 09:00:08.483 +00:00 [WRN] InitializeTasks failed
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at BTCPayServer.Services.Rates.CoinAverageRateProvider.GetExchangeTickersAsync() in /source/BTCPayServer.Rating/Providers/CoinAverageRateProvider.cs:line 212
   at BTCPayServer.HostedServices.RatesHostedService.RefreshCoinAverageSupportedExchanges() in /source/BTCPayServer/HostedServices/RatesHostedService.cs:line 70
   at BTCPayServer.HostedServices.BaseAsyncService.CreateLoopTask(Func`1 act, String caller) in /source/BTCPayServer/HostedServices/BaseAsyncService.cs:line 43
2021-06-20 09:01:08.563 +00:00 [WRN] InitializeTasks failed
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at BTCPayServer.Services.Rates.CoinAverageRateProvider.GetExchangeTickersAsync() in /source/BTCPayServer.Rating/Providers/CoinAverageRateProvider.cs:line 212
   at BTCPayServer.HostedServices.RatesHostedService.RefreshCoinAverageSupportedExchanges() in /source/BTCPayServer/HostedServices/RatesHostedService.cs:line 70
   at BTCPayServer.HostedServices.BaseAsyncService.CreateLoopTask(Func`1 act, String caller) in /source/BTCPayServer/HostedServices/BaseAsyncService.cs:line 43
2021-06-20 09:02:08.644 +00:00 [WRN] InitializeTasks failed
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at BTCPayServer.Services.Rates.CoinAverageRateProvider.GetExchangeTickersAsync() in /source/BTCPayServer.Rating/Providers/CoinAverageRateProvider.cs:line 212
   at BTCPayServer.HostedServices.RatesHostedService.RefreshCoinAverageSupportedExchanges() in /source/BTCPayServer/HostedServices/RatesHostedService.cs:line 70
   at BTCPayServer.HostedServices.BaseAsyncService.CreateLoopTask(Func`1 act, String caller) in /source/BTCPay
```

**Comment by vega113** [comment]
[btcpay20210620.log](https://github.com/btcpayserver/btcpayserver/files/6681989/btcpay20210620.log)

**Comment by bolatovumar** [comment]
@vega113 Logs don't seem related to this issue to me (I might be wrong). Have you tried signing out and signing back in and then going to RTL again? Or doing the same AND clearing your cookies and other site data?

**Comment by vega113** [comment]
Yes, also tried to login with a different browser - the same result.

**Comment by bolatovumar** [comment]
@vega113 what version of BTCPay are you using? Updating to the latest version may fix the issue if you are on an older version.

**Comment by vega113** [comment]
Version v1.0.3.127, which I guess is the latest, as I tried to update but nothing happened.

**Comment by dennisreimann** [comment]
Works for me with v1.1.2, which is actually the latest. Are you running the Docker deployment?

**Comment by vega113** [comment]
Yes. So, the update via web interface doesn't work for me. How do I trigger
the update manually?

**Comment by dennisreimann** [comment]
You can use the command line script `./btcpay-update.sh` in the BTCPayServer directory. ([reference](https://docs.btcpayserver.org/Docker/#tooling))

However it'd be interesting to find out why it isn't working via the web UI.

**Comment by vega113** [comment]
I tried again to trigger update, that was the output in the log:
```
21-06-21 07:06:55.949 +00:00 [WRN] Error while contacting coinaverage: Unauthorized access to the API, premium plan needed
2021-06-21 07:07:26.835 +00:00 [WRN] Error while contacting coinaverage: Unauthorized access to the API, premium plan needed
2021-06-21 07:07:41.738 +00:00 [INF] Running SSH command: sudo bash -c '. /etc/profile.d/btcpay-env.sh && nohup btcpay-update.sh > /dev/null 2>&1 & disown'
2021-06-21 07:07:41.743 +00:00 [INF] SSH command executed: 
2021-06-21 07:07:57.400 +00:00 [WRN] Error while contacting coinaverage: Unauthorized access to the API, premium plan needed
2021-06-21 07:08:03.807 +00:00 [INF] BTC: New block
2021-06-21 07:08:27.966 +00:00 [WRN] Error while contacting coinaverage: Unauthorized access to the API, premium plan needed

```
No, restart  happened, so I guess no update.

**Comment by vega113** [comment]
It looks like the script is triggered, but doesn't work.

**Comment by pavlenex** [comment]
> 2021-06-21 07:07:57.400 +00:00 [WRN] Error while contacting coinaverage: Unauthorized access to the API, premium plan needed

You're running a very old version, to fix this particular error you should change the rate source in your store settings to CoinGecko (upon update).

**Comment by vega113** [comment]
It looks like auto-update failed due to the following issue:
```
ubuntu@lunanodepayserver:~/btcpayserver-docker$ sudo ./btcpay-update.sh
Updating 0dbcdd9..51d0976
error: Your local changes to the following files would be overwritten by merge:
	groestlcoin-lightning-cli.sh
Please commit your changes or stash them before you merge.
Aborting
```
when checking what was the change, this was the output:
```
ubuntu@lunanodepayserver:~/btcpayserver-docker$ git diff
diff --git a/groestlcoin-lightning-cli.sh b/groestlcoin-lightning-cli.sh
old mode 100644
new mode 100755
```
I never touched this file and didn't login into the node for years.

The issue was fixed after manually stashing the changes and running the update script and updating to v1.1.2.0
pavlenex Maybe you might consider adding the `git stash` before pulling to the update script.

**Comment by pavlenex** [comment]
@vega113 Thanks, correct this happened because you were quite behind. Is your issue considered resolved now, if so please close it?
