### ISSUE TITLE
DB Error on insert to InvoiceSearches: value too long

### ISSUE THREAD

**Issue by janhn** [btcpayserver/btcpayserver#2641]
**Describe the bug**

An attempt to use BTCPay as a payment method from a WooCommerce eshop fails. The failure appears on the eshop side as a result of clicking on `Proceed to BTCPay`. It worked before, so it's not due to a fresh installation / configuration issue.
Server logs have an error in postgres insert and an exception in btcpayserver runtime:

```
postgres_1      | ERROR:  value too long for type character varying(512)
postgres_1      | STATEMENT:  INSERT INTO "InvoiceSearches" ("InvoiceDataId", "Value")
postgres_1      |       VALUES ($1, $2)
postgres_1      |       RETURNING "Id"
btcpayserver_1  | crit: PayServer:      Unhandled exception in BTCPayMiddleware
btcpayserver_1  | Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
btcpayserver_1  |  ---> Npgsql.PostgresException (0x80004005): 22001: value too long for type character varying(512)
btcpayserver_1  |    at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
btcpayserver_1  | --- End of stack trace from previous location where exception was thrown ---
btcpayserver_1  |    at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
btcpayserver_1  | --- End of stack trace from previous location where exception was thrown ---
btcpayserver_1  |    at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
btcpayserver_1  |    at Npgsql.EntityFrameworkCore.PostgreSQL.Update.Internal.NpgsqlModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
btcpayserver_1  |   Exception data:
btcpayserver_1  |     Severity: ERROR
btcpayserver_1  |     SqlState: 22001
btcpayserver_1  |     MessageText: value too long for type character varying(512)
btcpayserver_1  |     File: varchar.c
btcpayserver_1  |     Line: 624
btcpayserver_1  |     Routine: varchar
btcpayserver_1  |    --- End of inner exception stack trace ---
btcpayserver_1  |    at Npgsql.EntityFrameworkCore.PostgreSQL.Update.Internal.NpgsqlModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
btcpayserver_1  |    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
btcpayserver_1  |    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
btcpayserver_1  |    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
btcpayserver_1  |    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
btcpayserver_1  |    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
btcpayserver_1  |    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
btcpayserver_1  |    at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
btcpayserver_1  |    at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
btcpayserver_1  |    at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
btcpayserver_1  |    at BTCPayServer.Services.Invoices.InvoiceRepository.CreateInvoiceAsync(String storeId, InvoiceEntity invoice) in /source/BTCPayServer/Services/Invoices/InvoiceRepository.cs:line 215
btcpayserver_1  |    at BTCPayServer.Controllers.InvoiceController.CreateInvoiceCoreRaw(InvoiceEntity entity, StoreData store, IPaymentFilter invoicePaymentMethodFilter, CancellationToken cancellationToken) in /source/BTCPayServer/Controllers/InvoiceController.cs:line 276
btcpayserver_1  |    at BTCPayServer.Controllers.InvoiceController.CreateInvoiceCoreRaw(BitpayCreateInvoiceRequest invoice, StoreData store, String serverUrl, List`1 additionalTags, CancellationToken cancellationToken) in /source/BTCPayServer/Controllers/InvoiceController.cs:line 156
btcpayserver_1  |    at BTCPayServer.Controllers.InvoiceController.CreateInvoiceCore(BitpayCreateInvoiceRequest invoice, StoreData store, String serverUrl, List`1 additionalTags, CancellationToken cancellationToken) in /source/BTCPayServer/Controllers/InvoiceController.cs:line 83
btcpayserver_1  |    at BTCPayServer.Controllers.InvoiceControllerAPI.CreateInvoice(BitpayCreateInvoiceRequest invoice, CancellationToken cancellationToken) in /source/BTCPayServer/Controllers/InvoiceController.API.cs:line 37
btcpayserver_1  |    at lambda_method(Closure , Object )
btcpayserver_1  |    at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
btcpayserver_1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
btcpayserver_1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
btcpayserver_1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
btcpayserver_1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
btcpayserver_1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
btcpayserver_1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
btcpayserver_1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
btcpayserver_1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
btcpayserver_1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
btcpayserver_1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
btcpayserver_1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
btcpayserver_1  |    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
btcpayserver_1  |    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
btcpayserver_1  |    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
btcpayserver_1  |    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
btcpayserver_1  |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
btcpayserver_1  |    at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 95
btcpayserver_1  |    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
btcpayserver_1  |    at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 29
btcpayserver_1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

nginx | ... "POST /invoices HTTP/1.0" ...
```

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version: v1.1.2.0
- Deployment Method: Docker

**Comment by pavlenex** [comment]
Somewhat similar error mentioned in #2585

**Comment by pavlenex** [comment]
@janhn did you figure this one out, since this is on woocommerce side, you usually just need to make sure you have a wallet set up and that your server is in sync.

> Before submitting a bug report, check if your Woocommerce store is https, try disabling all plugins to make sure there's no conflict. If it's a pairing problem, try using different browser and disable heavy security plugins.

> If you're getting checkout error, make sure that your BTCPay Server is 100% synced and that you've set up your wallet https://docs.btcpayserver.org/WalletSetup/

**Comment by pavlenex** [comment]
@NicolasDorier you may want to look into the logs above postgres seems to be choking? Though I don't think it's the result of the error @janhn is getting, though it could be.

**Comment by janhn** [comment]
Tested the fix and I'm no longer getting the error and got to the invoice page correctly.
