### ISSUE TITLE
Custom btcpayserver docker image is getting error 500 with just one file change

### ISSUE THREAD

**Issue by franciscopaniskaseker** [btcpayserver/btcpayserver#2699]
**Describe the bug**
I cloned the btcpayserver git, changed the bg.png image to a custom one, and tested. I can see the new image, but i am getting some 500 errors like in "invoice" menu. And I did not see any errors (from default log configuration).

I know that not official docker image is not supported, however wwwroot is just a frontend and I do not see a reason to only one image modified file cause 500 error. I think there is more that official documentaton did not say.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. clone btcpayserver
2. change just one image, like bg.png
3. build the amd64 version
4. publish in a private docker hub
5. edit the .env file in /root/BTCPayServer/.env and change BTCPAY_IMAGE to BTCPAY_IMAGE=yourimage
6. execute btcpay-update.sh inside of /home/ubuntu/bitpayserver-docker
7. Click in "invoice" menu and get the error 500.
If I return the official image, the 500 error disappear.

**Expected behavior**
The frontend continue working.

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:  1.1.2.0
- Deployment Method:  docker
- Browser:  chrome and safari

**Logs (if applicable)**
i am seeing just one error from interface log:
```bash
2021-07-15 04:47:11.924 +00:00 [ERR] Connection id "0HMA79ED2T917", Request id "0HMA79ED2T917:00000001": An unhandled exception was thrown by the application.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path 'metadata.posData', line 1, position 308.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
```

**Setup Parameters**

just changed the domain. nothing else. the default from documentation.

**Additional context**

The idea is just do some customization with text and images, nothing more. So I am not changing any file from backend.

**Comment by franciscopaniskaseker** [comment]
well, no I confirmed that the error 500 is caused by

```bash
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMA79UP4DBDG", Request id "0HMA79UP4DBDG:00000001": An unhandled exception was thrown by the application.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path 'metadata.posData', line 1, position 308.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NBitcoin.JsonConverters.Serializer.ToObject[T](String data, Network network)
   at BTCPayServer.Data.InvoiceDataExtensions.GetBlob(InvoiceData invoiceData, BTCPayNetworkProvider networks) in /source/BTCPayServer/Data/InvoiceDataExtensions.cs:line 10
   at BTCPayServer.Services.Invoices.InvoiceRepository.ToEntity(InvoiceData invoice) in /source/BTCPayServer/Services/Invoices/InvoiceRepository.cs:line 516
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at BTCPayServer.Services.Invoices.InvoiceRepository.GetInvoices(InvoiceQuery queryObject) in /source/BTCPayServer/Services/Invoices/InvoiceRepository.cs:line 662
   at BTCPayServer.Controllers.InvoiceController.ListInvoices(InvoicesModel model) in /source/BTCPayServer/Controllers/InvoiceController.UI.cs:line 710
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 84
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 29
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by Kukks** [comment]
Hey Francis, is it a specific invoice that causes this? This sounds like a regression from https://github.com/btcpayserver/btcpayserver/pull/2456. Are you using the posData in a specific way by any chance?

**Comment by Kukks** [comment]
https://github.com/btcpayserver/btcpayserver/pull/2448 not #2456

**Comment by franciscopaniskaseker** [comment]
Hi @Kukks no. All invoices get that. And I am not using anything specific with posData. actually there is no customization in the code, just one image (background) to test.

**Comment by NicolasDorier** [comment]
I was looking at the bug. It seems like you don't have a valid JSON in the database.

It never happened before, and I can't see how it can happen because we are using a very popular JSON library to build our JSON (we never manipulate json strings directly)

The only reason I can see this happen is if you manually edited the database. Might it be the case?

**Comment by NicolasDorier** [comment]
@franciscopaniskaseker can you share the code you use to create the invoice, and which version it was?

**Comment by NicolasDorier** [comment]
also what was the version you were using?

**Comment by franciscopaniskaseker** [comment]
Actually I did not customized any code. just using the official code from repo. What i was doing was just image and html customization. When i put the official docker image (btcpayserver) it stop the error and when I try my own image it goes bad (even without any customization).

I think there is some inconsistence with the database. When I moved the environment, I did the rsync of the docker volumes to the new server. I saw that the backup script dump the database (oh, and it is failing by the way, but there is another issue about this).

The question is, even with no customization, if I use the official docker image, it works. If i build the image from this git using master branch (the last one) I get the problem.

**Comment by NicolasDorier** [comment]
I don't manage to reproduce. So I need to know when those invoice has been created and how (which API?)

**Comment by franciscopaniskaseker** [comment]
We are using woocommerce plugin "btc pay for woocommerce".

**Comment by NicolasDorier** [comment]
@franciscopaniskaseker what was the version of BTCPay before you did your changes?

**Comment by franciscopaniskaseker** [comment]
the image that is working is this one: https://hub.docker.com/r/btcpayserver/btcpayserver
and the image that got the problem is the one built with current git master branch.

**Comment by NicolasDorier** [comment]
thanks a lot, will give a try

**Comment by NicolasDorier** [comment]
@franciscopaniskaseker it doesn't respond to my question though. DockerHub host many version. Which version you used?

**Comment by franciscopaniskaseker** [comment]
> @franciscopaniskaseker it doesn't respond to my question though. DockerHub host many version. Which version you used?

@NicolasDorier always the latest

**Comment by NicolasDorier** [comment]
@franciscopaniskaseker I tried to go on 1.1.2, create invoice, then go on master, I could not reproduce.

the `posData` of problematic invoices show that you are not using the woocommerce plugin.

```
\"posData\": \"\"{\\\"test\\\":\\\"test\\\", \\\"y\\\":2}\"\"
```

How did you create the invoice with this posData?

**Comment by franciscopaniskaseker** [comment]
I am trying to get this info.

**Comment by pavlenex** [comment]
@franciscopaniskaseker any updates, do you still experience he same problem?

**Comment by pavlenex** [comment]
Closing due to inactivity. Will re-open once @franciscopaniskaseker gets back to us.
