### ISSUE TITLE
Greenfield API: Unhandled error on "preview proposed store on-chain payment method"

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#2795]
**Describe the bug**
On setting the `accountKeyPath` data of the [preview proposed store on-chain payment methods](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/StoreOnChainPaymentMethods_GetOnChainPaymentMethodPreview) BTCPay Server shows an unhandled Exception error in the logs.

**To Reproduce the bug**
On the mentioned endpoint when you set the `derivationScheme` with a legacy tpub key and the `accountKeyPath` to `m/84'/0'/0'` it throws an internal server error.

**Expected behavior**
Should return other http status code with meaningful error message.

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    v1.2.1.0
- Deployment Method:        Docker
              
**Logs (if applicable)**
```
2021-08-19 21:41:08.868 +00:00 [ERR] Connection id "0HMAUJTM9RLGR", Request id "0HMAUJTM9RLGR:00000001": An unhandled exception was thrown by the application.
NBitcoin.JsonConverters.JsonObjectException: Invalid rooted key path
   at NBitcoin.JsonConverters.KeyPathJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 95
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 30
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Additional context**

In the API docs the accountKeyPath example seems to have a fingerprint prefixed e.g. `abcd82a1/84'/0'/0'` from what I saw in searching some code it seems to be a fingerprint of the derivationScheme? Not sure how this get computed, any link to read about it + maybe docs need to be more explicit? Nevertheless using the normal account path should also work and if not it should throw a proper error I assume.

**Comment by bolatovumar** [comment]
@ndeet looks like the prefix is the wallet root fingerprint. You can see it by navigating to **Store > Settings > Modify** (next to your BTC walet). You will see a row labeled "Root Fingerprint".

I think this explains how it's calculated: https://bitcoin.stackexchange.com/questions/76816/trying-to-understand-parent-fingerprint-in-hd-wallets

**Comment by Kukks** [comment]
> **Describe the bug**
> On setting the `accountKeyPath` data of the [preview proposed store on-chain payment methods](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/StoreOnChainPaymentMethods_GetOnChainPaymentMethodPreview) BTCPay Server shows an unhandled Exception error in the logs.
> 
> **To Reproduce the bug**
> On the mentioned endpoint when you set the `derivationScheme` with a legacy tpub key and the `accountKeyPath` to `m/84'/0'/0'` it throws an internal server error.
> 
> **Expected behavior**
> Should return other http status code with meaningful error message.
> 
> **Your BTCPay Environment (please complete the following information):**
> 
> * BTCPay Server Version:    v1.2.1.0
> * Deployment Method:        Docker
> 
> **Logs (if applicable)**
> 
> ```
> 2021-08-19 21:41:08.868 +00:00 [ERR] Connection id "0HMAUJTM9RLGR", Request id "0HMAUJTM9RLGR:00000001": An unhandled exception was thrown by the application.
> NBitcoin.JsonConverters.JsonObjectException: Invalid rooted key path
>    at NBitcoin.JsonConverters.KeyPathJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
>    at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
>    at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
>    at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
>    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
>    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
>    at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 95
>    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
>    at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 30
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
> ```
> 
> **Additional context**
> 
> In the API docs the accountKeyPath example seems to have a fingerprint prefixed e.g. `abcd82a1/84'/0'/0'` from what I saw in searching some code it seems to be a fingerprint of the derivationScheme? Not sure how this get computed, any link to read about it + maybe docs need to be more explicit? Nevertheless using the normal account path should also work and if not it should throw a proper error I assume.

The accountKeyPath is a `RootedKeyPath`, which is a combination of a master fingerprint (computed from the seed) and the account path (the path used to generate the xpub from the seed). In BTCPay, we require both of these, and so does the `RootedKeyPath` type.

**Comment by ndeet** [comment]
Ok thanks so the correct way is to hash the private key `ripemd160(sha256(parentpriv))` but only use the first 8 chars as prefix (and combine with the account path)?

The exception when passing `m/84'/0'/0'` still needs fixing and return a proper http error?

**Comment by NicolasDorier** [comment]
Other problem is that this call shouldn't even have a accountKey parameter...

**Comment by NicolasDorier** [comment]
Updated the doc documenting an unused field, and also fixed the underlying issue of not properly reporting when we can't deserialize a JsonException.
