### ISSUE TITLE
Do not allow invoice `cancellation` for `payment requests` when "Allow payee to create invoices in their own denomination" is not enabled

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#2802]
**Describe the bug**

The payment request can be easily canceled, which is a bit out of ordinary behavior because such an invoice is marked as `invalid marked`. If a user is used to seeing `invalid` status in their invoices view, they may make a mistake of labeling it as `complete` thinking the payment request is paid but has not received confirmation on the blockchain on time.

This is indeed an edge-case, but due to this unexpected error, a mistake can happen. I've talked to @Kukks about this and we agreed this shouldn't happen.

The proposal is to disable `payment request cancelation` unless `Allow payee to create invoices in their own denomination` is enabled on the payment request. The reason behind this is to allow payee who may have created a wrong amount to `cancel the invoice`

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Create a payment request
2. Click `pay`button
3. Click `cancel invoice`
4. Go to `invoices` list and see the payment request invoice marked as `invalid`

![Screenshot 2021-08-23 at 10 43 23](https://user-images.githubusercontent.com/36959754/130417757-d85947ad-19fa-4d1e-bff6-34eb8bfe70bb.png)

### Logs

Interestingly enough this also throws an error in logs 

```
021-08-23 08:18:04.491 +00:00 [INF] BTC: New block
2021-08-23 08:18:09.140 +00:00 [INF] User with ID 2c117299-f3e3-424c-8709-587a14c27b95 logged in with 2fa.
2021-08-23 08:30:13.469 +00:00 [ERR] Failed to invoke hub method 'Pay'.
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.PaymentRequest.PaymentRequestHub.Pay(Nullable`1 amount) in /source/BTCPayServer/PaymentRequest/PaymentRequestHub.cs:line 52
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ExecuteHubMethod(ObjectMethodExecutor methodExecutor, THub hub, Object[] arguments)
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<>c__DisplayClass13_0.<<Invoke>g__ExecuteInvocation|0>d.MoveNext()
2021-08-23 08:30:22.624 +00:00 [INF] Invoice 9GxoEfPEf8Awf6YSF52qy new event: invoice_created (1001)
2021-08-23 08:30:26.275 +00:00 [INF] Invoice 9GxoEfPEf8Awf6YSF52qy new event: invoice_markedInvalid (1008)
```

**Comment by bolatovumar** [comment]
I wonder if it would make sense to include an additional status here so that if a user cancels a payment request it's marked as "cancelled" instead of "invalid"? Or would that be too much just for this one case?

**Comment by pavlenex** [comment]
Haha please let's not due that, the statuses we have are already mind-boggling for most users. Since this is an edge-case simply not allowing it makes sense to me so concept ack on #2843
