### ISSUE TITLE
Prune transactions error on wallet - stack trace in logs

### ISSUE THREAD

**Issue by danielalexiuc** [btcpayserver/btcpayserver#2832]
When I click "Prune old  transactions from history" on the Settings tab, the page returns a 500 error. Checking the logs, I see the error message below.

It is a large wallet with over 30,000 transactions.

BTCPayServer 1.2.1.0

```
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMB82F2B4T9H", Request id "0HMB82F2B4T9H:00000001": An unhandled exception was thrown by the application.
DBTrie.Storage.Cache.NoMorePageAvailableException: No page available to evict from cache, you should increase the maximum number of page, or commit more often.
   at DBTrie.Storage.Cache.PagePool.NewPage(Int32 pageNumber)
   at DBTrie.Storage.CacheStorage.FetchPage(Int32 p)
   at DBTrie.Storage.CacheStorage.Read(Int64 offset, Memory1 output)
   at DBTrie.TrieModel.LTrie.ReadNodeStruct(Int64 pointer)
   at DBTrie.TrieModel.LTrie.FindBestMatch(ReadOnlyMemory1 key)
   at DBTrie.TrieModel.LTrie.DeleteRow(ReadOnlyMemory1 key)
   at DBTrie.TrieModel.LTrie.DeleteRow(String key)
   at DBTrie.Table.Delete(String key)
   at NBXplorer.Repository.Index.RemoveKey(String key) in /source/NBXplorer/Repository.cs:line 266
   at NBXplorer.Repository.Prune(TrackedSource trackedSource, List1 prunable) in /source/NBXplorer/Repository.cs:line 1099
   at NBXplorer.Controllers.MainController.Prune(String cryptoCode, DerivationStrategyBase derivationScheme, PruneRequest request) in /source/NBXplorer/Controllers/MainController.cs:line 1214
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication1 application)
```

**Comment by pavlenex** [comment]
This one should've been fixed with latest NBX update. Please `btcpay-update.sh` as Nicolas mentioned on mattermost and it should work, let us know if it doesn't and we can troubleshoot further.

**Comment by danielalexiuc** [comment]
Problem solved! Thanks for the update.
