### ISSUE TITLE
Shopify Integration - unhandled exception on Umbrel

### ISSUE THREAD

**Issue by KayBeSee** [btcpayserver/btcpayserver#2838]
**Describe the bug**
I'm not able to connect my btcpayserver instance on my umbrel to shopify.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Install btcpayserver on Umbrel
2. Create store
3. Go to `http://umbrel.local:3003/stores/STORE_ID/integrations/shopify`
4. Input Example Url from Shopify Private App
5. Click "Connect to Spotify"

**Expected behavior**
I expected to see the `Shopify integration successfully updated` screen with my shop name, apikey, password, and additional script.

**Screenshots**
![Screen Shot 2021-09-03 at 5 09 50 PM](https://user-images.githubusercontent.com/1429113/132073167-c866d63b-c195-43be-87f8-d26179fce1ce.png)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    BTCPayServer v1.2.1.0
- Deployment Method:        Umbrel
- Browser:                 Chrome, Tor
- 
**Logs (if applicable)**
From docker container:

```
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMBBQLKR79B0", Request id "0HMBBQLKR79B0:00000001": An unhandled exception was thrown by the application.
System.Net.Http.HttpRequestException: Resource temporarily unavailable
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at BTCPayServer.Plugins.Shopify.ShopifyApiClient.SendRequest(HttpRequestMessage req) in /source/BTCPayServer/Plugins/Shopify/ShopifyApiClient.cs:line 48
   at BTCPayServer.Plugins.Shopify.ShopifyApiClient.OrdersCount() in /source/BTCPayServer/Plugins/Shopify/ShopifyApiClient.cs:line 115
   at BTCPayServer.Plugins.Shopify.ShopifyController.EditShopifyIntegration(String storeId, ShopifySettings vm, String command, String exampleUrl) in /source/BTCPayServer/Plugins/Shopify/ShopifyController.cs:line 256
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 95
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 30
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Setup Parameters**

**Additional context**
I tried on clearnet as well as tor and was unsuccessful. I was able to connect using the Live Demo on btcpayserver's website however.

**Comment by pavlenex** [comment]
Hey @KayBeSee I think this is because you're trying to connect to your `.local`. BTCPay needs to be exposed outside of your local network for this to work. However unsure, why we're throwing an exception there. 

@rockstardev any thoughts?

**Comment by KayBeSee** [comment]
That makes sense. I did a little more digging and came across [this page in the docs](https://docs.btcpayserver.org/ReverseProxyToTor/) about tor reverse proxy.

I'm still a little confused by these instructions though (I'm a devops pleb, sorry), so I'm gonna walk through what I think I need to do to get this working.

1) Sign up for LunaNode
2) Point the DNS record for my domain to some values that LunaNode provides me
3) Get into LundaNode server (SSH?)
4) Run those docker commands
5) Visit my domain, should direct me to my BTCPS store
      - sidenote: What is the domain / how can I access my store right now locally?

**Comment by pavlenex** [comment]
@KayBeSee I'm not sure, never tried it, but if you're already hosting a VPS, there's no really need to do it on Umbrel, just host BTCPay on a VPS. I think @openoms is the one who wrote the instructions.

**Comment by pavlenex** [comment]
Or @NicolasDorier maybe we can give a better error here instead of exception when someone tries to connect via .local?
