### ISSUE TITLE
Liquid transaction invoice not confirming on BTCpayserver. 

### ISSUE THREAD

**Issue by yilakb** [btcpayserver/btcpayserver#2867]
**Describe the bug**
BTCPayserver did not detect the payment on the liquid network after the invoice was paid and validated on chain, instead presenting 0 confirmation on the invoice.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. create an invoice to be paid in LBTC or USDt
2. pay the invoice using LBTC or USDt
3. even after payment confirmed on chain. 

**Expected behavior**

**Screenshots**

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    
- Deployment Method:        
- Browser:                  

**Logs (if applicable)**

2021-09-09 11:36:35.740 +00:00 [INF] Invoice MALGwogk6xX8z2WHpFpifB new event: invoice_created (1001)
2021-09-09 11:36:35.785 +00:00 [INF] LBTC: New block
2021-09-09 11:36:35.787 +00:00 [INF] LBTC: New block
2021-09-09 11:36:35.792 +00:00 [INF] LBTC: New block
2021-09-09 11:36:35.793 +00:00 [INF] LBTC: New block
2021-09-09 11:37:07.543 +00:00 [INF] BTC: New transaction af47a0d1ad6237fc77ce0c04d4e71770f5f54ae8beb3c14a8e768d386efe3ef4 (Unconfirmed)
2021-09-09 11:37:35.419 +00:00 [INF] LBTC: New block
2021-09-09 11:37:35.423 +00:00 [INF] LBTC: New block
2021-09-09 11:37:35.423 +00:00 [INF] LBTC: New block
2021-09-09 11:37:35.431 +00:00 [INF] LBTC: New block
2021-09-09 11:37:54.421 +00:00 [INF] Invoice QJKZeTMEy1ZytYxB4fqqdQ new event: invoice_created (1001)
2021-09-09 11:38:27.259 +00:00 [INF] LCAD: New transaction 2a384174c277fef4a3426472246f30b3221b9b135986cbf38e22bae7c2511713 (Unconfirmed)
2021-09-09 11:38:27.258 +00:00 [INF] USDt: New transaction 2a384174c277fef4a3426472246f30b3221b9b135986cbf38e22bae7c2511713 (Unconfirmed)
2021-09-09 11:38:27.263 +00:00 [INF] ETB: New transaction 2a384174c277fef4a3426472246f30b3221b9b135986cbf38e22bae7c2511713 (Unconfirmed)
2021-09-09 11:38:27.900 +00:00 [INF] LBTC (On-Chain): New payment details lq1qqwyy7x0lfqk4uulyt59ac4n8txahmesv7emgace59ga45uyxn3gvm5tgnqas9vvdhe2lkxrkp2rr2n7ja3anqnj4ugyay3mp7 for invoice QJKZeTMEy1ZytYxB4fqqdQ
2021-09-09 11:38:27.903 +00:00 [INF] Invoice QJKZeTMEy1ZytYxB4fqqdQ new event: invoice_receivedPayment (1002)
2021-09-09 11:38:27.910 +00:00 [INF] Adding 2 labels to 2a384174c277fef4a3426472246f30b3221b9b135986cbf38e22bae7c2511713 in wallet S-CB1xxE78rsSdJ5oee6PZbu3jU5WPc4FWVd78X3DKMJ79-LBTC

2021-09-09 11:38:27.912 +00:00 [INF] LBTC: New transaction 2a384174c277fef4a3426472246f30b3221b9b135986cbf38e22bae7c2511713 (Unconfirmed)
2021-09-09 11:38:35.417 +00:00 [INF] LBTC: New block
2021-09-09 11:38:35.420 +00:00 [INF] LBTC: New block
2021-09-09 11:38:35.426 +00:00 [INF] LBTC: New block
2021-09-09 11:38:35.427 +00:00 [INF] LBTC: New block
2021-09-09 11:39:36.586 +00:00 [INF] USDt: New transaction 2a384174c277fef4a3426472246f30b3221b9b135986cbf38e22bae7c2511713 (Confirmed)
2021-09-09 11:39:36.588 +00:00 [INF] LCAD: New transaction 2a384174c277fef4a3426472246f30b3221b9b135986cbf38e22bae7c2511713 (Confirmed)
2021-09-09 11:39:36.590 +00:00 [INF] ETB: New transaction 2a384174c277fef4a3426472246f30b3221b9b135986cbf38e22bae7c2511713 (Confirmed)
2021-09-09 11:39:36.611 +00:00 [INF] LBTC: New transaction 2a384174c277fef4a3426472246f30b3221b9b135986cbf38e22bae7c2511713 (Confirmed)
2021-09-09 11:39:36.645 +00:00 [INF] LBTC: New block
2021-09-09 11:39:36.662 +00:00 [INF] LBTC: New block
2021-09-09 11:39:36.662 +00:00 [INF] LBTC: New block
2021-09-09 11:39:36.670 +00:00 [INF] LBTC: New block

**Setup Parameters**

**Additional context**

**Comment by petzsch** [comment]
I was able to reproduce the issue. Using different seeds for LBTC and USDt if that is relevant.
On the invoice page a transaction is recognized, but crossed through:

![image](https://user-images.githubusercontent.com/1374810/132684681-e69e9ffc-f0fa-498e-ab37-4b47a1969f22.png)

**Comment by Kukks** [comment]
@NicolasDorier something related to the new nbx update?

**Comment by petzsch** [comment]
not sure if this is related, but shortly after the payment and the sweeping of the elemts wallet through the CLI script, the elements container reports this in it's log:

`2021-09-09T12:44:35Z UpdateTip: new best=fdab918e983a2f085fbb134199c185a28dd06c12ef15352f44de986cd2631495 height=1481090 version=0x22000000 tx=2328256 date='2021-09-09T12:43:58Z' progress=1.000000 cache=0.0MiB(118txo) warning='67 of last 100 blocks have unexpected version'`

and is shown as synching in the GUI.

**Comment by petzsch** [comment]
log from nbxplorer container (hope it helps debugging this)

`info: Events:         LBTC: New block 4a9c3c0fbb1cb8ff106f474e967bc5ec17a7ba066abd605bfc6f0c078e79b609 (1481075)
info: Events:         LBTC: New block cb55d143ead7611750f6fbe43c7eba5af80e405ea548b4e97963d4b720c876db (1481076)
fail: Explorer:       LBTC: Unhandled error while treating a message
fail: Explorer:       System.IO.EndOfStreamException: No more byte to read
         at NBitcoin.BitcoinStream.ReadWriteBytes(Span`1 data)
         at NBitcoin.BitcoinStream.ReadWriteBytes(Byte[]& data, Int32 offset, Int32 count)
         at NBitcoin.BitcoinStream.ReadWrite(Script data)
         at NBitcoin.BitcoinStream.ReadWrite(Script& script)
         at NBitcoin.TxOut.ReadWrite(BitcoinStream stream)
         at NBitcoin.BitcoinSerializableExtensions.ReadWrite(IBitcoinSerializable serializable, Stream stream, Boolean serializing, ConsensusFactory consensusFactory, Nullable`1 version)
         at NBitcoin.BitcoinSerializableExtensions.ReadWrite(IBitcoinSerializable serializable, Stream stream, Boolean serializing, Network network, Nullable`1 version)
         at NBXplorer.Repository.GetOutPointToTxOut(IList`1 outPoints) in /source/NBXplorer/Repository.cs:line 677
         at NBXplorer.Repository.GetOutPointToTxOut(IList`1 outPoints) in /source/NBXplorer/Repository.cs:line 670
         at NBXplorer.Repository.GetMatches(IList`1 txs, uint256 blockId, DateTimeOffset now, Boolean useCache) in /source/NBXplorer/Repository.cs:line 1262
         at NBXplorer.ExplorerBehavior.SaveMatches(Transaction transaction, Boolean fireEvents) in /source/NBXplorer/ExplorerBehavior.cs:line 224
         at NBXplorer.ExplorerBehavior.<>c__DisplayClass27_0.<<Run>b__0>d.MoveNext() in /source/NBXplorer/ExplorerBehavior.cs:line 169
info: Events:         LBTC: Node state changed: Ready => NotStarted
info: Configuration:  LBTC: Testing RPC connection to http://elementsd_liquid:43782/
info: Explorer:       LBTC: Closed connection with node
info: Configuration:  LBTC: RPC connection successful
info: Configuration:  LBTC: Full node version detected: 180112
info: Configuration:  LBTC: Loading chain from cache...
info: Configuration:  LBTC: Height: 1481010
info: Configuration:  LBTC: Trying to connect via the P2P protocol to trusted node (elementsd_liquid:39388)...
info: Explorer:       LBTC: TCP Connection succeed, handshaking...
info: Explorer:       LBTC: Handshaked
info: Configuration:  LBTC: Loading chain from node
info: Explorer:       LBTC: Loading chain...
info: Explorer:       LBTC: Chain loaded
info: Explorer:       LBTC: NBXplorer is correctly whitelisted by the node
info: Configuration:  LBTC: Height: 1481076
info: Configuration:  LBTC: Saving chain to cache...
info: Configuration:  LBTC: Chain cached
info: Explorer:       LBTC: Handshaked node
info: Explorer:       LBTC: Starting scan at block 1481076
info: Events:         LBTC: Node state changed: NotStarted => NBXplorerSynching
info: Events:         LBTC: Node state changed: NBXplorerSynching => Ready
info: Events:         LTC: New block 448ff53548e739d3078c13515c7a54f050e9d33d788de021f02d2efa09d0a448 (2119779)
warn: Explorer:       LBTC: Error while saving block in database, retrying in 1 seconds (No more byte to read)
System.IO.EndOfStreamException: No more byte to read
   at NBitcoin.BitcoinStream.ReadWriteBytes(Span`1 data)
   at NBitcoin.BitcoinStream.ReadWriteBytes(Byte[]& data, Int32 offset, Int32 count)
   at NBitcoin.BitcoinStream.ReadWrite(Script data)
   at NBitcoin.BitcoinStream.ReadWrite(Script& script)
   at NBitcoin.TxOut.ReadWrite(BitcoinStream stream)
   at NBitcoin.BitcoinSerializableExtensions.ReadWrite(IBitcoinSerializable serializable, Stream stream, Boolean serializing, ConsensusFactory consensusFactory, Nullable`1 version)
   at NBitcoin.BitcoinSerializableExtensions.ReadWrite(IBitcoinSerializable serializable, Stream stream, Boolean serializing, Network network, Nullable`1 version)
   at NBXplorer.Repository.GetOutPointToTxOut(IList`1 outPoints) in /source/NBXplorer/Repository.cs:line 677
   at NBXplorer.Repository.GetOutPointToTxOut(IList`1 outPoints) in /source/NBXplorer/Repository.cs:line 670
   at NBXplorer.Repository.GetMatches(IList`1 txs, uint256 blockId, DateTimeOffset now, Boolean useCache) in /source/NBXplorer/Repository.cs:line 1262
   at NBXplorer.ExplorerBehavior.SaveMatches(Block block) in /source/NBXplorer/ExplorerBehavior.cs:line 183
warn: Explorer:       LBTC: Error while saving block in database, retrying in 2 seconds (No more byte to read)`

**Comment by Kukks** [comment]
fix is in nbxplorer https://github.com/dgarage/NBXplorer/pull/340
