### ISSUE TITLE
Disabling altcoins breaks invoice creation

### ISSUE THREAD

**Issue by balboah** [btcpayserver/btcpayserver#2879]
**What**

After removing `BTCPAYGEN_CRYPTO2=xmr` from the docker compose generator leaving only Bitcoin and lightning enabled, I'm unable to create new invoices by posting to /invoices.

Logs says `Invalid PaymentMethodId`

**How**

1. Enable BTCPAYGEN_CRYPTO2=xmr
1. Run [docker setup scripts](https://github.com/btcpayserver/btcpayserver-docker)
1. Remove BTCPAYGEN_CRYPTO2
1. Run [docker setup scripts](https://github.com/btcpayserver/btcpayserver-docker)
1. no new invoices can be created
1. Enable BTCPAYGEN_CRYPTO2=xmr
1. Run [docker setup scripts](https://github.com/btcpayserver/btcpayserver-docker)
1. invoices can be created again

**Expected behavior**

New invoices should be created for the payment methods available, any invalid references should be ignored.

**BTCPay Environment**
- BTCPay Server Version:     v1.2.3.0 (altcoins)
- Deployment Method:         Docker

<details>
<summary>Logs</summary>

```
System.FormatException: Invalid PaymentMethodId
   at BTCPayServer.Payments.PaymentMethodId.Parse(String str) in /source/BTCPayServer/Payments/PaymentMethodId.cs:line 111
   at BTCPayServer.Data.StoreBlob.<>c.<GetExcludedPaymentMethods>b__125_0(String p) in /source/BTCPayServer/Data/StoreBlob.cs:line 174
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at BTCPayServer.Data.StoreBlob.GetExcludedPaymentMethods() in /source/BTCPayServer/Data/StoreBlob.cs:line 174
   at BTCPayServer.Controllers.InvoiceController.CreateInvoiceCoreRaw(InvoiceEntity entity, StoreData store, IPaymentFilter invoicePaymentMethodFilter, String[] additionalSearchTerms, CancellationToken cancellationToken) in /source/BTCPayServer/Controllers/InvoiceController.cs:line 230
   at BTCPayServer.Controllers.InvoiceController.CreateInvoiceCoreRaw(BitpayCreateInvoiceRequest invoice, StoreData store, String serverUrl, List`1 additionalTags, CancellationToken cancellationToken) in /source/BTCPayServer/Controllers/InvoiceController.cs:line 154
   at BTCPayServer.Controllers.InvoiceController.CreateInvoiceCore(BitpayCreateInvoiceRequest invoice, StoreData store, String serverUrl, List`1 additionalTags, CancellationToken cancellationToken) in /source/BTCPayServer/Controllers/InvoiceController.cs:line 82
   at BTCPayServer.Controllers.InvoiceControllerAPI.CreateInvoice(BitpayCreateInvoiceRequest invoice, CancellationToken cancellationToken) in /source/BTCPayServer/Controllers/InvoiceController.API.cs:line 37
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 95
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 30
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

</details>

<details>
<summary>Setup Parameters</summary>

```
BTCPAY_HOST=foobar
NBITCOIN_NETWORK=mainnet
BTCPAYGEN_CRYPTO1=btc
BTCPAYGEN_CRYPTO2=xmr
BTCPAYGEN_LIGHTNING=lnd
LETSENCRYPT_EMAIL=foobar
LIGHTNING_ALIAS=foobar
ACME_CA_URI=https://acme-v02.api.letsencrypt.org/directory
BTCPAYGEN_ADDITIONAL_FRAGMENTS="opt-more-memory"
```

</details>

**Comment by Kukks** [comment]
> **What**
> 
> After removing `BTCPAYGEN_CRYPTO2=xmr` from the docker compose generator leaving only Bitcoin and lightning enabled, I'm unable to create new invoices by posting to /invoices.
> 
> Logs says `Invalid PaymentMethodId`
> 
> **How**
> 
> 1. Enable BTCPAYGEN_CRYPTO2=xmr
> 2. Run [docker setup scripts](https://github.com/btcpayserver/btcpayserver-docker)
> 3. Remove BTCPAYGEN_CRYPTO2
> 4. Run [docker setup scripts](https://github.com/btcpayserver/btcpayserver-docker)
> 5. no new invoices can be created
> 6. Enable BTCPAYGEN_CRYPTO2=xmr
> 7. Run [docker setup scripts](https://github.com/btcpayserver/btcpayserver-docker)
> 8. invoices can be created again
> 
> **Expected behavior**
> 
> New invoices should be created for the payment methods available, any invalid references should be ignored.
> 
> **BTCPay Environment**
> 
> * BTCPay Server Version:     v1.2.3.0 (altcoins)
> * Deployment Method:         Docker
> 
> Logs
> Setup Parameters

Provide better logs.
