### ISSUE TITLE
Error creating invoice after merging commit 2df60bd12187fe36ccfb556c892bc0f257bb2954

### ISSUE THREAD

**Issue by lepipele** [btcpayserver/btcpayserver#29]
Here is full exception:

```
System.NullReferenceException: Object reference not set to an instance of an object.

   at BTCPayServer.Services.Wallets.BTCPayWallet.<ReserveAddressAsync>d__3.MoveNext() in D:\!Projects\BtcPayServer\btcpayserver\BTCPayServer\Services\Wallets\BTCPayWallet.cs:line 46

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

   at BTCPayServer.Controllers.InvoiceController.<CreateInvoiceCore>d__11.MoveNext() in D:\!Projects\BtcPayServer\btcpayserver\BTCPayServer\Controllers\InvoiceController.cs:line 138

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

   at BTCPayServer.Controllers.InvoiceController.<CreateInvoice>d__32.MoveNext() in D:\!Projects\BtcPayServer\btcpayserver\BTCPayServer\Controllers\InvoiceController.UI.cs:line 349

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.<Invoke>d__3.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at BTCPayServer.Hosting.BTCPayMiddleware.<Invoke>d__4.MoveNext() in D:\!Projects\BtcPayServer\btcpayserver\BTCPayServer\Hosting\BTCpayMiddleware.cs:line 96

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

I assume it maybe has to do with newly added LTC - maybe I it is now required to define derivation scheme for LTC network. These are the lines:

```
        public async Task<BitcoinAddress> ReserveAddressAsync(DerivationStrategy derivationStrategy)
        {
            var client = _Client.GetExplorerClient(derivationStrategy.Network);
            var pathInfo = await client.GetUnusedAsync(derivationStrategy.DerivationStrategyBase, DerivationFeature.Deposit, 0, true).ConfigureAwait(false);
            return pathInfo.ScriptPubKey.GetDestinationAddress(client.Network); // this line fails
        }
```

So, yeah... probably that. Guess we should give better error to customers before pushing this to production or support specifying if customers want to enable LTC payments also.

**Comment by NicolasDorier** [comment]
I don't manage to repro,  how do you do ?

**Comment by lepipele** [comment]
@NicolasDorier you probably just need to go to: http://localhost:14142/stores/[StoreId] and then delete LTC Derivation Scheme.

I've got the error just by:

1. Pulling changes 
2. Starting the BtcPayServer
3. Trying to create invoice -> got exception

So if you have outdated server - you may trying following that flow and it'll reproduce. Looking at code I'm now pretty sure that you can get the exception if you also delete LTC derivation scheme you've defined for yourself on your machine.

**Comment by NicolasDorier** [comment]
Ha I don't manage to reproduce. Can you step by step ?

What is null ? client ? pathInfo ? what is the network?

**Comment by lepipele** [comment]
@NicolasDorier pathInfo ... I'm connecting on Slack if you have time to talk.

**Comment by NicolasDorier** [comment]
You can close this issue I know where it comes from: I renamed the images, so when you started the service, you had a brand new nbxplorer, not the old one.

```
docker-compose down --v
docker-compose up dev
```
