### ISSUE TITLE
System.Net.Mail.SmtpException: Failure sending mail after changing mail settings

### ISSUE THREAD

**Issue by BigLogie** [btcpayserver/btcpayserver#2919]
After changing mail settings, mail is being sent however extensive errors within logs. 

This only occurred after changing mail settings. 

2021-09-24 08:55:12.307 +00:00 [WRN] Unhandled exception while job running
System.AggregateException: One or more errors occurred. (Failure sending mail.)
 ---> System.Net.Mail.SmtpException: Failure sending mail.
 ---> System.Net.Sockets.SocketException (99): Cannot assign requested address
   at System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.UnsafeBeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state, Boolean flowContext)
   at System.Net.Sockets.Socket.PostOneBeginConnect(MultipleAddressConnectAsyncResult context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)
   at System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.InitializeConnectionCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.End(IAsyncResult result)
   at System.Net.Mail.SmtpTransport.EndGetConnection(IAsyncResult result)
   at System.Net.Mail.SmtpClient.ConnectCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at NBitcoin.Extensions.WithCancellation(Task task, CancellationToken cancellationToken)
   at BTCPayServer.Services.Mails.EmailSender.<>c__DisplayClass2_0.<<SendEmail>b__0>d.MoveNext() in /source/BTCPayServer/Services/Mails/EmailSender.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at BTCPayServer.HostedServices.BackgroundJobClient.BackgroundJob.Run(CancellationToken cancellationToken) in /source/BTCPayServer/HostedServices/BackgroundJobSchedulerHostedService.cs:line 77
   --- End of inner exception stack trace ---

Is causing IPn notifications to be sent twice in quick succession as well. 

- BTCPay Server Version:    Latest current
- Deployment Method:     Raspberry Pi 4 - 8GB Ram

**Comment by satwo** [comment]
Can you be more specific? Which mail settings did you change?

**Comment by BigLogie** [comment]
> 
> 
> Can you be more specific? Which mail settings did you change?

Normal email settings in UI - Email Server - /server/emails

**Comment by pavlenex** [comment]
Server Settings > Email
or Store Settings > Email?

Can you screenshot or screen record what you're experiencing, it's not entirely clear.

**Comment by BigLogie** [comment]
Correction - Not related to IPN notifications issue. 

However no email being sent, but test emails work all ok.

**Comment by pavlenex** [comment]
What kind of email are you expecting to be sent? For now the only thing that works with this is `forgot your password`it doesn't send an email for anything else.
