### ISSUE TITLE
Crowdfunding topup invoice doesn't work when there isn't a perk added

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#3048]
**Describe the bug**
When you create a crowdfunding app and `do not add any perk` the topup feature
**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to Create a crowdfunding app with `sats` and don't add perks.
2. Click on `contribute`
3. See error, no invoice can be generated

**Expected behavior**

**Screenshots**

![2021-11-01_09-36-44 (1)](https://user-images.githubusercontent.com/36959754/139645001-be38ff38-0d1e-4b2a-a1b6-f0a21e4c541e.gif)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:     v1.3.1.0
- Deployment Method:         Docker
- Browser:                   Safari, Firefox

**Logs (if applicable)**

I am not sure if the logs below are about this error, but this appears in my logs at about the same time as the error.

```
ystem.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at BTCPayServer.Controllers.InvoiceController.GetInvoiceModel(String invoiceId, PaymentMethodId paymentMethodId, String lang) in /source/BTCPayServer/Controllers/InvoiceController.UI.cs:line 518
   at BTCPayServer.Controllers.InvoiceController.Checkout(String invoiceId, String id, String paymentMethodId, String view, String lang) in /source/BTCPayServer/Controllers/InvoiceController.UI.cs:line 448
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 94
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 29
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Setup Parameters**

**Additional context**

This creates 0-amount invoice which is marked as `paid`

Someone reported this additionally:

> I was able to bypass the entering data bug by leaving noscript on, then allowing scripts after the data was entered and the payment page with QR code opened replicated this in Brave Browser, Edge, and Safari

**Comment by satwo** [comment]
I replicated this issue using `sats`, `USD`, and `BTC`, so I assume it's not related to the currency selection. I'm happy to take this one off of @Kukks' hands.

**Comment by satwo** [comment]
@pavlenex , I am also having problems when a perk is added:

![image](https://user-images.githubusercontent.com/4956763/140169957-be04a875-bb63-4410-8cd7-eaa161846cef.png)

Can you replicate this? I'm seeing the same client-side js error for both situations:

![image](https://user-images.githubusercontent.com/4956763/140170094-ca764cab-b2d0-4f5a-93ec-95bd317e6d0c.png)



FWIW, I think the reason it's marked as `paid` is probably because being a 0-amount invoice, the amount is fully satisfied at the outset; due to whatever error is going on, it doesn't let you change the input from '0'.

**Comment by satwo** [comment]
A couple more notes: 

- This seems to be a breaking change as of `1.3.0`. 
- The reason for the 0-amount invoice is probably because, by having an amount of zero, it's already `paid` at the moment of creation.
