### ISSUE TITLE
BTCPayServer attempting to connect to Eclair using TLS

### ISSUE THREAD

**Issue by Kixunil** [btcpayserver/btcpayserver#3054]
**Describe the bug**
When creating an invoice using the `/invoices/create` page it's no longer possible to use `BTC`  currency. I remember this being possible in the past, so I'm filling this as a bug.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to "Invoices" page
2. Click on "Create an invoice"
3. Fill amount (e.g. 0.0001, doesn't matter)
4. Enter "BTC" (without quotes) into the "Currency" field
5. Click Create

**Expected behavior**

An invoice is created with specified amount in BTC.

(Ideally SAT would be possible too, but that'd be a feature request, not a bug.)

**Screenshots**

![Create an invoice - error "Please make sure you entered a valid currency symbol, a rate provider is configured in store settings, and your configured rate provider is both online and providing rates for your selected currency."](https://user-images.githubusercontent.com/1178779/139906505-10731e94-9f24-4865-9181-c80d6871d012.png)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    1.3.1
- Deployment Method:        Debian package
- Browser:                  Firefox ESR (probably irrelevant)

**Logs (if applicable)**

```
2021-11-02 17:30:04.436 +01:00 [ERR] Invoice creation failed due to invalid currency BTC
BTCPayServer.BitpayHttpException: 11/02/2021 16:30:04:Info Creation of invoice starting

   at BTCPayServer.Controllers.InvoiceController.CreateInvoiceCoreRaw(InvoiceEntity entity, StoreData store, IPaymentFilter invoicePaymentMethodFilter, String[] additionalSearchTerms, CancellationToken cancellationToken)
   at BTCPayServer.Controllers.InvoiceController.CreateInvoiceCoreRaw(BitpayCreateInvoiceRequest invoice, StoreData store, String serverUrl, List`1 additionalTags, CancellationToken cancellationToken) in /home/user/cadr-build/btcpayserver-1.3.1/BTCPayServer/Controllers/InvoiceController.cs:line 156
   at BTCPayServer.Controllers.InvoiceController.CreateInvoiceCore(BitpayCreateInvoiceRequest invoice, StoreData store, String serverUrl, List`1 additionalTags, CancellationToken cancellationToken) in /home/user/cadr-build/btcpayserver-1.3.1/BTCPayServer/Controllers/InvoiceController.cs:line 82
   at BTCPayServer.Controllers.InvoiceController.CreateInvoice(CreateInvoiceModel model, CancellationToken cancellationToken) in /home/user/cadr-build/btcpayserver-1.3.1/BTCPayServer/Controllers/InvoiceController.UI.cs:line 868
```

**Setup Parameters**

N/A

**Comment by pavlenex** [comment]
Thanks for catching this. I could replicate reliably, but only with the amount `0.0001`, so this has to be something with denomination.

ping @Kukks @NicolasDorier this one seems urgent.

**Comment by pavlenex** [comment]
My logs give a bit better context

```
11/02/2021 17:02:32:Info BTC_BTC: The rating rule is 1.0
11/02/2021 17:02:32:Info BTC_BTC: The evaluated rating rule is 1.0
11/02/2021 17:02:32:Info BTC_USD: The rating rule is coingecko(BTC_USD)
11/02/2021 17:02:32:Info BTC_USD: The evaluated rating rule is 63735.219
11/02/2021 17:02:32:Info BTC (On-Chain): Payment method details creation took 0 milliseconds
11/02/2021 17:02:32:Error BTC (On-Chain): invoice amount below accepted value for payment method
11/02/2021 17:02:32:Info BTC (Off-Chain): Payment method details creation took 4 milliseconds
11/02/2021 17:02:32:Error BTC (Off-Chain): invoice amount above accepted value for payment method
11/02/2021 17:02:32:Info BTC (LNURL-Pay): Payment method details creation took 0 milliseconds
11/02/2021 17:02:32:Error BTC (LNURL-Pay): invoice amount above accepted value for payment method

   at BTCPayServer.Controllers.InvoiceController.CreateInvoiceCoreRaw(InvoiceEntity entity, StoreData store, IPaymentFilter invoicePaymentMethodFilter, String[] additionalSearchTerms, CancellationToken cancellationToken)
   at BTCPayServer.Controllers.InvoiceController.CreateInvoiceCoreRaw(BitpayCreateInvoiceRequest invoice, StoreData store, String serverUrl, List`1 additionalTags, CancellationToken cancellationToken) in /source/BTCPayServer/Controllers/InvoiceController.cs:line 156
   at BTCPayServer.Controllers.InvoiceController.CreateInvoiceCore(BitpayCreateInvoiceRequest invoice, StoreData store, String serverUrl, List`1 additionalTags, CancellationToken cancellationToken) in /source/BTCPayServer/Controllers/InvoiceController.cs:line 82
   at BTCPayServer.Controllers.InvoiceController.CreateInvoice(CreateInvoiceModel model, CancellationToken cancellationToken) in /source/BTCPayServer/Controllers/InvoiceController.UI.cs:line 868
2021-11-02 17:02:35.672 +00:00 [ERR] Invoice creation failed due to invalid currency BTC
```

So this could be as well with something to do with payment method restructures and minimum amounts as it seems payment method cannot be generated.

@Kixunil can you check which of these options you have configured?

![Screenshot 2021-11-02 at 18 06 04](https://user-images.githubusercontent.com/36959754/139912156-3d64c9b3-041c-4a36-9a09-9965fe798760.png)

**Comment by satwo** [comment]
@pavlenex Your error might be because there's no payment method for a USD price between 5 USD and 100 USD, and 0.0001 BTC is currently just over 6 USD. I think OP's case might be different though, "BTC" should obviously never be an invalid currency.

@Kixunil do you see similar errors in the logs as @pavlenex showed?

**Comment by Kixunil** [comment]
I tried wider range of amounts, none of them works.

My settings are:
![Screenshot_2021-11-02 Checkout experience](https://user-images.githubusercontent.com/1178779/139962469-72de4f2c-a3a9-4c41-b0a9-17c96a4b9158.png)

I see no errors about amount being either high or low, however now I *also* started seeing:

```
Payment method unavailable (Impossible to create lightning invoice (The SSL connection could not be established, see inner exception.))
```

with GUI still saying invalid currency but this time also for EUR and USD.

Will have to deeply check the connection later, the node is definitely running - I could create an invoice by other means.

**Comment by satwo** [comment]
@Kixunil I tried to recreate your issue using exactly the same settings you showed, but was unable to do so. 

Based on this and the error message you mentioned above, it seems like a low-level lightning error that might be bubbling up in a way that obscures the underlying cause. I can take a look but as Pav said, probably better to punt to @Kukks @NicolasDorier on this one.

**Comment by Kixunil** [comment]
Ah, I just realized, it's Eclair not LND, so "The SSL connection could not be established" indicates that the LN client may be screwed up - Eclair doesn't use SSL.

My connection string (in config file) is:

```
btc.lightning=type=eclair;server=http://127.0.0.1:8080/;password=censored
```

**Comment by pavlenex** [comment]
It seems that in #3065 we'll be able to have better error messages so we can see what an underlaying error of this issue may be. Let's wait for 1.3.2 and fix this afterwards.

**Comment by pavlenex** [comment]
@Kixunil 1.3.2 is out, check if you get better logs :)

**Comment by Kixunil** [comment]
Yeah, I have this:

```
11/04/2021 19:36:50:Info Creation of invoice starting
11/04/2021 19:36:50:Info BTC_BTC: The rating rule is 1.0
11/04/2021 19:36:50:Info BTC_BTC: The evaluated rating rule is 1.0
11/04/2021 19:36:50:Info BTC (Off-Chain): Payment method details creation took 310 milliseconds
11/04/2021 19:36:50:Error BTC: Payment method unavailable (Impossible to create lightning invoice (The SSL connection could not be established, see inner exception.))
```

So it seems the issue is BTCPayServer attempting to connect to Eclair using SSL, which Eclair doesn't use.

**Comment by NicolasDorier** [comment]
what is your connection string?

**Comment by Kixunil** [comment]
https://github.com/btcpayserver/btcpayserver/issues/3054#issuecomment-959049708

**Comment by Kixunil** [comment]
I just realized I forgot to switch store in the latter tests - after 1.3.2 and the previous issue magically fixed itself. Closing now and if it ever repeats I'll probably open a new one. Sorry for the noise.
