### ISSUE TITLE
500 error when requesting an API key

### ISSUE THREAD

**Issue by BitcoinMitchell** [btcpayserver/btcpayserver#3074]
**Describe the bug**
If I request an API key, BTCPay Server errors and shows me a `500`-error.

**To Reproduce the bug**
Visit any of the following URLs and try to make an API key:
- [URL where I encountered the bug](https://testnet.demo.btcpayserver.org/api-keys/authorize?permissions=btcpay.store.canmodifystoresettings&permissions=btcpay.store.webhooks.canmodifywebhooks&permissions=btcpay.store.canviewstoresettings&permissions=btcpay.store.cancreateinvoice&permissions=btcpay.store.canviewinvoices&permissions=btcpay.store.canmodifyinvoices&applicationName=BTCPay&strict=true&selectiveStores=true&applicationIdentifier=BTCPay)
- [URL without permissions](https://testnet.demo.btcpayserver.org/api-keys/authorize?applicationName=BTCPay&strict=true&selectiveStores=true&applicationIdentifier=BTCPay)
- [Without strict](https://testnet.demo.btcpayserver.org/api-keys/authorize?applicationName=BTCPay&selectiveStores=true&applicationIdentifier=BTCPay)
- [Without selective](https://testnet.demo.btcpayserver.org/api-keys/authorize?applicationName=BTCPay&applicationIdentifier=BTCPay)
- [Without identifier](https://testnet.demo.btcpayserver.org/api-keys/authorize?applicationName=BTCPay)
- [Without application name](https://testnet.demo.btcpayserver.org/api-keys/authorize)

**Expected behavior**
I expected to get an API key back that I could use.

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version: BTCPayServer v1.3.1.0 (altcoins) + also tested and broken on BTCPayServer v1.3.3.0
- Deployment Method: [Third-party host](https://testnet.demo.btcpayserver.org) + Docker
- Browser: Chrome

**Logs (if applicable)**
```
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "XXXXXX", Request id "XXXXXX:00000001": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Controllers.ManageController.AuthorizeAPIKey(AuthorizeApiKeysViewModel viewModel) in /source/BTCPayServer/Controllers/ManageController.APIKeys.cs:line 299
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)  
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)       
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 95
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 30
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by bolatovumar** [comment]
I can repro this as well. Seems like the issue here is that the code always expects the redirect URL specified and breaks without it. #3077 fixes that.

**Comment by Kukks** [comment]
Fixed this on master directly
