### ISSUE TITLE
policies page not accessible.

### ISSUE THREAD

**Issue by yilakb** [btcpayserver/btcpayserver#3200]
**Describe the bug**
problem accesses  policies page,  I get error "This page isn’t workingbti.btcpayprovider.com is currently unable to handle this request.
HTTP ERROR 500" 

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to 'log in to btcpayserver as server admin'
2. Click on 'Server settings'
3. Scroll down to 'go to policies and click'

**Expected behavior**

**Screenshots**

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    [ BTCPayServer v1.3.6.0 (altcoins)] 
- Deployment Method:      [ Manual run only BTC and Liquid ]
- Browser:                  [Chrome]

**Logs (if applicable)**
root@ubuntu-s-4vcpu-8gb-sfo2-01:~/btcpayserver-docker# docker logs --tail 100 generated_btcpayserver_1
info: PayServer:      Remove pending invoice HHgdmwfjx88LK2r8RHFRd4
info: PayServer:      Remove pending invoice 7eBsz9zn3zQnMUiB5w29PR
info: PayServer:      Remove pending invoice DHzCB3Dk6135wcmXogQcSV
info: PayServer:      Remove pending invoice VaGUsZpFsM9KzzNkrG9d7c
info: PayServer:      Remove pending invoice Qs5Wu2x6gVU1LSL4kugH6E
info: PayServer:      Remove pending invoice 8gdW9nDarW2njGE3cVTuHw
info: PayServer:      Remove pending invoice VaGUsZpFsM9KzzNkrG9d7c
info: PayServer:      Remove pending invoice 5VD8k3ZZtEkRgpf6nmbeXX
info: PayServer:      Remove pending invoice WjHouANc9FBsr61HMC5KQP
info: PayServer:      Remove pending invoice 7eBsz9zn3zQnMUiB5w29PR
info: PayServer:      Remove pending invoice DHzCB3Dk6135wcmXogQcSV
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMDR8IK2LHCB", Request id "0HMDR8IK2LHCB:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at BTCPayServer.EnumExtensions.DisplayName(Type enumType, String input) in /source/BTCPayServer/Extensions/EnumExtensions.cs:line 11
   at BTCPayServer.Controllers.ServerController.<>c.<GetAppSelectList>b__29_0(ListAppViewModel a) in /source/BTCPayServer/Controllers/ServerController.cs:line 406
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at BTCPayServer.Controllers.ServerController.GetAppSelectList() in /source/BTCPayServer/Controllers/ServerController.cs:line 405
   at BTCPayServer.Controllers.ServerController.Policies() in /source/BTCPayServer/Controllers/ServerController.cs:line 277
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 95
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 30
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Setup Parameters**

**Additional context**
Different server running BTCPayServer v1.3.6.0 as well without (altcoins) Don't have the same issue.

**Comment by pavlenex** [comment]
Closing this since it's been resolved.

> The troubles were caused by an unknown app  that had been installed; deleting them resolved the issues. (DELETE FROM "Apps" WHERE "AppType" IN ('918096', '969430'); I don't even know what they were and how they got there but now every thing works.
