### ISSUE TITLE
getting HTTP error 500 when pressing Generate BTC Address button

### ISSUE THREAD

**Issue by ALeschinsky** [btcpayserver/btcpayserver#3210]
**Describe the bug**
I'm getting HTTP error 500 in BTCPayServer, when pressing Generate BTC Address button on Wallets / Receive page. I see the following error in the log of btcpay-server_nbxplorer_1 container: `NBitcoin.RPC.RPCException: No wallet is loaded. Load a wallet using loadwallet or create a new one with createwallet.`

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to Wallets / Receive page
2. Click on Generate BTC Address
4. See HTTP ERROR 500 page, and also the error in the logs of nbxplorer

**Expected behavior**

A new address should be generated

**Screenshots**

![image](https://user-images.githubusercontent.com/2109420/146584659-8bcc9154-3f34-4f6a-9d11-38e5a326481d.png)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    v1.3.4.0
- Deployment Method:        Umbrel App
- Browser:                  Chrome

**Logs (if applicable)**

Logs in Server Settings > Logs are not available in this fresh installation of BTCPayServer as an Umbrel App...
![image](https://user-images.githubusercontent.com/2109420/146584976-b978655d-0879-4896-ae7b-761d098983b2.png)

I can see the logs in the docker container though, here's what it looks like:
```
info: Events:         BTC: Node state changed: NBXplorerSynching => Ready


fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HME1G3TD191E", Request id "0HME1G3TD191E:00000008": An unhandled exception was thrown by the application.


NBitcoin.RPC.RPCException: No wallet is loaded. Load a wallet using loadwallet or create a new one with createwallet. (Note: A default wallet is no longer automatically created)


   at NBitcoin.RPC.RPCResponse.ThrowIfError()


   at NBitcoin.RPC.RPCClient.SendCommandAsync(RPCRequest request, CancellationToken cancellationToken)


   at NBitcoin.RPC.RPCClient.ImportPrivKeyAsync(BitcoinSecret secret, String label, Boolean rescan)


   at NBXplorer.Repository.ImportAddressToRPC(BitcoinExtKey accountKey, BitcoinAddress address, KeyPath keyPath) in /source/NBXplorer/Repository.cs:line 1448


   at NBXplorer.Repository.ImportAddressToRPC(TrackedSource trackedSource, BitcoinAddress address, KeyPath keyPath) in /source/NBXplorer/Repository.cs:line 1442


   at NBXplorer.Repository.GetUnused(DerivationStrategyBase strategy, DerivationFeature derivationFeature, Int32 n, Boolean reserve) in /source/NBXplorer/Repository.cs:line 540


   at NBXplorer.Controllers.MainController.GetUnusedAddress(String cryptoCode, DerivationStrategyBase strategy, DerivationFeature feature, Int32 skip, Boolean reserve) in /source/NBXplorer/Controllers/MainController.cs:line 156


   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)


   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)


   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)


   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)


   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)


   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)


   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)


   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)


   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)


   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)


   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)


   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)


   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)


   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)


   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

```

**Comment by samuelsoderberg** [comment]
Try to run this from the command line: `bitcoin-cli createwallet "dummywallet"`, and restart.

**Comment by samuelsoderberg** [comment]
Perhaps try this:

SSH into your machine, go to the "btcpayserver-docker"-directory (I have it @ /root), and run:

`./bitcoin-cli.sh createwallet ”dummywallet”`
`./btcpay-restart.sh`

See if that worked. You might have to wait for it to sync.

**Comment by ALeschinsky** [comment]
This BTCPayServer instance is running as an Umbrel app, I don't have easy access to the scripts.

My problem was fixed by disabling the setting "Auto publish to RPC" - I don't remember the exact wording and where this setting is, just went to look for it and can't find it anywhere... maybe it's just set once on initial setup? Anyway, I set it to false and it works fine now, thank you.
