### ISSUE TITLE
[ERR] BTC: NBXplorer error `Resource temporarily unavailable (nbxplorer:32838)`

### ISSUE THREAD

**Issue by mrvickter** [btcpayserver/btcpayserver#3610]
**Describe the bug**
Noticed that nbxplorer 2.3.5 was pulled and BTCPay won't start up.

![001](https://user-images.githubusercontent.com/60835163/161614571-b5d8062a-4078-47b1-a3ff-9b9a27630544.png)

**Logs from generated_bxplorer_1**
info: Configuration:  Data Directory: /datadir
info: Configuration:  Configuration File: /datadir/Main/settings.config
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  DBCache: 50 MB
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  DBCache: 50 MB
info: NBXplorer.DatabaseSetup: Postgres services activated
info: Explorer:       Trimming the event table if needed...
info: Explorer:       Applying migration if needed, do not close NBXplorer...
Unhandled exception. Npgsql.PostgresException (0x80004005): 42710: type "m_txs" already exists
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|211_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in /_/Dapper/SqlMapper.Async.cs:line 646
   at NBXplorer.HostedServices.DBTrieToPostgresMigratorHostedService.RegisterTypes(DbConnection conn) in /source/NBXplorer/HostedServices/DBTrieToPostgresMigratorHostedService.cs:line 177
   at NBXplorer.HostedServices.DBTrieToPostgresMigratorHostedService.Migrate(NBXplorerNetwork network, Repository legacyRepo, PostgresRepository postgresRepo, ILogger logger, CancellationToken cancellationToken) in /source/NBXplorer/HostedServices/DBTrieToPostgresMigratorHostedService.cs:line 214
   at NBXplorer.HostedServices.DBTrieToPostgresMigratorHostedService.StartAsync(CancellationToken cancellationToken) in /source/NBXplorer/HostedServices/DBTrieToPostgresMigratorHostedService.cs:line 140
   at Microsoft.AspNetCore.Hosting.HostedServiceExecutor.ExecuteAsync(Func`2 callback, Boolean throwOnFirstFailure)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at NBXplorer.Program.Main(String[] args) in /source/NBXplorer/Program.cs:line 60
  Exception data:
    Severity: ERROR
    SqlState: 42710
    MessageText: type "m_txs" already exists
    File: typecmds.c
    Line: 2124
    Routine: DefineCompositeType

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    BTCPay Server v1.4.9.0
- Deployment Method:        Docker
- Browser:                  Chrome

**Comment by mrvickter** [comment]
Fixed issue by shutting down BTCPay Server and deleting the contents of "/var/lib/docker/volumes/generated_nbxplorer_datadir/_data".

After reboot everything started up fine.

**Comment by NicolasDorier** [comment]
Note you might get `Resource temporarily unavailable` when the bitcoin node isn't working for some reason.
This typically happen when `peers.dat` is corrupted.

If that's the case, you need to delete the file.
If you use btcpayserver with docker deployment, run `rm /var/lib/docker/volumes/generated_bitcoin_datadir/_data/peers.dat`
