### ISSUE TITLE
Exception thrown when navigating to Pull Payments in menu

### ISSUE THREAD

**Issue by elvece** [btcpayserver/btcpayserver#3640]
**Describe the bug**
Navigating to pull payments menu item generates a blank page even when a wallet is fully setup for a store. 

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. On a device running EmbassyOS v0.3.0.2, install BTC Pay Server and it's dependencies from the Marketplace at v1.4.7
2. Wait until the "Explorer Synced" health check passes to ensure NBXplorer is fully synced with the Bitcoin Core node. 
3. Launch the UI from the EmbassyOS Services Dashboard
4. Create an account and login
5. Create a store
6. Set up a wallet for that store
7. Navigate to the Menu > Payments > Pull Payments
8. See screen is blank with a `500 Internal Server Error` failed GET request (screenshot)

**Expected behavior**

If a wallet is setup for a store, accessing the pull payments section should display, notifying the user if any additional setup needs to occur rather than the page crashing.

**Screenshots**
<img width="1670" alt="Screen Shot 2022-04-14 at 11 32 53 AM" src="https://user-images.githubusercontent.com/12953208/163443155-6297018e-41e1-4efe-8bdb-031d5811c965.png">

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version: 1.4.7
- Deployment Method: [Docker on EmbassyOS](https://github.com/Start9Labs/btcpayserver-wrapper)
- Browser: Firefox

**Logs**

```
2022-04-14T17:29:56.728669Z fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMGU7FQGUPEV", Request id "0HMGU7FQGUPEV:00000002": An unhandled exception was thrown by the application.
2022-04-14T17:29:56.729215Z System.InvalidOperationException: The LINQ expression 'DbSet()
2022-04-14T17:29:56.729667Z     .Where(p => p.StoreId == __storeId_0)
2022-04-14T17:29:56.729974Z     .OrderByDescending(p => p.StartDate)
2022-04-14T17:29:56.730193Z     .Where(p => !(p.Archived) && p.EndDate != null ? p.EndDate > (DateTimeOffset?)DateTimeOffset.UtcNow : True && p.StartDate <= DateTimeOffset.UtcNow)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
2022-04-14T17:29:56.730380Z    at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.g__CheckTranslated|15_0(ShapedQueryExpression translated, <>c__DisplayClass15_0& )
2022-04-14T17:29:56.730509Z    at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
2022-04-14T17:29:56.730641Z    at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
2022-04-14T17:29:56.730769Z    at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
2022-04-14T17:29:56.730934Z    at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
2022-04-14T17:29:56.731163Z    at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
2022-04-14T17:29:56.731421Z    at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
2022-04-14T17:29:56.731599Z    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
2022-04-14T17:29:56.731722Z    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.b__0()
2022-04-14T17:29:56.731880Z    at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
2022-04-14T17:29:56.732585Z    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
2022-04-14T17:29:56.732927Z    at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
2022-04-14T17:29:56.733212Z    at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
2022-04-14T17:29:56.733428Z    at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
2022-04-14T17:29:56.733616Z    at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
2022-04-14T17:29:56.733755Z    at BTCPayServer.Controllers.UIStorePullPaymentsController.PullPayments(String storeId, PullPaymentState pullPaymentState, Int32 skip, Int32 count, String sortOrder) in /source/BTCPayServer/Controllers/UIStorePullPaymentsController.PullPayments.cs:line 218
2022-04-14T17:29:56.733883Z    at BTCPayServer.Controllers.UIStorePullPaymentsController.PullPayments(String storeId, PullPaymentState pullPaymentState, Int32 skip, Int32 count, String sortOrder) in /source/BTCPayServer/Controllers/UIStorePullPaymentsController.PullPayments.cs:line 255
2022-04-14T17:29:56.733996Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
2022-04-14T17:29:56.734189Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
2022-04-14T17:29:56.734369Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2022-04-14T17:29:56.734491Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
2022-04-14T17:29:56.734597Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2022-04-14T17:29:56.734689Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
2022-04-14T17:29:56.734790Z --- End of stack trace from previous location ---
2022-04-14T17:29:56.734990Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2022-04-14T17:29:56.735140Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
2022-04-14T17:29:56.735259Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2022-04-14T17:29:56.735350Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResourceFilter()
2022-04-14T17:29:56.735444Z --- End of stack trace from previous location ---
2022-04-14T17:29:56.735549Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
2022-04-14T17:29:56.735655Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2022-04-14T17:29:56.735746Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
2022-04-14T17:29:56.735873Z --- End of stack trace from previous location ---
2022-04-14T17:29:56.736072Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2022-04-14T17:29:56.736237Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2022-04-14T17:29:56.736348Z    at Microsoft.AspNetCore.Routing.EndpointMiddleware.g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
2022-04-14T17:29:56.736463Z    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
2022-04-14T17:29:56.736579Z    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
2022-04-14T17:29:56.736692Z    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
2022-04-14T17:29:56.736831Z    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
2022-04-14T17:29:56.736938Z    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
2022-04-14T17:29:56.737051Z    at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 100
2022-04-14T17:29:56.737180Z    at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 50
2022-04-14T17:29:56.737291Z    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
2022-04-14T17:29:56.737391Z    at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 30
2022-04-14T17:29:56.737512Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Additional context**

Somewhat related, but different error message and condition: https://github.com/btcpayserver/btcpayserver/issues/3084

**Comment by pavlenex** [comment]
@elvece can you ask them to update? I cannot replicate this on our official deployment methods.

**Comment by elvece** [comment]
> @elvece can you ask them to update? I cannot replicate this on our official deployment methods.

Sure, will test with latest version release and provide more info.

**Comment by pavlenex** [comment]
@elvece is this still an issue for you? I assume it's not, so I'll go ahead and close it, but if it is, let us know and we'll re-open it.

**Comment by elvece** [comment]
Recently dove back into updating this service for EmbassyOS, and this still remains an issue after updating to v1.6.6. 

Error message:

```
2022-08-18T22:44:35.708003Z fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMK1C8NMV7H0", Request id "0HMK1C8NMV7H0:00000002": An unhandled exception was thrown by the application.
2022-08-18T22:44:35.709520Z System.InvalidOperationException: The LINQ expression 'DbSet<PullPaymentData>()
2022-08-18T22:44:35.712967Z     .Where(p => p.StoreId == __storeId_0)
2022-08-18T22:44:35.714475Z     .OrderByDescending(p => p.StartDate)
2022-08-18T22:44:35.714950Z     .Where(p => !(p.Archived) && p.EndDate != null ? p.EndDate > (DateTimeOffset?)DateTimeOffset.UtcNow : True && p.StartDate <= DateTimeOffset.UtcNow)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
2022-08-18T22:44:35.715346Z    at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|15_0(ShapedQueryExpression translated, <>c__DisplayClass15_0& )
2022-08-18T22:44:35.718228Z    at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
2022-08-18T22:44:35.718570Z    at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
2022-08-18T22:44:35.718818Z    at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
2022-08-18T22:44:35.719077Z    at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
2022-08-18T22:44:35.721985Z    at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
2022-08-18T22:44:35.722369Z    at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
2022-08-18T22:44:35.722616Z    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
2022-08-18T22:44:35.723879Z    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
2022-08-18T22:44:35.724918Z    at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
2022-08-18T22:44:35.725370Z    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
2022-08-18T22:44:35.726633Z    at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
2022-08-18T22:44:35.727081Z    at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
2022-08-18T22:44:35.727286Z    at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
2022-08-18T22:44:35.727503Z    at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
2022-08-18T22:44:35.727690Z    at BTCPayServer.Controllers.UIStorePullPaymentsController.PullPayments(String storeId, PullPaymentState pullPaymentState, Int32 skip, Int32 count, String sortOrder) in /source/BTCPayServer/Controllers/UIStorePullPaymentsController.PullPayments.cs:line 220
2022-08-18T22:44:35.727951Z    at BTCPayServer.Controllers.UIStorePullPaymentsController.PullPayments(String storeId, PullPaymentState pullPaymentState, Int32 skip, Int32 count, String sortOrder) in /source/BTCPayServer/Controllers/UIStorePullPaymentsController.PullPayments.cs:line 239
2022-08-18T22:44:35.728169Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
2022-08-18T22:44:35.728332Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
2022-08-18T22:44:35.728497Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2022-08-18T22:44:35.728766Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
2022-08-18T22:44:35.730314Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2022-08-18T22:44:35.730739Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
2022-08-18T22:44:35.730930Z --- End of stack trace from previous location ---
2022-08-18T22:44:35.735174Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2022-08-18T22:44:35.735576Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
2022-08-18T22:44:35.741383Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2022-08-18T22:44:35.742237Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResourceFilter()
2022-08-18T22:44:35.742552Z --- End of stack trace from previous location ---
2022-08-18T22:44:35.742816Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
2022-08-18T22:44:35.744787Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2022-08-18T22:44:35.745193Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
2022-08-18T22:44:35.745435Z --- End of stack trace from previous location ---
2022-08-18T22:44:35.745632Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2022-08-18T22:44:35.745836Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2022-08-18T22:44:35.746147Z    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
2022-08-18T22:44:35.746387Z    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
2022-08-18T22:44:35.746766Z    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
2022-08-18T22:44:35.747270Z    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
2022-08-18T22:44:35.747596Z    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
2022-08-18T22:44:35.747804Z    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
2022-08-18T22:44:35.747998Z    at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 101
2022-08-18T22:44:35.750164Z    at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 50
2022-08-18T22:44:35.750514Z    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
2022-08-18T22:44:35.750760Z    at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 30
2022-08-18T22:44:35.750996Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by jungleacademyfarm** [comment]
@elvece Is this btcpayserver instance running with sqlite? I'm experiencing the same issue and error logs in v1.6.10 of btcpayserver. The only thing I can think of is that this particular instance is running with sqlite.

**Comment by leesalminen** [comment]
@elvece Is this btcpayserver instance running with sqlite? I'm experiencing the same issue and error logs in v1.6.10 of btcpayserver. The only thing I can think of is that this particular instance is running with sqlite.

**Comment by elvece** [comment]
@leesalminen Yes, this instance is running with sqlite.
