### ISSUE TITLE
Lightning address HTTP/500

### ISSUE THREAD

**Issue by AbelLykens** [btcpayserver/btcpayserver#3659]
**Describe the bug**

My Lightning address does not work. I have created a lightning address in my store (admin@domain.com), but when sending, lntxbot says: `🔴 Error: failed to fetch lnurl params: unknown response tag`. If visit domain.com/.well-known/lnurlp/admin I get a HTTP 500 error.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Open site in BTCPayserver, navigate to Lightning Address in the menu, create new address (admin@domain.com)
2. Visit the `.well-known/lnurlp` page or try to send to the address
3. Fail! (see logs below ;) ).

**Expected behavior**
Me being able to send to the address!

**Screenshots**
![image](https://user-images.githubusercontent.com/47113175/164416633-0d5055ec-fd9e-4b86-8f49-389b772c43be.png)
![image](https://user-images.githubusercontent.com/47113175/164416804-11e6d955-3317-4603-8fc9-df3d7dd0d4bc.png)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    © BTCPay Server v1.4.9.0 
- Deployment Method:       Manual deployment (git clone, checkout tag, build, run)
- Browser:                  Firefox

**Logs (if applicable)**

```
Apr 21 08:31:18 btcpay run[18541]: fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMH3E4FP4KJM", Request id "0HMH3E4FP4KJM:00000004": An unhandled exception was thrown by the application.
Apr 21 08:31:18 btcpay run[18541]: BTCPayServer.BitpayHttpException: 04/21/2022 08:31:18:Info Creation of invoice starting
Apr 21 08:31:18 btcpay run[18541]: 04/21/2022 08:31:18:Info BTC_SAT: The rating rule is (coingecko(BTC_SAT)) * (0.995, 1.005)
Apr 21 08:31:18 btcpay run[18541]: 04/21/2022 08:31:18:Info BTC_SAT: The evaluated rating rule is (ERR_RATE_UNAVAILABLE(coingecko, BTC_SAT)) * (0.995, 1.005)
Apr 21 08:31:18 btcpay run[18541]: 04/21/2022 08:31:18:Error BTC_SAT: Rate rule error (RateUnavailable)
Apr 21 08:31:18 btcpay run[18541]: 04/21/2022 08:31:18:Info BTC_EUR: The rating rule is (coingecko(BTC_EUR)) * (0.995, 1.005)
Apr 21 08:31:18 btcpay run[18541]: 04/21/2022 08:31:18:Info BTC_EUR: The evaluated rating rule is (38336.474) * (0.995, 1.005)
Apr 21 08:31:18 btcpay run[18541]:    at BTCPayServer.Controllers.UIInvoiceController.CreateInvoiceCoreRaw(InvoiceEntity entity, StoreData store, IPaymentFilter invoicePaymentMethodFilter, String[] additionalSearchTerms, CancellationToken cancellationToken) in /opt/btcpayserver/BTCPayServer/Controllers/UIInvoiceController.cs:line 310
Apr 21 08:31:18 btcpay run[18541]:    at BTCPayServer.Controllers.UIInvoiceController.CreateInvoiceCoreRaw(CreateInvoiceRequest invoice, StoreData store, String serverUrl, List`1 additionalTags, CancellationToken cancellationToken) in /opt/btcpayserver/BTCPayServer/Controllers/UIInvoiceController.cs:line 204
Apr 21 08:31:18 btcpay run[18541]:    at BTCPayServer.UILNURLController.GetLNURL(String cryptoCode, String storeId, String currencyCode, Nullable`1 min, Nullable`1 max, Func`1 internalDetails) in /opt/btcpayserver/BTCPayServer/Controllers/UILNURLController.cs:line 247
Apr 21 08:31:18 btcpay run[18541]:    at BTCPayServer.UILNURLController.ResolveLightningAddress(String username) in /opt/btcpayserver/BTCPayServer/Controllers/UILNURLController.cs:line 196
Apr 21 08:31:18 btcpay run[18541]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Apr 21 08:31:18 btcpay run[18541]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Apr 21 08:31:18 btcpay run[18541]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Apr 21 08:31:18 btcpay run[18541]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Apr 21 08:31:18 btcpay run[18541]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Apr 21 08:31:18 btcpay run[18541]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Apr 21 08:31:18 btcpay run[18541]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Apr 21 08:31:18 btcpay run[18541]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
Apr 21 08:31:18 btcpay run[18541]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Apr 21 08:31:18 btcpay run[18541]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Apr 21 08:31:18 btcpay run[18541]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Apr 21 08:31:18 btcpay run[18541]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Apr 21 08:31:18 btcpay run[18541]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Apr 21 08:31:18 btcpay run[18541]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Apr 21 08:31:18 btcpay run[18541]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Apr 21 08:31:18 btcpay run[18541]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Apr 21 08:31:18 btcpay run[18541]:    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Apr 21 08:31:18 btcpay run[18541]:    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Apr 21 08:31:18 btcpay run[18541]:    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Apr 21 08:31:18 btcpay run[18541]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Apr 21 08:31:18 btcpay run[18541]:    at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /opt/btcpayserver/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 101
Apr 21 08:31:18 btcpay run[18541]:    at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /opt/btcpayserver/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 50
Apr 21 08:31:18 btcpay run[18541]:    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
Apr 21 08:31:18 btcpay run[18541]:    at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /opt/btcpayserver/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 30
Apr 21 08:31:18 btcpay run[18541]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Setup Parameters**

I could not find the btcpay-setup script... Sorry!

**Additional context**

This has not worked for me yet (eg it did not _break_)

**Comment by AbelLykens** [comment]
Hello! Yes, my unchanged settings:
![image](https://user-images.githubusercontent.com/47113175/164464561-759bc874-e3b8-4e8c-b0ec-81529e0e5aa7.png)

**Comment by AbelLykens** [comment]
Yeah looks like it. It's odd BTC_SAT would need conversion. And ave no clue why any conversion would actually be needed at all for lightning addresses. Oh well. My regular webshop works:
![image](https://user-images.githubusercontent.com/47113175/164465586-f29e2214-8e4b-4f5c-8554-7aaa29f5e70e.png)

**Comment by Kukks** [comment]
Please use SATS instead of SAT

**Comment by AbelLykens** [comment]
That works! Thanks @Kukks !
