### ISSUE TITLE
LNURL does not work with c-lightning v0.11.0

### ISSUE THREAD

**Issue by Sjors** [btcpayserver/btcpayserver#3720]
When attempting to pay a LNURL invoice using Phoenix, BTCPay displays a QR code, Phoenix will scan it and show the amount, but attempting pay fails.

In the server log I see the following 400 error:

```
BTC/lnurl/pay/i/Jk5Sfw1M...?amount=29000
```

When I check the URL in a browser:

```json
{"status":"ERROR","reason":"Lightning node could not generate invoice with description hash"}
```

I don't (fully) understand how LNURL works, but I suspect that you need to use the new `deschashonly` option for c-lighting (added in https://github.com/btcpayserver/btcpayserver/pull/3559).

See also https://github.com/btcpayserver/btcpayserver/pull/3559#issuecomment-1118829186

**Comment by pavlenex** [comment]
Ah I experienced this as well. Do you have this enabled in your LNURL settings?
![Screenshot 2022-05-05 at 19 53 28](https://user-images.githubusercontent.com/36959754/166983797-799d4e35-d4dd-45ca-bba5-fd748981bc53.png)

**Comment by pavlenex** [comment]
Hmmm it's not that actually. 
I tried with BTCPay 1.5.1 and Phoenix tweeking these options but it always worked.

**Comment by pavlenex** [comment]
Managed to replicate after an update. This is def a bug it seems cc @Kukks

**Comment by Sjors** [comment]
@pavlenex glad you were able to reproduce! Yes, I did have that 3rd option selected. I initially found out while trying a lightning address, but it also happens when I manually create a LNURL invoice.

I did not dare to downgrade my production c-lightning node. I'm reckless, but there's limits :-)

**Comment by Kukks** [comment]
> Managed to replicate after an update. This is def a bug it seems cc @Kukks

Impossible, we have not even built binaries or docker images for c-lightning 0.11+.

**Comment by Kukks** [comment]
0.11 CLN has definitely added some annoying breaking changes, it will even break paying an invoice that uses desc_hash unless we provide the plaintext desc for it to verify (why must we keep forcing logic levels lower when we can do this in the application *sigh*)

**Comment by Kukks** [comment]
> When attempting to pay a LNURL invoice using Phoenix, BTCPay displays a QR code, Phoenix will scan it and show the amount, but attempting pay fails.
> 
> In the server log I see the following 400 error:
> 
> ```
> BTC/lnurl/pay/i/Jk5Sfw1M...?amount=29000
> ```
> 
> When I check the URL in a browser:
> 
> ```json
> {"status":"ERROR","reason":"Lightning node could not generate invoice with description hash"}
> ```
> 
> I don't (fully) understand how LNURL works, but I suspect that you need to use the new `deschashonly` option for c-lighting (added in #3559).
> 
> See also [#3559 (comment)](https://github.com/btcpayserver/btcpayserver/pull/3559#issuecomment-1118829186)

Since you're not running our stack, the missing link here for you is that we bundle CLN with @fiatjaf's plugin to create invoices with `h` : https://github.com/fiatjaf/sparko/releases/tag/invoicewithdescriptionhash-v1.2

It seems that even with the native support that @rustyrussell added in 0.11 for `h`, this plugin is still better as passing down the plaintext description will be a hassle to refactor.

**Comment by Sjors** [comment]
Oh yeah I forgot to clarify: I selected the _maximum pain_ option and installed everything without Docker.

Just to clarify, if I install the sparko plugin, it will Just Work(tm)? Or is there still going to be a problem because I run the 0.11 c-lightning version?

**Comment by Kukks** [comment]
> Oh yeah I forgot to clarify: I selected the _maximum pain_ option and installed everything without Docker.
> 
> Just to clarify, if I install the sparko plugin, it will Just Work(tm)? Or is there still going to be a problem because I run the 0.11 c-lightning version?

There are 2 plugins in that repo: sparko and invoicewithdescriptionhash. I think sparko bundles the latter but I've only tested with the individual one. 

Just works™️

**Comment by Kukks** [comment]
let m

> Oh yeah I forgot to clarify: I selected the _maximum pain_ option and installed everything without Docker.
> 
> Just to clarify, if I install the sparko plugin, it will Just Work(tm)? Or is there still going to be a problem because I run the 0.11 c-lightning version?

Well, actually I don't know if CLN 0.11 broke anything more..

**Comment by Sjors** [comment]
I like to keep the number of dependencies small, so if `invoicewithdescriptionhash` is enough, I'll try that first.

**Comment by Sjors** [comment]
Ok, I was able build the `invoicewithdescriptionhash` plugin. I installed [gox](https://github.com/mitchellh/gox), then ran `make` inside `invoicewithdescriptionhash/cmd` (optionally edit `make` to drop architectures you don't need), copied the result to `~/.lightning/plugins` and restarted c-lightning.

This shows the new command as available in `lightning-cli help`, but I still get an error when trying to pay (`Lightning node could not generate invoice with description hash`).

I can't find `invoicewithdescriptionhash` or `sparko` in this repo or the docker repo, so not sure what configuration step I'm missing.

**Comment by Sjors** [comment]
Found the right repo, will study further:

https://github.com/btcpayserver/BTCPayServer.Lightning/blob/33d11e68ac8d39767b0faaa4b0c7f2f9910c9a73/src/BTCPayServer.Lightning.CLightning/CLightningClient.cs#L295-L305

**Comment by Sjors** [comment]
@fiatjaf it's a great question, but I'm not sure what the correct usage is:

```
$ lightning-cli help invoicewithdescriptionhash
No manual entry for lightning-invoicewithdescriptionhash
man: ./../doc/lightning-invoicewithdescriptionhash.7: No such file or directory
command=invoicewithdescriptionhash msatoshi label description_hash [expiry] [preimage]
category=plugin
description=Create an invoice for {msatoshi} with {label} and {description_hash} with optional {expiry} seconds (default 1 week) and optional {preimage} (default autogenerated)
verbose=
```

Here's one attempt, which fails:

```
$ lightning-cli invoicewithdescriptionhash 1000 no-hash "My Label" 185f8db32271fe25f561a6fc938b2e264306ec304eda518007d1764826381969
{
   "code": 477,
   "message": "description_hash is invalid or not given",
   "data": null
}
```

**Comment by Sjors** [comment]
Ok, it's definitely a c-lightning upgrade related regression, see https://github.com/fiatjaf/sparko/issues/18

**Comment by Sjors** [comment]
We've narrowed it down to a signet-specific problem, see https://github.com/fiatjaf/invoicewithdescriptionhash/issues/1

**Comment by Sjors** [comment]
Ok, I'm now able to generate the invoice, but when trying to pay I get:

```
% bos --node signet lnurl pay --url  lightning:lnurl1dp68g....c93
? Amount to pay? (min: 35, max: 35) 35

err: 
  - 503
  - FailedToParseReturnedPaymentRequest
  - 
    err: 
      message: UnknownCurrencyCodeInPaymentRequest
      stack: 
        - Error: UnknownCurrencyCodeInPaymentRequest
        -     at module.exports (/Volumes/SSD/Dev/balanceofsatoshis/node_modules/invoices/bolt11/decode_prefix.js:38:11)
        -     at module.exports (/Volumes/SSD/Dev/balanceofsatoshis/node_modules/invoices/bolt11/parse_payment_request.js:76:36)
        -     at /Volumes/SSD/Dev/balanceofsatoshis/lnurl/get_pay_request.js:68:13
        -     at IncomingMessage.<anonymous> (/Volumes/SSD/Dev/balanceofsatoshis/commands/simple_request.js:66:16)
        -     at IncomingMessage.emit (node:events:539:35)
        -     at endReadableNT (node:internal/streams/readable:1345:12)
        -     at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by alexbosworth** [comment]
signet is not a supported network

**Comment by Sjors** [comment]
@alexbosworth indeed, I just noticed that. Is that easy to add? https://github.com/alexbosworth/ln-service/issues/155

**Comment by fiatjaf** [comment]
The problem was that my manual code for detecting the chain for each invoice was missing signet and was treating it as mainnet (default case).

Solved by skipping the LND `*chaincfg.Params` premade stuff and just passing the code manually.

**Comment by zechendorf** [comment]
Just for posterity because I ran into this issue with my older BTCPay setup: If you're using LNBank with CLN as backend to recieve lightning payments you also need to upgrade the LNBank plugin to the newest version to fix this issue.

Maybe this hint helps somebody out who stumbled over this GitHub issue googling the error message.
