### ISSUE TITLE
No Webinterface if startup fails to contact coingecko (internet connection down) AND no auto resume of operation thereafter

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#3741]
**Describe the bug**
I noticed that during a power outage where my solar battery powers the house (with a small interruption, hence the reboot) and the DSL connection is still down, the btcpayserver does not resume normal operation even after the dsl comes back on.

Looking at the logs I noticed, that btcpay is not listening on it's service port, the logs show this:

```
warn: PayServer:      Error while contacting exchange coingecko: Resource temporarily unavailable (api.coingecko.com:443)
warn: PayServer:      Error while contacting exchange coingecko: Resource temporarily unavailable (api.coingecko.com:443)
warn: PayServer:      Error while contacting exchange coingecko: Resource temporarily unavailable (api.coingecko.com:443)
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
info: Configuration:  Data Directory: /datadir
info: Configuration:  Configuration File: /datadir/Main/settings.config
info: BTCPayServer.Plugins.PluginManager: Loading plugins from /root/.btcpayserver/Plugins
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer - 1.5.2.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Shopify - 1.5.2.0
info: Configuration:  Supported chains: BTC
info: Configuration:  BTC: Explorer url is http://nbxplorer:32838/
info: Configuration:  BTC: Cookie file is /root/.nbxplorer/Main/.cookie
info: Configuration:  Network: Mainnet
info: Configuration:  LogFile: /datadir/btcpay.log
info: Configuration:  Log Level: Debug
```

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. on a locally running btcpay setup, disconnect DSL and power from your Pi
2. reconnect power and wait for it to boot
3. When trying to connect to it through the home network, you'll notice a 503 error
4. to resume normal operation when the DSL is back on you need to run btcpay-restart.sh

**Expected behavior**

I would have expected btcpayserver to bind to it's port even if coingecko is unavailable or at least continue trying to reach coingecko and automatically restore normal operation upon resuming of the internet connection.

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    v1.5.2.0
- Deployment Method:       Docker
- Browser:                  Chrome

**Comment by petzsch** [comment]
Same problem today with 1.5.4.0:

```
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
info: Configuration:  Data Directory: /datadir
info: Configuration:  Configuration File: /datadir/Main/settings.config
info: BTCPayServer.Plugins.PluginManager: Loading plugins from /root/.btcpayserver/Plugins
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer - 1.5.4.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Shopify - 1.5.4.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.LNbank - 1.2.2.0
info: Configuration:  Supported chains: BTC
info: Configuration:  BTC: Explorer url is http://nbxplorer:32838/
info: Configuration:  BTC: Cookie file is /root/.nbxplorer/Main/.cookie
info: Configuration:  Network: Mainnet
info: Configuration:  LogFile: /datadir/btcpay.log
info: Configuration:  Log Level: Debug
info: Configuration:  Root Path: /
info: Configuration:  Connection to NBXplorer's database successful, dashboard and reporting features activated.
info: Configuration:  SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
info: PayServer:      Starting listening NBXplorer (BTC)
info: PayServer:      Start watching invoices
info: PayServer:      Starting payment request expiration watcher
info: Configuration:  SSH connection succeeded
info: PayServer:      0 pending payment requests being checked since last run
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Starting
info: Configuration:  Now listening on: http://0.0.0.0:49392
warn: PayServer:      Error while contacting exchange coingecko: Resource temporarily unavailable (api.coingecko.com:443)
fail: Events:         Error while performing new version check
System.Net.Http.HttpRequestException: Resource temporarily unavailable (api.github.com:443)
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at BTCPayServer.HostedServices.GithubVersionFetcher.Fetch(CancellationToken cancellation) in /source/BTCPayServer/HostedServices/NewVersionCheckerHostedService.cs:line 103
   at BTCPayServer.HostedServices.NewVersionCheckerHostedService.ProcessVersionCheck() in /source/BTCPayServer/HostedServices/NewVersionCheckerHostedService.cs:line 55
   at BTCPayServer.HostedServices.NewVersionCheckerHostedService.LoopVersionCheck() in /source/BTCPayServer/HostedServices/NewVersionCheckerHostedService.cs:line 41
info: PayServer:      BTC: Checking if any pending invoice got paid while offline...
info: PayServer:      BTC: 0 payments happened while offline
info: PayServer:      Connected to WebSocket of NBXplorer (BTC)
warn: PayServer:      Error while contacting exchange coingecko: Resource temporarily unavailable (api.coingecko.com:443)
warn: PayServer:      Error while contacting exchange coingecko: Resource temporarily unavailable (api.coingecko.com:443)
```

**Comment by pavlenex** [comment]
@NicolasDorier Why is a plugin recommended approach to address this? Can't we "just fix it"?

**Comment by petzsch** [comment]
I think Nicolas meant a plugin could be causing this?

Don't have anything creazy enabled on this raspi node though:
only the pre-enabled shopify, btcpayserver core and lnbank

**Comment by pavlenex** [comment]
@petzsch does this still occur with never versions?

**Comment by petzsch** [comment]
I tried to reproduce the issue:

1. removed phone cable from my router
2. ran `btcpay-restart.sh`
3. tried to access btcpay through a .local address

Did get the regular Login page and was able to view my invoices and such while offline.

**No 503 error anymore -> Issue seems to be resolved.**

The docker log output is still unchanged:

```
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
info: Configuration:  Data Directory: /datadir
info: Configuration:  Configuration File: /datadir/Main/settings.config
info: BTCPayServer.Plugins.PluginManager: Loading plugins from /root/.btcpayserver/Plugins
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer - 1.6.10.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Shopify - 1.6.10.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.PayButton - 1.6.10.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.NFC - 1.0.3.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.LNbank - 1.2.3.0
info: Configuration:  Supported chains: BTC
info: Configuration:  BTC: Explorer url is http://nbxplorer:32838/
info: Configuration:  BTC: Cookie file is /root/.nbxplorer/Main/.cookie
info: Configuration:  Network: Mainnet
info: Configuration:  LogFile: /datadir/btcpay.log
info: Configuration:  Log Level: Debug
info: Configuration:  Root Path: /
info: Configuration:  Connection to NBXplorer's database successful, dashboard and reporting features activated.
info: Configuration:  SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
info: Configuration:  SSH connection succeeded
info: PayServer:      Starting listening NBXplorer (BTC)
info: PayServer:      Start watching invoices
info: PayServer:      Starting payment request expiration watcher
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Starting
info: PayServer:      1 pending payment requests being checked since last run
info: Configuration:  Now listening on: http://0.0.0.0:49392
info: PayServer:      BTC: Checking if any pending invoice got paid while offline...
info: PayServer:      BTC: 0 payments happened while offline
info: PayServer:      Connected to WebSocket of NBXplorer (BTC)
fail: Events:         Error while performing new version check
System.Net.Http.HttpRequestException: Resource temporarily unavailable (api.github.com:443)
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at BTCPayServer.HostedServices.GithubVersionFetcher.Fetch(CancellationToken cancellation) in /source/BTCPayServer/HostedServices/NewVersionCheckerHostedService.cs:line 103
   at BTCPayServer.HostedServices.NewVersionCheckerHostedService.ProcessVersionCheck() in /source/BTCPayServer/HostedServices/NewVersionCheckerHostedService.cs:line 55
   at BTCPayServer.HostedServices.NewVersionCheckerHostedService.LoopVersionCheck() in /source/BTCPayServer/HostedServices/NewVersionCheckerHostedService.cs:line 41
warn: PayServer:      Error while contacting exchange coingecko: A task was canceled.
warn: PayServer:      Error while contacting exchange coingecko: A task was canceled.
warn: PayServer:      Error while contacting exchange coingecko: A task was canceled.
warn: PayServer:      Error while contacting exchange coingecko: A task was canceled.
```

**Comment by petzsch** [comment]
Now I'm getting a 502 after a power outage. (DSL Line returned about 5 minutes after power came back)

nginx log:

```
2022/12/05 08:37:37 [error] 9#9: *37 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: btcpay.4sats.net, request: "GET / HTTP/2.0", upstream: "http://172.19.0.14:49392/", host: "btcpay.4sats.net"
btcpay.4sats.net 172.19.0.1 - - [05/Dec/2022:08:37:37 +0000] "GET / HTTP/2.0" 502 552 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.68"
```

btcpayserver container log:

```
root@cryptonode:~# docker logs generated_btcpayserver_1 
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
info: Configuration:  Data Directory: /datadir
info: Configuration:  Configuration File: /datadir/Main/settings.config
info: BTCPayServer.Plugins.PluginManager: Loading plugins from /root/.btcpayserver/Plugins
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer - 1.7.1.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Shopify - 1.7.1.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Crowdfund - 1.7.1.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.PayButton - 1.7.1.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.PointOfSale - 1.7.1.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.NFC - 1.0.7.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.BitcoinWhitepaper - 1.0.1.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.LNbank - 1.3.4.0
info: Configuration:  Supported chains: BTC
info: Configuration:  BTC: Explorer url is http://nbxplorer:32838/
info: Configuration:  BTC: Cookie file is /root/.nbxplorer/Main/.cookie
info: Configuration:  Network: Mainnet
info: Configuration:  LogFile: /datadir/btcpay.log
info: Configuration:  Log Level: Debug
info: Configuration:  Root Path: /
info: Configuration:  Connection to NBXplorer's database successful, dashboard and reporting features activated.
info: Configuration:  SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
info: Configuration:  SSH connection succeeded
info: PayServer:      Starting listening NBXplorer (BTC)
info: PayServer:      Start watching invoices
info: PayServer:      Starting payment request expiration watcher
info: PayServer:      1 pending payment requests being checked since last run
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Starting
info: Configuration:  Now listening on: http://0.0.0.0:49392
info: PayServer:      BTC: Checking if any pending invoice got paid while offline...
info: PayServer:      BTC: 0 payments happened while offline
info: PayServer:      Connected to WebSocket of NBXplorer (BTC)
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
info: Configuration:  Data Directory: /datadir
info: Configuration:  Configuration File: /datadir/Main/settings.config
info: BTCPayServer.Plugins.PluginManager: Loading plugins from /root/.btcpayserver/Plugins
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer - 1.7.1.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Shopify - 1.7.1.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Crowdfund - 1.7.1.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.PayButton - 1.7.1.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.PointOfSale - 1.7.1.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.NFC - 1.0.7.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.BitcoinWhitepaper - 1.0.1.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.LNbank - 1.3.4.0
info: Configuration:  Supported chains: BTC
info: Configuration:  BTC: Explorer url is http://nbxplorer:32838/
info: Configuration:  BTC: Cookie file is /root/.nbxplorer/Main/.cookie
info: Configuration:  Network: Mainnet
info: Configuration:  LogFile: /datadir/btcpay.log
info: Configuration:  Log Level: Debug
info: Configuration:  Root Path: /
info: Configuration:  Connection to NBXplorer's database successful, dashboard and reporting features activated.
info: Configuration:  SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
info: Configuration:  SSH connection succeeded
info: PayServer:      Starting listening NBXplorer (BTC)
info: PayServer:      Start watching invoices
info: PayServer:      Starting payment request expiration watcher
warn: PayServer:      Error while contacting exchange coingecko: Resource temporarily unavailable (api.coingecko.com:443)
fail: Events:         Error while performing new version check
System.Net.Http.HttpRequestException: Resource temporarily unavailable (api.github.com:443)
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at BTCPayServer.HostedServices.GithubVersionFetcher.Fetch(CancellationToken cancellation) in /source/BTCPayServer/HostedServices/NewVersionCheckerHostedService.cs:line 103
   at BTCPayServer.HostedServices.NewVersionCheckerHostedService.ProcessVersionCheck() in /source/BTCPayServer/HostedServices/NewVersionCheckerHostedService.cs:line 55
   at BTCPayServer.HostedServices.NewVersionCheckerHostedService.LoopVersionCheck() in /source/BTCPayServer/HostedServices/NewVersionCheckerHostedService.cs:line 41
info: PayServer:      1 pending payment requests being checked since last run
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Starting
info: Configuration:  Now listening on: http://0.0.0.0:49392
warn: PayServer:      Error while contacting exchange coingecko: Resource temporarily unavailable (api.coingecko.com:443)
warn: PayServer:      Error while contacting exchange coingecko: Resource temporarily unavailable (api.coingecko.com:443)
warn: PayServer:      Error while contacting exchange coingecko: Resource temporarily unavailable (api.coingecko.com:443)
warn: PayServer:      Error while contacting exchange coingecko: Resource temporarily unavailable (api.coingecko.com:443)
warn: PayServer:      Error while contacting exchange coingecko: Resource temporarily unavailable (api.coingecko.com:443)
warn: PayServer:      Error while contacting exchange coingecko: Resource temporarily unavailable (api.coingecko.com:443)
warn: PayServer:      Error while contacting exchange coingecko: Resource temporarily unavailable (api.coingecko.com:443)
warn: PayServer:      Error while contacting exchange coingecko: Resource temporarily unavailable (api.coingecko.com:443)
warn: PayServer:      Error while contacting exchange coingecko: Resource temporarily unavailable (api.coingecko.com:443)
warn: PayServer:      Error while contacting exchange coingecko: Resource temporarily unavailable (api.coingecko.com:443)
```

It doesn't seem to bring up the webinterface on its own, even after the internet connection is restored.

**Comment by pavlenex** [comment]
@petzsch Is this still an issue for you?

**Comment by petzsch** [comment]
no power outages as of recently. So the issue didn't show up again. I would close it now and reopen if it happens again.
