### ISSUE TITLE
On Initial Startup, Blockchain Synchronisation Sticks at 0: NBXplorer.Indexer.BTC: Unhandled exception in the indexer

### ISSUE THREAD

**Issue by aeschylus** [btcpayserver/btcpayserver#3797]
**Describe the bug**
After a first boot up, and registration, everything seems to be going well, except the "your nodes are synching" dialog box is stuck at 0 blockheight. This seems to be related to the indexer not being able to connect to postgres, and it seems this is because the postgres container does not create the necessary databases correctly. See logs below.

**To Reproduce the bug**
Following this guide on a t2.medium on AWS with 600 GB storage:
https://wiki.ion.radar.tech/tutorials/nodes/btcpay-+-aws-ec2

**Expected behavior**
"Your Node is Synching..." dialog should begin retrieving blocks.

**Screenshots**
<img width="520" alt="Screenshot 2022-05-30 at 11 59 03 PM" src="https://user-images.githubusercontent.com/145874/171096094-4aa63997-e38a-41f4-96dc-08b70a1d8ebf.png">

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:  © BTCPay Server v1.5.4.0
- Deployment Method: docker on AWS
- Browser: Chrome, but this is a backend deployment orchestration issue

**Logs (if applicable)**
`docker logs --tail 1000 generated_nbxplorer_1`
```
info: Configuration:  Data Directory: /datadir
info: Configuration:  Configuration File: /datadir/Main/settings.config
info: Configuration:  Creating configuration file
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  DBCache: 50 MB
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  DBCache: 50 MB
info: NBXplorer.DatabaseSetup: Postgres services activated
info: NBXplorer.DatabaseSetup: Database 'nbxplorermainnet' doesn't exists, creating it...
info: NBXplorer.DatabaseSetup: Execute script 001.Migrations...
info: NBXplorer.DatabaseSetup: Execute script 002.Model...
info: NBXplorer.DatabaseSetup: Execute script 003.Legacy...
info: NBXplorer.DatabaseSetup: Execute script 004.Fixup...
info: NBXplorer.DatabaseSetup: Execute script 005.ToBTCFix...
info: NBXplorer.DatabaseSetup: Execute script 006.GetWalletsRecent2...
info: NBXplorer.DatabaseSetup: Execute script 007.FasterSaveMatches...
info: NBXplorer.DatabaseSetup: Execute script 008.FasterGetUnused...
info: NBXplorer.DatabaseSetup: Execute script 009.FasterGetUnused2...
info: Explorer:       Trimming the event table if needed...
fail: NBXplorer.Indexer.BTC: Unhandled exception in the indexer, retrying in 0 seconds
System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at NBitcoin.Protocol.Connectors.DefaultEndpointConnector.ConnectSocket(Socket socket, EndPoint endpoint, NodeConnectionParameters nodeConnectionParameters, CancellationToken cancellationToken)
   at NBitcoin.Protocol.Node.ConnectAsync(Network network, EndPoint endpoint, NetworkAddress peer, NodeConnectionParameters parameters)
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.ConnectNode(CancellationToken token, Boolean forceRestart) in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 199
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 76
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoop() in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 55
fail: NBXplorer.Indexer.BTC: Unhandled exception in the indexer, retrying in 5 seconds
System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at NBitcoin.Protocol.Connectors.DefaultEndpointConnector.ConnectSocket(Socket socket, EndPoint endpoint, NodeConnectionParameters nodeConnectionParameters, CancellationToken cancellationToken)
   at NBitcoin.Protocol.Node.ConnectAsync(Network network, EndPoint endpoint, NetworkAddress peer, NodeConnectionParameters parameters)
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.ConnectNode(CancellationToken token, Boolean forceRestart) in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 199
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 76
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoop() in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 55
Hosting environment: Production
Content root path: /app/
Now listening on: http://0.0.0.0:32838
Application started. Press Ctrl+C to shut down.
info: NBXplorer.Indexer.BTC: TCP Connection succeed, handshaking...
info: NBXplorer.Indexer.BTC: Handshaked
info: NBXplorer.Indexer.BTC: Testing RPC connection to http://bitcoind:43782/
info: NBXplorer.Indexer.BTC: RPC connection successful
info: NBXplorer.Indexer.BTC: Full node version detected: 220000
info: NBXplorer.Indexer.BTC: NBXplorer is correctly whitelisted by the node
info: NBXplorer.Events: BTC: Node state changed: NotStarted => CoreSynching
```
logs from the bitcoin daemon (bitcoind container)
```
docker logs --tail 100 btcpayserver_bitcoind
2022-05-31T16:41:13Z Default data directory /home/bitcoin/.bitcoin
2022-05-31T16:41:13Z Using data directory /home/bitcoin/.bitcoin
2022-05-31T16:41:13Z Config file: /home/bitcoin/.bitcoin/bitcoin.conf
2022-05-31T16:41:13Z Config file arg: [main] dbcache="1024"
2022-05-31T16:41:13Z Config file arg: [main] maxmempool="500"
2022-05-31T16:41:13Z Config file arg: [main] onion="tor:9050"
2022-05-31T16:41:13Z Config file arg: [main] port="39388"
2022-05-31T16:41:13Z Config file arg: [main] printtoconsole="1"
2022-05-31T16:41:13Z Config file arg: [main] rpcallowip="::/0"
2022-05-31T16:41:13Z Config file arg: [main] rpcallowip="0.0.0.0/0"
2022-05-31T16:41:13Z Config file arg: [main] rpcauth=****
2022-05-31T16:41:13Z Config file arg: [main] rpcauth=****
2022-05-31T16:41:13Z Config file arg: [main] rpcbind=****
2022-05-31T16:41:13Z Config file arg: [main] rpcport="43782"
2022-05-31T16:41:13Z Config file arg: [main] walletdir="/walletdata/mainnet"
2022-05-31T16:41:13Z Config file arg: [main] whitelist="0.0.0.0/0"
2022-05-31T16:41:13Z Config file arg: [main] zmqpubhashblock="tcp://0.0.0.0:28334"
2022-05-31T16:41:13Z Config file arg: [main] zmqpubrawblock="tcp://0.0.0.0:28332"
2022-05-31T16:41:13Z Config file arg: [main] zmqpubrawtx="tcp://0.0.0.0:28333"
2022-05-31T16:41:13Z Using at most 125 automatic connections (1048576 file descriptors available)
2022-05-31T16:41:13Z Using 16 MiB out of 32/2 requested for signature cache, able to store 524288 elements
2022-05-31T16:41:13Z Using 16 MiB out of 32/2 requested for script execution cache, able to store 524288 elements
2022-05-31T16:41:13Z Script verification uses 1 additional threads
2022-05-31T16:41:13Z WARNING: the RPC server is not safe to expose to untrusted networks such as the public internet
2022-05-31T16:41:13Z HTTP: creating work queue of depth 16
2022-05-31T16:41:13Z Using random cookie authentication.
2022-05-31T16:41:13Z scheduler thread start
2022-05-31T16:41:13Z Generated RPC authentication cookie /home/bitcoin/.bitcoin/.cookie
2022-05-31T16:41:13Z Using rpcauth authentication.
2022-05-31T16:41:13Z HTTP: starting 4 worker threads
2022-05-31T16:41:13Z Using wallet directory /walletdata/mainnet
2022-05-31T16:41:13Z init message: Verifying wallet(s)…
2022-05-31T16:41:13Z Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
2022-05-31T16:41:13Z Using wallet /walletdata/mainnet/wallet.dat
2022-05-31T16:41:13Z BerkeleyEnvironment::Open: LogDir=/walletdata/mainnet/database ErrorFile=/walletdata/mainnet/db.log
2022-05-31T16:41:13Z init message: Loading banlist…
2022-05-31T16:41:13Z Missing or invalid file /home/bitcoin/.bitcoin/banlist.dat
2022-05-31T16:41:13Z Recreating the banlist database
2022-05-31T16:41:13Z SetNetworkActive: true
2022-05-31T16:41:13Z Failed to read fee estimates from /home/bitcoin/.bitcoin/fee_estimates.dat. Continue anyway.
2022-05-31T16:41:13Z Using /16 prefix for IP bucketing
2022-05-31T16:41:13Z Cache configuration:
2022-05-31T16:41:13Z * Using 2.0 MiB for block index database
2022-05-31T16:41:13Z * Using 8.0 MiB for chain state database
2022-05-31T16:41:13Z * Using 1014.0 MiB for in-memory UTXO set (plus up to 476.8 MiB of unused mempool space)
2022-05-31T16:41:13Z init message: Loading block index…
2022-05-31T16:41:13Z Switching active chainstate to Chainstate [ibd] @ height -1 (null)
2022-05-31T16:41:13Z Opening LevelDB in /home/bitcoin/.bitcoin/blocks/index
2022-05-31T16:41:13Z Opened LevelDB successfully
2022-05-31T16:41:13Z Using obfuscation key for /home/bitcoin/.bitcoin/blocks/index: 0000000000000000
2022-05-31T16:41:13Z LoadBlockIndexDB: last block file = 0
2022-05-31T16:41:13Z LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=0, size=0, heights=0...0, time=1970-01-01...1970-01-01)
2022-05-31T16:41:13Z Checking all blk files are present...
2022-05-31T16:41:13Z Initializing databases...
2022-05-31T16:41:13Z Opening LevelDB in /home/bitcoin/.bitcoin/chainstate
2022-05-31T16:41:13Z Opened LevelDB successfully
2022-05-31T16:41:13Z Wrote new obfuscate key for /home/bitcoin/.bitcoin/chainstate: 31a89694c4033f49
2022-05-31T16:41:13Z Using obfuscation key for /home/bitcoin/.bitcoin/chainstate: 31a89694c4033f49
2022-05-31T16:41:13Z  block index              25ms
2022-05-31T16:41:13Z init message: Loading wallet…
2022-05-31T16:41:13Z BerkeleyEnvironment::Open: LogDir=/walletdata/mainnet/database ErrorFile=/walletdata/mainnet/db.log
2022-05-31T16:41:13Z [default wallet] Wallet File Version = 139900
2022-05-31T16:41:13Z [default wallet] Keys: 2001 plaintext, 0 encrypted, 2001 w/ metadata, 2001 total. Unknown wallet records: 0
2022-05-31T16:41:13Z [default wallet] Wallet completed loading in              78ms
2022-05-31T16:41:13Z [default wallet] setKeyPool.size() = 2000
2022-05-31T16:41:13Z [default wallet] mapWallet.size() = 0
2022-05-31T16:41:13Z [default wallet] m_address_book.size() = 0
2022-05-31T16:41:13Z loadblk thread start
2022-05-31T16:41:13Z UpdateTip: new best=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f height=0 version=0x00000001 log2_work=32.000022 tx=1 date='2009-01-03T18:15:05Z' progress=0.000000 cache=0.0MiB(0txo)
2022-05-31T16:41:13Z block tree size = 1
2022-05-31T16:41:13Z nBestHeight = 0
2022-05-31T16:41:13Z Failed to open mempool file from disk. Continuing anyway.
2022-05-31T16:41:13Z loadblk thread exit
2022-05-31T16:41:13Z Bound to 127.0.0.1:8334
2022-05-31T16:41:13Z Bound to [::]:39388
2022-05-31T16:41:13Z Bound to 0.0.0.0:39388
2022-05-31T16:41:13Z init message: Loading P2P addresses…
2022-05-31T16:41:13Z Missing or invalid file /home/bitcoin/.bitcoin/peers.dat
2022-05-31T16:41:13Z Recreating peers.dat
2022-05-31T16:41:13Z torcontrol thread start
2022-05-31T16:41:13Z Missing or invalid file /home/bitcoin/.bitcoin/anchors.dat
2022-05-31T16:41:13Z 0 block-relay-only anchors will be tried for connections.
2022-05-31T16:41:13Z init message: Starting network threads…
2022-05-31T16:41:13Z init message: Done loading
2022-05-31T16:41:13Z dnsseed thread start
2022-05-31T16:41:13Z Loading addresses from DNS seed dnsseed.emzy.de
2022-05-31T16:41:13Z addcon thread start
2022-05-31T16:41:13Z opencon thread start
2022-05-31T16:41:13Z net thread start
2022-05-31T16:41:13Z msghand thread start
2022-05-31T16:41:14Z Loading addresses from DNS seed seed.bitcoin.sipa.be
2022-05-31T16:41:14Z Loading addresses from DNS seed seed.bitcoin.wiz.biz
2022-05-31T16:41:15Z Loading addresses from DNS seed seed.bitcoinstats.com
2022-05-31T16:41:15Z Loading addresses from DNS seed seed.bitcoin.sprovoost.nl
2022-05-31T16:41:16Z Loading addresses from DNS seed seed.btc.petertodd.org
2022-05-31T16:41:16Z Loading addresses from DNS seed dnsseed.bluematt.me
2022-05-31T16:41:16Z Loading addresses from DNS seed dnsseed.bitcoin.dashjr.org
2022-05-31T16:41:16Z Loading addresses from DNS seed seed.bitcoin.jonasschnelli.ch
2022-05-31T16:41:16Z 209 addresses found from DNS seeds
2022-05-31T16:41:16Z dnsseed thread exit
```

Postgres Container logs
```
 docker logs --tail 100 2df7889a5e4d
********************************************************************************
WARNING: POSTGRES_HOST_AUTH_METHOD has been set to "trust". This will allow
         anyone with access to the Postgres port to access your database without
         a password, even if POSTGRES_PASSWORD is set. See PostgreSQL
         documentation about "trust":
         https://www.postgresql.org/docs/current/auth-trust.html
         In Docker's default configuration, this is effectively any other
         container on the same system.

         It is not recommended to use POSTGRES_HOST_AUTH_METHOD=trust. Replace
         it with "-e POSTGRES_PASSWORD=password" instead to set a password in
         "docker run".
********************************************************************************
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok


Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
waiting for server to start....2022-05-31 16:41:12.002 UTC [49] LOG:  starting PostgreSQL 13.6 (Debian 13.6-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-05-31 16:41:12.006 UTC [49] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2022-05-31 16:41:12.016 UTC [50] LOG:  database system was shut down at 2022-05-31 16:41:11 UTC
2022-05-31 16:41:12.023 UTC [49] LOG:  database system is ready to accept connections
 done
server started

/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

2022-05-31 16:41:12.299 UTC [49] LOG:  received fast shutdown request
waiting for server to shut down....2022-05-31 16:41:12.310 UTC [49] LOG:  aborting any active transactions
2022-05-31 16:41:12.323 UTC [49] LOG:  background worker "logical replication launcher" (PID 56) exited with exit code 1
2022-05-31 16:41:12.323 UTC [51] LOG:  shutting down
2022-05-31 16:41:12.420 UTC [49] LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

2022-05-31 16:41:12.554 UTC [1] LOG:  starting PostgreSQL 13.6 (Debian 13.6-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-05-31 16:41:12.562 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2022-05-31 16:41:12.562 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2022-05-31 16:41:12.568 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2022-05-31 16:41:12.574 UTC [61] LOG:  database system was shut down at 2022-05-31 16:41:12 UTC
2022-05-31 16:41:12.580 UTC [1] LOG:  database system is ready to accept connections
2022-05-31 16:41:15.667 UTC [68] FATAL:  database "nbxplorermainnet" does not exist
2022-05-31 16:41:16.392 UTC [70] ERROR:  relation "nbxv1_migrations" does not exist at character 25
2022-05-31 16:41:16.392 UTC [70] STATEMENT:  SELECT script_name FROM nbxv1_migrations
2022-05-31 16:41:18.683 UTC [71] FATAL:  database "btcpayservermainnet" does not exist
2022-05-31 16:41:18.725 UTC [72] FATAL:  database "btcpayservermainnet" does not exist
```
**Setup Parameters**
No special setup parameters.

**Comment by aeschylus** [comment]
Seems to have something to do with being unable to connect to the postgres container.

**Comment by aeschylus** [comment]
A similar issue with a .Net connexion string seems to have caused a similar error. Is the indexer configured with the right port to connect to postgres? How can I find that out?

https://stackoverflow.com/questions/60364008/application-startup-exception-system-net-sockets-socketexception-111-connec

**Comment by aeschylus** [comment]
It seems I needed to open port 8333 to allow synchronisation to start.

**Comment by NicolasDorier** [comment]
@aeschylus you shouldn't need the port 8333 (inbound traffic) open. Though outbount traffic should be allowed.

Given the error you got, I think the problem was different though. Glad it eventually worked though!
