### ISSUE TITLE
Improve Shopify error when incorrect store url is entered instead of giving 500

### ISSUE THREAD

**Issue by gkrizek** [btcpayserver/btcpayserver#3853]
### What is your BTCPay version?

I'm running v1.5.4.0

### How did you deploy BTCPay Server?

btcpayserver-docker repo, so the standard Docker deployment

### What happened?

When trying to connect a Shopify store via the Plugin, BTCPay Server throws a 500. It is not able to save the Shopify integration information

### How did you encounter this bug?

1) Go to your store's settings page
2) Click on Plugins
3) Besides Shopify, click Setup
4) Enter in your store details and keys
5) Click Save
6) Receive a 500 error

### Relevant log output

```shell
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Plugins.Shopify.ShopifyApiClient.CheckScopes() in /source/BTCPayServer/Plugins/Shopify/ShopifyApiClient.cs:line 76
   at BTCPayServer.Plugins.Shopify.UIShopifyController.EditShopify(String storeId, ShopifySettings vm, String command) in /source/BTCPayServer/Plugins/Shopify/UIShopifyController.cs:line 252
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 101
   at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 50
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 30
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### What browser do you use?

Safari and Chrome

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by BaderSZ** [comment]
We were able to figure out the cause in a similar example. It was either:

1. Using an incorrect Shop Name when setting up the Shopify plugin in BTCPay (e.g. myshop instead of my-shop like it was in the Shopify URL "my-shop.myshopify.com"), or
2. Incorrect admin API access scopes (enabled order editing instead of orders).

Could you double check to make sure the shop name you entered is exactly what your subdomain is?

**Comment by BaderSZ** [comment]
> You are correct, I received this message from the customer actually:
> 
> > this issue was that in the setup I put in the Google domain URL for the store instead of the shopify admin URL.
> 
> So it is user error, but I'd definitely recommend handling the error better and surfacing a message so a user knows how to fix it.

Definitely. I'll see what I can do and send a fix in a MR.

**Comment by pavlenex** [comment]
So @BaderSZ would you like to tackle this issue and provide better error, or did I misunderstood something? Feel free to do so if you'd like 💯

**Comment by BaderSZ** [comment]
@pavlenex yes I will. :)
