### ISSUE TITLE
[Bug]: Manage Plugin not working

### ISSUE THREAD

**Issue by Pavlos584** [btcpayserver/btcpayserver#3924]
### What is your BTCPay version?

 v1.5.4.0

### How did you deploy BTCPay Server?

Ubuntu 18.04 and Ubuntu 22.04

### What happened?

Hello, today I installed the Btcpay server on ubuntu 18.04 and I noticed that the manage plugins tab is not working, do you know how to solve it? The page takes a long time to load and then it says 504 Gateway Time-out.

### How did you encounter this bug?

"Manage Plugins" and 504 Gateway Time-out error

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
That sounds like an issue retrieving the list of available plugins from GitHub. In that case it would be a temporary problem — does this problem persist and are you experiencing it consistently?

**Comment by Pavlos584** [comment]
Yes I still have this problem I have already reinstalled ubuntu several times, I tried version 18,20,22 and the problem is still the same and I have been working on it for 2 days now.

**Comment by dennisreimann** [comment]
Can you provide the logs for BTCPay Server?

**Comment by Pavlos584** [comment]
2022-07-03 15:57:57.158 +00:00 [INF] LightningListener successfully exited...
2022-07-03 15:57:57.188 +00:00 [INF] Stop watching invoices
2022-07-03 15:58:25.162 +00:00 [INF] DynamicDnsHostedService successfully exited...
2022-07-03 15:58:25.177 +00:00 [INF] NewVersionCheckerHostedService successfully exited...
2022-07-03 15:59:56.057 +00:00 [INF] Root Path: /
2022-07-03 15:59:59.407 +00:00 [INF] Starting listening Monero-like daemons (XMR)
2022-07-03 16:00:00.015 +00:00 [INF] Connection to NBXplorer's database successful, dashboard and reporting features activated.
2022-07-03 16:00:00.055 +00:00 [INF] SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
2022-07-03 16:00:00.386 +00:00 [INF] Starting listening NBXplorer (BTC)
2022-07-03 16:00:00.422 +00:00 [WRN] SSH connection issue of type SshConnectionException: An established connection was aborted by the server.
2022-07-03 16:00:00.428 +00:00 [WRN] Retrying SSH connection in 10 seconds
2022-07-03 16:00:00.481 +00:00 [INF] Starting listening NBXplorer (LTC)
2022-07-03 16:00:00.481 +00:00 [INF] Starting listening NBXplorer (DOGE)
2022-07-03 16:00:00.510 +00:00 [INF] Starting listening NBXplorer (DASH)
2022-07-03 16:00:00.654 +00:00 [INF] Start watching invoices
2022-07-03 16:00:01.028 +00:00 [INF] Starting payment request expiration watcher
2022-07-03 16:00:02.528 +00:00 [INF] 0 pending payment requests being checked since last run
2022-07-03 16:00:06.438 +00:00 [INF] XMR just became unavailable
2022-07-03 16:00:10.429 +00:00 [INF] SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
2022-07-03 16:00:10.587 +00:00 [WRN] SSH connection issue of type SshConnectionException: An established connection was aborted by the server.
2022-07-03 16:00:10.593 +00:00 [WRN] Retrying SSH connection in 20 seconds
2022-07-03 16:00:30.591 +00:00 [INF] SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
2022-07-03 16:00:30.654 +00:00 [WRN] SSH connection issue of type SshConnectionException: An established connection was aborted by the server.
2022-07-03 16:00:30.656 +00:00 [WRN] Retrying SSH connection in 40 seconds
2022-07-03 16:01:10.659 +00:00 [INF] SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
2022-07-03 16:01:10.771 +00:00 [WRN] SSH connection issue of type SshConnectionException: An established connection was aborted by the server.
2022-07-03 16:01:10.771 +00:00 [WRN] Retrying SSH connection in 80 seconds
2022-07-03 16:01:42.256 +00:00 [ERR] Error while performing new version check
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at BTCPayServer.HostedServices.GithubVersionFetcher.Fetch(CancellationToken cancellation) in /source/BTCPayServer/HostedServices/NewVersionCheckerHostedService.cs:line 103
   at BTCPayServer.HostedServices.NewVersionCheckerHostedService.ProcessVersionCheck() in /source/BTCPayServer/HostedServices/NewVersionCheckerHostedService.cs:line 55
   at BTCPayServer.HostedServices.NewVersionCheckerHostedService.LoopVersionCheck() in /source/BTCPayServer/HostedServices/NewVersionCheckerHostedService.cs:line 41
2022-07-03 16:02:30.773 +00:00 [INF] SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
2022-07-03 16:02:30.924 +00:00 [WRN] SSH connection issue of type SshConnectionException: An established connection was aborted by the server.
2022-07-03 16:02:30.925 +00:00 [WRN] Retrying SSH connection in 160 seconds
2022-07-03 16:05:10.933 +00:00 [INF] SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
2022-07-03 16:05:11.023 +00:00 [WRN] SSH connection issue of type SshConnectionException: An established connection was aborted by the server.
2022-07-03 16:05:11.024 +00:00 [WRN] Retrying SSH connection in 320 seconds
2022-07-03 16:10:31.027 +00:00 [INF] SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
2022-07-03 16:10:31.209 +00:00 [WRN] SSH connection issue of type SshConnectionException: An established connection was aborted by the server.
2022-07-03 16:10:31.209 +00:00 [WRN] Retrying SSH connection in 600 seconds
2022-07-03 16:11:38.409 +00:00 [INF] DelayedTransactionBroadcasterHostedService successfully exited...
2022-07-03 16:11:38.428 +00:00 [INF] TorServices successfully exited...
2022-07-03 16:11:38.439 +00:00 [INF] CheckConfigurationHostedService successfully exited...
2022-07-03 16:11:38.550 +00:00 [INF] PullPaymentHostedService successfully exited...
2022-07-03 16:11:43.344 +00:00 [INF] NBXplorerListener successfully exited...
2022-07-03 16:11:43.369 +00:00 [INF] LightningListener successfully exited...
2022-07-03 16:11:43.398 +00:00 [INF] Stop watching invoices
2022-07-03 16:11:55.881 +00:00 [INF] DynamicDnsHostedService successfully exited...
2022-07-03 16:11:55.892 +00:00 [INF] NewVersionCheckerHostedService successfully exited...
2022-07-03 16:13:34.907 +00:00 [INF] Root Path: /
2022-07-03 16:13:39.742 +00:00 [INF] Starting listening Monero-like daemons (XMR)
2022-07-03 16:13:40.316 +00:00 [INF] Connection to NBXplorer's database successful, dashboard and reporting features activated.
2022-07-03 16:13:40.395 +00:00 [INF] SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
2022-07-03 16:13:40.560 +00:00 [INF] Starting listening NBXplorer (BTC)
2022-07-03 16:13:40.643 +00:00 [INF] Starting listening NBXplorer (LTC)
2022-07-03 16:13:40.664 +00:00 [INF] Starting listening NBXplorer (DOGE)
2022-07-03 16:13:40.666 +00:00 [INF] Starting listening NBXplorer (DASH)
2022-07-03 16:13:40.718 +00:00 [INF] Start watching invoices
2022-07-03 16:13:40.762 +00:00 [WRN] SSH connection issue of type SshConnectionException: An established connection was aborted by the server.
2022-07-03 16:13:40.762 +00:00 [WRN] Retrying SSH connection in 10 seconds
2022-07-03 16:13:41.060 +00:00 [INF] Starting payment request expiration watcher
2022-07-03 16:13:41.950 +00:00 [INF] 0 pending payment requests being checked since last run
2022-07-03 16:13:48.436 +00:00 [INF] XMR just became unavailable
2022-07-03 16:13:50.763 +00:00 [INF] SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
2022-07-03 16:13:50.936 +00:00 [WRN] SSH connection issue of type SshConnectionException: An established connection was aborted by the server.
2022-07-03 16:13:50.936 +00:00 [WRN] Retrying SSH connection in 20 seconds
2022-07-03 16:14:10.938 +00:00 [INF] SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
2022-07-03 16:14:11.009 +00:00 [WRN] SSH connection issue of type SshConnectionException: An established connection was aborted by the server.
2022-07-03 16:14:11.010 +00:00 [WRN] Retrying SSH connection in 40 seconds
2022-07-03 16:14:51.027 +00:00 [INF] SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
2022-07-03 16:14:51.189 +00:00 [WRN] SSH connection issue of type SshConnectionException: An established connection was aborted by the server.
2022-07-03 16:14:51.189 +00:00 [WRN] Retrying SSH connection in 80 seconds
2022-07-03 16:15:21.825 +00:00 [ERR] Error while performing new version check
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at BTCPayServer.HostedServices.GithubVersionFetcher.Fetch(CancellationToken cancellation) in /source/BTCPayServer/HostedServices/NewVersionCheckerHostedService.cs:line 103
   at BTCPayServer.HostedServices.NewVersionCheckerHostedService.ProcessVersionCheck() in /source/BTCPayServer/HostedServices/NewVersionCheckerHostedService.cs:line 55
   at BTCPayServer.HostedServices.NewVersionCheckerHostedService.LoopVersionCheck() in /source/BTCPayServer/HostedServices/NewVersionCheckerHostedService.cs:line 41
2022-07-03 16:16:11.189 +00:00 [INF] SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
2022-07-03 16:16:11.293 +00:00 [WRN] SSH connection issue of type SshConnectionException: An established connection was aborted by the server.
2022-07-03 16:16:11.293 +00:00 [WRN] Retrying SSH connection in 160 seconds
2022-07-03 16:17:43.400 +00:00 [INF] User 'e7743df3-5899-4293-9aa0-d66a69edeacf' logged in.

**Comment by Pavlos584** [comment]
[log1.txt](https://github.com/btcpayserver/btcpayserver/files/9035356/log1.txt)

**Comment by dennisreimann** [comment]
Thanks! As assumed the GitHub version check isn't working. This is the relevant part from the logs:

```
2022-07-03 16:15:21.825 +00:00 [ERR] Error while performing new version check
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at BTCPayServer.HostedServices.GithubVersionFetcher.Fetch(CancellationToken cancellation) in /source/BTCPayServer/HostedServices/NewVersionCheckerHostedService.cs:line 103
   at BTCPayServer.HostedServices.NewVersionCheckerHostedService.ProcessVersionCheck() in /source/BTCPayServer/HostedServices/NewVersionCheckerHostedService.cs:line 55
   at BTCPayServer.HostedServices.NewVersionCheckerHostedService.LoopVersionCheck() in /source/BTCPayServer/HostedServices/NewVersionCheckerHostedService.cs:line 41
```

@Kukks Do you have an idea why this might happen consistently? I cannot reproduce it — might this be a firewall issue?

**Comment by Pavlos584** [comment]
So I discovered the problem, changed the vpn server and the plugins started working!

**Comment by dennisreimann** [comment]
Thanks for reporting, glad it's working for you now!
