### ISSUE TITLE
[Bug]: LNURL NFC Support - 500 Error

### ISSUE THREAD

**Issue by leesalminen** [btcpayserver/btcpayserver#3950]
### What is your BTCPay version?

v1.6.0

### How did you deploy BTCPay Server?

Docker

### What happened?

Trying out the new plugin to accept payment via NFC with LNURLw codes. I'm getting a 500 error at checkout using a lnurl withdraw string.

### How did you encounter this bug?

1.) Enable LNURL NFC Support Plugin v1.0.2.0
2.) Create an Invoice
3.) Navigate to checkout for that invoice
4.) Click "Pay by LNURL Withdraw"
5.) Enter a LNURL...... encoded withdraw code and hit OK
6.) `POST /plugins/NFC` returns 500 (body of `{"lnurl":"LNURLxxx","destination":"lnbcxxx"}`)
7.) Invoice isn't paid

### Relevant log output

```shell
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMJ176OUKP7I", Request id "0HMJ176OUKP7I:00000002": An unhandled exception was thrown by the application.
System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<LNURLPayRequestCallbackResponse> LNURL.LNURLPayRequest.SendRequest(BTCPayServer.Lightning.LightMoney, NBitcoin.Network, System.Net.Http.HttpClient, System.String)'.
   at BTCPayServer.Plugins.NFC.NFCController.SubmitLNURLWithdrawForInvoice(SubmitRequest request)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at BTCPayServer.Plugins.NFC.NFCController.SubmitLNURLWithdrawForInvoice(SubmitRequest request)
   at lambda_method2850(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResourceFilter()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 101
   at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 50
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 30
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### What browser do you use?

Chrome 103 on Android 11

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by leesalminen** [comment]
The only thing I can think of here is that this instance is using clightning and not lnd. Could be?

**Comment by Kukks** [comment]
Just released a new version. Can you try again?

**Comment by leesalminen** [comment]
Confirmed working now in that same environment. Thanks!
