### ISSUE TITLE
Integrating external identity provider and JWT token authorization 

### ISSUE THREAD

**Issue by sigHash** [btcpayserver/btcpayserver#401]
Hi everyone!

I have an existing identity provider that users can login and obtain JWT tokens. How can I use those tokens to authorize access to BTCPayserver's routes? 

I basically wanna disable local logins and BitPay authentication and use my own JWT tokens for authentication. 

P.S. I am using BTCPayserver as as a non public facing application.

**Comment by NicolasDorier** [comment]
@Kukks is working on OpenId type of authentication which will support two flows.

**Comment by sigHash** [comment]
@NicolasDorier That's swell 
Can I temporarily disable auth without breaking the pay server?

**Comment by NicolasDorier** [comment]
if you mean creating an invoice without auth, you already can via API in the store settings.

**Comment by sigHash** [comment]
No I mean completely removing the Auth flow and replace it with something like this:

https://www.c-sharpcorner.com/article/jwt-json-web-token-authentication-in-asp-net-core/

**Comment by Kukks** [comment]
Not without modifying the code. A lot of the controllers are hard coded to use cookie authentication or bitpay auth; that's why for the new api I am not reusing the old controllers. Furthermore, to make btcpay use an external identity provider requires way more work than simply supporting jwts on the site which is a separate issue that I'm working on. 

If your identity provider implements Oauth, you can set up the mvc site to allow authentication via your provider but you'd still need a local account on btcpay that would be linked to it. You could use OAuth introspection to validate foreign tokens but the site has custom, dynamic claims and Asp.Net Identity baked into it deep so without a mjaor refactor nothing would work anyway.

**Comment by sigHash** [comment]
Been trying to test Oauth2,  I have added new controller to BTCPay and tried to disable auth by removing:

```
            services.AddAuthorization(o => Policies.AddBTCPayPolicies(o));
            BitpayAuthentication.AddAuthentication(services);
```

```
            app.UseMiddleware<BTCPayMiddleware>();
```

```
            services.TryAddSingleton<Bitpay>(o =>
            {
                if (o.GetRequiredService<BTCPayServerOptions>().NetworkType == NetworkType.Mainnet)
                    return new Bitpay(new Key(), new Uri("https://bitpay.com/"));
                else
                    return new Bitpay(new Key(), new Uri("https://test.bitpay.com/"));
            });
```

```
            services.AddTransient<IConfigureOptions<MvcOptions>, BTCPayClaimsFilter>();
```

I get this error trying [Authorize] on new route:

```

fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: An unhandled exception has occurred while executing the request.
System.InvalidOperationException: The AuthorizationPolicy named: 'btcpay.store.cancreateinvoice' was not found.
   at Microsoft.AspNetCore.Authorization.AuthorizationPolicy.CombineAsync(IAuthorizationPolicyProvider policyProvider, IEnumerable`1 authorizeData)
   at Microsoft.AspNetCore.Mvc.Internal.AuthorizationApplicationModelProvider.GetFilter(IAuthorizationPolicyProvider policyProvider, IEnumerable`1 authData)
   at Microsoft.AspNetCore.Mvc.Internal.AuthorizationApplicationModelProvider.OnProvidersExecuting(ApplicationModelProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.UpdateCollection()
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.get_ActionDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
```

I'm little bit confuse why it's still looking for `btcpay.store.cancreateinvoice`?

**Comment by NicolasDorier** [comment]
look at controller or action level. Authorize attribute.

**Comment by sigHash** [comment]
Thanks. I managed to make it work with JWT tokens.
