### ISSUE TITLE
[Bug]: NBXplorer few blocks behind

### ISSUE THREAD

**Issue by 2ge** [btcpayserver/btcpayserver#4057]
### What is your BTCPay version?

v1.6.3.0

### How did you deploy BTCPay Server?

docker

### What happened?

sometimes (not all the time) NBXplorer is behind sync.

### How did you encounter this bug?

just happening

### Relevant log output

```shell
info: NBXplorer.Events: BTC: New block 000000000000000000050c9fe55e1a5baa4a0cb2ad00b3b4050422a52405b7df (750098)
info: NBXplorer.Events: BTC: New block 000000000000000000099a18cf7626fc49b4e278a2cb5cafd849b23a0d7b9454 (750099)
info: NBXplorer.Events: BTC: Node state changed: Ready => NBXplorerSynching
info: NBXplorer.Events: BTC: New block 00000000000000000002647619c31eefe7140e032879f106e423989160aa5979 (750100)
fail: NBXplorer.Indexer.BTC: Unhandled exception in the indexer, retrying in 60 seconds
Npgsql.NpgsqlException (0x80004005): Exception while reading from stream
 ---> System.TimeoutException: Timeout during reading attempt
   at Npgsql.Internal.NpgsqlReadBuffer.<Ensure>g__EnsureLong|41_0(NpgsqlReadBuffer buffer, Int32 count, Boolean async, Boolean readingNotifications)
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|211_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteScalar(Boolean async, CancellationToken cancellationToken)
   at Dapper.SqlMapper.ExecuteScalarImplAsync[T](IDbConnection cnn, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 1219
   at NBXplorer.Backends.Postgres.DbConnectionHelper.FetchMatches(IEnumerable`1 newOuts, IEnumerable`1 newIns) in /source/NBXplorer/Backends/Postgres/DbConnectionHelper.cs:line 131
   at NBXplorer.Backends.Postgres.PostgresRepository.GetMatches(DbConnectionHelper connection, IList`1 txs, SlimChainedBlock slimBlock, DateTimeOffset now, Boolean useCache, Boolean immediateSave) in /source/NBXplorer/Backends/Postgres/PostgresRepository.cs:line 575
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.SaveMatches(DbConnectionHelper conn, List`1 transactions, SlimChainedBlock slimChainedBlock, Boolean fireEvents) in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 366
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 164
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 164
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 77
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoop() in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 55
info: NBXplorer.Events: BTC: Node state changed: NBXplorerSynching => NotStarted
info: NBXplorer.Indexer.BTC: Restarting node connection...
info: NBXplorer.Indexer.BTC: TCP Connection succeed, handshaking...
info: NBXplorer.Indexer.BTC: Handshaked
info: NBXplorer.Indexer.BTC: Testing RPC connection to http://bitcoind:43782/
info: NBXplorer.Indexer.BTC: RPC connection successful
info: NBXplorer.Indexer.BTC: Full node version detected: 220000
info: NBXplorer.Indexer.BTC: NBXplorer is correctly whitelisted by the node
info: NBXplorer.Events: BTC: Node state changed: NotStarted => NBXplorerSynching
info: NBXplorer.Events: BTC: New block 00000000000000000002d5c0f54e40bf0bbcf87f533c45c8ac2f047ac6daac00 (750101)
info: NBXplorer.Events: BTC: New block 00000000000000000001082e4690747e63c24526f0251ffb01fe5d0f4e437520 (750102)
info: NBXplorer.Events: BTC: New block 00000000000000000004404a54dde1a2c266a12be7b174f790a34d2b1c07cbd8 (750103)
info: NBXplorer.Events: BTC: New block 00000000000000000001ee543a5836330c71593f2d8cbcc3cf48a0693533caa3 (750104)
```

### What browser do you use?

Brave, not important.

### Additional information

<img width="483" alt="image" src="https://user-images.githubusercontent.com/1067032/185635241-a9a26ee3-835d-4464-9b35-271739b8683a.png">

I tried to resync, delete block chain then resync, then fastsync...it is just happening - i got enough ram, I got enough CPU...

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by Pavlos584** [comment]
Hi, I had the same problem, are you using HDD or SSD? I solved it by replacing the HDD with an SSD. I do not recommend installing btcpayserver on HDD, it absolutely does not keep up.

**Comment by 2ge** [comment]
I run it in VS, Proxmox, SSD is there, here are some stats, I can give it more RAM, but not sure if this is issue:
```
# docker stats
CONTAINER ID   NAME                       CPU %     MEM USAGE / LIMIT    MEM %     NET I/O           BLOCK I/O         PIDS
2d089ac60ec0   nginx-gen                  0.24%     5.254MiB / 3.84GiB   0.13%     13.2kB / 0B       14.6MB / 0B       12
cdebe57f5350   nginx                      0.00%     3.996MiB / 3.84GiB   0.10%     27.8MB / 14.3MB   6.54MB / 0B       2
2b15a41d1d10   generated_btcpayserver_1   0.08%     257.9MiB / 3.84GiB   6.56%     83.6MB / 50.4MB   910MB / 47.1kB    22
89e549a679cc   generated_bitcoin_rtl_1    0.00%     24.69MiB / 3.84GiB   0.63%     14kB / 1.14kB     13.2MB / 0B       12
cecb8d8c20d4   generated_nbxplorer_1      0.02%     565.4MiB / 3.84GiB   14.38%    2.73GB / 2.07GB   495MB / 43kB      23
a0133ab07c3c   btcpayserver_lnd_bitcoin   0.15%     456.2MiB / 3.84GiB   11.60%    2.56GB / 49.3MB   890MB / 5.2GB     22
980bce8a9808   btcpayserver_bitcoind      0.58%     888.9MiB / 3.84GiB   22.61%    1.73GB / 11.4GB   139GB / 22.6GB    16
2d05b8336696   generated_postgres_1       0.00%     276.3MiB / 3.84GiB   7.03%     1.87GB / 152MB    74.9MB / 51.3GB   18

# free -h
              total        used        free      shared  buff/cache   available
Mem:          3.8Gi       2.2Gi       130Mi        67Mi       1.5Gi       1.3Gi
Swap:         2.0Gi       107Mi       1.9Gi

# df -h
Filesystem                  Size  Used Avail Use% Mounted on
udev                        1.9G     0  1.9G   0% /dev
tmpfs                       394M  1.7M  392M   1% /run
/dev/mapper/vg_sys-root     4.0G  780M  3.3G  20% /
/dev/mapper/vg_sys-usr      4.0G  3.5G  571M  87% /usr
tmpfs                       2.0G     0  2.0G   0% /dev/shm
tmpfs                       5.0M     0  5.0M   0% /run/lock
tmpfs                       2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/sda2                   974M  400M  507M  45% /boot
/dev/mapper/vg_sys-var      4.0G  509M  3.5G  13% /var
/dev/mapper/vg_sys-home     4.0G   61M  4.0G   2% /home
/dev/loop0                   45M   45M     0 100% /snap/aria2c/9
/dev/loop2                   47M   47M     0 100% /snap/snapd/16292
/dev/loop1                   56M   56M     0 100% /snap/core18/2538
/dev/mapper/vg_sys-tmp      2.0G   47M  2.0G   3% /tmp
/dev/mapper/vg_sys-var_log  4.0G  527M  3.5G  13% /var/log
/dev/sdb                    500G  105G  396G  21% /var/lib/docker
tmpfs                       394M     0  394M   0% /run/user/0
overlay                     500G  105G  396G  21% /var/lib/docker/overlay2/f80d4afabfd4b97d8a39c127cbfb038a76036ca86589565385c30c42f12830ae/merged
overlay                     500G  105G  396G  21% /var/lib/docker/overlay2/168abf03d6560a210bca353a119c82e519b7f2b1befb68a757c4efb0f3028bb9/merged
overlay                     500G  105G  396G  21% /var/lib/docker/overlay2/8effaf17832a3cfdc2b180487776e17e053261cb13d286bac97986e0ed0e0ab3/merged
overlay                     500G  105G  396G  21% /var/lib/docker/overlay2/954ba0c1b24e3aac5c08b860258a189a51a34d9c3654e2755b9433d8c65cade6/merged
overlay                     500G  105G  396G  21% /var/lib/docker/overlay2/e48c5b8b6cdf1a82d7cd15970dd9bd9540c18617343978a246949ad9b7f751ac/merged
overlay                     500G  105G  396G  21% /var/lib/docker/overlay2/565d184625528aeb690e0a19e0d97954e38f70c20f472bc7cd578efa1045d34e/merged
overlay                     500G  105G  396G  21% /var/lib/docker/overlay2/847d385f93ad3e93f6f9911f074fe75ed178566ef27f57b9d19d5c85d4cfbaf5/merged
overlay                     500G  105G  396G  21% /var/lib/docker/overlay2/5d879b9b5568ace508670ccb94f49f35a67524c4a8b352260a94f6b55a4f8dd3/merged

```

Running bonnie++ there, will take time, will post update.

**Comment by 2ge** [comment]
```
# bonnie++ -u root
Using uid:0, gid:0.
Writing a byte at a time...done
Writing intelligently...done
Rewriting...done
Reading a byte at a time...done
Reading intelligently...done
start 'em...done...done...done...done...done...
Create files in sequential order...done.
Stat files in sequential order...done.
Delete files in sequential order...done.
Create files in random order...done.
Stat files in random order...done.
Delete files in random order...done.
Version  1.98       ------Sequential Output------ --Sequential Input- --Random-
                    -Per Chr- --Block-- -Rewrite- -Per Chr- --Block-- --Seeks--
Name:Size etc        /sec %CP  /sec %CP  /sec %CP  /sec %CP  /sec %CP  /sec %CP
btcpay           8G  820k  45 22.9m   4 4232k   0 3117k  89 82.0m  11  5411 121
Latency             13744us     408ms     1459s    9639us     796ms   19743us
Version  1.98       ------Sequential Create------ --------Random Create--------
btcpay              -Create-- --Read--- -Delete-- -Create-- --Read--- -Delete--
              files  /sec %CP  /sec %CP  /sec %CP  /sec %CP  /sec %CP  /sec %CP
                 16     0   1 +++++ +++ 724249376   1     0   1 +++++ +++ 724249376   2
Latency               121ms     133us     632ms     104ms      86us    5204ms
1.98,1.98,btcpay,1,1660594334,8G,,8192,5,820,45,23443,4,4232,0,3117,89,83924,11,5411,121,16,,,,,896,1,+++++,+++,1207,1,988,1,+++++,+++,942,2,13744us,408ms,1459s,9639us,796ms,19743us,121ms,133us,632ms,104ms,86us,5204ms
```

I will try to move instance to another server, maybe it will solve the problem, because on this I am running elastic search and so on. I will post results later.

**Comment by 2ge** [comment]
so it seems, it was in the end HDD performance, after migrating to SSD problem seems to be gone. NOFIX.
