### ISSUE TITLE
[Bug]: Exception thrown when navigating to Pull Payments page

### ISSUE THREAD

**Issue by leesalminen** [btcpayserver/btcpayserver#4101]
### What is your BTCPay version?

BTCPayServer v1.6.10.0 on SQLite
NBXplorer v2.3.33 on Postgres

### How did you deploy BTCPay Server?

I've deployed BTCPayServer manually to Ubuntu 20.04.

### What happened?

Navigating to the Pull Payments screen fails to load for all stores in the instance.

### How did you encounter this bug?

1.) Log into your BTCPayServer instance
2.) Navigate to Left Navigation -> Pull Payments
3.) An exception is thrown in the logs and the page fails to load

### Relevant log output

```shell
Sep 05 20:15:11 x11r0n.local bash[176969]: fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMKFCI3T3D9E", Request id "0HMKFCI3T3D9E:00000002": An unhandled exception was thrown by the application.
Sep 05 20:15:11 x11r0n.local bash[176969]: System.InvalidOperationException: The LINQ expression 'DbSet<PullPaymentData>()
Sep 05 20:15:11 x11r0n.local bash[176969]:     .Where(p => p.StoreId == __storeId_0)
Sep 05 20:15:11 x11r0n.local bash[176969]:     .OrderByDescending(p => p.StartDate)
Sep 05 20:15:11 x11r0n.local bash[176969]:     .Where(p => !(p.Archived) && p.EndDate != null ? p.EndDate > (DateTimeOffset?)DateTimeOffset.UtcNow : True && p.StartDate <= DateTimeOffset.UtcNow)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
Sep 05 20:15:11 x11r0n.local bash[176969]:    at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|15_0(ShapedQueryExpression translated, <>c__DisplayClass15_0& )
Sep 05 20:15:11 x11r0n.local bash[176969]:    at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
Sep 05 20:15:11 x11r0n.local bash[176969]:    at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
Sep 05 20:15:11 x11r0n.local bash[176969]:    at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
Sep 05 20:15:11 x11r0n.local bash[176969]:    at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
Sep 05 20:15:11 x11r0n.local bash[176969]:    at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
Sep 05 20:15:11 x11r0n.local bash[176969]:    at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
Sep 05 20:15:11 x11r0n.local bash[176969]:    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
Sep 05 20:15:11 x11r0n.local bash[176969]:    at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
Sep 05 20:15:11 x11r0n.local bash[176969]:    at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
Sep 05 20:15:11 x11r0n.local bash[176969]:    at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
Sep 05 20:15:11 x11r0n.local bash[176969]:    at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
Sep 05 20:15:11 x11r0n.local bash[176969]:    at BTCPayServer.Controllers.UIStorePullPaymentsController.PullPayments(String storeId, PullPaymentState pullPaymentState, Int32 skip, Int32 count, String sortOrder) in /home/ubuntu/btcpayserver/BTCPayServer/Controllers/UIStorePullPaymentsController.PullPayments.cs:line 220
Sep 05 20:15:11 x11r0n.local bash[176969]:    at BTCPayServer.Controllers.UIStorePullPaymentsController.PullPayments(String storeId, PullPaymentState pullPaymentState, Int32 skip, Int32 count, String sortOrder) in /home/ubuntu/btcpayserver/BTCPayServer/Controllers/UIStorePullPaymentsController.PullPayments.cs:line 239
Sep 05 20:15:11 x11r0n.local bash[176969]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Sep 05 20:15:11 x11r0n.local bash[176969]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Sep 05 20:15:11 x11r0n.local bash[176969]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Sep 05 20:15:11 x11r0n.local bash[176969]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Sep 05 20:15:11 x11r0n.local bash[176969]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Sep 05 20:15:11 x11r0n.local bash[176969]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
Sep 05 20:15:11 x11r0n.local bash[176969]: --- End of stack trace from previous location ---
Sep 05 20:15:11 x11r0n.local bash[176969]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Sep 05 20:15:11 x11r0n.local bash[176969]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
Sep 05 20:15:11 x11r0n.local bash[176969]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Sep 05 20:15:11 x11r0n.local bash[176969]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResourceFilter()
Sep 05 20:15:11 x11r0n.local bash[176969]: --- End of stack trace from previous location ---
Sep 05 20:15:11 x11r0n.local bash[176969]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Sep 05 20:15:11 x11r0n.local bash[176969]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Sep 05 20:15:11 x11r0n.local bash[176969]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Sep 05 20:15:11 x11r0n.local bash[176969]: --- End of stack trace from previous location ---
Sep 05 20:15:11 x11r0n.local bash[176969]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Sep 05 20:15:11 x11r0n.local bash[176969]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Sep 05 20:15:11 x11r0n.local bash[176969]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Sep 05 20:15:11 x11r0n.local bash[176969]:    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Sep 05 20:15:11 x11r0n.local bash[176969]:    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Sep 05 20:15:11 x11r0n.local bash[176969]:    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
Sep 05 20:15:11 x11r0n.local bash[176969]:    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Sep 05 20:15:11 x11r0n.local bash[176969]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Sep 05 20:15:11 x11r0n.local bash[176969]:    at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /home/ubuntu/btcpayserver/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 101
Sep 05 20:15:11 x11r0n.local bash[176969]:    at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /home/ubuntu/btcpayserver/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 50
Sep 05 20:15:11 x11r0n.local bash[176969]:    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
Sep 05 20:15:11 x11r0n.local bash[176969]:    at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /home/ubuntu/btcpayserver/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 30
Sep 05 20:15:11 x11r0n.local bash[176969]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### What browser do you use?

Safari Version 15.6.1 (17613.3.9.1.16) on MacOS 12.5.1 (21G83)

### Additional information

I believe this issue may be related to running btcpayserver with SQLite as the backend db.

This issue may be related to issue #3640. That issue is closed and reported on an older version of BTCPayServer, so I am reporting again on the latest version.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
Closing due to inactivty if you're still having issues, please provide info we asked so we can help troubleshoot.
