### ISSUE TITLE
[Bug]: 502 Bad gateway on 1.6.10.0

### ISSUE THREAD

**Issue by Juandurdaneta** [btcpayserver/btcpayserver#4162]
### What is your BTCPay version?

v1.6.10.0

### How did you deploy BTCPay Server?

btcpayserver-docker

### What happened?

Getting a 502 bad gateway after restarting btcpay server, also getting a "Error on the MigrationStartupTask" whenever i check the logs for generated_btcpayserver_1

### How did you encounter this bug?

Restarted the server via btcpay-restart.sh and got a 502 bad gateway.

### Relevant log output

```shell
info: Configuration:  Data Directory: /datadir
info: Configuration:  Configuration File: /datadir/Main/settings.config
info: BTCPayServer.Plugins.PluginManager: Loading plugins from /root/.btcpayserver/Plugins
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer - 1.6.10.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Shopify - 1.6.10.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.PayButton - 1.6.10.0
info: Configuration:  Supported chains: BTC
info: Configuration:  BTC: Explorer url is http://nbxplorer:32838/
info: Configuration:  BTC: Cookie file is /root/.nbxplorer/Main/.cookie
info: Configuration:  Network: Mainnet
info: Configuration:  LogFile: /datadir/btcpay.log
info: Configuration:  Log Level: Debug
fail: BTCPayServer.Hosting.MigrationStartupTask: Error on the MigrationStartupTask
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Data.StoreDataExtensions.GetStoreBlob(StoreData storeData) in /source/BTCPayServer/Data/StoreDataExtensions.cs:line 53
   at BTCPayServer.Hosting.MigrationStartupTask.MigratePaymentMethodCriteria() in /source/BTCPayServer/Hosting/MigrationStartupTask.cs:line 677
   at BTCPayServer.Hosting.MigrationStartupTask.ExecuteAsync(CancellationToken cancellationToken) in /source/BTCPayServer/Hosting/MigrationStartupTask.cs:line 100
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Data.StoreDataExtensions.GetStoreBlob(StoreData storeData) in /source/BTCPayServer/Data/StoreDataExtensions.cs:line 53
   at BTCPayServer.Hosting.MigrationStartupTask.MigratePaymentMethodCriteria() in /source/BTCPayServer/Hosting/MigrationStartupTask.cs:line 677
   at BTCPayServer.Hosting.MigrationStartupTask.ExecuteAsync(CancellationToken cancellationToken) in /source/BTCPayServer/Hosting/MigrationStartupTask.cs:line 100
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.StartWithTasksAsync(IWebHost webHost, CancellationToken cancellationToken) in /source/BTCPayServer/Extensions/WebHostExtensions.cs:line 19
   at BTCPayServer.Program.Main(String[] args) in /source/BTCPayServer/Program.cs:line 70
```

### What browser do you use?

Safari, Chrome

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by NicolasDorier** [comment]
Thanks @Juandurdaneta we will release a new version today fixing this.
