### ISSUE TITLE
[Bug]: When restarting BTCPay Server, the automated payout processors are really spamming logs

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#4193]
### What is your BTCPay version?

1.6.11.0

### How did you deploy BTCPay Server?

Docker deployment

### What happened?

When restarting BTCPay Server, the automated payout processor are really spammy.

### How did you encounter this bug?

Start BTCPay Server with lot's of Lightning payout processor.

Then `docker restart generated_btcpayserver_1`

### Relevant log output

```shell
info: LightningAutomatedPayoutSenderFactory:Gpuwiyfaw8aCMALPG2dWjBhM3SFEJJqtYyoseRW4s81n:BTC_LightningLike: LightningAutomatedPayoutProcessor successfully exited...
info: OnChainAutomatedPayoutSenderFactory:H568hNSBXfSFfRmsDdQ6EBV4E7TjgARVY79XezwLH194:BTC: OnChainAutomatedPayoutProcessor successfully exited...
info: OnChainAutomatedPayoutSenderFactory:AhTPb8mxCtdb7tY2w3i16atES3Chwfwf8RGprSmkdsbs:BTC: OnChainAutomatedPayoutProcessor successfully exited...
info: LightningAutomatedPayoutSenderFactory:8J6CXWoxDCh9ZAdgTvzEW11UMSojuN3eGrtTnzBi4rBT:BTC_LightningLike: LightningAutomatedPayoutProcessor successfully exited...
info: OnChainAutomatedPayoutSenderFactory:4vHRPJzrkjvSzwa9MkngepAbLqszSucGfz84mpc2dCvZ:BTC: OnChainAutomatedPayoutProcessor successfully exited...
info: OnChainAutomatedPayoutSenderFactory:DGLEgAEPNt7kb5YiV5zw3FwY65tLcHoowYqjPMtwm5TS:BTC: OnChainAutomatedPayoutProcessor successfully exited...
info: LightningAutomatedPayoutSenderFactory:HqyMka4i63GwmsxYJsEwPwEhLw4wyMk5DiyP8cmjjkHN:BTC_LightningLike: LightningAutomatedPayoutProcessor successfully exited...
info: OnChainAutomatedPayoutSenderFactory:2wFnsRULXYfhRWAT6M6Lat768nYSbXhDjxxDrRPJK1EM:BTC: OnChainAutomatedPayoutProcessor successfully exited...
info: OnChainAutomatedPayoutSenderFactory:FgGTsGYP7ZhVuTCLnSeuRB84GPdYds117qq4y1epiLdm:BTC: OnChainAutomatedPayoutProcessor successfully exited...
info: LightningAutomatedPayoutSenderFactory:GQqbNrbv9qCoNATzqZHQA2oxxZtT1oYRhcfMUmMnMQHD:BTC_LightningLike: LightningAutomatedPayoutProcessor successfully exited...
info: OnChainAutomatedPayoutSenderFactory:HwQBYX9GRyn6DjCjZMT6joUE2bD5RF5zqSsHLTTxG15W:BTC: OnChainAutomatedPayoutProcessor successfully exited...
info: OnChainAutomatedPayoutSenderFactory:HWnxzR6KwRCwaqLS5FjrqNMfxqKwbPDukXVneoE4REyy:BTC: OnChainAutomatedPayoutProcessor successfully exited...
info: OnChainAutomatedPayoutSenderFactory:6rERBPKRpoatSnb7GwzmFnGeUhxcAFDjFVmhZ5Ur4uGT:BTC: OnChainAutomatedPayoutProcessor successfully exited...
info: OnChainAutomatedPayoutSenderFactory:12dzxmrSijy6fesGy46UzymnYyfGphB7k1eN4P57dWpY:BTC: OnChainAutomatedPayoutProcessor successfully exited...
info: OnChainAutomatedPayoutSenderFactory:8iJvJxjdFuuJ2McK2LkqaaXRb8mytMHqXMknvY59ebLG:BTC: OnChainAutomatedPayoutProcessor successfully exited...
info: OnChainAutomatedPayoutSenderFactory:7ZePEDpdvkffQq7gQza5MriSEyXLEWtBZxiU7mnvXqCw:BTC: OnChainAutomatedPayoutProcessor successfully exited...
info: OnChainAutomatedPayoutSenderFactory:38EPKk73uhnaigyG5HoPN58Y6sd1vc5UBSGjCyMmq9Yj:BTC: OnChainAutomatedPayoutProcessor successfully exited...
info: OnChainAutomatedPayoutSenderFactory:2xJFZv9DWR3KSDjpJYoBP1hKgU3aqx39u26bg7AHXXG5:BTC: OnChainAutomatedPayoutProcessor successfully exited...
info: OnChainAutomatedPayoutSenderFactory:ENAYfgg8caXWqknGrAT5Y4HepJnbtYPU1Zc6i1kfBqDR:BTC: OnChainAutomatedPayoutProcessor successfully exited...
info: OnChainAutomatedPayoutSenderFactory:FqKDYme2yBCEj4DtfHuvrmnofWh2ArYgT4iojeVJTdD8:BTC: OnChainAutomatedPayoutProcessor successfully exited...
info: OnChainAutomatedPayoutSenderFactory:CAsEYKwf1mCyQBmLzCpYPpTY42MLs1hA5Y1x9dTSA5wn:BTC: OnChainAutomatedPayoutProcessor successfully exited...
info: OnChainAutomatedPayoutSenderFactory:Gh6Cf4WhVyYbCDgHYSKcFpZwXBkTB7mXo3Z9eqWPEyuX:BTC: OnChainAutomatedPayoutProcessor successfully exited...
info: LightningAutomatedPayoutSenderFactory:25ZnQoD7wa6GU7mhFCMYnt16FcvKUHkNTgSuLTioDh7U:BTC_LightningLike: LightningAutomatedPayoutProcessor successfully exited...
info: LightningAutomatedPayoutSenderFactory:9NrouqjPcJ7ev8SD4fW1JZZdcFFfaoooiD9v8CaqWiSp:BTC_LightningLike: LightningAutomatedPayoutProcessor successfully exited...
info: LightningAutomatedPayoutSenderFactory:NbbVEuVm8oFECTaTQjnmQWXWm5b48Hp52G7ataamCwa:BTC_LightningLike: LightningAutomatedPayoutProcessor successfully exited...
info: OnChainAutomatedPayoutSenderFactory:FVWRAgXkES91YmEXhFjFY4d67MR6Nbc3V6iCm4WZk4Y2:BTC: OnChainAutomatedPayoutProcessor successfully exited...
info: OnChainAutomatedPayoutSenderFactory:EgWxkTwdGMypnzyvi6ayB3Y2rih1jVX8EoE4XJtAc6vz:BTC: OnChainAutomatedPayoutProcessor successfully exited...
info: LightningAutomatedPayoutSenderFactory:6Uid7o4zm6XmsvfgoTQw63bhnJ8vaeBUheZ31LHNX9X3:BTC_LightningLike: LightningAutomatedPayoutProcessor successfully exited...
info: LightningAutomatedPayoutSenderFactory:FYucnLTGzH522JJguQmEpLvrYiT7rFnKAxspxpVTnBLF:BTC_LightningLike: LightningAutomatedPayoutProcessor successfully exited...
info: OnChainAutomatedPayoutSenderFactory:2vZoueEHJ1bsAon1BHUm6KTRd9TYn1JjAWGisNJ28gLX:BTC: OnChainAutomatedPayoutProcessor successfully exited...
info: OnChainAutomatedPayoutSenderFactory:3K3e36WqbLBpABuCC7Zt9DDsipm31gMsck1gKdw22vM8:BTC: OnChainAutomatedPayoutProcessor successfully exited...
info: OnChainAutomatedPayoutSenderFactory:A65gtSN7PkT5bPEKn1iHSefTdsG7xm5QEwkV6bLaEBw3:BTC: OnChainAutomatedPayoutProcessor successfully exited...
info: LightningAutomatedPayoutSenderFactory:GeNgtXXRayrTCruu5r4arctksBpdXBKPEaZRqY4c6kt5:BTC_LightningLike: LightningAutomatedPayoutProcessor successfully exited...
info: LightningAutomatedPayoutSenderFactory:5Fifyf1fDC6ndNLog6TPmaRNNts6pDmrUEJFN4yuknCs:BTC_LightningLike: LightningAutomatedPayoutProcessor successfully exited...
info: LightningAutomatedPayoutSenderFactory:7CcSfJHcZC2xRrYWDX6bBActx1b91VnqLTEd1QrkWFYq:BTC_LightningLike: LightningAutomatedPayoutProcessor successfully exited...
info: OnChainAutomatedPayoutSenderFactory:4nJEkLuqm3atLeyeGxpLwZoKDnf9Suhix9GvwcCgm1sn:BTC: OnChainAutomatedPayoutProcessor successfully exited...
info: OnChainAutomatedPayoutSenderFactory:HpRPAGUSHuYgeVq38XUv4z8vPYYVVV7aZAbawSJeVnsj:BTC: OnChainAutomatedPayoutProcessor successfully exited...
info: OnChainAutomatedPayoutSenderFactory:5za96yEZmbaeNCaoZjwJn4cZVvVz3ju7tUcLcpeEL7bd:BTC: OnChainAutomatedPayoutProcessor successfully exited...
info: LightningAutomatedPayoutSenderFactory:Ei6CmgQpXAbmoV856yHEcC77ejxNTci2ZNaPUBn6XAVX:BTC_LightningLike: LightningAutomatedPayoutProcessor successfully exited...
info: LightningAutomatedPayoutSenderFactory:HWPr82S9brDUemtsV4oW4RCmacC8QUBVW97yXCgF5hdv:BTC_LightningLike: LightningAutomatedPayoutProcessor successfully exited...
info: OnChainAutomatedPayoutSenderFactory:6WTkSJW4hs4XiGgUgodCSmaepETwvhqRrR7LKVMBMDHt:BTC: OnChainAutomatedPayoutProcessor successfully exited...
info: OnChainAutomatedPayoutSenderFactory:BQknWi6GNEKwuW9bEENEdsEwWPb7wQ2iyemaryCLgtMm:BTC: OnChainAutomatedPayoutProcessor successfully exited...
info: OnChainAutomatedPayoutSenderFactory:7NXoMMAmLePoKoTjTTvJDD5PtLSaHsEANZ3MnHLfcrWT:BTC: OnChainAutomatedPayoutProcessor successfully exited...
info: OnChainAutomatedPayoutSenderFactory:EwdhVverq6GbD5xVwbEBGVGVxokUNcwXifkcNqdFudbz:BTC: OnChainAutomatedPayoutProcessor successfully exited...
info: OnChainAutomatedPayoutSenderFactory:WJaTL74kT8j4GyGzP3N3NbQ95hHUrBWvvmBiGEC7L7m:BTC: OnChainAutomatedPayoutProcessor successfully exited...
```

```
info: PayServer:      User '7e21b9c4-8403-41e0-9242-78387a369831' logged in.
fail: LightningAutomatedPayoutSenderFactory:9s4SeJpBkFVsTE5h2oUKKWwvBr7XG6pKuzA3arXJsUzH:BTC_LightningLike: Could not process payout 25CfrPSAzsHrgNAJEm5WTYA157qx
BTCPayServer.Lightning.LND.LndException: permission denied
   at BTCPayServer.Lightning.LND.LndClient.PayAsync(String bolt11, PayInvoiceParams payParams, CancellationToken cancellation)
   at BTCPayServer.Lightning.LND.LndClient.BTCPayServer.Lightning.ILightningClient.Pay(String bolt11, PayInvoiceParams payParams, CancellationToken cancellation)
   at BTCPayServer.Data.Payouts.LightningLike.UILightningLikePayoutController.TrypayBolt(ILightningClient lightningClient, PayoutBlob payoutBlob, PayoutData payoutData, BOLT11PaymentRequest bolt11PaymentRequest, PaymentMethodId pmi) in /source/BTCPayServer/Data/Payouts/LightningLike/UILightningLikePayoutController.cs:line 285
   at BTCPayServer.PayoutProcessors.Lightning.LightningAutomatedPayoutProcessor.TrypayBolt(ILightningClient lightningClient, PayoutBlob payoutBlob, PayoutData payoutData, BOLT11PaymentRequest bolt11PaymentRequest) in /source/BTCPayServer/PayoutProcessors/Lightning/LightningAutomatedPayoutProcessor.cs:line 106
   at BTCPayServer.PayoutProcessors.Lightning.LightningAutomatedPayoutProcessor.Process(ISupportedPaymentMethod paymentMethod, List`1 payouts) in /source/BTCPayServer/PayoutProcessors/Lightning/LightningAutomatedPayoutProcessor.cs:line 91
info: Configuration:  SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
warn: Configuration:  SSH invalid credentials (Permission denied (publickey).)
warn: Configuration:  Retrying SSH connection in 40 seconds
info: PayServer:      BTC: 0 payments happened while offline
info: PayServer:      Connected to WebSocket of NBXplorer (BTC)
warn: PayServer:      Error while contacting exchange binance: No market symbol metadata returned or unable to find symbol metadata for AXSBIDR
info: Configuration:  SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
info: Configuration:  SSH connection succeeded
info: OnChainAutomatedPayoutSenderFactory:EwdhVverq6GbD5xVwbEBGVGVxokUNcwXifkcNqdFudbz:BTC: 1 found to process. Starting (and after will sleep for 00:01:00)
info: LightningAutomatedPayoutSenderFactory:9s4SeJpBkFVsTE5h2oUKKWwvBr7XG6pKuzA3arXJsUzH:BTC_LightningLike: 1 found to process. Starting (and after will sleep for 00:01:00)
fail: LightningAutomatedPayoutSenderFactory:9s4SeJpBkFVsTE5h2oUKKWwvBr7XG6pKuzA3arXJsUzH:BTC_LightningLike: Could not process payout 25CfrPSAzsHrgNAJEm5WTYA157qx
BTCPayServer.Lightning.LND.LndException: permission denied
   at BTCPayServer.Lightning.LND.LndClient.PayAsync(String bolt11, PayInvoiceParams payParams, CancellationToken cancellation)
   at BTCPayServer.Lightning.LND.LndClient.BTCPayServer.Lightning.ILightningClient.Pay(String bolt11, PayInvoiceParams payParams, CancellationToken cancellation)
   at BTCPayServer.Data.Payouts.LightningLike.UILightningLikePayoutController.TrypayBolt(ILightningClient lightningClient, PayoutBlob payoutBlob, PayoutData payoutData, BOLT11PaymentRequest bolt11PaymentRequest, PaymentMethodId pmi) in /source/BTCPayServer/Data/Payouts/LightningLike/UILightningLikePayoutController.cs:line 285
   at BTCPayServer.PayoutProcessors.Lightning.LightningAutomatedPayoutProcessor.TrypayBolt(ILightningClient lightningClient, PayoutBlob payoutBlob, PayoutData payoutData, BOLT11PaymentRequest bolt11PaymentRequest) in /source/BTCPayServer/PayoutProcessors/Lightning/LightningAutomatedPayoutProcessor.cs:line 106
   at BTCPayServer.PayoutProcessors.Lightning.LightningAutomatedPayoutProcessor.Process(ISupportedPaymentMethod paymentMethod, List`1 payouts) in /source/BTCPayServer/PayoutProcessors/Lightning/LightningAutomatedPayoutProcessor.cs:line 91
```
```


### What browser do you use?

_No response_

### Additional information

_No response_

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by NicolasDorier** [comment]
Ping @Kukks
