### ISSUE TITLE
[Bug]: brand new btcpayserver can't generate new btc receive address

### ISSUE THREAD

**Issue by anycolo** [btcpayserver/btcpayserver#4208]
### What is your BTCPay version?

 v1.6.12.0 (Altcoins) 

### How did you deploy BTCPay Server?

docker build

### What happened?

Create a new store, create a btc wallet, check import private key to rpc
Then, creating a new bitcoin address fails

### How did you encounter this bug?

Add bitcoin wallet, select segwit, check import private key to rpc
generate new receive address

### Relevant log output

```shell
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMLCA8B39H2P", Request id "0HMLCA8B39H2P:0000002D": An unhandled exception was thrown by the application.
NBitcoin.RPC.RPCException: This type of wallet does not support this command
   at NBitcoin.RPC.RPCResponse.ThrowIfError()
   at NBitcoin.RPC.RPCClient.SendCommandAsync(RPCRequest request, CancellationToken cancellationToken)
   at NBitcoin.RPC.RPCClient.ImportPrivKeyAsync(BitcoinSecret secret, String label, Boolean rescan)
   at NBXplorer.Backends.Postgres.PostgresRepository.ImportAddressToRPC(BitcoinExtKey accountKey, BitcoinAddress address, KeyPath keyPath) in /source/NBXplorer/Backends/Postgres/PostgresRepository.cs:line 886
   at NBXplorer.Backends.Postgres.PostgresRepository.ImportAddressToRPC(DbConnectionHelper connection, TrackedSource trackedSource, BitcoinAddress address, KeyPath keyPath) in /source/NBXplorer/Backends/Postgres/PostgresRepository.cs:line 880
   at NBXplorer.Backends.Postgres.PostgresRepository.GetUnused(DerivationStrategyBase strategy, DerivationFeature derivationFeature, Int32 n, Boolean reserve) in /source/NBXplorer/Backends/Postgres/PostgresRepository.cs:line 807
   at NBXplorer.Backends.Postgres.PostgresRepository.GetUnused(DerivationStrategyBase strategy, DerivationFeature derivationFeature, Int32 n, Boolean reserve) in /source/NBXplorer/Backends/Postgres/PostgresRepository.cs:line 808
   at NBXplorer.Controllers.MainController.GetUnusedAddress(String cryptoCode, DerivationStrategyBase strategy, DerivationFeature feature, Int32 skip, Boolean reserve) in /source/NBXplorer/Controllers/MainController.cs:line 142
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by Kukks** [comment]
@NicolasDorier  this seems like an issue with latest bitcoind where new wallets are descriptor wallets which don't support importprivkey. We need to check this somehow and start using `importdescriptors` instead?

**Comment by NicolasDorier** [comment]
interesting, will check this..

**Comment by anycolo** [comment]
Yes, i know, but i WANT to import the addresses to RPC.

**Comment by NicolasDorier** [comment]
So I solved it at two level:
* From now, new bitcoin core node will create a "legacy" wallet instead of "descriptor" wallet, to keep old behavior.
* NBXplorer now support descriptor (you can run `btcpay-update.sh` to pull the new version)
* I do not fix old wallets that crashed on this error before. Instead, you need to create a new wallet.

Note that you mentioned that you wanted Payjoin. You do not need to import keys in RPC for using it.

I closed this, feel free to re-open if after update and creating a new wallet on btcpay you still have issues.

**Comment by anycolo** [comment]
@NicolasDorier , this still doesn't work for me. I'm trying to generate a new wallet for BTC.

```
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMLLKA85N3JA", Request id "0HMLLKA85N3JA:00000030": An unhandled exception was thrown by the application.
NBitcoin.RPC.RPCException: new range must include current range = [0,999]
   at NBitcoin.RPC.RPCResponse.ThrowIfError()
   at NBXplorer.RPCClientExtensions.ImportDescriptors(RPCClient rpc, String descriptor, Int64 from, Int64 to) in /source/NBXplorer/RPCClientExtensions.cs:line 226
   at NBXplorer.Backends.Postgres.PostgresRepository.ImportDescriptorToRPCIfNeeded(DbConnection connection, WalletKey walletKey, Int64 fromIndex, Int64 toGenerate, KeyPathTemplate keyTemplate) in /source/NBXplorer/Backends/Postgres/PostgresRepository.cs:line 338
   at NBXplorer.Backends.Postgres.PostgresRepository.GenerateAddressesCore(DbConnection connection, DerivationStrategyBase strategy, DerivationFeature derivationFeature, GenerateAddressQuery query) in /source/NBXplorer/Backends/Postgres/PostgresRepository.cs:line 295
   at NBXplorer.Backends.Postgres.PostgresRepository.GenerateAddresses(DerivationStrategyBase strategy, DerivationFeature derivationFeature, GenerateAddressQuery query) in /source/NBXplorer/Backends/Postgres/PostgresRepository.cs:line 234
   at NBXplorer.Backends.Postgres.PostgresRepository.GenerateAddresses(DerivationStrategyBase strategy, DerivationFeature derivationFeature, GenerateAddressQuery query) in /source/NBXplorer/Backends/Postgres/PostgresRepository.cs:line 234
   at NBXplorer.Controllers.MainController.TrackWallet(String cryptoCode, DerivationStrategyBase derivationScheme, BitcoinAddress address, TrackWalletRequest request) in /source/NBXplorer/Controllers/MainController.cs:line 521
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

```

**Comment by NicolasDorier** [comment]
@anycolo what a mess... thanks will fix.

**Comment by NicolasDorier** [comment]
@anycolo I fixed it again, please update thanks for the feedback.

To summarize, the issue is that 23.0 by default create a "descriptor" RPC wallet, which NBXplorer didn't support.
I changed the docker to create a legacy wallet for new installs, but we are stuck with yours to use the `descriptor` wallet.
This is why other people doesn't have your issue.

Anyway, should be fixed now, try to update.

**Comment by anycolo** [comment]
I realized that it was caused by my old wallet. I just removed all the wallets and started everything from scratch and it worked.

**Comment by hashes4merkle** [comment]
@NicolasDorier -  I'm also seeing this issue.  Following the comments, I completed an update via `btcpay-update.sh`, restarted the service and created a new store.  Currently running nbxplorer 2.3.42 against bitcoin 23.0-1.  Generating a new wallet address produces the same error message.  Can you provide any additional steps necessary?   Thanks!

**Comment by NicolasDorier** [comment]
https://github.com/btcpayserver/btcpayserver/issues/4269#issuecomment-1313363342

Sorry for the inconvenience :(
