### ISSUE TITLE
Restrict editing amount and currency after invoices have been generated for the payment request.

### ISSUE THREAD

**Issue by jacobburrell** [btcpayserver/btcpayserver#4241]
### What is your BTCPay version?

v1.6.12.0

### How did you deploy BTCPay Server?

Docker

### What happened?

When editing the currency or amount of an existing payment request with existing and outstanding related invoice, the amount in the invoice isn't updated, which may or may not be what is expected.

However, if the payment request's currency or amount is edited, saved, and a user then selects to pay the invoice, selecting "pay invoice" defaults to using the same existing and not yet expired invoice with the old data, rather than create a new invoice with the correct details or update the existing invoice with the correct details.

Perhaps this would be easier if there was a _revision history_ of sorts with Payment Requests.
Allowing invoices to be associated to specific versions of a Payment Request but still being recognised in any version in case a user pays an older or newer invoice associated with an older or newer version of a Payment Request.

This can also lead to certain issues with payments both over and underpayments that I have yet to explore.

This caused an issue with a client attempting to pay an amount in USD, and even after updating the Payment Request to USD, the client was still being shown the wrong price.
I ended up solving it by cloning the Payment Request, as that didn't have an associated invoice, and thus generated a correct invoice the first time the client tried to pay the PR.

### How did you encounter this bug?

[Steps](https://scribehow.com/shared/BTCPayServer_Payment_Request_Currency_swap_bug__hwfO1RJaQX-zsOVKfnF2iw)

![image](https://user-images.githubusercontent.com/61520543/198201581-4b322f23-5d81-47ec-aad7-3f6c746857f4.png)
![image](https://user-images.githubusercontent.com/61520543/198201608-df9f56d6-9c46-4d69-a447-ed07af06b4fa.png)
![image](https://user-images.githubusercontent.com/61520543/198201640-984dc077-6130-49b1-873f-a5942a755a66.png)
![image](https://user-images.githubusercontent.com/61520543/198201662-b7c919f0-99ad-40ad-a182-52f0dab9333e.png)
![image](https://user-images.githubusercontent.com/61520543/198201695-1847a2d0-3d6d-498c-b864-5c15c6ca99db.png)
![image](https://user-images.githubusercontent.com/61520543/198201744-aff309d7-0a8f-440f-ac8d-626ccdb32bc7.png)
![image](https://user-images.githubusercontent.com/61520543/198201777-e121e3a8-9f22-40a4-bd75-8ba34e94c88f.png)
![image](https://user-images.githubusercontent.com/61520543/198201806-b20f3343-1aad-45db-92e2-089b82abe00e.png)
![image](https://user-images.githubusercontent.com/61520543/198201819-600366ef-effd-4e26-b0d3-da926db833e2.png)
![image](https://user-images.githubusercontent.com/61520543/198201840-df0ff5d6-51dd-444c-bd32-63bbfae889b7.png)
![image](https://user-images.githubusercontent.com/61520543/198201859-9f0e3f17-efd2-47d4-8c3e-a60b8c2e3830.png)
![image](https://user-images.githubusercontent.com/61520543/198201876-78351178-8d14-41c8-bed1-612152b78d0f.png)
![image](https://user-images.githubusercontent.com/61520543/198201908-46a67fdb-462d-453f-bf2d-b084ccdd8d83.png)

### Relevant log output

```shell
2022-10-27 02:02:57.911 +00:00 [INF] BTC (Lightning): Start listening http://lnd_bitcoin:8080/
2022-10-27 02:16:42.155 +00:00 [INF] User with ID 6a43bce3-9d10-4522-bb72-e1c0bc382644 has enabled 2FA with an authenticator app.
2022-10-27 02:29:37.712 +00:00 [INF] BTC (Lightning): No more invoice to listen on http://lnd_bitcoin:8080/, releasing the connection.
2022-10-27 02:34:01.500 +00:00 [WRN] Invalid authenticator code entered for user with ID 6a43bce3-9d10-4522-bb72-e1c0bc382644.
2022-10-27 02:34:20.855 +00:00 [WRN] User with ID 6a43bce3-9d10-4522-bb72-e1c0bc382644 account locked out.
2022-10-27 02:41:16.745 +00:00 [INF] BTC (Lightning): Start listening http://lnd_bitcoin:8080/
2022-10-27 02:58:37.711 +00:00 [INF] BTC (Lightning): No more invoice to listen on http://lnd_bitcoin:8080/, releasing the connection.
2022-10-27 03:00:08.353 +00:00 [INF] BTC (Lightning): Start listening http://lnd_bitcoin:8080/
2022-10-27 03:15:37.716 +00:00 [INF] BTC (Lightning): No more invoice to listen on http://lnd_bitcoin:8080/, releasing the connection.
2022-10-27 03:46:21.526 +00:00 [INF] User with ID 6a43bce3-9d10-4522-bb72-e1c0bc382644 logged in with 2fa.
2022-10-27 05:26:20.227 +00:00 [INF] BTC (Lightning): Start listening http://lnd_bitcoin:8080/
2022-10-27 05:26:47.991 +00:00 [ERR] Failed to invoke hub method 'Pay'.
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.PaymentRequest.PaymentRequestHub.Pay(Nullable`1 amount) in /source/BTCPayServer/PaymentRequest/PaymentRequestHub.cs:line 67
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ExecuteMethod(ObjectMethodExecutor methodExecutor, Hub hub, Object[] arguments)
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<Invoke>g__ExecuteInvocation|16_0(DefaultHubDispatcher`1 dispatcher, ObjectMethodExecutor methodExecutor, THub hub, Object[] arguments, AsyncServiceScope scope, IHubActivator`1 hubActivator, HubConnectionContext connection, HubMethodInvocationMessage hubMethodInvocationMessage, Boolean isStreamCall)
2022-10-27 05:41:37.726 +00:00 [INF] BTC (Lightning): No more invoice to listen on http://lnd_bitcoin:8080/, releasing the connection.
2022-10-27 05:50:18.015 +00:00 [INF] BTC (Lightning): Start listening http://lnd_bitcoin:8080/
```

### What browser do you use?

[Brave](https://brave.com)

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by NicolasDorier** [comment]
A proper fix would be to not allow payment edit request once an invoice as been issued.

**Comment by pavlenex** [comment]
@Kukks Thoughts on this?

**Comment by Kukks** [comment]
Yes, I would restrict editing amount and currency after invoices have been
generated for the payment request.

**Comment by pavlenex** [comment]
Renaming the issue to that then. 👍
