### ISSUE TITLE
[Bug]: Wallet type not compatible with NBXplorer RPC command

### ISSUE THREAD

**Issue by hashes4merkle** [btcpayserver/btcpayserver#4269]
### What is your BTCPay version?

`BTCPay Server v1.6.12.0 (Altcoins)`
`nbxplorer 2.3.44`
`bitcoin 23.0-1`

### How did you deploy BTCPay Server?

VPS deployment

### What happened?

On install, the BTC wallet is unable to generate a new address.  NBXplorer returns an RPC exception stating the wallet does not support this command.  Following the comments on #4208,  I completed an update via `btcpay-update.sh`, restarted the service and created a new store.  I am currently running `nbxplorer 2.3.44` against `bitcoin 23.0-1`.  Attempts to generate a new wallet address leads to the same error.

### How did you encounter this bug?

1. Create new store
2. Create a hot wallet
3. Click receive on the store BTC wallet page then generate next available BTC address

### Relevant log output

```shell
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMLU4LPF17O0", Request id "0HMLU4LPF17O0:000001BF": An unhandled exception was thrown by the application.
NBitcoin.RPC.RPCException: This type of wallet does not support this command
   at NBitcoin.RPC.RPCResponse.ThrowIfError()
   at NBitcoin.RPC.RPCClient.SendCommandAsync(RPCRequest request, CancellationToken cancellationToken)
   at NBitcoin.RPC.RPCClient.ImportPrivKeyAsync(BitcoinSecret secret, String label, Boolean rescan)
   at NBXplorer.Backends.Postgres.PostgresRepository.ImportAddressToRPC(BitcoinExtKey accountKey, BitcoinAddress address, KeyPath keyPath) in /source/NBXplorer/Backends/Postgres/PostgresRepository.cs:line 924
   at NBXplorer.Backends.Postgres.PostgresRepository.ImportAddressToRPC(DbConnectionHelper connection, TrackedSource trackedSource, BitcoinAddress address, KeyPath keyPath) in /source/NBXplorer/Backends/Postgres/PostgresRepository.cs:line 918
   at NBXplorer.Backends.Postgres.PostgresRepository.GetUnused(DerivationStrategyBase strategy, DerivationFeature derivationFeature, Int32 n, Boolean reserve) in /source/NBXplorer/Backends/Postgres/PostgresRepository.cs:line 845
   at NBXplorer.Backends.Postgres.PostgresRepository.GetUnused(DerivationStrategyBase strategy, DerivationFeature derivationFeature, Int32 n, Boolean reserve) in /source/NBXplorer/Backends/Postgres/PostgresRepository.cs:line 846
   at NBXplorer.Controllers.MainController.GetUnusedAddress(String cryptoCode, DerivationStrategyBase strategy, DerivationFeature feature, Int32 skip, Boolean reserve) in /source/NBXplorer/Controllers/MainController.cs:line 143
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### What browser do you use?

`Version 1.45.113 Chromium: 107.0.5304.62`

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by hashes4merkle** [comment]
Issue resolved by deleting existing volumes and restarting setup.

**Comment by NicolasDorier** [comment]
So this issue came because during update to bitcon core 23.0, for a while, new nodes would create a descriptor wallet (new type of wallet in core) and NBXplorer wasn't supporting it.

I did two things, first is to go back to old wallet type in bitcoin core. (which is why deleting volumes worked)

The other thing is to actually support descriptor wallets. So I need to check why in your case it was crashing, it shouldn't have crashed.

**Comment by NicolasDorier** [comment]
Looking at the code, I understand that descriptor wallet generated when NBXplorer wasn't supporting them would trigger this bug.

I close this, as this shouldn't happen again. The main mistake I did was to not test 23.0 on btcpayserver and NBXplorer before bumping it in production. The tests caught those problems.
