### ISSUE TITLE
[Bug]: HTTP ERROR 500 if I try generate a USDT adress

### ISSUE THREAD

**Issue by ProTechEx** [btcpayserver/btcpayserver#4332]
### What is your BTCPay version?

 BTCPay Server v1.6.12.0 (Altcoins)

### How did you deploy BTCPay Server?

Docker, Oracle VPS instance

### What happened?

Just just add as second crytpo LBTC to be able receive USDt

### How did you encounter this bug?

1. Follow your Guide: https://docs.btcpayserver.org/FAQ/Altcoin/
2. Wait until the Blockchain Sync is done
3. Add a USDT Wallet

4. Click the receive Button
![image](https://user-images.githubusercontent.com/5677301/203406493-e8404663-6bff-4106-959d-0570d17257b6.png)

5. Click the Wallet Adress generate button
![image](https://user-images.githubusercontent.com/5677301/203406764-605ba95a-2663-4089-befc-edc77f51c104.png)

6. After I get the HTTP ERROR 500 
![image](https://user-images.githubusercontent.com/5677301/203406973-963ead4f-e2c2-4380-83b9-0886ca013e1f.png)

**MY SETUP:**
`root@btcpay:~/BTCPayServer/btcpayserver-docker# . ./btcpay-setup.sh -i

-------SETUP-----------
Parameters passed:
BTCPAY_PROTOCOL:https
BTCPAY_HOST:mybtcpayserver.com
BTCPAY_ADDITIONAL_HOSTS:
REVERSEPROXY_HTTP_PORT:80
REVERSEPROXY_HTTPS_PORT:443
REVERSEPROXY_DEFAULT_HOST:mybtcpayserver.com
LIBREPATRON_HOST:
ZAMMAD_HOST:
WOOCOMMERCE_HOST:
BTCTRANSMUTER_HOST:
CHATWOOT_HOST:
BTCPAY_ENABLE_SSH:true
BTCPAY_HOST_SSHKEYFILE:
LETSENCRYPT_EMAIL:
NBITCOIN_NETWORK:mainnet
LIGHTNING_ALIAS:
BTCPAYGEN_CRYPTO1:btc
BTCPAYGEN_CRYPTO2:lbtc
BTCPAYGEN_CRYPTO3:
BTCPAYGEN_CRYPTO4:
BTCPAYGEN_CRYPTO5:
BTCPAYGEN_CRYPTO6:
BTCPAYGEN_CRYPTO7:
BTCPAYGEN_CRYPTO8:
BTCPAYGEN_CRYPTO9:
BTCPAYGEN_REVERSEPROXY:nginx
BTCPAYGEN_LIGHTNING:clightning
BTCPAYGEN_ADDITIONAL_FRAGMENTS:opt-save-storage-xs;opt-add-btctransmuter;opt-add-cloudflared
BTCPAYGEN_EXCLUDE_FRAGMENTS:nginx-https
BTCPAY_IMAGE:
ACME_CA_URI:production
TOR_RELAY_NICKNAME:
TOR_RELAY_EMAIL:
PIHOLE_SERVERIP:
FIREFLY_HOST:
----------------------
Additional exported variables:
BTCPAY_DOCKER_COMPOSE=/root/BTCPayServer/btcpayserver-docker/Generated/docker-compose.generated.yml
BTCPAY_BASE_DIRECTORY=/root/BTCPayServer
BTCPAY_ENV_FILE=/root/BTCPayServer/.env
BTCPAYGEN_OLD_PREGEN=false
BTCPAY_SSHKEYFILE=/datadir/host_id_ed25519
BTCPAY_SSHAUTHORIZEDKEYS=/datadir/host_authorized_keys
BTCPAY_HOST_SSHAUTHORIZEDKEYS:/root/.ssh/authorized_keys
BTCPAY_SSHTRUSTEDFINGERPRINTS:
BTCPAY_CRYPTOS:btc;lbtc
BTCPAY_ANNOUNCEABLE_HOST:mybtcpayserver.com
----------------------

BTCPay Server environment variables successfully saved in /etc/profile.d/btcpay-env.sh

BTCPay Server docker-compose parameters saved in /root/BTCPayServer/.env

Using default tag: latest
latest: Pulling from btcpayserver/docker-compose-generator
Digest: sha256:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Status: Image is up to date for btcpayserver/docker-compose-generator:latest
docker.io/btcpayserver/docker-compose-generator:latest
Crypto: btc, lbtc
Lightning: clightning
ReverseProxy: nginx
Generating /app/Generated/docker-compose.generated.yml
Selected fragments:
        nginx
        btcpayserver
        bitcoin
        bitcoin-clightning
        liquid
        opt-save-storage-xs
        opt-add-btctransmuter
        opt-add-cloudflared
        liquid-default-prune
        opt-add-tor
        nbxplorer
        postgres
        btcpayserver-nginx
Generated /app/Generated/pull-images.sh
Generated /app/Generated/save-images.sh
Generated /app/Generated/docker-compose.generated.yml

Adding btcpayserver.service to systemd
BTCPay Server systemd configured in /etc/systemd/system/btcpayserver.service

BTCPay Server starting... this can take 5 to 10 minutes...
BTCPay Server started
tor is up-to-date
nginx is up-to-date
generated_bitcoin_rtl_1 is up-to-date
generated_postgres_1 is up-to-date
btcpayserver_elementsd_liquid is up-to-date
tor-gen is up-to-date
btcpayserver_bitcoind is up-to-date
cloudflared-tunnel is up-to-date
generated_nbxplorer_1 is up-to-date
btcpayserver_clightning_bitcoin is up-to-date
generated_btcpayserver_1 is up-to-date
generated_clightning_bitcoin_rest_1 is up-to-date
generated_clightning_bitcoin_charge_1 is up-to-date
generated_clightning_bitcoin_spark_1 is up-to-date
nginx-gen is up-to-date
btctransmuter is up-to-date
Installed bitcoin-cli.sh to /usr/local/bin: Command line for your Bitcoin instance
Installed bitcoin-lightning-cli.sh to /usr/local/bin: Command line for your Bitcoin C-Lightning instance
Installed elements-cli.sh to /usr/local/bin: Command line for your Elements/Liquid instance
Installed btcpay-clean.sh to /usr/local/bin: Command line for deleting old unused docker images
Installed btcpay-down.sh to /usr/local/bin: Command line for stopping all services related to BTCPay Server
Installed btcpay-restart.sh to /usr/local/bin: Command line for restarting all services related to BTCPay Server
Installed btcpay-setup.sh to /usr/local/bin: Command line for restarting all services related to BTCPay Server
Installed btcpay-up.sh to /usr/local/bin: Command line for starting all services related to BTCPay Server
Installed btcpay-admin.sh to /usr/local/bin: Command line for some administrative operation in BTCPay Server
Installed btcpay-update.sh to /usr/local/bin: Command line for updating your BTCPay Server to the latest commit of this repository
Installed changedomain.sh to /usr/local/bin: Command line for changing the external domain of your BTCPay Server
`

 

### Relevant log output

```shell
2022-11-22 19:19:31.744 +00:00 [ERR] Connection id "0HMMCN888HMNE", Request id "0HMMCN888HMNE:00000002": An unhandled exception was thrown by the application.
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NBXplorer.ExplorerClient.ParseResponse[T](HttpResponseMessage response)
   at NBXplorer.ExplorerClient.SendAsync[T](HttpMethod method, Object body, String relativePath, Object[] parameters, CancellationToken cancellation)
   at NBXplorer.ExplorerClient.GetUnusedAsync(DerivationStrategyBase strategy, DerivationFeature feature, Int32 skip, Boolean reserve, CancellationToken cancellation)
   at BTCPayServer.Services.Wallets.BTCPayWallet.ReserveAddressAsync(DerivationStrategyBase derivationStrategy) in /source/BTCPayServer/Services/Wallets/BTCPayWallet.cs:line 78
   at BTCPayServer.Services.Wallets.WalletReceiveService.GetOrGenerate(WalletId walletId, Boolean forceGenerate) in /source/BTCPayServer/Services/Wallets/WalletReceiveService.cs:line 75
   at BTCPayServer.Controllers.UIWalletsController.WalletReceive(WalletId walletId, WalletReceiveViewModel vm, String command) in /source/BTCPayServer/Controllers/UIWalletsController.cs:line 407
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 101
   at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 50
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 30
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### What browser do you use?

Last Chrome Version: 107.0.5304.107

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by NicolasDorier** [comment]
Can you report NXBplorer logs `docker logs generated_nbxplorer_1`

**Comment by ProTechEx** [comment]
> NXBplorer logs `docker logs`

**docker logs generated\_nbxplorer\_1**

```
root@btcpay:~/BTCPayServer/btcpayserver-docker# docker logs --tail 100 generated_nbxplorer_1
info: NBXplorer.Events: LBTC: New block 1047946c4350efa567f570e22eea64cf8349d2c76a4ff39fe91ab74ba5eaa989 (2107277)
info: NBXplorer.Events: LBTC: New block 15d7cfd8fbd67c226f72e32b93d0e96b590d68042714e45cf237d58df55ae886 (2107278)
info: NBXplorer.Events: LBTC: New block 881b3e685c05997a4e69672d6a0410af22537ece6067c693892dadd3ac7b1cdd (2107279)
info: NBXplorer.Events: LBTC: New block dc7b06587998b0e6254de0c08314228ceea5f16b9200a022c045a82b9df20948 (2107280)
info: NBXplorer.Events: LBTC: New block d6ed45d8f7fa2d4b6870d44a23e8d15cb98c8a69405e52a77fedc62034831271 (2107281)
info: NBXplorer.Events: LBTC: New block 7c96131e8313ca08a30efeba9eeebe074949fa9edae63af5a1dcbcd2e12eb4cf (2107282)
info: NBXplorer.Events: LBTC: New block 44fb49db3c98b5977f14bf1c03b0d3f1d582fdf375b20e9b8bb64b560712065c (2107283)
info: NBXplorer.Events: LBTC: New block 9c64e4b7e861ee22c9d591c0f1a37550ab6de15f578a6c6a04c7de6c0d2d4268 (2107284)
info: NBXplorer.Events: LBTC: New block 5379331ba3481217b886da5075b0ee435692c72a366096a9a61c2e3843276308 (2107285)
info: NBXplorer.Events: LBTC: New block 12bf4f038aa3aed6f2bd23cf8ce8b377683f8f7b735cc16f6503b1acc8a10c96 (2107286)
info: NBXplorer.Events: LBTC: New block d716249d4af35114a7706eb711aa30eed5b2078b525aad7ed28af68f907b9e1b (2107287)
info: NBXplorer.Events: BTC: New block 0000000000000000000304f17daeec44d7e9952888902542ef7e752e62908db2 (764377)
info: NBXplorer.Events: LBTC: New block ae5948c1bf084bb20611b100ff2c36e5f782d5e621ba8e300d37930ead06bf1a (2107288)
info: NBXplorer.Events: LBTC: New block 7c13e8c0b7e1282a9710a3bb65151261ffbe1a59c430fc41e4d237d40c4993c9 (2107289)
info: NBXplorer.Events: LBTC: New block fc5daf0a4f8098780b9b65fd7daac4cf76b3c00b4c3b6f67d866596d709c729a (2107290)
info: NBXplorer.Events: LBTC: New block 9bd36038822c63510891d9d8e1ac081eab0d162bcce0d7225b124a12444793e8 (2107291)
info: NBXplorer.Events: LBTC: New block ceb9c21a91b2cc353a7cb2aa3320486a4ed75b297808edef4fb89a056eec6bef (2107292)
info: NBXplorer.Events: LBTC: New block 6eeea83cd81eae8a49215013b61d4c450642949da47f6d258d887716ac23e9a0 (2107293)
info: NBXplorer.Events: LBTC: New block f00d24430da12f62f14eacd8cefe9745afe0afffd13684c20f81e3b103ad9f7a (2107294)
info: NBXplorer.Events: LBTC: New block 1d5eceb3e933852b9fde2921c4bdafbc91598b7667cbe5b5846906f11db10bf1 (2107295)
info: NBXplorer.Events: LBTC: New block a33da29c4ec9b5465d12917fdc31e2740e46ff11ba8dada729722c5dca371b12 (2107296)
info: NBXplorer.Events: LBTC: New block 9b7274fe1164884b1737796ccd35f655d9c82dd2f1b5d32d65e1d55f91d2e03a (2107297)
info: NBXplorer.Events: LBTC: New block b14fb4b247fd4bd51ef9f0dc549b41e49a86ee9f73652a693b566cbca8024c42 (2107298)
info: NBXplorer.Events: LBTC: New block e793a94158b16bcc93a7f977ce0f6dcb15e9d4401b7279d7cead4715e3a4427c (2107299)
info: NBXplorer.Events: LBTC: New block 272d86919650bb74b5ff7d6f974b38eed7364aa1396ee7768ad09345a79e70e4 (2107300)
info: NBXplorer.Events: LBTC: New block 116b98f72584c6d12b440d85f4199f4d94c85b4c32a730d7419a7d79c41ad198 (2107301)
info: NBXplorer.Events: LBTC: New block d7d744a706fe8a62da4fd5ad45fc1beb3b9580b380d366cda0f04ee26afeb491 (2107302)
info: NBXplorer.Events: BTC: New block 000000000000000000040d73bd66604fcc9a8412efc0af0134288b236e8591a6 (764378)
info: NBXplorer.Events: LBTC: New block fc3150e53d09ce24111a0df0ed082f8d2ae0f0dc86ec6bc3a5718fbbba26492c (2107303)
info: NBXplorer.Events: LBTC: New block bc600cade0345a176d1ec91e8c7feeb8fcf61b36fa5868e87f9fc6e25996bfe4 (2107304)
info: NBXplorer.Events: LBTC: New block ef79d263d3744a6d0f3f2820f1027a8115bfcd8bf765841e01c54450b8e5dec0 (2107305)
info: NBXplorer.Events: LBTC: New block 28b9fd6c95a117eafa10d613f117e462a449f3c781d0e8bd9f94c670a1096719 (2107306)
info: NBXplorer.Events: LBTC: New block 6119e289050b28db41d81c87ca11b4f1772ec2752f76d14e3df302bba6dba44c (2107307)
info: NBXplorer.Events: LBTC: New block eac896e81e8ddaa1687712ffd34ed7a9832c6bfaeda7399702c1af5d7799e065 (2107308)
info: NBXplorer.Events: LBTC: New block 38bff521a56dfe8b29c3046f4cab11327f77719c1743ec564081626203561fe6 (2107309)
info: NBXplorer.Events: LBTC: New block c5f579672e9ea569f82d6df5274c3f96eb111f179f25a5a5f2069e5f6d92fda0 (2107310)
info: NBXplorer.Events: LBTC: New block ac28fe257c35b42de813981ebd9d41b1b2c7f1c8b2fcf09da822cbaf763c0370 (2107311)
info: NBXplorer.Events: LBTC: New block 947d29ed7a65d012056dbbdac7073abc35d101a29e2f02fc80610d698962dbfa (2107312)
info: NBXplorer.Events: LBTC: New block aa8d863065b0a65b105938f5d43eb578a6860d62e34835f7e6369c192e4433ce (2107313)
info: NBXplorer.Events: BTC: New block 00000000000000000001afdf760a2adcd53bee8abec11ae60711cbc1da3ee98d (764379)
info: NBXplorer.Events: LBTC: New block 330fcc11524c53dcf1d763ebc4ed554330d9e99b6fa45dd3691d72684e094bf6 (2107314)
info: NBXplorer.Events: LBTC: New block d2319cae0a37d0d32e5d265c91298e0cc52c561bb6167bd136a5ea09f67c5daa (2107315)
info: NBXplorer.Events: LBTC: New block e47422ed16420b3b0e3788d736fbc6d540ea43cf9fc62eda136325730608e9e3 (2107316)
info: NBXplorer.Events: LBTC: New block 124d7b9730f10cdc350f36b73cc31c8b3444bca33555783df8badb4d08025922 (2107317)
info: NBXplorer.Events: LBTC: New block 30b60c5f2bfd04376b5cb114d8770082e7707935365b269da411ba3aa1bb5b28 (2107318)
info: NBXplorer.Events: LBTC: New block 5f10b4c04c06cf8d474fb21d4f95303a04a665836d0542f679162c961be073ea (2107319)
info: NBXplorer.Events: LBTC: New block 9f868fb08af188a6a87fe7b31ae89f4c880dab82fac27bbfdb557536e59646dd (2107320)
info: NBXplorer.Events: BTC: New block 0000000000000000000293f3892d4e15270c65f26c8bb3b36fd136fa29eae45a (764380)
info: NBXplorer.Events: LBTC: New block 65aef9026793c1e2b086dc4a0fcd295453161070352de5a8ea8031b1f15d6327 (2107321)
info: NBXplorer.Events: LBTC: New block e17a8d85f4f9bf7158e1f660092451fae0d3daee9d823a62c868e1d7561f6314 (2107322)
info: NBXplorer.Events: LBTC: New block 03299bc5879151bb32c89e2141e5453e9d2c3778e9215ba059c31828fb7c63e2 (2107323)
info: NBXplorer.Events: LBTC: New block b5363a0132f4423c79e7954325bb06e0a0590781cba6e27239c7312d32037738 (2107324)
info: NBXplorer.Events: LBTC: New block fabfe338b825d11eca7c368600c124cead2b36529877847678e7cbf5c332c79c (2107325)
info: NBXplorer.Events: LBTC: New block 3f17830b4dcd316ec20b0f6b32f860cb155dc33a688c7ae1e797797631544db6 (2107326)
info: NBXplorer.Events: LBTC: New block 18b2845f722a1be6a7bbbc4ab6bd27fb072c428278f29bb41a6628acd6e0748d (2107327)
info: NBXplorer.Events: LBTC: New block 57963b0c7fcb61fe491d0a644b1e982c153ebb48b2e8a7aff34e52f7fc70af11 (2107328)
info: NBXplorer.Events: LBTC: New block 86ed2d1b8d0f6f0ecef0b1b7db05684a701316caad00ce4ed1591c8389e90e57 (2107329)
info: NBXplorer.Events: LBTC: New block 28b1c991e72c13173d10e7e37233eb73fd8f208c2d9bde228d6677e18785148c (2107330)
info: NBXplorer.Events: LBTC: New block a0c5ffcd5eb4cdb89ddf6d8ca956048c13755a2a5c65a54f3764d80119bf8b34 (2107331)
info: NBXplorer.Events: LBTC: New block d71bf6748ffb78c55a175ccfde07e6d64604258a0ec0a590b6b102eb8e8236b8 (2107332)
info: NBXplorer.Events: LBTC: New block e9fd143bb80fb5eb3c0b5343e4ae6a436be528f17bbc6bc5d7f5fcfe59ad61c6 (2107333)
info: NBXplorer.Events: LBTC: New block 092bf63af58c642e94c404d24fd9d81124e1f6afb8f091365a6a9d00544dc221 (2107334)
info: NBXplorer.Events: LBTC: New block 5bc0088ea313b5616441e8d50e4ac9697fd0a50d5a80752f5d634042b1576af7 (2107335)
info: NBXplorer.Events: LBTC: New block b989dbadef6490164fb4498c30bf24d7638efc2f3e99bb4814969ac8672843a8 (2107336)
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMMCN80P5MUR", Request id "0HMMCN80P5MUR:000001C8": An unhandled exception was thrown by the application.
NBitcoin.RPC.RPCException: No wallet is loaded. Load a wallet using loadwallet or create a new one with createwallet. (Note: A default wallet is no longer automatically created)
   at NBitcoin.RPC.RPCResponse.ThrowIfError()
   at NBitcoin.RPC.RPCClient.SendCommandAsync(RPCRequest request, CancellationToken cancellationToken)
   at NBitcoin.RPC.RPCClient.ImportPrivKeyAsync(BitcoinSecret secret, String label, Boolean rescan)
   at NBXplorer.Backends.Postgres.PostgresRepository.ImportAddressToRPC(BitcoinExtKey accountKey, BitcoinAddress address, KeyPath keyPath) in /source/NBXplorer/Backends/Postgres/PostgresRepository.cs:line 924
   at NBXplorer.Backends.Postgres.PostgresRepository.ImportAddressToRPC(DbConnectionHelper connection, TrackedSource trackedSource, BitcoinAddress address, KeyPath keyPath) in /source/NBXplorer/Backends/Postgres/PostgresRepository.cs:line 919
   at NBXplorer.Backends.Postgres.PostgresRepository.GetUnused(DerivationStrategyBase strategy, DerivationFeature derivationFeature, Int32 n, Boolean reserve) in /source/NBXplorer/Backends/Postgres/PostgresRepository.cs:line 845
   at NBXplorer.Backends.Postgres.PostgresRepository.GetUnused(DerivationStrategyBase strategy, DerivationFeature derivationFeature, Int32 n, Boolean reserve) in /source/NBXplorer/Backends/Postgres/PostgresRepository.cs:line 846
   at NBXplorer.Controllers.MainController.GetUnusedAddress(String cryptoCode, DerivationStrategyBase strategy, DerivationFeature feature, Int32 skip, Boolean reserve) in /source/NBXplorer/Controllers/MainController.cs:line 143
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: NBXplorer.Events: LBTC: New block 8a80363317be9f5d031c80e235ddac3d5599972b63b67cc11d1e5a357195700e (2107337)
info: NBXplorer.Events: LBTC: New block c1705ee5153b9e2ed2fe37ca6fc8306565ca3a73078bf85ec9f44b179a56f954 (2107338)
info: NBXplorer.Events: BTC: New block 00000000000000000002ee32986122f2f6d78b63d996549557f1098e6fd9d695 (764381)
info: NBXplorer.Events: LBTC: New block 1e0a8aea00a9c6678e7cae7400485964712a2614e98b205f5c0b374257944105 (2107339)
info: NBXplorer.Events: LBTC: New block e6f4de26db638d7ee9b44d76dfed9305cf68f9b87c66c242e141649df76936d2 (2107340)
info: NBXplorer.Events: LBTC: New block dfb65be41cf949a138a0f773a4ab3cb4db1128a1bbf627d6d272925edfc90c42 (2107341)
info: NBXplorer.Events: BTC: New block 0000000000000000000451ccecfb1e19f88e3615c39638e68c281ad7d74e4e82 (764382)
info: NBXplorer.Events: LBTC: New block 5e06edf37c65b7bfb7f643b6ccfebb8d10656ed40c054d75b461647161ad0706 (2107342)
info: NBXplorer.Events: BTC: New block 0000000000000000000300d783f7adfd2ee07d85f21d345058363297e47a30a1 (764383)
```

**Comment by ProTechEx** [comment]
![](https://user-images.githubusercontent.com/5677301/203500912-31033154-0c65-4adc-8312-5a079e5b1520.png)

**Comment by NicolasDorier** [comment]
We should do it automatically. I probably need to fix our image.

**Comment by NicolasDorier** [comment]
@ProTechEx as a workaround, if your wallet is empty, you can create a new hot wallet for USDT, however do not check "Save keys in RPC"

**Comment by NicolasDorier** [comment]
I could repro. I'm on it.

**Comment by NicolasDorier** [comment]
@ProTechEx please run `btcpay-update.sh`, it should fix the issue. If not, reopen the issue.

**Comment by ProTechEx** [comment]
I wan't just confirm, that after update it has been fixed and every thing is fine now.  
Thanks a lot!

**Comment by NicolasDorier** [comment]
@ProTechEx I pushed another update, can you make sure an update don't break stuff? I found out that there was probably a bug where restarting the container might fail, and also for people who had old wallet.
