### ISSUE TITLE
[Bug]: BTCPay invoice not settling after successful Lightning payment (CLN + Lightning Charge)

### ISSUE THREAD

**Issue by nitramiz** [btcpayserver/btcpayserver#4383]
### What is your BTCPay version?

BTCPay v1.6.11.0-altcoins

### How did you deploy BTCPay Server?

BTCPayServer is deployed via Docker containers managed by `systemd` services (BTCPay, NBX, Postgres 13). Using the official upstream images. 
The CLN node and Lightning Charge are running on a separate machine. Lightning Charge's HTTP port is port-forwarded to the BTCPay box over an SSH tunnel. An Nginx reverse proxy is running on the BTCPay box (`localhost:8080`) and forwarding traffic to Charge. 

### What happened?

A BTCPay invoice expired after an hour because BTCPay did not recognize a completed Lightning payment. The LN invoice was paid after 10 minutes. Both CLN and Lighting Charge have recognized the payment. 

### How did you encounter this bug?

A customer emailed us that their BTCPay Checkout window was still showing a Pending invoice, even though they had paid the LN invoice, which was confirmed directly on the CLN node and Lightning Charge.

### Relevant log output

```shell
2022-11-24T00:23:47.152412857Z info: PayServer:      BTC (Lightning): Start listening http://localhost:8080/
2022-11-24T00:32:21.042887068Z fail: PayServer:      BTC (Lightning): Error while contacting http://localhost:8080/
2022-11-24T00:32:21.042923138Z System.FormatException: Input string was not in a correct format.
2022-11-24T00:32:21.043852325Z    at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
2022-11-24T00:32:21.043866297Z    at BTCPayServer.Lightning.JsonConverters.LightMoneyJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
2022-11-24T00:32:21.044269030Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
2022-11-24T00:32:21.044523238Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
2022-11-24T00:32:21.044533232Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
2022-11-24T00:32:21.044776997Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
2022-11-24T00:32:21.045027259Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
2022-11-24T00:32:21.045323960Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
2022-11-24T00:32:21.045334254Z    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
2022-11-24T00:32:21.045611706Z    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
2022-11-24T00:32:21.045621211Z    at BTCPayServer.Lightning.Charge.ChargeSession.WaitInvoice(CancellationToken cancellation)
2022-11-24T00:32:21.045756052Z    at BTCPayServer.Lightning.Charge.ChargeSession.BTCPayServer.Lightning.ILightningInvoiceListener.WaitInvoice(CancellationToken token)
2022-11-24T00:32:21.045763997Z    at BTCPayServer.Payments.Lightning.LightningInstanceListener.Listen(CancellationToken cancellation) in /source/BTCPayServer/Payments/Lightning/LightningListener.cs:line 473
2022-11-24T00:32:21.046617331Z info: PayServer:      BTC (Lightning): Stop listening http://localhost:8080/
```

### What browser do you use?

Firefox 107.0

### Additional information
![screenshot](https://user-images.githubusercontent.com/16788093/204564881-9dfaad70-7442-4ffc-beb1-0b59a2b7775d.jpeg)

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
Was this a one time problem or does it persist? It looks like one of the amount values or the whole data in general couldn't be read.

As this is an external Lightning node: Which versions of Charge and Core Lightning are you running?
Our internal versions are behind the official releases quite a bit by now, so there might be a discrepancy here, which we might not have noticed, because internally we are running older versions (also in the tests).

**Comment by nitramiz** [comment]
Hi! It was a one-time failure. It was a slightly larger payment but nothing crazy (0.0271 4143).

 [Latest Lightning Charge](https://github.com/ElementsProject/lightning-charge/releases/tag/v0.4.23)
 [CLN 0.12.1](https://github.com/ElementsProject/lightning/releases/tag/v0.12.1)

**Comment by nitramiz** [comment]
Hi @dennisreimann! I may have to reopen this because the same thing happened, again with a larger payment. Running latest NBX (`nicolasdorier/nbxplorer:2.3.54`) and BTCPayServer (`btcpayserver/btcpayserver:1.7.1-altcoins`).

The BTCPay invoice was never marked as paid and it expired when the payment was made on time.

**Comment by nitramiz** [comment]
Invoice `"created_at": 1671487999` (Mon 19 Dec 2022 10:13:19 PM GMT)
`"paid_at": 1671488044` (Mon 19 Dec 2022 10:14:04 PM GMT)
BTCPay's logs at the time:
```
2022-12-19T22:14:45.380274475Z info: PayServer:      BTC (Lightning): Start listening http://localhost:8080/
2022-12-19T22:14:45.697766816Z fail: PayServer:      BTC (Lightning): Error while contacting http://localhost:8080/
2022-12-19T22:14:45.697827582Z System.FormatException: Input string was not in a correct format.
2022-12-19T22:14:45.698220118Z    at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
2022-12-19T22:14:45.698229940Z    at BTCPayServer.Lightning.JsonConverters.LightMoneyJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
2022-12-19T22:14:45.698537281Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
2022-12-19T22:14:45.698797723Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
2022-12-19T22:14:45.698806829Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
2022-12-19T22:14:45.699036823Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
2022-12-19T22:14:45.699238963Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
2022-12-19T22:14:45.699464360Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
2022-12-19T22:14:45.699474650Z    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
2022-12-19T22:14:45.699723569Z    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
2022-12-19T22:14:45.699732065Z    at BTCPayServer.Lightning.Charge.ChargeClient.GetInvoice(String invoiceId, CancellationToken cancellation)
2022-12-19T22:14:45.700010289Z    at BTCPayServer.Lightning.Charge.ChargeClient.BTCPayServer.Lightning.ILightningClient.GetInvoice(String invoiceId, CancellationToken cancellation)
2022-12-19T22:14:45.700246644Z    at BTCPayServer.Payments.Lightning.LightningInstanceListener.PollPayment(ListenedInvoice listenedInvoice, CancellationToken cancellation) in /source/BTCPayServer/Payments/Lightning/LightningListener.cs:line 444
2022-12-19T22:14:45.700256758Z    at BTCPayServer.Payments.Lightning.LightningInstanceListener.PollAllListenedInvoices(CancellationToken cancellation) in /source/BTCPayServer/Payments/Lightning/LightningListener.cs:line 514
2022-12-19T22:14:45.700556786Z    at BTCPayServer.Payments.Lightning.LightningInstanceListener.Listen(CancellationToken cancellation) in /source/BTCPayServer/Payments/Lightning/LightningListener.cs:line 465
2022-12-19T22:14:45.701284517Z info: PayServer:      BTC (Lightning): Stop listening http://localhost:8080/
2022-12-19T22:15:45.377671380Z info: PayServer:      BTC (Lightning): Start listening http://localhost:8080/
```

**Comment by dennisreimann** [comment]
As discussed on Mattermost, this is a conversion problem for float values in our Lightning library.

The JSON from Charge looks like this:

```json
  {
    "msatoshi": "3187032000",
    "msatoshi_received": "3187032000.0"
  },
```

Fixed here:
