### ISSUE TITLE
Lightning-charge container is not running when setting up development environment of BTCPay Server.

### ISSUE THREAD

**Issue by adityaSSS2022** [btcpayserver/btcpayserver#4512]
Using lightningd directory mounted in /etc/lightning... 
2023-01-09 18:49:16 Starting Lightning Charge
2023-01-09 18:49:16 Lightning client connection error Error: connect ECONNREFUSED /etc/lightning/lightning-rpc
2023-01-09 18:49:16     at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
2023-01-09 18:49:16   errno: 'ECONNREFUSED',
2023-01-09 18:49:16   code: 'ECONNREFUSED',
2023-01-09 18:49:16   syscall: 'connect',
2023-01-09 18:49:16   address: '/etc/lightning/lightning-rpc'
2023-01-09 18:49:16 }
2023-01-09 18:49:16 events.js:287
2023-01-09 18:49:16       throw er; // Unhandled 'error' event
2023-01-09 18:49:16       ^
2023-01-09 18:49:16 
2023-01-09 18:49:16 Error: connect ECONNREFUSED /etc/lightning/lightning-rpc
2023-01-09 18:49:16     at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
2023-01-09 18:49:16 Emitted 'error' event on LightningClient instance at:
2023-01-09 18:49:16     at Socket.<anonymous> (/opt/charged/node_modules/clightning-client/index.js:65:23)
2023-01-09 18:49:16     at Socket.emit (events.js:310:20)
2023-01-09 18:49:16     at emitErrorNT (internal/streams/destroy.js:92:8)
2023-01-09 18:49:16     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
2023-01-09 18:49:16     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
2023-01-09 18:49:16   errno: 'ECONNREFUSED',
2023-01-09 18:49:16   code: 'ECONNREFUSED',
2023-01-09 18:49:16   syscall: 'connect',
2023-01-09 18:49:16   address: '/etc/lightning/lightning-rpc'
2023-01-09 18:49:16 }

**Comment by petzsch** [comment]
replied to on Mattermost:
https://chat.btcpayserver.org/btcpayserver/pl/o468cay8tt8bdqgi4imiijtuwh

Please check this issue for more details:
https://github.com/ElementsProject/lightning-charge/issues/82
