### ISSUE TITLE
[Bug]: Disqus integration breaks in Crowdfunding store

### ISSUE THREAD

**Issue by lopezdp** [btcpayserver/btcpayserver#4572]
### What is your BTCPay version?

BTCPay Server v1.7.5+372df93c1

### How did you deploy BTCPay Server?

aws ec2

### What happened?

in the crowdfunding app after adding my Disqus short name the discussion tab on the crowd fund page doesnt show up

<img width="491" alt="Screenshot 2023-01-29 at 1 27 32 AM" src="https://user-images.githubusercontent.com/5707191/215309156-d717bb87-5dff-4143-b453-5c506e9b447c.png">

### How did you encounter this bug?

after setting the discussion settings in the crowd fund settings page and after buying premium Disqus service

<img width="913" alt="Screenshot 2023-01-29 at 1 28 40 AM" src="https://user-images.githubusercontent.com/5707191/215309206-0f23a888-9549-4928-8eb9-cb7308b1ece9.png">

### Relevant log output

```shell
2023-01-29 00:00:36.408 +00:00 [INF] SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
2023-01-29 00:00:36.449 +00:00 [WRN] SSH connection issue of type SshConnectionException: Connection reset by peer
2023-01-29 00:00:36.450 +00:00 [WRN] Retrying SSH connection in 600 seconds
2023-01-29 00:10:36.453 +00:00 [INF] SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
2023-01-29 00:10:36.502 +00:00 [WRN] SSH connection issue of type SshConnectionException: Connection reset by peer
2023-01-29 00:10:36.503 +00:00 [WRN] Retrying SSH connection in 600 seconds
2023-01-29 00:20:36.507 +00:00 [INF] SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
2023-01-29 00:20:36.563 +00:00 [WRN] SSH connection issue of type SshConnectionException: Connection reset by peer
2023-01-29 00:20:36.564 +00:00 [WRN] Retrying SSH connection in 600 seconds
2023-01-29 00:30:36.565 +00:00 [INF] SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
2023-01-29 00:30:36.588 +00:00 [WRN] SSH connection issue of type SshConnectionException: Connection reset by peer
2023-01-29 00:30:36.588 +00:00 [WRN] Retrying SSH connection in 600 seconds
2023-01-29 00:40:36.592 +00:00 [INF] SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
2023-01-29 00:40:36.623 +00:00 [WRN] SSH connection issue of type SshConnectionException: Connection reset by peer
2023-01-29 00:40:36.623 +00:00 [WRN] Retrying SSH connection in 600 seconds
2023-01-29 00:50:36.628 +00:00 [INF] SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
2023-01-29 00:50:36.658 +00:00 [WRN] SSH connection issue of type SshConnectionException: An established connection was aborted by the server.
2023-01-29 00:50:36.658 +00:00 [WRN] Retrying SSH connection in 600 seconds
2023-01-29 01:00:03.444 +00:00 [INF] User 'ed098f23-671f-45a6-b54a-66fb7f189fda' logged in.
2023-01-29 01:00:36.662 +00:00 [INF] SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
2023-01-29 01:00:36.714 +00:00 [WRN] SSH connection issue of type SshConnectionException: Connection reset by peer
2023-01-29 01:00:36.715 +00:00 [WRN] Retrying SSH connection in 600 seconds
2023-01-29 01:03:37.460 +00:00 [INF] BTC (Lightning): Start listening unix://etc/clightning_bitcoin/lightning-rpc
2023-01-29 01:10:36.721 +00:00 [INF] SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
2023-01-29 01:10:36.761 +00:00 [WRN] SSH connection issue of type SshConnectionException: Connection reset by peer
2023-01-29 01:10:36.761 +00:00 [WRN] Retrying SSH connection in 600 seconds
2023-01-29 01:16:52.321 +00:00 [ERR] BTC (Lightning): Error while contacting unix://etc/clightning_bitcoin/lightning-rpc
Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.LoadAsync(JsonReader reader, JsonLoadSettings settings, CancellationToken cancellationToken)
   at BTCPayServer.Lightning.CLightning.CLightningClient.SendCommandAsync[T](String command, Object[] parameters, Boolean noReturn, Boolean isArray, CancellationToken cancellation)
   at BTCPayServer.Lightning.CLightning.CLightningInvoiceListener.WaitInvoice(CancellationToken cancellation)
   at BTCPayServer.Payments.Lightning.LightningInstanceListener.Listen(CancellationToken cancellation) in /source/BTCPayServer/Payments/Lightning/LightningListener.cs:line 471
2023-01-29 01:16:52.322 +00:00 [ERR] Error while connecting to WebSocket of NBXplorer (BTC)
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at NBXplorer.WebsocketMessageListener.NextMessageAsync(CancellationToken cancellation)
   at BTCPayServer.Payments.Bitcoin.NBXplorerListener.Listen(BTCPayWallet wallet) in /source/BTCPayServer/Payments/Bitcoin/NBXplorerListener.cs:line 142
2023-01-29 01:16:52.323 +00:00 [INF] BTC (Lightning): Stop listening unix://etc/clightning_bitcoin/lightning-rpc
2023-01-29 01:16:52.325 +00:00 [INF] Disconnected from WebSocket of NBXplorer (BTC)
2023-01-29 01:16:54.328 +00:00 [INF] DelayedTransactionBroadcasterHostedService successfully exited...
2023-01-29 01:16:54.329 +00:00 [INF] TorServices successfully exited...
2023-01-29 01:16:54.341 +00:00 [INF] CheckConfigurationHostedService successfully exited...
2023-01-29 01:16:54.384 +00:00 [INF] PullPaymentHostedService successfully exited...
2023-01-29 01:16:59.285 +00:00 [INF] NBXplorerListener successfully exited...
2023-01-29 01:16:59.288 +00:00 [INF] LightningListener successfully exited...
2023-01-29 01:16:59.294 +00:00 [INF] Stop watching invoices
2023-01-29 01:16:59.369 +00:00 [INF] RatesHostedService successfully exited...
2023-01-29 01:17:00.176 +00:00 [INF] DynamicDnsHostedService successfully exited...
2023-01-29 01:17:00.179 +00:00 [INF] NewVersionCheckerHostedService successfully exited...
2023-01-29 01:17:00.187 +00:00 [INF] LightningAutomatedPayoutProcessor successfully exited...
2023-01-29 01:17:00.188 +00:00 [INF] LightningAutomatedPayoutProcessor successfully exited...
2023-01-29 01:17:00.188 +00:00 [INF] OnChainAutomatedPayoutProcessor successfully exited...
2023-01-29 01:17:00.188 +00:00 [INF] OnChainAutomatedPayoutProcessor successfully exited...
2023-01-29 01:17:00.197 +00:00 [INF] Stopping
2023-01-29 01:17:14.200 +00:00 [INF] Root Path: /
2023-01-29 01:17:15.996 +00:00 [INF] Connection to NBXplorer's database successful, dashboard and reporting features activated.
2023-01-29 01:17:16.011 +00:00 [INF] SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
2023-01-29 01:17:16.541 +00:00 [INF] SSH connection succeeded
2023-01-29 01:17:16.693 +00:00 [INF] Starting listening NBXplorer (BTC)
2023-01-29 01:17:16.896 +00:00 [INF] Start watching invoices
2023-01-29 01:17:17.138 +00:00 [INF] Starting payment request expiration watcher
2023-01-29 01:17:17.727 +00:00 [INF] 0 pending payment requests being checked since last run
2023-01-29 01:17:18.565 +00:00 [INF] Importing 40 invoices into the search table in 1 pages
2023-01-29 01:17:18.565 +00:00 [INF] Import to search table progress: 1/1 pages
2023-01-29 01:17:18.864 +00:00 [INF] Starting
2023-01-29 01:17:19.346 +00:00 [INF] Full invoice search import successful
2023-01-29 01:17:19.422 +00:00 [INF] Wallet transaction label importing transactions 0/0
2023-01-29 01:17:19.463 +00:00 [INF] Wallet transaction label successfully migrated
2023-01-29 01:17:38.894 +00:00 [INF] BTC: Checking if any pending invoice got paid while offline...
2023-01-29 01:17:39.240 +00:00 [INF] BTC: 0 payments happened while offline
2023-01-29 01:17:39.242 +00:00 [INF] Connected to WebSocket of NBXplorer (BTC)
2023-01-29 01:18:13.668 +00:00 [INF] DelayedTransactionBroadcasterHostedService successfully exited...
2023-01-29 01:18:13.671 +00:00 [INF] TorServices successfully exited...
2023-01-29 01:18:13.676 +00:00 [INF] CheckConfigurationHostedService successfully exited...
2023-01-29 01:18:13.725 +00:00 [INF] PullPaymentHostedService successfully exited...
2023-01-29 01:18:13.732 +00:00 [INF] Disconnected from WebSocket of NBXplorer (BTC)
2023-01-29 01:18:13.740 +00:00 [INF] NBXplorerListener successfully exited...
2023-01-29 01:18:13.779 +00:00 [INF] LightningListener successfully exited...
2023-01-29 01:18:13.780 +00:00 [INF] LightningPendingPayoutListener successfully exited...
2023-01-29 01:18:13.829 +00:00 [INF] Stop watching invoices
2023-01-29 01:18:15.213 +00:00 [INF] DynamicDnsHostedService successfully exited...
2023-01-29 01:18:15.235 +00:00 [INF] NewVersionCheckerHostedService successfully exited...
2023-01-29 01:18:15.235 +00:00 [INF] DbMigrationsHostedService successfully exited...
2023-01-29 01:18:15.266 +00:00 [INF] Stopping
2023-01-29 01:18:31.071 +00:00 [INF] Root Path: /
2023-01-29 01:18:32.470 +00:00 [INF] Connection to NBXplorer's database successful, dashboard and reporting features activated.
2023-01-29 01:18:32.485 +00:00 [INF] SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
2023-01-29 01:18:32.777 +00:00 [INF] Starting listening NBXplorer (BTC)
2023-01-29 01:18:32.855 +00:00 [INF] Start watching invoices
2023-01-29 01:18:33.318 +00:00 [INF] SSH connection succeeded
2023-01-29 01:18:34.234 +00:00 [INF] Starting payment request expiration watcher
2023-01-29 01:18:34.502 +00:00 [INF] 0 pending payment requests being checked since last run
2023-01-29 01:18:35.150 +00:00 [INF] Starting
2023-01-29 01:18:45.393 +00:00 [INF] BTC: Checking if any pending invoice got paid while offline...
2023-01-29 01:18:45.833 +00:00 [INF] BTC: 0 payments happened while offline
2023-01-29 01:18:45.833 +00:00 [INF] Connected to WebSocket of NBXplorer (BTC)
2023-01-29 01:19:32.638 +00:00 [INF] BTC (Lightning): Start listening unix://etc/clightning_bitcoin/lightning-rpc
2023-01-29 02:02:54.641 +00:00 [INF] User 'ed098f23-671f-45a6-b54a-66fb7f189fda' logged in.
2023-01-29 02:12:02.035 +00:00 [INF] User 'ed098f23-671f-45a6-b54a-66fb7f189fda' logged in.
2023-01-29 02:45:32.560 +00:00 [INF] BTC (Lightning): No more invoice to listen on unix://etc/clightning_bitcoin/lightning-rpc, releasing the connection.
2023-01-29 02:55:16.749 +00:00 [INF] BTC (Lightning): Start listening unix://etc/clightning_bitcoin/lightning-rpc
2023-01-29 03:49:32.552 +00:00 [INF] BTC (Lightning): No more invoice to listen on unix://etc/clightning_bitcoin/lightning-rpc, releasing the connection.
```

### What browser do you use?

safari

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by jwolfe419** [comment]
- [x] I'm sorry did you get the issue resolved

**Comment by jwolfe419** [comment]
- [ ]

**Comment by lopezdp** [comment]
> [x] I'm sorry did you get the issue resolved

@jwolfe419 ???? nope. please reference the issue how would I get it resolved?

**Comment by NicolasDorier** [comment]
Ping @Kukks

**Comment by Kukks** [comment]
I think we should just remove disqus native support and turn it into a plugin. I have never seen it used except this time!

**Comment by NicolasDorier** [comment]
so we don't fix it?

**Comment by lopezdp** [comment]
> I think we should just remove disqus native support and turn it into a plugin. I have never seen it used except this time!

its a crowdfunding plugin. you need your community to discuss your project. its pretty important to the success of the crowdfund/raise to let the community `Disqus`

please; fix it.

**Comment by dennisreimann** [comment]
It's a CSP issue, I can reproduce it and will take a look.

**Comment by lopezdp** [comment]
thank you!

**Comment by lopezdp** [comment]
this update worked out beautifully

**Comment by lopezdp** [comment]
@NicolasDorier @Kukks fyi

### this is what it look like on Safari

<img width="1032" alt="Screenshot 2023-02-19 at 5 33 14 PM" src="https://user-images.githubusercontent.com/5707191/219979214-4cc02e1b-1f5d-4514-8bc1-6186d5025ede.png">



### this is what it look like on Chrome

<img width="1096" alt="Screenshot 2023-02-19 at 5 32 43 PM" src="https://user-images.githubusercontent.com/5707191/219979184-b2f5dfdc-8cfd-4c93-bb67-bc377ae1c4db.png">

**Comment by dennisreimann** [comment]
I'll check.

**Comment by dennisreimann** [comment]
@lopezdp For me it loads in Safari (16.3). Do you see any errors or wanring in the browser console?

**Comment by lopezdp** [comment]
@dennisreimann must've been something weird with the cache on my side it works perfectly sir
