### ISSUE TITLE
[Bug]: MessageText: column "AType" does not exist

### ISSUE THREAD

**Issue by ZoneMix** [btcpayserver/btcpayserver#4603]
### What is your BTCPay version?

I'm running BTCPay Server v1.7.3

### How did you deploy BTCPay Server?

I'm running BTCPay Server on a raspberry pi as a system service. 

### What happened?

I have not touched anything with my server over the past few weeks, however, I noticed that it randomly started breaking a few days ago when I tried to generate a QR Code for my Bitcoin Wallet. I went onto the server, tryed to browse to the "Bitcoin Wallet" section for the pay server and I get a 500 error. Not sure what is going on here, but I included log ouput.

### How did you encounter this bug?

1. I browse to my server in the web
2. I click on :
![image](https://user-images.githubusercontent.com/38586893/217071051-1eb7ec90-e1a5-428b-a2d2-4fab67466e50.png)

3. Then I get the error in the logs described.

### Relevant log output

```shell
Feb 06 13:44:18 pi run.sh[7599]: fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMO8F9F8V3S1", Request id "0HMO8F9F8V3S1:00000002": An unhandled exception was thrown by the application.
Feb 06 13:44:18 pi run.sh[7599]: Npgsql.PostgresException (0x80004005): 42703: column "AType" does not exist
Feb 06 13:44:18 pi run.sh[7599]: POSITION: 278
Feb 06 13:44:18 pi run.sh[7599]:    at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|215_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readi>
Feb 06 13:44:18 pi run.sh[7599]:    at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
Feb 06 13:44:18 pi run.sh[7599]:    at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
Feb 06 13:44:18 pi run.sh[7599]:    at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
Feb 06 13:44:18 pi run.sh[7599]:    at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
Feb 06 13:44:18 pi run.sh[7599]:    at BTCPayServer.Services.WalletRepository.GetWalletObjects(GetWalletObjectsQuery queryObject) in /root/btcpayserver/BTCPayServer/Services/WalletRepository.cs:line 174
Feb 06 13:44:18 pi run.sh[7599]:    at BTCPayServer.Services.WalletRepository.GetWalletTransactionsInfo(WalletId walletId, String[] transactionIds) in /root/btcpayserver/BTCPayServer/Services/WalletRepos>
Feb 06 13:44:18 pi run.sh[7599]:    at BTCPayServer.Controllers.UIWalletsController.WalletTransactions(WalletId walletId, String labelFilter, Int32 skip, Int32 count) in /root/btcpayserver/BTCPayServer/C>
Feb 06 13:44:18 pi run.sh[7599]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Obje>
Feb 06 13:44:18 pi run.sh[7599]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultVa>
Feb 06 13:44:18 pi run.sh[7599]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State n>
Feb 06 13:44:18 pi run.sh[7599]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Feb 06 13:44:18 pi run.sh[7599]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 06 13:44:18 pi run.sh[7599]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, >
Feb 06 13:44:18 pi run.sh[7599]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope sc>
Feb 06 13:44:18 pi run.sh[7599]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
Feb 06 13:44:18 pi run.sh[7599]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 06 13:44:18 pi run.sh[7599]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, O>
Feb 06 13:44:18 pi run.sh[7599]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Feb 06 13:44:18 pi run.sh[7599]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 06 13:44:18 pi run.sh[7599]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, >
Feb 06 13:44:18 pi run.sh[7599]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Feb 06 13:44:18 pi run.sh[7599]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Feb 06 13:44:18 pi run.sh[7599]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Feb 06 13:44:18 pi run.sh[7599]:    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Feb 06 13:44:18 pi run.sh[7599]:    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Feb 06 13:44:18 pi run.sh[7599]:    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, Po>
Feb 06 13:44:18 pi run.sh[7599]:    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Feb 06 13:44:18 pi run.sh[7599]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Feb 06 13:44:18 pi run.sh[7599]:    at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /root/btcpayserver/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 101
Feb 06 13:44:18 pi run.sh[7599]:    at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /root/btcpayserver/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 50
Feb 06 13:44:18 pi run.sh[7599]:    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
Feb 06 13:44:18 pi run.sh[7599]:    at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /root/btcpayserver/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 30
Feb 06 13:44:18 pi run.sh[7599]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
Feb 06 13:44:18 pi run.sh[7599]:   Exception data:
Feb 06 13:44:18 pi run.sh[7599]:     Severity: ERROR
Feb 06 13:44:18 pi run.sh[7599]:     SqlState: 42703
Feb 06 13:44:18 pi run.sh[7599]:     MessageText: column "AType" does not exist
Feb 06 13:44:18 pi run.sh[7599]:     Hint: Perhaps you meant to reference the column "wos.Type".
Feb 06 13:44:18 pi run.sh[7599]:     Position: 278
Feb 06 13:44:18 pi run.sh[7599]:     File: parse_relation.c
Feb 06 13:44:18 pi run.sh[7599]:     Line: 3633
Feb 06 13:44:18 pi run.sh[7599]:     Routine: errorMissingColumn
```
```


### What browser do you use?

_No response_

### Additional information

_No response_

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by petzsch** [comment]
According to @NicolasDorier on this [issue](https://github.com/btcpayserver/btcpayserver/issues/4544#issuecomment-1399253445) this was caused by running a master branch of nbxplorer instead of a tagged version.

**Comment by ZoneMix** [comment]
I am running v2.3.58 Tag for NBXplorer, could it be that the database is just screwed up now and I need to wipe it? I've only ever ran from release/tagged versions for both BTCPay Server and NBXplorer.

**Comment by ZoneMix** [comment]
Issue resolved by dropping the database and restarting BTCPay Server and NBXplorer. You have to setup everything again in the store, but doesn't take too long.
