### ISSUE TITLE
[Bug]: Confirmed LC transactions not showing up and invoices not confirming on check-out

### ISSUE THREAD

**Issue by exznomak** [btcpayserver/btcpayserver#4621]
### What is your BTCPay version?

© BTCPay Server v1.7.9+57f5c1567 (Altcoins)

### How did you deploy BTCPay Server?

Docker on LunaNode

### What happened?

I think after the update Server lost ability to read incoming transactions on the chain. For some time the chain got de-synched, but synced back after I restarted VPS. I went to sleep and woke up to clients reporting that transaction is confirmed but the invoice expired. Later I tested myself - did checkout on website, server did not catch the verified transaction and timed out. Then created invoice on server page itself and it still did not work.

I got scared and tried moving litecoins out of the hot wallet used on website, but this failed too. 

I feel like server lost connection with the wallet? I haven't changed anything.

### How did you encounter this bug?

1. Updated to latest version
2. Coins de-synched from chain and restarted VPS
3. Restarted BTCpay server from settings

### Relevant log output

```shell
2023-02-10 02:01:59.184 +00:00 [WRN] Error while contacting exchange binance_us: The operation was canceled.
2023-02-10 03:54:08.003 +00:00 [WRN] Error while contacting exchange binance_us: The operation was canceled.
2023-02-10 03:56:59.166 +00:00 [WRN] Error while contacting exchange binance_us: The operation was canceled.
2023-02-10 04:00:50.768 +00:00 [WRN] Error while contacting exchange binance_us: The operation was canceled.
2023-02-10 04:04:41.385 +00:00 [WRN] Error while contacting exchange binance_us: The operation was canceled.
2023-02-10 04:07:36.364 +00:00 [WRN] Error while contacting exchange binance_us: The operation was canceled.
2023-02-10 04:10:33.867 +00:00 [WRN] Error while contacting exchange binance_us: The operation was canceled.
2023-02-10 04:11:23.868 +00:00 [WRN] Error while contacting exchange binance_us: The operation was canceled.
2023-02-10 05:16:09.174 +00:00 [WRN] Error while contacting exchange binance_us: The operation was canceled.
2023-02-10 07:18:23.088 +00:00 [WRN] Error while contacting exchange binance_us: The operation was canceled.
2023-02-10 07:18:54.374 +00:00 [INF] User with ID 162ae730-14da-4c85-89ac-abc22dc67a75 logged in with 2fa.
2023-02-10 07:19:13.692 +00:00 [ERR] Connection id "0HML7LC965L4P", Request id "0HML7LC965L4P:00000002": An unhandled exception was thrown by the application.
NBXplorer.Models.NBXplorerException: The RPC interface is currently not available.
   at NBXplorer.ExplorerClient.ParseResponse[T](HttpResponseMessage response)
   at NBXplorer.ExplorerClient.SendAsync[T](HttpMethod method, Object body, String relativePath, Object[] parameters, CancellationToken cancellation)
   at BTCPayServer.Controllers.UIWalletsController.GetSeed(WalletId walletId, BTCPayNetwork network) in /source/BTCPayServer/Controllers/UIWalletsController.cs:line 541
   at BTCPayServer.Controllers.UIWalletsController.WalletSend(WalletId walletId, String defaultDestination, String defaultAmount, String[] bip21) in /source/BTCPayServer/Controllers/UIWalletsController.cs:line 495
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 100
   at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 50
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 30
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2023-02-10 07:20:44.915 +00:00 [INF] DelayedTransactionBroadcasterHostedService successfully exited...
2023-02-10 07:20:44.920 +00:00 [INF] TorServices successfully exited...
2023-02-10 07:20:44.926 +00:00 [INF] CheckConfigurationHostedService successfully exited...
2023-02-10 07:20:45.032 +00:00 [INF] PullPaymentHostedService successfully exited...
2023-02-10 07:20:45.058 +00:00 [INF] Disconnected from WebSocket of NBXplorer (LTC)
2023-02-10 07:20:45.063 +00:00 [INF] Disconnected from WebSocket of NBXplorer (BTC)
2023-02-10 07:20:45.066 +00:00 [INF] NBXplorerListener successfully exited...
2023-02-10 07:20:45.089 +00:00 [INF] LightningListener successfully exited...
2023-02-10 07:20:45.112 +00:00 [INF] Stop watching invoices
2023-02-10 07:20:45.165 +00:00 [INF] RatesHostedService successfully exited...
2023-02-10 07:20:45.855 +00:00 [INF] DynamicDnsHostedService successfully exited...
2023-02-10 07:20:45.879 +00:00 [INF] NewVersionCheckerHostedService successfully exited...
2023-02-10 07:20:45.879 +00:00 [INF] DbMigrationsHostedService successfully exited...
2023-02-10 07:22:35.804 +00:00 [INF] Root Path: /
2023-02-10 07:22:40.656 +00:00 [INF] Starting listening Monero-like daemons (XMR)
2023-02-10 07:22:41.229 +00:00 [INF] SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
2023-02-10 07:22:41.412 +00:00 [INF] Starting listening NBXplorer (BTC)
2023-02-10 07:22:41.430 +00:00 [INF] Starting listening NBXplorer (LTC)
2023-02-10 07:22:41.516 +00:00 [INF] Start watching invoices
2023-02-10 07:22:41.547 +00:00 [INF] XMR just became unavailable
2023-02-10 07:22:42.023 +00:00 [ERR] BTC: NBXplorer error `Connection refused (nbxplorer:32838)`
2023-02-10 07:22:42.487 +00:00 [INF] Starting payment request expiration watcher
2023-02-10 07:22:43.624 +00:00 [INF] 0 pending payment requests being checked since last run
2023-02-10 07:22:43.933 +00:00 [INF] SSH connection succeeded
2023-02-10 07:24:15.103 +00:00 [INF] LTC: Checking if any pending invoice got paid while offline...
2023-02-10 07:24:15.421 +00:00 [INF] LTC: 0 payments happened while offline
2023-02-10 07:24:15.422 +00:00 [INF] Connected to WebSocket of NBXplorer (LTC)
2023-02-10 07:24:25.758 +00:00 [ERR] Connection id "0HMOB6UDCU1R4", Request id "0HMOB6UDCU1R4:00000002": An unhandled exception was thrown by the application.
NBXplorer.Models.NBXplorerException: The RPC interface is currently not available.
   at NBXplorer.ExplorerClient.ParseResponse[T](HttpResponseMessage response)
   at NBXplorer.ExplorerClient.SendAsync[T](HttpMethod method, Object body, String relativePath, Object[] parameters, CancellationToken cancellation)
   at BTCPayServer.Controllers.UIWalletsController.GetSeed(WalletId walletId, BTCPayNetwork network) in /source/BTCPayServer/Controllers/UIWalletsController.cs:line 535
   at BTCPayServer.Controllers.UIWalletsController.WalletSend(WalletId walletId, String defaultDestination, String defaultAmount, String[] bip21) in /source/BTCPayServer/Controllers/UIWalletsController.cs:line 495
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 99
   at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 30
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 29
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2023-02-10 07:27:13.234 +00:00 [INF] Running SSH command: . /etc/profile.d/btcpay-env.sh && nohup btcpay-update.sh > /dev/null 2>&1 & disown
2023-02-10 07:28:34.223 +00:00 [INF] DelayedTransactionBroadcasterHostedService successfully exited...
2023-02-10 07:28:34.246 +00:00 [INF] TorServices successfully exited...
2023-02-10 07:28:34.254 +00:00 [INF] CheckConfigurationHostedService successfully exited...
2023-02-10 07:28:34.323 +00:00 [INF] PullPaymentHostedService successfully exited...
2023-02-10 07:28:34.360 +00:00 [INF] Disconnected from WebSocket of NBXplorer (LTC)
2023-02-10 07:28:34.366 +00:00 [INF] NBXplorerListener successfully exited...
2023-02-10 07:28:34.384 +00:00 [INF] LightningListener successfully exited...
2023-02-10 07:28:34.406 +00:00 [INF] Stop watching invoices
2023-02-10 07:28:34.586 +00:00 [INF] RatesHostedService successfully exited...
2023-02-10 07:28:34.611 +00:00 [INF] DynamicDnsHostedService successfully exited...
2023-02-10 07:28:34.620 +00:00 [INF] NewVersionCheckerHostedService successfully exited...
2023-02-10 07:28:34.620 +00:00 [INF] DbMigrationsHostedService successfully exited...
2023-02-10 07:28:58.630 +00:00 [INF] Root Path: /
2023-02-10 07:29:00.242 +00:00 [INF] Starting listening Monero-like daemons (XMR)
2023-02-10 07:29:00.497 +00:00 [INF] Connection to NBXplorer's database successful, dashboard and reporting features activated.
2023-02-10 07:29:00.507 +00:00 [INF] XMR just became unavailable
2023-02-10 07:29:00.523 +00:00 [INF] SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
2023-02-10 07:29:01.627 +00:00 [INF] Starting listening NBXplorer (BTC)
2023-02-10 07:29:01.645 +00:00 [INF] Starting listening NBXplorer (LTC)
2023-02-10 07:29:01.663 +00:00 [INF] Start watching invoices
2023-02-10 07:29:01.737 +00:00 [ERR] LTC: NBXplorer error `Connection refused (nbxplorer:32838)`
2023-02-10 07:29:01.766 +00:00 [ERR] BTC: NBXplorer error `Connection refused (nbxplorer:32838)`
2023-02-10 07:29:01.780 +00:00 [INF] SSH connection succeeded
2023-02-10 07:29:02.319 +00:00 [INF] Starting payment request expiration watcher
2023-02-10 07:29:02.508 +00:00 [INF] 0 pending payment requests being checked since last run
2023-02-10 07:29:02.720 +00:00 [INF] Wallet transaction label importing transactions 0/783
2023-02-10 07:29:04.657 +00:00 [INF] Wallet transaction label successfully migrated
2023-02-10 07:31:07.984 +00:00 [INF] User with ID 162ae730-14da-4c85-89ac-abc22dc67a75 logged in with 2fa.
2023-02-10 07:33:39.889 +00:00 [ERR] Connection id "0HMOB71VT0PNT", Request id "0HMOB71VT0PNT:00000002": An unhandled exception was thrown by the application.
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at AspNetCoreGeneratedDocument.Views_UIWallets_WalletSend.<>c__DisplayClass59_0.<<ExecuteAsync>b__4>d.MoveNext() in /source/BTCPayServer/Views/UIWallets/WalletSend.cshtml:line 176
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.GetChildContentAsync(Boolean useCachedResult, HtmlEncoder encoder)
   at Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
   at AspNetCoreGeneratedDocument.Views_UIWallets_WalletSend.ExecuteAsync() in /source/BTCPayServer/Views/UIWallets/WalletSend.cshtml:line 54
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 101
   at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 50
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 30
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2023-02-10 07:35:25.515 +00:00 [INF] LTC: Checking if any pending invoice got paid while offline...
2023-02-10 07:35:26.015 +00:00 [INF] LTC: 0 payments happened while offline
2023-02-10 07:35:26.015 +00:00 [INF] Connected to WebSocket of NBXplorer (LTC)
2023-02-10 07:38:52.253 +00:00 [INF] BTC: Checking if any pending invoice got paid while offline...
2023-02-10 07:38:52.463 +00:00 [INF] BTC: 0 payments happened while offline
2023-02-10 07:38:52.463 +00:00 [INF] Connected to WebSocket of NBXplorer (BTC)
2023-02-10 10:01:40.956 +00:00 [INF] Running SSH command: . /etc/profile.d/btcpay-env.sh && nohup btcpay-restart.sh > /dev/null 2>&1 & disown
2023-02-10 10:01:41.029 +00:00 [INF] A hard restart has been requested
2023-02-10 10:01:44.435 +00:00 [INF] DelayedTransactionBroadcasterHostedService successfully exited...
2023-02-10 10:01:44.442 +00:00 [INF] TorServices successfully exited...
2023-02-10 10:01:44.444 +00:00 [INF] CheckConfigurationHostedService successfully exited...
2023-02-10 10:01:44.548 +00:00 [INF] PullPaymentHostedService successfully exited...
2023-02-10 10:01:44.630 +00:00 [INF] Disconnected from WebSocket of NBXplorer (BTC)
2023-02-10 10:01:44.686 +00:00 [INF] Disconnected from WebSocket of NBXplorer (LTC)
2023-02-10 10:01:44.703 +00:00 [INF] NBXplorerListener successfully exited...
2023-02-10 10:01:44.727 +00:00 [INF] LightningListener successfully exited...
2023-02-10 10:01:44.733 +00:00 [INF] LightningPendingPayoutListener successfully exited...
2023-02-10 10:01:44.803 +00:00 [INF] Stop watching invoices
2023-02-10 10:01:46.321 +00:00 [INF] DynamicDnsHostedService successfully exited...
2023-02-10 10:01:46.352 +00:00 [INF] NewVersionCheckerHostedService successfully exited...
2023-02-10 10:01:46.353 +00:00 [INF] DbMigrationsHostedService successfully exited...
2023-02-10 10:02:04.908 +00:00 [INF] Root Path: /
2023-02-10 10:02:06.176 +00:00 [INF] Starting listening Monero-like daemons (XMR)
2023-02-10 10:02:06.319 +00:00 [INF] XMR just became unavailable
2023-02-10 10:02:06.375 +00:00 [INF] Connection to NBXplorer's database successful, dashboard and reporting features activated.
2023-02-10 10:02:06.384 +00:00 [INF] SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
2023-02-10 10:02:07.044 +00:00 [INF] SSH connection succeeded
2023-02-10 10:02:07.076 +00:00 [INF] Starting listening NBXplorer (BTC)
2023-02-10 10:02:07.120 +00:00 [INF] Starting listening NBXplorer (LTC)
2023-02-10 10:02:07.171 +00:00 [INF] Start watching invoices
2023-02-10 10:02:08.085 +00:00 [INF] Starting payment request expiration watcher
2023-02-10 10:02:08.407 +00:00 [INF] 0 pending payment requests being checked since last run
2023-02-10 10:02:38.322 +00:00 [INF] BTC: Checking if any pending invoice got paid while offline...
2023-02-10 10:02:38.706 +00:00 [INF] BTC: 0 payments happened while offline
2023-02-10 10:02:38.707 +00:00 [INF] Connected to WebSocket of NBXplorer (BTC)
2023-02-10 10:02:58.455 +00:00 [INF] LTC: Checking if any pending invoice got paid while offline...
2023-02-10 10:02:58.535 +00:00 [INF] LTC: 0 payments happened while offline
2023-02-10 10:02:58.535 +00:00 [INF] Connected to WebSocket of NBXplorer (LTC)
2023-02-10 10:05:49.392 +00:00 [INF] Running SSH command: . /etc/profile.d/btcpay-env.sh && nohup btcpay-update.sh > /dev/null 2>&1 & disown
2023-02-10 10:08:51.688 +00:00 [INF] DelayedTransactionBroadcasterHostedService successfully exited...
2023-02-10 10:08:51.692 +00:00 [INF] TorServices successfully exited...
2023-02-10 10:08:51.785 +00:00 [INF] CheckConfigurationHostedService successfully exited...
2023-02-10 10:08:52.383 +00:00 [INF] PullPaymentHostedService successfully exited...
2023-02-10 10:08:52.388 +00:00 [INF] NBXplorerListener successfully exited...
2023-02-10 10:08:52.483 +00:00 [INF] Disconnected from WebSocket of NBXplorer (BTC)
2023-02-10 10:08:52.485 +00:00 [INF] LightningListener successfully exited...
2023-02-10 10:08:52.485 +00:00 [INF] LightningPendingPayoutListener successfully exited...
2023-02-10 10:08:52.581 +00:00 [INF] Disconnected from WebSocket of NBXplorer (LTC)
2023-02-10 10:08:52.679 +00:00 [INF] Stop watching invoices
2023-02-10 10:08:53.592 +00:00 [INF] RatesHostedService successfully exited...
2023-02-10 10:08:53.785 +00:00 [INF] DynamicDnsHostedService successfully exited...
2023-02-10 10:08:53.792 +00:00 [INF] NewVersionCheckerHostedService successfully exited...
2023-02-10 10:08:53.792 +00:00 [INF] DbMigrationsHostedService successfully exited...
2023-02-10 10:12:19.591 +00:00 [INF] Root Path: /
2023-02-10 10:12:47.885 +00:00 [INF] Starting listening Monero-like daemons (XMR)
2023-02-10 10:12:53.792 +00:00 [INF] Connection to NBXplorer's database successful, dashboard and reporting features activated.
2023-02-10 10:12:54.189 +00:00 [INF] SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
2023-02-10 10:13:07.482 +00:00 [INF] SSH connection succeeded
2023-02-10 10:13:14.082 +00:00 [INF] Starting listening NBXplorer (BTC)
2023-02-10 10:13:16.887 +00:00 [INF] Starting listening NBXplorer (LTC)
2023-02-10 10:13:19.889 +00:00 [INF] Start watching invoices
2023-02-10 10:13:29.886 +00:00 [INF] Starting payment request expiration watcher
2023-02-10 10:13:33.784 +00:00 [INF] BTC: Checking if any pending invoice got paid while offline...
2023-02-10 10:13:35.481 +00:00 [INF] 0 pending payment requests being checked since last run
2023-02-10 10:13:36.491 +00:00 [INF] LTC: Checking if any pending invoice got paid while offline...
2023-02-10 10:13:44.388 +00:00 [WRN] Error while contacting exchange binance_us: A task was canceled.
2023-02-10 10:13:44.491 +00:00 [WRN] Error while contacting exchange coingecko: A task was canceled.
2023-02-10 10:13:56.789 +00:00 [INF] BTC: 0 payments happened while offline
2023-02-10 10:13:56.790 +00:00 [INF] Connected to WebSocket of NBXplorer (BTC)
2023-02-10 10:13:56.991 +00:00 [INF] LTC: 0 payments happened while offline
2023-02-10 10:13:56.991 +00:00 [INF] Connected to WebSocket of NBXplorer (LTC)
2023-02-10 10:14:31.285 +00:00 [INF] XMR just became unavailable
2023-02-10 11:10:22.878 +00:00 [WRN] Error while contacting exchange binance_us: The operation was canceled.
```

### What browser do you use?

Chrome Version 109.0.5414.120 (Official Build) (64-bit)

### Additional information

Everything was working perfectly for last year. But first transactions after the yesterdays update reviled the problem. I have no idea  what's going on.

### Are you sure this is a bug report?

- [x] I confirm this is a bug report

**Comment by exznomak** [comment]
The previous scan completed and found 6 UTXOs in 07:01 (The total UTXO set size is 32267230)

But showing up in transaction ID's in LTC wallet page

**Comment by dennisreimann** [comment]
Can you check the logs of the NBXplorer and LTC containers?

**Comment by exznomak** [comment]
can you please tell me exact commands?

**Comment by petzsch** [comment]
I think this could be related to this LTC problem:
https://github.com/btcpayserver/btcpayserver/discussions/4626

Please check your litecoind logs (ad described in above's discussions answer by me)

**Comment by exznomak** [comment]
https://github.com/dgarage/NBXplorer/issues/403#issuecomment-1426688912

**Comment by dennisreimann** [comment]
> can you please tell me exact commands?

```bash
docker logs generated_nbxplorer_1
```

I don't know the name of the Litecoin container, but you can look it up using `docker ps` and then using the container name instead of `generated_nbxplorer_1`.

**Comment by exznomak** [comment]
i posted all logs to other topic

**Comment by petzsch** [comment]
logs where exported pre nbxplorer 2.3.62 update and before resycning the LTC blockchain.
If you are still seeing these issues despite all of this, we need to further investigate it.

But for this to happen we need recent logs of the current state.

Also I would ask you to continue this discussion on [Mattermost](https://chat.btcpayserver.org/btcpayserver/channels/support), where we have allready started looking at your issue.

**Comment by exznomak** [comment]
everything is fixed after ltc resync and nbxplorer patch
