### ISSUE TITLE
[Bug]: HTTP ERROR 500

### ISSUE THREAD

**Issue by jaonoctus** [btcpayserver/btcpayserver#4625]
### What is your BTCPay version?

v1.7.10+8c6fe91c7

### How did you deploy BTCPay Server?

Docker

### What happened?

Cannot access an app or create invoices

![image](https://user-images.githubusercontent.com/7918067/218268886-e9b1de66-4b13-4559-936e-c789c27a0305.png)

### How did you encounter this bug?

Access my store at `/apps/<APP_ID>/pos`

### Relevant log output

```shell
2023-02-11 16:14:12.998 +00:00 [ERR] Connection id "0HMOC99NEAGHJ", Request id "0HMOC99NEAGHJ:00000002": An unhandled exception was thrown by the application.
System.ArgumentException: An element with the key 'appId' already exists in the RouteValueDictionary. (Parameter 'key')
   at Microsoft.AspNetCore.Routing.RouteValueDictionary.Add(String key, Object value)
   at BTCPayServer.Filters.DomainMappingConstraintAttribute.Accept(ActionConstraintContext context) in /source/BTCPayServer/Filters/DomainMappingConstraintAttribute.cs:line 65
   at Microsoft.AspNetCore.Mvc.Routing.ActionConstraintMatcherPolicy.EvaluateActionConstraintsCore(HttpContext httpContext, CandidateSet candidateSet, IReadOnlyList`1 items, Nullable`1 startingOrder)
   at Microsoft.AspNetCore.Mvc.Routing.ActionConstraintMatcherPolicy.EvaluateActionConstraints(HttpContext httpContext, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Mvc.Routing.ActionConstraintMatcherPolicy.ApplyAsync(HttpContext httpContext, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 101
   at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 50
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 30
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### What browser do you use?

Chrome Version 110.0.5481.78 (Official Build) (64-bit)

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by petzsch** [comment]
This issue was addressed by @dennisreimann in this https://github.com/btcpayserver/btcpayserver/pull/4622

But apparently not released yet.
