### ISSUE TITLE
Unable to authorise woocommerce. 

### ISSUE THREAD

**Issue by Hodl-Solo** [btcpayserver/btcpayserver#4627]
<img width="1240" alt="Screenshot 2023-02-11 at 17 41 29" src="https://user-images.githubusercontent.com/53113533/218279680-7eac126e-9d5c-4354-a4bc-bdfa4c92908a.png">

<img width="502" alt="Screenshot 2023-02-11 at 17 52 40" src="https://user-images.githubusercontent.com/53113533/218280375-37c85680-9fc4-4a4e-bccc-7f01b366bb9a.png">

[Logs](https://pastebin.com/fpDKkjvx)

Using BTCPay 1.7.9

**Comment by petzsch** [comment]
try https://btcpay.thebitcoinshop.uk (with https:// not http://) as your BTCPAY URL in Woocommerce.

**Comment by Hodl-Solo** [comment]
that doesn't seem to work.

**Comment by petzsch** [comment]
what error are you getting now? Can't be the 301 anymore.

**Comment by Hodl-Solo** [comment]
I get these screens in this order.


<img width="813" alt="Screenshot 2023-02-12 at 14 42 31" src="https://user-images.githubusercontent.com/53113533/218317858-22f3da80-6633-414b-8aef-f74c17a58961.png">

<img width="813" alt="Screenshot 2023-02-12 at 14 42 31" src="https://user-images.githubusercontent.com/53113533/218317952-f896aad1-509f-4f07-b28a-e6e7150c7635.png">

<img width="799" alt="Screenshot 2023-02-12 at 14 43 14" src="https://user-images.githubusercontent.com/53113533/218317969-aea12b81-da63-4a58-bc57-4cce967663a7.png">

<img width="560" alt="Screenshot 2023-02-12 at 14 44 05" src="https://user-images.githubusercontent.com/53113533/218317974-7ec549de-a966-4749-ac02-28cf80948a02.png">

**Comment by michmh286** [comment]
Help

**Comment by petzsch** [comment]
I guess you could create the API key manually for the time being:

![grafik](https://user-images.githubusercontent.com/1374810/218318754-6d32e284-14aa-40c4-a03a-3e210b43902a.png)

Enter the API key you get after this screen, together with the store-id manually in woocommerce.

One of the devs will have to have a look at the stack trace you included to know whats wrong with the Woocommerce Authorization flow.

Thanks for reporting the bug.

**Comment by Kukks** [comment]
Can we get the server logs in BTCPay admin after the error occurred

**Comment by ndeet** [comment]
@Kukks the error happens after clicking on the "Authorize app" in BTCPay before redirecting back to the site. So nothing wrong with the plugin but something on BTCPay crashing. I successfully tested with 1.7.5 but got same error as op with 1.7.9. 

```
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMOD1PJOFTHA", Request id "0HMOD1PJOFTHA:00000002": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Controllers.UIManageController.AuthorizeAPIKey(AuthorizeApiKeysViewModel viewModel) in /source/BTCPayServer/Controllers/UIManageController.APIKeys.cs:line 167
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResourceFilter()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 100
   at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 30
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 29
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

```

**Comment by ndeet** [comment]
Seems after clicking on "authorize app" the internal request hits the BTCPay Server url in http instead of https. But maybe that's just a sideeffect of above error.

**Comment by Hodl-Solo** [comment]
I created a key manually as a workaround as you suggested, and it worked ok.

**Comment by Kukks** [comment]
Thank you, on it
