### ISSUE TITLE
[Bug]: Jade + Vault Error Cannot Fetch Pub Keys

### ISSUE THREAD

**Issue by webwworthy** [btcpayserver/btcpayserver#4692]
### What is your BTCPay version?

BTCPay Server v1.7.12

### How did you deploy BTCPay Server?

Lunanode

### What happened?

While setting up a new Jade hardware wallet with vault it returns an error trying to locate the pubkeys.

### How did you encounter this bug?

To recreate:
1. set up BTC Wallet
2.  connect hardware wallet
3.  running vault in background
4. Connect Jade, Device Connected
5.  Select Address type > confirm
6.  Error fetching pub keys

### Relevant log output

```shell
BTCPayServer.Hwi.HwiException
   at BTCPayServer.Hwi.HwiClient.SendCommandCoreAsync(DeviceSelector deviceSelector, IEnumerable1 options, Nullable1 command, String[] commandArguments, CancellationToken cancellationToken)
   at BTCPayServer.Hwi.HwiClient.SendCommandAsync(DeviceSelector deviceSelector, IEnumerable1 options, Nullable1 command, String[] commandArguments, CancellationToken cancel)
   at BTCPayServer.Hwi.HwiClient.SendCommandAsync(DeviceSelector deviceSelector, IEnumerable1 options, Nullable1 command, String[] commandArguments, CancellationToken cancel)
   at BTCPayServer.Hwi.HwiDeviceClient.GetXPubAsync(KeyPath keyPath, CancellationToken cancellationToken)
   at BTCPayServer.Controllers.UIVaultController.VaultBridgeConnection(String cryptoCode, WalletId walletId) in /source/BTCPayServer/Controllers/UIVaultController.cs:line 244
showError @ vaultbridge.ui.js?v=bIoKwI91oWShzOszeaEarBAHBNCwifEk5SpXCL9yBxw:117
needRetry @ vaultbridge.ui.js?v=bIoKwI91oWShzOszeaEarBAHBNCwifEk5SpXCL9yBxw:157
VaultBridgeUI.askForXPubs @ vaultbridge.ui.js?v=bIoKwI91oWShzOszeaEarBAHBNCwifEk5SpXCL9yBxw:254
```

### Additional information

![unexpectedError](https://user-images.githubusercontent.com/95507488/220723814-4c304de6-1224-4da5-939b-8e027c18f1b1.PNG)

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by webwworthy** [comment]
On a fresh Jade device it worked no problem @Bangalisch my apologies @pavlenex @NicolasDorier no need to look into this issue further
