### ISSUE TITLE
[Bug]: Error 500 when viewing Receipt Page of Zap Payments

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#4884]
### What is your BTCPay version?

v1.9.0+717f1610f 

### How did you deploy BTCPay Server?

Docker

### What happened?

I clicked on the Receipt Button in the backend for a Zap induced invoice. After seeing a blank page, I checked the browser console and saw that it was getting error code 500.

### How did you encounter this bug?

see above

### Relevant log output

```shell
2023-04-15 17:22:39.909 +00:00 [ERR] Connection id "0HMPS3JV4Q63K", Request id "0HMPS3JV4Q63K:00000002": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Payments.Lightning.LightningLikePaymentData.GetPaymentProof() in /source/BTCPayServer/Payments/Lightning/LightningLikePaymentData.cs:line 69
   at BTCPayServer.Controllers.UIInvoiceController.<>c__DisplayClass41_0.<InvoiceReceipt>b__0(PaymentEntity paymentEntity) in /source/BTCPayServer/Controllers/UIInvoiceController.UI.cs:line 230
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at BTCPayServer.Controllers.UIInvoiceController.InvoiceReceipt(String invoiceId) in /source/BTCPayServer/Controllers/UIInvoiceController.UI.cs:line 213
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 101
   at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 50
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 30
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### What browser do you use?

Firefox 112.0 (Win64)

### Additional information

none

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by petzsch** [comment]
Just noticed the payment was from 08.04.23, 07:40 (pre 1.9.0 update)
so that explains the missing payment proof... still the page should render for old invoices as well.

I also just tested a Lightning Adress payment with WoS and also the payment proof is empty and the receipt page is empty with error code 500. Not great.

**Comment by mjlamb** [comment]
Latest v1.9.0 still an issue

System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Payments.Lightning.LightningLikePaymentData.GetPaymentProof() in C:\CryptoStuff\BtcPayServer\BTCPayServer\Payments\Lightning\LightningLikePaymentData.cs:line 69

**Comment by mjlamb** [comment]
Than you good sir, TG said the same, have updated and can confirm it is working, Thanks Team !
