### ISSUE TITLE
Having issues with the bitpay-rest client

### ISSUE THREAD

**Issue by Preisschild** [btcpayserver/btcpayserver#490]
Pairing up works without issues, but when I use this example:
`./node_modules/bitpay-rest/bin/bitpay.js request -T pos -X post -R invoices -P '{"price": 1, "currency": "USD"}'
`
I get this: 
```
Error: Error: Server did not return JSON and gave statusCode 401
    at Request.handleResponse [as _callback] (/home/preisschild/PATH/node_modules/bitpay-rest/lib/rest-client.js:210:23)
    at Request.self.callback (/home/preisschild/PATH/node_modules/bitpay-rest/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/home/preisschild/PATH/node_modules/bitpay-rest/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/home/preisschild/PATH/node_modules/bitpay-rest/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

```

BTCPayserver is running behind my own nginx reverse proxy with https.

**Comment by Preisschild** [comment]
bitpay-rest is the official client from bitpay. I thought bitpay is compatible?

**Comment by Preisschild** [comment]
Or is there some setting I forgot in bitpay-rest? I did keygen and pair.

**Comment by NicolasDorier** [comment]
@Preisschild that is good point.
So here is the thing: On Bitpay the Invoice route is not protected.

However, we found out some people were putting some confidential information in there which could be used by a malicious buyer to fake payments. (depending on how they implemented)

So we added authentication on this route.

Can you move to https://github.com/btcpayserver/node-btcpay ?

If not, I can fork bitpay-rest and add signed requests to this route.

I can probably also make a compatibility mode, but since this is dangerous I prefer not doing this.

What would be the best for you?

**Comment by Preisschild** [comment]
Switched to btcpayserver/node-btcpay and it works. Thanks.
Just a quick question: what do you add in the client.create_invoice to have btcpay not ask for refund email? Also can I use something to make BTCLightning the default and not BTC? 
I've tested refundEmail and email and for the cryptocurrency I tested transactionCurrency = 'BTC_LightningLike' but it's not working.

**Comment by NicolasDorier** [comment]
try `buyer.email`

**Comment by NicolasDorier** [comment]
Closing this as solved
