### ISSUE TITLE
Error scanning Print Only POS Scan QR code since v1.9.1 upgrade.

### ISSUE THREAD

**Issue by mjlamb** [btcpayserver/btcpayserver#4904]
### What is your BTCPay version?

BTCPay Server v1.9.1

### How did you deploy BTCPay Server?

Manual deploy

### What happened?

When using Print only option in POS app, scanning the QR causes error in WoZ and Zeus apps.

### How did you encounter this bug?

Choose "Print Display" option in POS app, SAVE and then VIEW, try scan QR code presented.

### What browser do you use?

Brave

### Additional information

Error regarding decoding QR code.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by mjlamb** [comment]
![image](https://user-images.githubusercontent.com/2274034/233782328-bbeb8542-6a4e-417a-bb6a-864828e233d2.png)

**Comment by mjlamb** [comment]
Is there a work around for this issue, a bit stuck at moment.

**Comment by mjlamb** [comment]
Here is the exception being thrown. 
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMPVS8EME3EM", Request id "0HMPVS8EME3EM:00000003": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.UILNURLController.CreateLNUrlRequestFromInvoice(String cryptoCode, InvoiceEntity i, StoreData store, StoreBlob blob, LNURLPayRequest lnurlRequest, Dictionary`2 lnUrlMetadata, Boolean allowOverpay) in \BtcPayServer\BTCPayServer\Controllers\UILNURLController.cs:line 521
   at BTCPayServer.UILNURLController.GetLNURLRequest(String cryptoCode, StoreData store, StoreBlob blob, CreateInvoiceRequest createInvoice, LNURLPayRequest lnurlRequest, Dictionary`2 lnUrlMetadata, List`1 additionalTags, Boolean allowOverpay) in \BtcPayServer\BTCPayServer\Controllers\UILNURLController.cs:line 453
   at BTCPayServer.UILNURLController.GetLNURLForApp(String cryptoCode, String appId, String itemCode) in \BtcPayServer\BTCPayServer\Controllers\UILNURLController.cs:line 318
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.

**Comment by mjlamb** [comment]
Still not working team.

I checkout latest commit = 47f5d97eaf577ff88979164c929db90a04c24324

And same decoding issues.

**Comment by mjlamb** [comment]
Team is it possible to get a static lightning invoice for this product from the store, via the Api, i need a workaround for now ?
Any ideas?

**Comment by mjlamb** [comment]
Also to note the exception must be being suppressed as I'm not seeing it in the run screen anymore. I have a manual setup FYI.

**Comment by mjlamb** [comment]
![image](https://user-images.githubusercontent.com/2274034/234137795-737c9365-e8a4-4167-be79-fd17e0f12653.png)

If I have these 3 switches turned on it works, if any of the last 2 highlighted ones are off, the decode QR fails as above.

**Comment by dennisreimann** [comment]
Yup, the final fix is part of #4911 – thanks for the feedback and testing! 💚

**Comment by Kukks** [comment]
![image](https://user-images.githubusercontent.com/1818366/234264505-3436b306-e90b-4d19-b925-51b9df464cf5.png)

![image](https://user-images.githubusercontent.com/1818366/234264554-3c5c187a-f1ee-4111-ac67-dd57c69e357a.png)


the difference is too big for now

**Comment by mjlamb** [comment]
Running v1.9.2 I still have this issue scanning these codes, as above image.
If I have these 3 switches turned on it works, if any of the last 2 highlighted ones are off, the decode QR fails as above.

**Comment by dennisreimann** [comment]
@mjlamb I just tried and for me it works, but " LNURL Classic Mode" needs to be on. See the compatibility list that kukks posted above.
