### ISSUE TITLE
[Bug]: Clicking on "Return to {App Name}" returns "No Connection with that ID"

### ISSUE THREAD

**Issue by Liongrass** [btcpayserver/btcpayserver#4930]
### What is your BTCPay version?

BTCPay Server v1.9.2+6193835ea 

### How did you deploy BTCPay Server?

On Lunanode using the Lunanode installer

### What happened?

I have a crowdfund set up [for example this one](https://we.encrypt.cash/apps/1Chngwii4XMnueujJpWk78fMe75/crowdfund).

I can successfully generate invoices and pay them, but upon clicking on "Return to {App Name}", I'm directed to a page with the URL `https://we.encrypt.cash/apps/hub?id=av_oczbja99i2mXl2iuDlw`, which displays the error `No Connection with that ID`.

### How did you encounter this bug?

1. Generate invoice
2. Pay invoice
3. Click on "Return to {App Name}

### Relevant log output

```shell
info: PayServer:      BTC (Lightning): Payment detected via notification (3kJSeZU5YUaqxmSpfoSQBz)
fail: Microsoft.AspNetCore.SignalR.HubConnectionContext: Failed writing message. Aborting connection.
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Data.StoreDataExtensions.GetStoreBlob(StoreData storeData) in /source/BTCPayServer/Data/StoreDataExtensions.cs:line 85
   at BTCPayServer.Plugins.Crowdfund.CrowdfundAppType.GetInfo(AppData appData) in /source/BTCPayServer/Plugins/Crowdfund/CrowdfundPlugin.cs:line 192
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteUsingSerializer[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize(Utf8JsonWriter writer, Object value, Type inputType, JsonSerializerOptions options)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteArguments(Object[] arguments, Utf8JsonWriter writer)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteInvocationMessage(InvocationMessage message, Utf8JsonWriter writer)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteMessageCore(HubMessage message, IBufferWriter`1 stream)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteMessage(HubMessage message, IBufferWriter`1 output)
   at Microsoft.AspNetCore.SignalR.Protocol.HubProtocolExtensions.GetMessageBytes(IHubProtocol hubProtocol, HubMessage message)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.GetMessageBytes(HubMessage message)
   at Microsoft.AspNetCore.SignalR.SerializedHubMessage.GetSerializedMessage(IHubProtocol protocol)
   at Microsoft.AspNetCore.SignalR.HubConnectionContext.WriteCore(SerializedHubMessage message, CancellationToken cancellationToken)
```
```


### What browser do you use?

_No response_

### Additional information

_No response_

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by Bas02** [comment]
Hey thanks for filing bug! 

Did you perhaps set the root domain of your BTCPayServer to this specific crowdfund app? 
I've noticed similar behaviour in this set up :)

**Comment by dennisreimann** [comment]
This looks like a case in which the return URL doesn't get generated correctly and the web socket endpoint is used instead of the app URL.

**Comment by Liongrass** [comment]
Hi! Thank you for taking a look. The crowdfund app is not running on the root domain or on an external domain. The URL is like this: https://we.encrypt.cash/apps/1Chngwii4XMnueujJpWk78fMe75/crowdfund

**Comment by dennisreimann** [comment]
I can confirm that this is easily reproducible without the domain mapping feature. More info in the fix PR.
