### ISSUE TITLE
[Bug]: Prism plugin - tons of errors and load average

### ISSUE THREAD

**Issue by Perlover** [btcpayserver/btcpayserver#4981]
### What is your BTCPay version?

v1.9.3+781190a65

### How did you deploy BTCPay Server?

LunaNode Docker template

### What happened?

I've been experimenting with the Prism plugin for a while. I tried splitting payments and it partially worked. But I do not know what broke down there. But while I have it installed, errors are constantly falling out of it, which leads to constant server loading and unstable operation (to get into the admin panel, I had to restart the container `docker restart generated_btcpayserver_1`). I also use the LNBank plugin, maybe the error occurs when they work together. All plugins are fresh versions in present time.

### How did you encounter this bug?

I don't know exactly steps.

### Relevant log output

```shell
at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at BTCPayServer.Lightning.LNbank.LNbankClient.Send[TRequest,TResponse](HttpMethod method, String path, TRequest payload, CancellationToken cancellation)
   at BTCPayServer.Lightning.LNbank.LNbankClient.Get[TResponse](String path, CancellationToken cancellation)
   at BTCPayServer.Lightning.LNbank.LNbankClient.GetPayment(String paymentHash, CancellationToken cancellation)
   at BTCPayServer.Lightning.LNbank.LNbankLightningClient.GetPayment(String paymentHash, CancellationToken cancellation)
   at BTCPayServer.Plugins.Prism.SatBreaker.CheckPayouts(CancellationToken cancellationToken) in /build/Plugins/BTCPayServer.Plugins.Prism/SatBreaker.cs:line 142
fail: BTCPayServer.Plugins.Prism.SatBreaker: Error while checking payouts
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Plugins.Prism.SatBreaker.CheckPayouts(CancellationToken cancellationToken) in /build/Plugins/BTCPayServer.Plugins.Prism/SatBreaker.cs:line 142
fail: BTCPayServer.Plugins.Prism.SatBreaker: Error while checking payouts
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Plugins.Prism.SatBreaker.CheckPayouts(CancellationToken cancellationToken) in /build/Plugins/BTCPayServer.Plugins.Prism/SatBreaker.cs:line 142
fail: BTCPayServer.Plugins.Prism.SatBreaker: Error while checking payouts
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Plugins.Prism.SatBreaker.CheckPayouts(CancellationToken cancellationToken) in /build/Plugins/BTCPayServer.Plugins.Prism/SatBreaker.cs:line 142
fail: BTCPayServer.Plugins.Prism.SatBreaker: Error while checking payouts
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Plugins.Prism.SatBreaker.CheckPayouts(CancellationToken cancellationToken) in /build/Plugins/BTCPayServer.Plugins.Prism/SatBreaker.cs:line 142
fail: BTCPayServer.Plugins.Prism.SatBreaker: Error while checking payouts
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Plugins.Prism.SatBreaker.CheckPayouts(CancellationToken cancellationToken) in /build/Plugins/BTCPayServer.Plugins.Prism/SatBreaker.cs:line 142
fail: BTCPayServer.Plugins.Prism.SatBreaker: Error while checking payouts
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Plugins.Prism.SatBreaker.CheckPayouts(CancellationToken cancellationToken) in /build/Plugins/BTCPayServer.Plugins.Prism/SatBreaker.cs:line 142
fail: BTCPayServer.Plugins.Prism.SatBreaker: Error while checking payouts
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Plugins.Prism.SatBreaker.CheckPayouts(CancellationToken cancellationToken) in /build/Plugins/BTCPayServer.Plugins.Prism/SatBreaker.cs:line 142
fail: BTCPayServer.Plugins.Prism.SatBreaker: Error while checking payouts
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Plugins.Prism.SatBreaker.CheckPayouts(CancellationToken cancellationToken) in /build/Plugins/BTCPayServer.Plugins.Prism/SatBreaker.cs:line 142
fail: BTCPayServer.Plugins.Prism.SatBreaker: Error while checking payouts
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Plugins.Prism.SatBreaker.CheckPayouts(CancellationToken cancellationToken) in /build/Plugins/BTCPayServer.Plugins.Prism/SatBreaker.cs:line 142
fail: BTCPayServer.Plugins.Prism.SatBreaker: Error while checking payouts
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Plugins.Prism.SatBreaker.CheckPayouts(CancellationToken cancellationToken) in /build/Plugins/BTCPayServer.Plugins.Prism/SatBreaker.cs:line 142
fail: BTCPayServer.Plugins.Prism.SatBreaker: Error while checking payouts
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Plugins.Prism.SatBreaker.CheckPayouts(CancellationToken cancellationToken) in /build/Plugins/BTCPayServer.Plugins.Prism/SatBreaker.cs:line 142
fail: BTCPayServer.Plugins.Prism.SatBreaker: Error while checking payouts
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Plugins.Prism.SatBreaker.CheckPayouts(CancellationToken cancellationToken) in /build/Plugins/BTCPayServer.Plugins.Prism/SatBreaker.cs:line 142
fail: BTCPayServer.Plugins.Prism.SatBreaker: Error while checking payouts
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Plugins.Prism.SatBreaker.CheckPayouts(CancellationToken cancellationToken) in /build/Plugins/BTCPayServer.Plugins.Prism/SatBreaker.cs:line 142
fail: BTCPayServer.Plugins.Prism.SatBreaker: Error while checking payouts
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Plugins.Prism.SatBreaker.CheckPayouts(CancellationToken cancellationToken) in /build/Plugins/BTCPayServer.Plugins.Prism/SatBreaker.cs:line 142
fail: BTCPayServer.Plugins.Prism.SatBreaker: Error while checking payouts
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Plugins.Prism.SatBreaker.CheckPayouts(CancellationToken cancellationToken) in /build/Plugins/BTCPayServer.Plugins.Prism/SatBreaker.cs:line 142
fail: BTCPayServer.Plugins.Prism.SatBreaker: Error while checking payouts
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Plugins.Prism.SatBreaker.CheckPayouts(CancellationToken cancellationToken) in /build/Plugins/BTCPayServer.Plugins.Prism/SatBreaker.cs:line 142
fail: BTCPayServer.Plugins.Prism.SatBreaker: Error while checking payouts
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Plugins.Prism.SatBreaker.CheckPayouts(CancellationToken cancellationToken) in /build/Plugins/BTCPayServer.Plugins.Prism/SatBreaker.cs:line 142
fail: BTCPayServer.Plugins.Prism.SatBreaker: Error while checking payouts
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Plugins.Prism.SatBreaker.CheckPayouts(CancellationToken cancellationToken) in /build/Plugins/BTCPayServer.Plugins.Prism/SatBreaker.cs:line 142
fail: BTCPayServer.Plugins.Prism.SatBreaker: Error while checking payouts
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Plugins.Prism.SatBreaker.CheckPayouts(CancellationToken cancellationToken) in /build/Plugins/BTCPayServer.Plugins.Prism/SatBreaker.cs:line 142
fail: BTCPayServer.Plugins.Prism.SatBreaker: Error while checking payouts
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Plugins.Prism.SatBreaker.CheckPayouts(CancellationToken cancellationToken) in /build/Plugins/BTCPayServer.Plugins.Prism/SatBreaker.cs:line 142
fail: BTCPayServer.Plugins.Prism.SatBreaker: Error while checking payouts
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Plugins.Prism.SatBreaker.CheckPayouts(CancellationToken cancellationToken) in /build/Plugins/BTCPayServer.Plugins.Prism/SatBreaker.cs:line 142
fail: BTCPayServer.Plugins.Prism.SatBreaker: Error while checking payouts
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Plugins.Prism.SatBreaker.CheckPayouts(CancellationToken cancellationToken) in /build/Plugins/BTCPayServer.Plugins.Prism/SatBreaker.cs:line 142
fail: BTCPayServer.Plugins.Prism.SatBreaker: Error while checking payouts
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Plugins.Prism.SatBreaker.CheckPayouts(CancellationToken cancellationToken) in /build/Plugins/BTCPayServer.Plugins.Prism/SatBreaker.cs:line 142
fail: BTCPayServer.Plugins.Prism.SatBreaker: Error while checking payouts
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Plugins.Prism.SatBreaker.CheckPayouts(CancellationToken cancellationToken) in /build/Plugins/BTCPayServer.Plugins.Prism/SatBreaker.cs:line 142
fail: BTCPayServer.Plugins.Prism.SatBreaker: Error while checking payouts
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Plugins.Prism.SatBreaker.CheckPayouts(CancellationToken cancellationToken) in /build/Plugins/BTCPayServer.Plugins.Prism/SatBreaker.cs:line 142
fail: BTCPayServer.Plugins.Prism.SatBreaker: Error while checking payouts
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
```

### What browser do you use?

Not important

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by Kukks** [comment]
Building a new version that potentially fixes this @perlover. Try it out,
and let me know if it works.

**Comment by Perlover** [comment]
I installed v1.0.8
Now I just see a following errors from Prism:

```
fail: BTCPayServer.Plugins.Prism.SatBreaker: Error while checking payouts
System.InvalidOperationException: Nullable object must have a value.
   at BTCPayServer.Plugins.Prism.SatBreaker.CheckPayouts(CancellationToken cancellationToken)
fail: BTCPayServer.Plugins.Prism.SatBreaker: Error while checking payouts
System.InvalidOperationException: Nullable object must have a value.
   at BTCPayServer.Plugins.Prism.SatBreaker.CheckPayouts(CancellationToken cancellationToken)

```

Is it OK? I don't see now a high load average at server

**Comment by Perlover** [comment]
And a following logs after:

```
fail: BTCPayServer.Plugins.Prism.SatBreaker: Error while checking payouts
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at BTCPayServer.Lightning.LNbank.LNbankClient.Send[TRequest,TResponse](HttpMethod method, String path, TRequest payload, CancellationToken cancellation)
   at BTCPayServer.Lightning.LNbank.LNbankClient.Get[TResponse](String path, CancellationToken cancellation)
   at BTCPayServer.Lightning.LNbank.LNbankClient.GetPayment(String paymentHash, CancellationToken cancellation)
   at BTCPayServer.Lightning.LNbank.LNbankLightningClient.GetPayment(String paymentHash, CancellationToken cancellation)
   at BTCPayServer.Plugins.Prism.SatBreaker.CheckPayouts(CancellationToken cancellationToken) in /build/Plugins/BTCPayServer.Plugins.Prism/SatBreaker.cs:line 142
fail: BTCPayServer.Plugins.Prism.SatBreaker: Error while checking payouts
System.InvalidOperationException: Nullable object must have a value.
   at BTCPayServer.Plugins.Prism.SatBreaker.CheckPayouts(CancellationToken cancellationToken)
fail: BTCPayServer.Plugins.Prism.SatBreaker: Error while checking payouts
System.InvalidOperationException: Nullable object must have a value.
   at BTCPayServer.Plugins.Prism.SatBreaker.CheckPayouts(CancellationToken cancellationToken)
```

**Comment by Kukks** [comment]
> Now I have uninstalled the plugin again and the CPU consumption does not exceed 1.5% of one core. All the errors are gone. Apparently, there are still some bugs in the plugin.
> 
> ```
> info: Configuration:  Data Directory: /datadir
> info: Configuration:  Configuration File: /datadir/Main/settings.config
> info: BTCPayServer.Plugins.PluginManager: Loading plugins from /root/.btcpayserver/Plugins
> info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer - 1.9.3
> info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Shopify - 1.9.3
> info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.PointOfSale - 1.9.3
> info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.PayButton - 1.9.3
> info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.NFC - 1.9.3
> info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Crowdfund - 1.9.3
> info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.BitcoinWhitepaper - 1.0.2
> info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.LNbank - 1.5.0
> info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.NIP05 - 1.0.13
> info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.LNDhubApi - 1.0.1
> info: Configuration:  Supported chains: BTC
> info: Configuration:  BTC: Explorer url is http://nbxplorer:32838/
> info: Configuration:  BTC: Cookie file is /root/.nbxplorer/Main/.cookie
> info: Configuration:  Network: Mainnet
> info: Configuration:  LogFile: /datadir/btcpay.log
> info: Configuration:  Log Level: Debug
> info: Configuration:  Root Path: /
> info: Configuration:  Connection to NBXplorer's database successful, dashboard and reporting features activated.
> info: Configuration:  SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
> info: PayServer:      Checking if any payment arrived on lightning while the server was offline...
> info: PayServer:      Processing lightning payments...
> info: PayServer:      Starting listening NBXplorer (BTC)
> info: PayServer:      Start watching invoices
> info: PayServer:      Starting payment request expiration watcher
> info: PayServer:      1 pending payment requests being checked since last run
> info: Configuration:  SSH connection succeeded
> info: PayServer:      BTC: Checking if any pending invoice got paid while offline...
> info: PayServer:      BTC: 0 payments happened while offline
> info: PayServer:      Connected to WebSocket of NBXplorer (BTC)
> info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Starting
> info: Configuration:  Now listening on: http://0.0.0.0:49392
> 
> NO ERRORS HERE...
> ```

Can you try another update please?
