### ISSUE TITLE
[Bug]: Do not throw error 500 if the transaction list of wallet is timing out

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#4987]
### What is your BTCPay version?

1.9.3

### How did you deploy BTCPay Server?

docker

### What happened?

A big wallet timeout on the wallet page.

### How did you encounter this bug?

Have a big wallet, then go to the transaction list of the wallet, see an error 500

We should have a proper fallback in this situation. There are some pattern of wallet that may timeout like this, it is caused because we do not paginate based on the date.

Another idea would just to ajaxify the page. @dennisreimann do you think we can put that in next release?

### Relevant log output

```shell
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMQG63U0LBDI", Request id "0HMQG63U0LBDI:00000002": An unhandled exception was thrown by the application.
Npgsql.NpgsqlException (0x80004005): Exception while reading from stream
 ---> System.TimeoutException: Timeout during reading attempt
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|215_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.<ReadMessage>g__ReadMessageSequential|44_0(NpgsqlConnector connector, Boolean async)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 418
   at BTCPayServer.Services.Wallets.BTCPayWallet.FetchTransactionHistory(DerivationStrategyBase derivationStrategyBase, Nullable`1 skip, Nullable`1 count, Nullable`1 interval) in /source/BTCPayServer/Services/Wallets/BTCPayWallet.cs:line 246
```

### Workaround

1. Sweep your wallet by browsing directly to `https://yourserver/wallets/<walletid>/send`
2. Create a new emtpy wallet by browsing `https://yourserver/stores/<storeid>/onchain/BTC/settings`

**Comment by Billiej88** [comment]
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMQG63U0LBDI", Request id "0HMQG63U0LBDI:00000002": An unhandled exception was thrown by the application.
Npgsql.NpgsqlException (0x80004005): Exception while reading from stream
 ---> System.TimeoutException: Timeout during reading attempt
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|215_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.<ReadMessage>g__ReadMessageSequential|44_0(NpgsqlConnector connector, Boolean async)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 418
   at BTCPayServer.Services.Wallets.BTCPayWallet.FetchTransactionHistory(DerivationStrategyBase derivationStrategyBase, Nullable`1 skip, Nullable`1 count, Nullable`1 interval) in /source/BTCPayServer/Services/Wallets/BTCPayWallet.cs:line 246
