### ISSUE TITLE
[Bug]: Page "Pay button" is empty after upgrade

### ISSUE THREAD

**Issue by RadekSip** [btcpayserver/btcpayserver#5038]
### What is your BTCPay version?

version 1.10.1 (upgrade from 1.9.3)

### How did you deploy BTCPay Server?

Docker, Ubuntu, ARM64

### What happened?

After upgrade from 1.9.3 to 1.10.1, the page with settings for "Pay button" is empty.

### How did you encounter this bug?

Steps to reproduce:
1. enable Store Settings -> General –> "Allow anyone to create invoice"
2. go to "Pay button" settings (path https://<yourserver>/stores/<yourstore>/paybutton )
3. page is empty, error log attached

When "Allow anyone to create invoice" is disabled, the page shows correctly warning and "Enable" button.
After click to "Enable", page is empty.

### Relevant log output

```shell
2023-06-03 15:22:16.082 +00:00 [ERR] Connection id "xxx", Request id "xxx:yyy": An unhandled exception was thrown by the application.
Newtonsoft.Json.JsonSerializationException: Self referencing loop detected for property 'storeData' with type 'BTCPayServer.Data.StoreData'. Path 'apps[0].app.storeData.userStores[0]'.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Microsoft.AspNetCore.Mvc.NewtonsoftJson.NewtonsoftJsonHelper.Serialize(Object value, JsonSerializer jsonSerializer)
   at BTCPayServer.Abstractions.Services.Safe.Json(Object model) in /source/BTCPayServer.Abstractions/Services/Safe.cs:line 27
   at BTCPayServer.Plugins.PayButton.Views.Views_Shared_PayButton_PayButton.<ExecuteAsync>b__48_24() in /source/BTCPayServer/Views/Shared/PayButton/PayButton.cshtml:line 119
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
   at BTCPayServer.Plugins.PayButton.Views.Views_Shared_PayButton_PayButton.<ExecuteAsync>b__48_1() in /source/BTCPayServer/Views/Shared/PayButton/PayButton.cshtml:line 17
   at Microsoft.AspNetCore.Mvc.Razor.RazorPage.RenderSectionAsyncCore(String sectionName, Boolean required)
   at AspNetCoreGeneratedDocument.Views_Shared__Layout.<>c__DisplayClass19_0.<<ExecuteAsync>b__1>d.MoveNext() in /source/BTCPayServer/Views/Shared/_Layout.cshtml:line 78
```

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
Thanks for reporting!
