### ISSUE TITLE
[Bug]: LTC/DOGE got response (500)

### ISSUE THREAD

**Issue by hell0-w** [btcpayserver/btcpayserver#5050]
### What is your BTCPay version?

BTCPay Server v1.10.1+c0bc19ea5 (Altcoins) 

### How did you deploy BTCPay Server?

[docker](https://install.btcpayserver.org/)

### What happened?

cannot send payment got response (500)
Same Error on DOGE and LTC

### How did you encounter this bug?

1. After update server cannot send payment.

![image](https://github.com/btcpayserver/btcpayserver/assets/17591751/7a845105-4012-420c-baf5-2b5068d2637e)

### Relevant log output

```shell
btcpayserver_1                       | 2023-06-06T13:21:24.209385526Z fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMR6I3LN2CK3", Request id "0HMR6I3LN2CK3:00000002": An unhandled exception was thrown by the application.
btcpayserver_1                       | 2023-06-06T13:21:24.209458768Z System.ArgumentNullException: Value cannot be null. (Parameter 'uri')
btcpayserver_1                       | 2023-06-06T13:21:24.209473892Z    at NBitcoin.Payment.BitcoinUrlBuilder..ctor(String uri, Network network)
btcpayserver_1                       | 2023-06-06T13:21:24.209486330Z    at BTCPayServer.Controllers.Greenfield.GreenfieldStoreOnChainWalletsController.CreateOnChainTransaction(String storeId, String cryptoCode, CreateOnChainTransactionRequest request) in /source/BTCPayServer/Controllers/GreenField/GreenfieldStoreOnChainWalletsController.cs:line 425
btcpayserver_1                       | 2023-06-06T13:21:24.209497803Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
btcpayserver_1                       | 2023-06-06T13:21:24.209508809Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
btcpayserver_1                       | 2023-06-06T13:21:24.209520414Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
btcpayserver_1                       | 2023-06-06T13:21:24.209531667Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
btcpayserver_1                       | 2023-06-06T13:21:24.209542643Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
btcpayserver_1                       | 2023-06-06T13:21:24.209553813Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
btcpayserver_1                       | 2023-06-06T13:21:24.209581857Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
btcpayserver_1                       | 2023-06-06T13:21:24.209591618Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
btcpayserver_1                       | 2023-06-06T13:21:24.209602449Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
btcpayserver_1                       | 2023-06-06T13:21:24.209611832Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
btcpayserver_1                       | 2023-06-06T13:21:24.209621131Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
btcpayserver_1                       | 2023-06-06T13:21:24.209630014Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
btcpayserver_1                       | 2023-06-06T13:21:24.209639103Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
btcpayserver_1                       | 2023-06-06T13:21:24.209648307Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
btcpayserver_1                       | 2023-06-06T13:21:24.209657707Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
btcpayserver_1                       | 2023-06-06T13:21:24.209666722Z    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
btcpayserver_1                       | 2023-06-06T13:21:24.209675716Z    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
btcpayserver_1                       | 2023-06-06T13:21:24.209684439Z    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
btcpayserver_1                       | 2023-06-06T13:21:24.209693342Z    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
btcpayserver_1                       | 2023-06-06T13:21:24.209702443Z    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
btcpayserver_1                       | 2023-06-06T13:21:24.209711233Z    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
btcpayserver_1                       | 2023-06-06T13:21:24.209719920Z    at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 97
btcpayserver_1                       | 2023-06-06T13:21:24.209728775Z    at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 30
btcpayserver_1                       | 2023-06-06T13:21:24.209738141Z    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
btcpayserver_1                       | 2023-06-06T13:21:24.209747152Z    at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 29
btcpayserver_1                       | 2023-06-06T13:21:24.209756299Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
nginx                                | 2023-06-06T13:21:24.221732254Z ltc.acp-master.dedyn.io 213.252.246.6 - - [06/Jun/2023:13:21:24 +0000] "POST /api/v1/stores/DyCTC3bxGgKRAoiNz4BSjgBJBtQ2CRKwGV9uAG3ZfA6j/payment-methods/OnChain/LTC/wallet/transactions HTTP/2.0" 500 0 "-" "-"
btcpayserver_litecoind               | 2023-06-06T13:21:25.606411696Z 2023-06-06T13:21:25Z New outbound peer connected: version: 70016, blocks=2486965, peer=8 (full-relay)
```

### What browser do you use?

Chrome, FF

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by hell0-w** [comment]
Miss configuration on my side.
