### ISSUE TITLE
[Bug]: Invoice generation fails with invoice value in thousands

### ISSUE THREAD

**Issue by jansila** [btcpayserver/btcpayserver#5056]
### What is your BTCPay version?

I'm running BTCPay `1.10.1` and we run a store in CZK. We just found out that charging amounts > 999czk, we get error
```
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMR89Q44MF28", Request id "0HMR89Q44MF28:00000002": An unhandled exception was thrown by the application.
Newtonsoft.Json.JsonReaderException: Could not convert string to decimal: 1 500,00. Path 'subTotal', line 1, position 22.
```

It seems to only happened on mobile phones and tablets, works ok on a pc.
I am pasting the full log and docker versions of all of the services below

```CONTAINER ID   IMAGE                                                   COMMAND                  CREATED         STATUS          PORTS                                                                                    NAMES
c3b1a3b6be15   btcpayserver/letsencrypt-nginx-proxy-companion:1.12.2   "/bin/bash /app/entr…"   4 days ago      Up 13 minutes                                                                                            letsencrypt-nginx-proxy-companion
9ea54df442a8   btcpayserver/docker-gen:0.7.8                           "/usr/local/bin/dock…"   4 days ago      Up 13 minutes                                                                                            nginx-gen
9f0440f22578   btcpayserver/btcpayserver:1.10.1                        "/app/docker-entrypo…"   4 days ago      Up 13 minutes   49392/tcp                                                                                generated_btcpayserver_1
f66b82ce646a   nicolasdorier/nbxplorer:2.3.64                          "dotnet NBXplorer.dll"   4 days ago      Up 13 minutes   32838/tcp                                                                                generated_nbxplorer_1
93e0705b188c   nginx:1.23.3                                            "/docker-entrypoint.…"   4 days ago      Up 13 minutes   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp                                                 nginx
d757fe657107   shahanafarooqui/rtl:0.13.3                              "/sbin/tini -g -- no…"   4 days ago      Up 13 minutes   3000/tcp                                                                                 generated_bitcoin_rtl_1
dd383257d5af   btcpayserver/lnd:v0.16.2-beta                           "/sbin/tini -g -- /d…"   4 days ago      Up 13 minutes   8080-8081/tcp, 0.0.0.0:9735->9735/tcp                                                    btcpayserver_lnd_bitcoin
21fbad8c886d   btcpayserver/bitcoin:25.0                               "/entrypoint.sh bitc…"   4 days ago      Up 13 minutes   8332-8333/tcp, 18332-18333/tcp, 18443-18444/tcp, 28332-28334/tcp, 39388/tcp, 43782/tcp   btcpayserver_bitcoind
61d4b058a8ac   btcpayserver/postgres:13.10                             "/migrate-docker-ent…"   4 days ago      Up 13 minutes   5432/tcp                                                                                 generated_postgres_1
6cf01143025a   btcpayserver/docker-gen:0.7.8                           "/usr/local/bin/dock…"   7 months ago    Up 13 minutes                                                                                            tor-gen
1bec3531eeb9   btcpayserver/tor:0.4.7.10                               "./entrypoint.sh tor"    7 months ago    Up 13 minutes   9050-9051/tcp                                                                            tor
6c3c91c574e8   registry.gitlab.com/jansila/pivoklub-cloud-db:0.0.1     "docker-entrypoint.s…"   20 months ago   Up 7 months     0.0.0.0:8001->5432/tcp                                                                   pkb_pgdb-dev_1
1b4412704a92   registry.gitlab.com/jansila/pivoklub-cloud-db:0.0.1     "docker-entrypoint.s…"   20 months ago   Up 7 months     0.0.0.0:8002->5432/tcp                                                                   pkb_pgdb-prod_1
```

### How did you deploy BTCPay Server?

VPS with Docker

### What happened?

We get error response from the server immediately.

### How did you encounter this bug?

Just trying to generate the invoice

### Relevant log output

```shell
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMR89Q44MF28", Request id "0HMR89Q44MF28:00000002": An unhandled exception was thrown by the application.
Newtonsoft.Json.JsonReaderException: Could not convert string to decimal: 1 500,00. Path 'subTotal', line 1, position 22.
   at Newtonsoft.Json.JsonReader.ReadDecimalString(String s)
   at Newtonsoft.Json.JsonReader.ReadAsDecimal()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at BTCPayServer.Plugins.PointOfSale.Controllers.UIPointOfSaleController.<>c__DisplayClass10_0.<ViewPointOfSale>b__5(InvoiceEntity entity) in /source/BTCPayServer/Plugins/PointOfSale/Controllers/UIPointOfSaleController.cs:line 317
   at BTCPayServer.Controllers.UIInvoiceController.CreateInvoiceCoreRaw(InvoiceEntity entity, StoreData store, IPaymentFilter invoicePaymentMethodFilter, String[] additionalSearchTerms, CancellationToken cancellationToken, Action`1 entityManipulator) in /source/BTCPayServer/Controllers/UIInvoiceController.cs:line 391
   at BTCPayServer.Controllers.UIInvoiceController.CreateInvoiceCoreRaw(BitpayCreateInvoiceRequest invoice, StoreData store, String serverUrl, List`1 additionalTags, CancellationToken cancellationToken, Action`1 entityManipulator) in /source/BTCPayServer/Controllers/UIInvoiceController.cs:line 191
   at BTCPayServer.Controllers.UIInvoiceController.CreateInvoiceCore(BitpayCreateInvoiceRequest invoice, StoreData store, String serverUrl, List`1 additionalTags, CancellationToken cancellationToken, Action`1 entityManipulator) in /source/BTCPayServer/Controllers/UIInvoiceController.cs:line 115
   at BTCPayServer.Plugins.PointOfSale.Controllers.UIPointOfSaleController.ViewPointOfSale(String appId, Nullable`1 viewType, Nullable`1 amount, String email, String orderId, String notificationUrl, String redirectUrl, String choiceKey, String posData, String formResponse, RequiresRefundEmail requiresRefundEmail, CancellationToken cancellationToken) in /source/BTCPayServer/Plugins/PointOfSale/Controllers/UIPointOfSaleController.cs:line 283
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 98
   at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 50
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 30
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
> It seems to only happened on mobile phones and tablets, works ok on a pc.

Can you specify which OS and browser this happens with? 

Also, is this in a specific context (e.g. POS or Crowdfund) or does it also happen for raw invoice creation?

It does not seem to be a general problem.

**Comment by dennisreimann** [comment]
Can reproduce this with the POS app and with european number format. The problem is the decimal separator — `1.234,56` vs. `1,234.56`. We'll fix this.

**Comment by Brooksie18** [comment]
Thank you so much😃
