### ISSUE TITLE
[Bug]: Unhandled error on watching invoice

### ISSUE THREAD

**Issue by prusnak** [btcpayserver/btcpayserver#5115]
### What is your BTCPay version?

I am running BTCPay Server v1.10.2

### How did you deploy BTCPay Server?

custom

### What happened?

Showing the list of invoices `https://<hostname>/stores/<store_id>/invoices` throws error 500

### How did you encounter this bug?

1. Clicked Payments > Invoices in the left menu of my store

### Relevant log output

```
fail: PayServer:     Unhandled error on watching invoice LBwCEeXdz1AgTdnKpBCYZN
System.OverflowException: Value was either too large or too small for an Int64.
  at System.Decimal.ToInt64(Decimal d)
  at System.Decimal.op_Explicit(Decimal value)
  at NBitcoin.Money..ctor(Decimal amount, MoneyUnit unit)
  at NBitcoin.Money.Coins(Decimal coins)
  at BTCPayServer.Services.Invoices.PaymentMethod.Calculate(Func`2 paymentPredicate) in /build/source/BTCPayServer/Services/Invoices/InvoiceEntity.cs:line 1067
  at BTCPayServer.HostedServices.InvoiceWatcher.GetNearestClearedPayment(PaymentMethodDictionary allPaymentMethods, PaymentMethodAccounting& accounting) in /build/source/BTCPayServer/HostedServices/InvoiceWatcher.cs:line 213
  at BTCPayServer.HostedServices.InvoiceWatcher.UpdateInvoice(UpdateInvoiceContext context) in /build/source/BTCPayServer/HostedServices/InvoiceWatcher.cs:line 87
  at BTCPayServer.HostedServices.InvoiceWatcher.StartLoop(CancellationToken cancellation) in /build/source/BTCPayServer/HostedServices/InvoiceWatcher.cs:line 320
fail: PayServer:     Unhandled error on watching invoice LBwCEeXdz1AgTdnKpBCYZN
System.OverflowException: Value was either too large or too small for an Int64.
  at System.Decimal.ToInt64(Decimal d)
  at System.Decimal.op_Explicit(Decimal value)
  at NBitcoin.Money..ctor(Decimal amount, MoneyUnit unit)
  at NBitcoin.Money.Coins(Decimal coins)
  at BTCPayServer.Services.Invoices.PaymentMethod.Calculate(Func`2 paymentPredicate) in /build/source/BTCPayServer/Services/Invoices/InvoiceEntity.cs:line 1067
  at BTCPayServer.HostedServices.InvoiceWatcher.GetNearestClearedPayment(PaymentMethodDictionary allPaymentMethods, PaymentMethodAccounting& accounting) in /build/source/BTCPayServer/HostedServices/InvoiceWatcher.cs:line 213
  at BTCPayServer.HostedServices.InvoiceWatcher.UpdateInvoice(UpdateInvoiceContext context) in /build/source/BTCPayServer/HostedServices/InvoiceWatcher.cs:line 87
  at BTCPayServer.HostedServices.InvoiceWatcher.StartLoop(CancellationToken cancellation) in /build/source/BTCPayServer/HostedServices/InvoiceWatcher.cs:line 320
```

### What browser do you use?

all browsers

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by prusnak** [comment]
If you tell me how to retrieve the details of invoice `LBwCEeXdz1AgTdnKpBCYZN`, I can provide them, but I am unsure how at the moment.

**Comment by prusnak** [comment]
Still happens with BTCPay Server v1.10.2
