### ISSUE TITLE
[Bug]: crash on startup on 1.10.3 (and master at 73fbfbd7c)

### ISSUE THREAD

**Issue by darosior** [btcpayserver/btcpayserver#5173]
### What is your BTCPay version?

Happens on v1.10.3 and master.

### How did you deploy BTCPay Server?

Manually.

### What happened?

It crashes on startup.

### How did you encounter this bug?

By upgrading from v1.9.2 to v1.10.3.

### Relevant log output

```shell
Jul 13 12:37:34 redacted.com run.sh[392469]: fail: BTCPayServer.Hosting.MigrationStartupTask: Error on the MigrationStartupTask
Jul 13 12:37:34 --REDACTED--.com run.sh[392469]: System.NullReferenceException: Object reference not set to an instance of an object.
Jul 13 12:37:34 --REDACTED--.com run.sh[392469]:    at BTCPayServer.Hosting.MigrationStartupTask.ParsePOSYML(String yaml) in /home/btcpay/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 342
Jul 13 12:37:34 --REDACTED--.com run.sh[392469]:    at BTCPayServer.Hosting.MigrationStartupTask.MigrateAppYmlToJson()
Jul 13 12:37:34 --REDACTED--.com run.sh[392469]:    at BTCPayServer.Hosting.MigrationStartupTask.MigrateAppYmlToJson() in /home/btcpay/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 337
Jul 13 12:37:34 --REDACTED--.com run.sh[392469]:    at BTCPayServer.Hosting.MigrationStartupTask.ExecuteAsync(CancellationToken cancellationToken) in /home/btcpay/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 249
Jul 13 12:37:34 --REDACTED--.com run.sh[392469]: Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
Jul 13 12:37:34 --REDACTED--.com run.sh[392469]:    at BTCPayServer.Hosting.MigrationStartupTask.ParsePOSYML(String yaml) in /home/btcpay/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 342
Jul 13 12:37:34 --REDACTED--.com run.sh[392469]:    at BTCPayServer.Hosting.MigrationStartupTask.MigrateAppYmlToJson()
Jul 13 12:37:34 --REDACTED--.com run.sh[392469]:    at BTCPayServer.Hosting.MigrationStartupTask.MigrateAppYmlToJson() in /home/btcpay/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 337
Jul 13 12:37:34 --REDACTED--.com run.sh[392469]:    at BTCPayServer.Hosting.MigrationStartupTask.ExecuteAsync(CancellationToken cancellationToken) in /home/btcpay/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 249
Jul 13 12:37:34 --REDACTED--.com run.sh[392469]:    at Microsoft.AspNetCore.Hosting.WebHostExtensions.StartWithTasksAsync(IWebHost webHost, CancellationToken cancellationToken) in /home/btcpay/btcpayserver/BTCPayServer/Extensions/WebHostExtensions.cs:line 19
Jul 13 12:37:34 --REDACTED--.com run.sh[392469]:    at BTCPayServer.Program.Main(String[] args) in /home/btcpay/btcpayserver/BTCPayServer/Program.cs:line 76
Jul 13 12:37:35 --REDACTED--.com run.sh[392468]: /home/btcpay/btcpayserver/run.sh: line 4: 392469 Aborted                 dotnet "BTCPayServer.dll" $@
```
```


### What browser do you use?

_No response_

### Additional information

_No response_

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by darosior** [comment]
That fixed the crash. Thanks for the responsivity!

I'm not sure what you are asking about the template, i've not set any. You can access it here: https://btcpay.bitcoin-lyon.fr/apps/2qSXWsi1adSZHT2xtr91Zi4jjkrt/pos. It's the basic PoS with a blue color instead of the green one.

**Comment by Kukks** [comment]
ah that's it then. An empty pos template does the error.

I would suggest you rollback to 1.10.3 now, the migration is executed and you wont run into the error now
