### ISSUE TITLE
[Bug]: POS LNURL fails on System.InvalidOperationException

### ISSUE THREAD

**Issue by iBobik** [btcpayserver/btcpayserver#5178]
### What is your BTCPay version?

BTCPay Server v1.10.3+983b8c1f5

### How did you deploy BTCPay Server?

Official Docker stack

### What happened?

Calling LNURL fails with 500 code on a client and `System.InvalidOperationException: Nullable object must have a value.` in a Btcpay logs.

### How did you encounter this bug?

1. Having POS app with static QR codes
2. Scanned QR code by a walet or called LNURL by Curl
3. Client reports 500 status code with no message

### Relevant log output

```shell
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMS5B9NJNJOC", Request id "0HMS5B9NJNJOC:00000009": An unhandled exception was thrown by the application.
System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at BTCPayServer.UILNURLController.GetLNURLForApp(String cryptoCode, String appId, String itemCode) in /source/BTCPayServer/Controllers/UILNURLController.cs:line 297
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 98
   at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 50
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 30
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### What browser do you use?

Curl, Phoenix, Breez

### Additional information

I checked LND logs, but nothing was printed at the time of request.

Tried also internal node and LNbank.

LNURL codes stopped working without any admin action at Thu, 13 Jul 2023 at the morning with some older version, today I tried if update will fix it.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by Kukks** [comment]
this should be fixed in https://github.com/btcpayserver/btcpayserver/pull/5172

**Comment by Dochinds** [comment]
That card betting game will work for papa

**Comment by pavlenex** [comment]
@iBobik Can you give it a try again?

**Comment by iBobik** [comment]
In meantime I migrated node (new lnd instance) and there it works.

3. 8. 2023 19:55:05, Pavlenex ***@***.***> napsal:

**Comment by Mirafshinas** [comment]
My Public Address to Receive BTC bc1q7jjhyzr2pmxmvujh9rf4dc5khhcsh6532amkq2

Pay me via Trust Wallet:
https://link.trustwallet.com/send?coin=0&address=bc1q7jjhyzr2pmxmvujh9rf4dc5khhcsh6532amkq2

در تاریخ جمعه ۴ اوت ۲۰۲۳،‏ ۰۰:۱۵ Honza Pobořil ***@***.***>
نوشت:
