### ISSUE TITLE
[Bug]: API function StoreOnChainWallets_ShowOnChainWalletTransactions returns 500 Internal Server Error when ?skip>0

### ISSUE THREAD

**Issue by danijcom** [btcpayserver/btcpayserver#5183]
### What is your BTCPay version?

I'm running BTCPay Server v1.10.3+983b8c1f5

### How did you deploy BTCPay Server?

I'm running the BTCPayServer on LunaNode

### What happened?

I'm getting **500 Internal Server Error** when I try to use the [StoreOnChainWallets_ShowOnChainWalletTransactions](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/StoreOnChainWallets_ShowOnChainWalletTransactions) API function by passing the skip > 0 parameter to it.

### How did you encounter this bug?

_[my_server_url]/api/v1/stores/[my_store_id]/payment-methods/onchain/BTC/wallet/transactions?skip=0_ - correct output, a list of my wallet transactions
<img width="1180" alt="Screenshot_81" src="https://github.com/btcpayserver/btcpayserver/assets/46953160/3d2a49a2-49c1-463d-9f57-81a9889c380f">

_[my_server_url]/api/v1/stores/[my_store_id]/payment-methods/onchain/BTC/wallet/transactions_ - correct output, a list of my wallet transactions
![image](https://github.com/btcpayserver/btcpayserver/assets/46953160/be474db1-a82d-41d3-823b-56a5bfb11a4f)

_[my_server_url]/api/v1/stores/[my_store_id]/payment-methods/onchain/BTC/wallet/transactions?**skip=1**_ - 500 Internal Server Error
![image](https://github.com/btcpayserver/btcpayserver/assets/46953160/c2523cc4-8f6b-479e-836e-c92109df1f25)

_[my_server_url]/api/v1/stores/[my_store_id]/payment-methods/onchain/BTC/wallet/transactions?**skip=10**_ - 500 Internal Server Error
![image](https://github.com/btcpayserver/btcpayserver/assets/46953160/65646c75-8bd9-4b7a-a628-daac55cbcb77)

I also want to make a couple of points.
1. I have a large number of transactions (I can view them through the web interface, and also when using skip=0, or not using skip at all), so skip=1/10/100 and so on should not be the cause of the error.
2. I don't use Invoices, I use [StoreOnChainWallets_GetOnChainWalletReceiveAddress](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/StoreOnChainWallets_GetOnChainWalletReceiveAddress), and send funds to the created wallet. However, this, judging by the code, should not be the cause of the error either.

### Relevant log output

```shell
2023-07-18 17:31:52.048 +00:00 [ERR] Connection id "0HMRN65U5F9QO", Request id "0HMRN65U5F9QO:00000002": An unhandled exception was thrown by the application.
Npgsql.PostgresException (0x80004005): 22003: integer out of range
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|215_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 418
   at BTCPayServer.Services.Wallets.BTCPayWallet.FetchTransactionHistory(DerivationStrategyBase derivationStrategyBase, Nullable`1 skip, Nullable`1 count, Nullable`1 interval, CancellationToken cancellationToken) in /source/BTCPayServer/Services/Wallets/BTCPayWallet.cs:line 260
   at BTCPayServer.Services.Wallets.BTCPayWallet.FetchTransactionHistory(DerivationStrategyBase derivationStrategyBase, Nullable`1 skip, Nullable`1 count, Nullable`1 interval, CancellationToken cancellationToken)
   at BTCPayServer.Controllers.Greenfield.GreenfieldStoreOnChainWalletsController.ShowOnChainWalletTransactions(String storeId, String cryptoCode, TransactionStatus[] statusFilter, String labelFilter, Int32 skip, Int32 limit, CancellationToken cancellationToken) in /source/BTCPayServer/Controllers/GreenField/GreenfieldStoreOnChainWalletsController.cs:line 200
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 98
   at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 50
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 30
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
  Exception data:
    Severity: ERROR
    SqlState: 22003
    MessageText: integer out of range
    File: int.c
    Line: 779
    Routine: int4pl


👆 I always have the same error when I request a transaction list with ?skip=[>0] value.
```

### What browser do you use?

I'm testing the API using the [Postman ](https://www.postman.com/) app, but it basically doesn't affect the behavior of the API in any way. Making requests with Python comes out all the same.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by danijcom** [comment]
UPD
I updated the server to the new version (v1.11.0), the problem still persists.
