### ISSUE TITLE
[Bug]: nbxplorer unhandled exception in the indexer 

### ISSUE THREAD

**Issue by warioishere** [btcpayserver/btcpayserver#5187]
### What is your BTCPay version?

 BTCPay Server v1.10.3+983b8c1f5 

### How did you deploy BTCPay Server?

Docker

### What happened?

I cannot actually tell, last thing was that i updated an plugin and removed coinjoin plugin as im not currently using it.

### How did you encounter this bug?

just checked btcpay server a day letter and saw that node needed to be synced. but the Node didnt start syncing even after restarts of the docker container or restart of the whole machine.
Checked nbxplorer logs afterwards showing me the follwing:

This is a productive machine, unfurtunatly the last backup is more then 3 months old. We have a big inbound channel from a shop here in switerland, in actually dont want to loose this channel. There are 20000 Sats on the LND Wallet. I cannot got into RTL to do any backups because its says node not synced. LND is waiting for the server to be synced. 
I cannot request the LND Seed as LND is not running til the node synced.

Does it make sense to back.sh the server now and pull this on the VPS backup that is 3 Months old?
im Afraid its going to take the faulty parts of it if i restore it on the VPS backup

I would be interested to fix this nbxplorer first before trying the backup method. I restartet nbxplorer container manually, updated manually. Of course restarted the whole machine always with the same error.

Anyone has an Idea?

### Relevant log output

```shell
fail: NBXplorer.Indexer.BTC: Unhandled exception in the indexer, retrying in 25 seconds
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known
   at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily, ValueStopwatch stopwatch)
   at System.Net.Dns.<>c.<GetHostEntryOrAddressesCoreAsync>b__33_0(Object s, ValueStopwatch stopwatch)
   at System.Net.Dns.<>c__DisplayClass39_0`1.<RunAsync>b__0(Task <p0>, Object <p1>)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at NBitcoin.Protocol.DnsResolver.GetHostAddressesAsync(String hostNameOrAddress, CancellationToken cancellationToken)
   at NBitcoin.Protocol.Connectors.DefaultEndpointConnector.ConnectSocket(Socket socket, EndPoint endpoint, NodeConnectionParameters nodeConnectionParameters, CancellationToken cancellationToken)
   at NBitcoin.Protocol.Node.ConnectAsync(Network network, EndPoint endpoint, NetworkAddress peer, NodeConnectionParameters parameters)
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.ConnectNode(CancellationToken token, Boolean forceRestart) in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 236
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 77
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoop() in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 56
```

### What browser do you use?

doesnt depend on the browser, internal machine

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by NicolasDorier** [comment]
Given the error, NBXplorer doesn't manage to connect to your BTC node.
So we need to find out why you BTC node is offline.

Can you check `docker ps` and the stat of bitcoind container?  If it restarts, please check the logs with `docker logs btcpayserver_bitcoind`

**Comment by NicolasDorier** [comment]
to me it seems you aren't running pruned mode here.

You can check with

`cat $BTCPAY_DOCKER_COMPOSE`

Then look for something like..
```yaml
  bitcoind:
    restart: unless-stopped
    container_name: btcpayserver_bitcoind
    environment:
      BITCOIN_EXTRA_ARGS: |-
        ...
        prune=50000
        ....
```

If you can't find the `prune=` then you aren't pruned.

You can prune with

```bash
BTCPAYGEN_ADDITIONAL_FRAGMENTS="$BTCPAYGEN_ADDITIONAL_FRAGMENTS;opt-save-storage-s"
. btcpay-setup.sh -i
```

**Comment by warioishere** [comment]
`prune=` indeed doesnt show up anymore.  
`opt-save-storage` was also missing..
I am telling you we didnt change anything and we were always running in pruning mode (opt-save-storage) ->100gb. I only removed the coinjoin plugin and afterwards some weird stuff startet to happen.
I also didnt remove any fragments or play with settings internal. 

okay i added the fragment again and we are up an running. Alle channels are still there, and I am super happy! :)

thanks alot for your help. Sorry for causing any inconvinience and thank you very much for your time Nicolas and the rest of the btcpay team!! Great to have you here!

Can be closed :)

**Comment by NicolasDorier** [comment]
That's weird. We will keep an eye if that happen again to other people.
