### ISSUE TITLE
[Bug]: 500 error when i go to my wallet

### ISSUE THREAD

**Issue by DDFLACIA2** [btcpayserver/btcpayserver#5339]
### What is your BTCPay version?

BTCPay Server v1.11.4+79b2f1652

### How did you deploy BTCPay Server?

im running btcpay server on lunanode

### What happened?

Today i simply logged into my account and when i clicked on " bitcoin " under "wallet section " i get this error 

Error link: https://sub.domain.com/wallets/S-xxxxxxxxxxx-BTC/transactions

https://prnt.sc/Uxs7IZfEfmdu

### How did you encounter this bug?

1. logged into
2. clicked on bitcoin 
3. Boom i got this error

I tried multiple browser/laptops/mobile ( Clearing cache and cookies still same error )

### Relevant log output

```shell
2023-09-21 20:39:04.582 +00:00 [ERR] Connection id "0HMTQS5K3P387", Request id "0HMTQS5K3P387:00000002": An unhandled exception was thrown by the application.
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at BTCPayServer.Services.Rates.ExchangeRateHostRateProvider.GetRatesAsync(CancellationToken cancellationToken) in /source/BTCPayServer.Rating/Providers/ExchangeRateHostRateProvider.cs:line 23
   at BTCPayServer.Components.WalletNav.WalletNav.InvokeAsync(WalletId walletId) in /source/BTCPayServer/Components/WalletNav/WalletNav.cs:line 71
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsyncCore(ObjectMethodExecutor executor, Object component, ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsync(ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsync(ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper.InvokeCoreAsync(ViewComponentDescriptor descriptor, Object arguments)
   at AspNetCoreGeneratedDocument.Views_UIWallets__Nav.__Generated__WalletNavViewComponentTagHelper.ProcessAsync(TagHelperContext __context, TagHelperOutput __output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
   at AspNetCoreGeneratedDocument.Views_UIWallets__Nav.ExecuteAsync() in /source/BTCPayServer/Views/UIWallets/_Nav.cshtml:line 10
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper.RenderPartialViewAsync(TextWriter writer, Object model, IView view)
   at Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
   at AspNetCoreGeneratedDocument.Views_Shared__NavLayout.ExecuteAsync() in /source/BTCPayServer/Views/Shared/_NavLayout.cshtml:line 21
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|28_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 98
   at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 50
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 30
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### What browser do you use?

Safari,chrome,firefox

### Are you sure this is a bug report?

- [x] I confirm this is a bug report

**Comment by DDFLACIA2** [comment]
Please help!

**Comment by ndeet** [comment]
Can confirm on main and testnet, it used to work a couple of days ago but I restarted the server today. :thinking:

**Comment by DDFLACIA2** [comment]
im using mainnet on lunanode

> Can confirm on main and testnet, it used to work a couple of days ago but I restarted the server today. 🤔

**Comment by DDFLACIA2** [comment]
> Can confirm on main and testnet, it used to work a couple of days ago but I restarted the server today. 🤔

im using mainnet on lunanode

@ndeet

**Comment by DDFLACIA2** [comment]
> Can confirm on main and testnet, it used to work a couple of days ago but I restarted the server today. 🤔

im using mainnet on lunanode

@ndeet 

even this gives same error 

https://mainnet.demo.btcpayserver.org/wallets/S-xxxxx-BTC/transactions 

Please help my money is stuck

**Comment by ndeet** [comment]
yes, have it also on several servers, the fix has been done 3 days ago (https://github.com/btcpayserver/btcpayserver/pull/5328) and we will release a new version soon

**Comment by ndeet** [comment]
no money is stuck, just the wallet page has an error, with new release you will be able to access the page again; on that demo page you likely have a watch only wallet which you can still access on another interface than BTCPay

**Comment by DDFLACIA2** [comment]
> no money is stuck, just the wallet page has an error, with new release you will be able to access the page again; on that demo page you likely have a watch only wallet which you can still access on another interface than BTCPay

@ndeet is it fix ? is updated already released ?

**Comment by dennisreimann** [comment]
We'll release it shortly with #5341
