### ISSUE TITLE
[Bug]: Invoice is hodled by BTCPay, and incoming payment is not accepted/processed

### ISSUE THREAD

**Issue by Liongrass** [btcpayserver/btcpayserver#5385]
### What is your BTCPay version?

I'm running  `BTCPay Server v1.11.6+44a7e9387` with LND `0.16.4-beta commit=basedon-v0.16.4-beta-1-fresh-btcpay`

### How did you deploy BTCPay Server?

Lunanode FTW

### What happened?

I'm having a weird Lightning issue. My Lightning node is synced to chain and graph, it's channels are active, but when I create an invoice and try to pay it from an external wallet, the invoice appears to be "hodld" until it times out. I made sure I'm up to date and restarted the node. I can't find anything interesting in the LND logs.

### How did you encounter this bug?

The example app used today:

https://we.encrypt.cash/apps/37QCBufiLtDMq6mo9dbpZtZY37hr/crowdfund

### Relevant log output

```shell
The BTCPay logs say:

info: PayServer:      BTC (Lightning): Start listening http://lnd_bitcoin:8080/
fail: Microsoft.AspNetCore.SignalR.HubConnectionContext: Failed writing message. Aborting connection.
System.NotSupportedException: Serialization and deserialization of 'System.Action' instances are not supported. Path: $.MoveNextAction.
 ---> System.NotSupportedException: Serialization and deserialization of 'System.Action' instances are not supported.
   at System.Text.Json.Serialization.Converters.UnsupportedTypeConverter`1.Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(WriteStack& state, NotSupportedException ex)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteUsingSerializer[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize(Utf8JsonWriter writer, Object value, Type inputType, JsonSerializerOptions options)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteArguments(Object[] arguments, Utf8JsonWriter writer)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteInvocationMessage(InvocationMessage message, Utf8JsonWriter writer)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteMessageCore(HubMessage message, IBufferWriter`1 stream)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteMessage(HubMessage message, IBufferWriter`1 output)
   at Microsoft.AspNetCore.SignalR.Protocol.HubProtocolExtensions.GetMessageBytes(IHubProtocol hubProtocol, HubMessage message)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.GetMessageBytes(HubMessage message)
   at Microsoft.AspNetCore.SignalR.SerializedHubMessage.GetSerializedMessage(IHubProtocol protocol)
   at Microsoft.AspNetCore.SignalR.HubConnectionContext.WriteCore(SerializedHubMessage message, CancellationToken cancellationToken)
info: PayServer:      BTC (Lightning): No more invoice to listen on http://lnd_bitcoin:8080/, releasing the connection.
```

From the LND logs, not much of interest there:

```
2023-10-10 18:36:13.665 [INF] INVC: New invoice subscription client: id=4
2023-10-10 18:36:31.916 [WRN] BTCN: Query(0) from peer nkz5czphoyrvzhkijwopwda22ywfzknqhhkqksuhs2nublo5lwgmkbyd.onion:8333 failed, rescheduling: did not get response before timeout
2023-10-10 18:36:40.126 [INF] CRTR: Processed channels=0 updates=129 nodes=4 in last 59.998857015s
2023-10-10 18:37:03.919 [WRN] BTCN: Query(0) from peer nkz5czphoyrvzhkijwopwda22ywfzknqhhkqksuhs2nublo5lwgmkbyd.onion:8333 failed, rescheduling: did not get response before timeout
2023-10-10 18:37:35.927 [WRN] BTCN: Query(0) from peer nkz5czphoyrvzhkijwopwda22ywfzknqhhkqksuhs2nublo5lwgmkbyd.onion:8333 failed, rescheduling: did not get response before timeout
2023-10-10 18:37:40.126 [INF] CRTR: Processed channels=0 updates=146 nodes=8 in last 59.999859061s
2023-10-10 18:38:07.936 [WRN] BTCN: Query(0) from peer wockkiso5afh47gppalqlyrqddpjafgtq5sysupkdiwwsqn6hgqytlyd.onion:8333 failed, rescheduling: did not get response before timeout
2023-10-10 18:38:39.939 [WRN] BTCN: Query(0) from peer nkz5czphoyrvzhkijwopwda22ywfzknqhhkqksuhs2nublo5lwgmkbyd.onion:8333 failed, rescheduling: did not get response before timeout
2023-10-10 18:38:40.126 [INF] CRTR: Processed channels=0 updates=131 nodes=3 in last 59.999691551s
2023-10-10 18:39:11.943 [WRN] BTCN: Query(0) from peer nkz5czphoyrvzhkijwopwda22ywfzknqhhkqksuhs2nublo5lwgmkbyd.onion:8333 failed, rescheduling: did not get response before timeout
2023-10-10 18:39:40.127 [INF] CRTR: Processed channels=0 updates=157 nodes=3 in last 59.999868647s
2023-10-10 18:39:43.946 [WRN] BTCN: Query(0) from peer nkz5czphoyrvzhkijwopwda22ywfzknqhhkqksuhs2nublo5lwgmkbyd.onion:8333 failed, rescheduling: did not get response before timeout
2023-10-10 18:40:11.276 [INF] DISC: GossipSyncer(026478c86f8ddbc7fe484bc29f16edbe270d36c0e3fec4359736e63e350885b573): filtering chan range: start_height=0, num_blocks=811573
2023-10-10 18:40:15.978 [WRN] BTCN: Query(0) from peer nkz5czphoyrvzhkijwopwda22ywfzknqhhkqksuhs2nublo5lwgmkbyd.onion:8333 failed, rescheduling: did not get response before timeout
2023-10-10 18:40:16.123 [INF] DISC: GossipSyncer(026478c86f8ddbc7fe484bc29f16edbe270d36c0e3fec4359736e63e350885b573): sending range chunk of size=8000
2023-10-10 18:40:16.136 [INF] DISC: GossipSyncer(026478c86f8ddbc7fe484bc29f16edbe270d36c0e3fec4359736e63e350885b573): sending range chunk of size=8000
2023-10-10 18:40:16.145 [INF] DISC: GossipSyncer(026478c86f8ddbc7fe484bc29f16edbe270d36c0e3fec4359736e63e350885b573): sending range chunk of size=8000
2023-10-10 18:40:16.170 [INF] DISC: GossipSyncer(026478c86f8ddbc7fe484bc29f16edbe270d36c0e3fec4359736e63e350885b573): sending range chunk of size=8000
2023-10-10 18:40:16.181 [INF] DISC: GossipSyncer(026478c86f8ddbc7fe484bc29f16edbe270d36c0e3fec4359736e63e350885b573): sending range chunk of size=7995
2023-10-10 18:40:16.188 [INF] DISC: GossipSyncer(026478c86f8ddbc7fe484bc29f16edbe270d36c0e3fec4359736e63e350885b573): sending range chunk of size=8000
2023-10-10 18:40:16.193 [INF] DISC: GossipSyncer(026478c86f8ddbc7fe484bc29f16edbe270d36c0e3fec4359736e63e350885b573): sending range chunk of size=8000
2023-10-10 18:40:16.207 [INF] DISC: GossipSyncer(026478c86f8ddbc7fe484bc29f16edbe270d36c0e3fec4359736e63e350885b573): sending range chunk of size=8000
2023-10-10 18:40:16.214 [INF] DISC: GossipSyncer(026478c86f8ddbc7fe484bc29f16edbe270d36c0e3fec4359736e63e350885b573): sending final chan range chunk, size=714
2023-10-10 18:40:40.606 [INF] CRTR: Processed channels=0 updates=115 nodes=11 in last 1m0.478615581s
2023-10-10 18:40:41.588 [INF] DISC: GossipSyncer(026478c86f8ddbc7fe484bc29f16edbe270d36c0e3fec4359736e63e350885b573): applying new update horizon: start=2023-10-10 18:40:41 +0000 UTC, end=2159-11-17 01:08:56 +0000 UTC, backlog_size=52
2023-10-10 18:40:47.980 [WRN] BTCN: Query(0) from peer nkz5czphoyrvzhkijwopwda22ywfzknqhhkqksuhs2nublo5lwgmkbyd.onion:8333 failed, rescheduling: did not get response before timeout
2023-10-10 18:41:19.981 [WRN] BTCN: Query(0) from peer nkz5czphoyrvzhkijwopwda22ywfzknqhhkqksuhs2nublo5lwgmkbyd.onion:8333 failed, rescheduling: did not get response before timeout
2023-10-10 18:41:35.554 [INF] CRTR: Pruning channel graph using block 00000000000000000000662f4635ee88019347b646eec2361fd0ba78250a3f1f (height=811574)
2023-10-10 18:41:43.144 [INF] CRTR: Block 00000000000000000000662f4635ee88019347b646eec2361fd0ba78250a3f1f (height=811574) closed 39 channels
2023-10-10 18:41:43.195 [INF] NTFN: New block: height=811574, sha=00000000000000000000662f4635ee88019347b646eec2361fd0ba78250a3f1f
2023-10-10 18:41:43.229 [INF] CRTR: Processed channels=0 updates=136 nodes=7 in last 1m2.545832792s
2023-10-10 18:41:43.273 [INF] UTXN: Attempting to graduate height=811574: num_kids=0, num_babies=0
2023-10-10 18:41:51.995 [WRN] BTCN: Query(0) from peer nkz5czphoyrvzhkijwopwda22ywfzknqhhkqksuhs2nublo5lwgmkbyd.onion:8333 failed, rescheduling: did not get response before timeout
2023-10-10 18:42:24.002 [WRN] BTCN: Query(0) from peer nkz5czphoyrvzhkijwopwda22ywfzknqhhkqksuhs2nublo5lwgmkbyd.onion:8333 failed, rescheduling: did not get response before timeout
2023-10-10 18:42:40.162 [INF] CRTR: Processed channels=0 updates=124 nodes=10 in last 56.889886611s
2023-10-10 18:42:56.008 [WRN] BTCN: Query(0) from peer kme4pipybdo7kmyrpgtaectf5e4b44ms52ddf6du34kqpmyhyzbqxtid.onion:8333 failed, rescheduling: did not get response before timeout
2023-10-10 18:43:28.010 [WRN] BTCN: Query(0) from peer nkz5czphoyrvzhkijwopwda22ywfzknqhhkqksuhs2nublo5lwgmkbyd.onion:8333 failed, rescheduling: did not get response before timeout
2023-10-10 18:43:40.134 [INF] CRTR: Processed channels=2 updates=113 nodes=16 in last 59.97186908s
2023-10-10 18:44:00.012 [WRN] BTCN: Query(0) from peer nkz5czphoyrvzhkijwopwda22ywfzknqhhkqksuhs2nublo5lwgmkbyd.onion:8333 failed, rescheduling: did not get response before timeout
2023-10-10 18:44:32.015 [WRN] BTCN: Query(0) from peer vjch3u5h7ai67yx5dz4ob4yy4vccgabpcxpucnn4dguwbhqbnbqoeryd.onion:8333 failed, rescheduling: did not get response before timeout
2023-10-10 18:44:36.837 [INF] PEER: Peer(0216f956ad1000914d6cb1d0885049da342ac045b23539d00436324b8d366d243a): unable to read message from peer: read tcp 172.18.0.7:48632->172.18.0.2:9050: i/o timeout
2023-10-10 18:44:36.840 [INF] PEER: Peer(0216f956ad1000914d6cb1d0885049da342ac045b23539d00436324b8d366d243a): disconnecting 0216f956ad1000914d6cb1d0885049da342ac045b23539d00436324b8d366d243a@zpsr2gdzkw4ixyzwdojtv7slx23jiscrexubefn4unkdpfqbwza5ruad.onion:9735, reason: read handler closed
2023-10-10 18:44:36.841 [INF] NTFN: Cancelling epoch notification, epoch_id=14
2023-10-10 18:44:36.942 [INF] DISC: Removing GossipSyncer for peer=0216f956ad1000914d6cb1d0885049da342ac045b23539d00436324b8d366d243a
2023-10-10 18:44:36.943 [INF] DISC: GossipSyncer(029ba9303f003e1073963a64ef1553ab6cf3b5756526ca164e90032c4c059f1749): applying gossipFilter(start=2023-10-10 18:44:36.943912557 +0000 UTC m=+3852.001063591, end=2159-11-17 01:12:51.943912557 +0000 UTC)
2023-10-10 18:44:40.126 [INF] CRTR: Processed channels=1 updates=130 nodes=5 in last 59.989134163s
2023-10-10 18:45:04.016 [WRN] BTCN: Query(0) from peer nkz5czphoyrvzhkijwopwda22ywfzknqhhkqksuhs2nublo5lwgmkbyd.onion:8333 failed, rescheduling: did not get response before timeout
2023-10-10 18:45:36.017 [WRN] BTCN: Query(0) from peer nkz5czphoyrvzhkijwopwda22ywfzknqhhkqksuhs2nublo5lwgmkbyd.onion:8333 failed, rescheduling: did not get response before timeout
2023-10-10 18:45:40.126 [INF] CRTR: Processed channels=0 updates=80 nodes=0 in last 1m0.00045088s
2023-10-10 18:46:08.019 [WRN] BTCN: Query(0) from peer wockkiso5afh47gppalqlyrqddpjafgtq5sysupkdiwwsqn6hgqytlyd.onion:8333 failed, rescheduling: did not get response before timeout
2023-10-10 18:46:40.021 [WRN] BTCN: Query(0) from peer nkz5czphoyrvzhkijwopwda22ywfzknqhhkqksuhs2nublo5lwgmkbyd.onion:8333 failed, rescheduling: did not get response before timeout
2023-10-10 18:46:40.127 [INF] CRTR: Processed channels=0 updates=88 nodes=11 in last 59.995294404s
2023-10-10 18:47:12.023 [WRN] BTCN: Query(0) from peer nkz5czphoyrvzhkijwopwda22ywfzknqhhkqksuhs2nublo5lwgmkbyd.onion:8333 failed, rescheduling: did not get response before timeout
2023-10-10 18:47:40.127 [INF] CRTR: Processed channels=0 updates=74 nodes=13 in last 59.999305305s
2023-10-10 18:47:44.024 [WRN] BTCN: Query(0) from peer nkz5czphoyrvzhkijwopwda22ywfzknqhhkqksuhs2nublo5lwgmkbyd.onion:8333 failed, rescheduling: did not get response before timeout
2023-10-10 18:47:55.291 [INF] CRTR: Pruning channel graph using block 000000000000000000030e3297c1e72f1da63fff0c66a666a4349403ae8c1607 (height=811575)
2023-10-10 18:48:02.300 [INF] CRTR: Block 000000000000000000030e3297c1e72f1da63fff0c66a666a4349403ae8c1607 (height=811575) closed 13 channels
2023-10-10 18:48:02.306 [INF] NTFN: New block: height=811575, sha=000000000000000000030e3297c1e72f1da63fff0c66a666a4349403ae8c1607
2023-10-10 18:48:02.336 [INF] UTXN: Attempting to graduate height=811575: num_kids=0, num_babies=0
2023-10-10 18:48:16.030 [WRN] BTCN: Query(0) from peer kme4pipybdo7kmyrpgtaectf5e4b44ms52ddf6du34kqpmyhyzbqxtid.onion:8333 failed, rescheduling: did not get response before timeout
2023-10-10 18:48:20.617 [INF] DISC: GossipSyncer(026478c86f8ddbc7fe484bc29f16edbe270d36c0e3fec4359736e63e350885b573): applying gossipFilter(start=0001-01-01 00:00:00 +0000 UTC, end=0001-01-01 00:00:00 +0000 UTC)
2023-10-10 18:48:20.622 [INF] DISC: GossipSyncer(02b9eb4df1fdcff4e607894cd75e0b22da66d833826fefcbf19ed44eca5deb3d37): applying gossipFilter(start=2023-10-10 18:48:20.622660015 +0000 UTC m=+4075.679811054, end=2159-11-17 01:16:35.622660015 +0000 UTC)
2023-10-10 18:48:40.127 [INF] CRTR: Processed channels=0 updates=173 nodes=0 in last 59.998705515s
2023-10-10 18:48:48.032 [WRN] BTCN: Query(0) from peer nkz5czphoyrvzhkijwopwda22ywfzknqhhkqksuhs2nublo5lwgmkbyd.onion:8333 failed, rescheduling: did not get response before timeout
2023-10-10 18:49:09.282 [INF] DISC: GossipSyncer(029ba9303f003e1073963a64ef1553ab6cf3b5756526ca164e90032c4c059f1749): applying new update horizon: start=2023-10-10 18:49:09 +0000 UTC, end=2159-11-17 01:17:24 +0000 UTC, backlog_size=52
2023-10-10 18:49:20.032 [WRN] BTCN: Query(0) from peer nkz5czphoyrvzhkijwopwda22ywfzknqhhkqksuhs2nublo5lwgmkbyd.onion:8333 failed, rescheduling: did not get response before timeout
2023-10-10 18:49:40.126 [INF] CRTR: Processed channels=1 updates=102 nodes=12 in last 59.998980609s
2023-10-10 18:49:45.579 [INF] CRTR: Examining channel graph for zombie channels
2023-10-10 18:49:49.111 [INF] CRTR: Pruning 1 zombie channels
2023-10-10 18:49:51.861 [INF] CHDB: Pruned unconnected node 021ae1e5b99cd56ffe5040e24bf8f00ee394393e01c46d713d181dd7b2a17f236c from channel graph
2023-10-10 18:49:51.863 [INF] CHDB: Pruned 1 unconnected nodes from the channel graph
2023-10-10 18:49:52.035 [WRN] BTCN: Query(0) from peer nkz5czphoyrvzhkijwopwda22ywfzknqhhkqksuhs2nublo5lwgmkbyd.onion:8333 failed, rescheduling: did not get response before timeout
2023-10-10 18:50:05.272 [INF] DISC: GossipSyncer(026478c86f8ddbc7fe484bc29f16edbe270d36c0e3fec4359736e63e350885b573): requesting new chans from height=0 and 811575 blocks after
2023-10-10 18:50:06.132 [INF] DISC: GossipSyncer(026478c86f8ddbc7fe484bc29f16edbe270d36c0e3fec4359736e63e350885b573): buffering chan range reply of size=7999
2023-10-10 18:50:06.241 [INF] DISC: GossipSyncer(026478c86f8ddbc7fe484bc29f16edbe270d36c0e3fec4359736e63e350885b573): buffering chan range reply of size=8000
2023-10-10 18:50:06.280 [INF] DISC: GossipSyncer(026478c86f8ddbc7fe484bc29f16edbe270d36c0e3fec4359736e63e350885b573): buffering chan range reply of size=7997
2023-10-10 18:50:06.337 [INF] DISC: GossipSyncer(026478c86f8ddbc7fe484bc29f16edbe270d36c0e3fec4359736e63e350885b573): buffering chan range reply of size=7999
2023-10-10 18:50:06.605 [INF] DISC: GossipSyncer(026478c86f8ddbc7fe484bc29f16edbe270d36c0e3fec4359736e63e350885b573): buffering chan range reply of size=7998
2023-10-10 18:50:06.972 [INF] DISC: GossipSyncer(026478c86f8ddbc7fe484bc29f16edbe270d36c0e3fec4359736e63e350885b573): buffering chan range reply of size=7996
2023-10-10 18:50:07.054 [INF] DISC: GossipSyncer(026478c86f8ddbc7fe484bc29f16edbe270d36c0e3fec4359736e63e350885b573): buffering chan range reply of size=7999
2023-10-10 18:50:07.209 [INF] DISC: GossipSyncer(026478c86f8ddbc7fe484bc29f16edbe270d36c0e3fec4359736e63e350885b573): buffering chan range reply of size=7998
2023-10-10 18:50:07.327 [INF] DISC: GossipSyncer(026478c86f8ddbc7fe484bc29f16edbe270d36c0e3fec4359736e63e350885b573): buffering chan range reply of size=2333
2023-10-10 18:50:07.327 [INF] DISC: GossipSyncer(026478c86f8ddbc7fe484bc29f16edbe270d36c0e3fec4359736e63e350885b573): filtering through 66319 chans
2023-10-10 18:50:10.168 [INF] DISC: GossipSyncer(026478c86f8ddbc7fe484bc29f16edbe270d36c0e3fec4359736e63e350885b573): starting query for 12 new chans
2023-10-10 18:50:10.168 [INF] DISC: GossipSyncer(026478c86f8ddbc7fe484bc29f16edbe270d36c0e3fec4359736e63e350885b573): querying for 12 new channels
2023-10-10 18:50:10.765 [INF] DISC: GossipSyncer(026478c86f8ddbc7fe484bc29f16edbe270d36c0e3fec4359736e63e350885b573): no more chans to query
2023-10-10 18:50:24.054 [WRN] BTCN: Query(0) from peer nkz5czphoyrvzhkijwopwda22ywfzknqhhkqksuhs2nublo5lwgmkbyd.onion:8333 failed, rescheduling: did not get response before timeout
2023-10-10 18:50:40.127 [INF] CRTR: Processed channels=12 updates=121 nodes=20 in last 59.999228747s
2023-10-10 18:50:56.075 [WRN] BTCN: Query(0) from peer nkz5czphoyrvzhkijwopwda22ywfzknqhhkqksuhs2nublo5lwgmkbyd.onion:8333 failed, rescheduling: did not get response before timeout
2023-10-10 18:51:28.077 [WRN] BTCN: Query(0) from peer kme4pipybdo7kmyrpgtaectf5e4b44ms52ddf6du34kqpmyhyzbqxtid.onion:8333 failed, rescheduling: did not get response before timeout
2023-10-10 18:51:31.248 [INF] INVC: Cancelling invoice subscription for client=4
2023-10-10 18:51:40.127 [INF] CRTR: Processed channels=0 updates=113 nodes=6 in last 59.999005393s
2023-10-10 18:52:00.079 [WRN] BTCN: Query(0) from peer vjch3u5h7ai67yx5dz4ob4yy4vccgabpcxpucnn4dguwbhqbnbqoeryd.onion:8333 failed, rescheduling: did not get response before timeout
```
```


### What browser do you use?

_No response_

### Additional information

_No response_

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by Liongrass** [comment]
I'm going to close this as I'm not convinced anymore that it's a BTCPay issue
