### ISSUE TITLE
[Bug]: Invoice summary calculations are completely miscalculating. 

### ISSUE THREAD

**Issue by divinationstar** [btcpayserver/btcpayserver#5464]
### What is your BTCPay version?

BTCPay Server v1.11.7+a921504bc (Altcoins)

### How did you deploy BTCPay Server?

Install from Lunanode from years ago. 

### What happened?

These examples are with BTC transactions.

Example #1 - Invoice total amount due - $15, Rate - 
$36,978.60, Total due - 0.00056938, Paid - 0.00040077, Still due - 0.00016861.  Total due 0.00056938 X Rate $36,978.60 = $21.054875268. That doesn't match invoice amount of $15. 

Example #2, Invoice Total Amount Due - $19.00, Rate - $36,294.99, Total due - 0.00106289 = $38.577581921. That's more than double the invoice amount. This should add up to $19, not $38.577581921.

Paid 0.00062546 X Rate $36,294.99 = $22.701064445. That amount is above the Invoice amount of $19.00 yet shows as "expired, paid partial". 

I have plenty more of these to show if needed.

### How did you encounter this bug?

I checked the transaction details of Partial payment, expired transactions and saw the numbers in Invoice Summary do not add up properly.

### Relevant log output

```shell
2023-11-10 17:02:22.243 +00:00 [INF] Running SSH command: . /etc/profile.d/btcpay-env.sh && nohup btcpay-update.sh > /dev/null 2>&1 & disown
2023-11-10 17:02:35.196 +00:00 [ERR] Error while connecting to WebSocket of NBXplorer (LTC)
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at NBXplorer.WebsocketMessageListener.NextMessageAsync(CancellationToken cancellation)
   at BTCPayServer.Payments.Bitcoin.NBXplorerListener.Listen(BTCPayWallet wallet) in /source/BTCPayServer/Payments/Bitcoin/NBXplorerListener.cs:line 144
2023-11-10 17:02:35.196 +00:00 [ERR] Error while connecting to WebSocket of NBXplorer (BTC)
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at NBXplorer.WebsocketMessageListener.NextMessageAsync(CancellationToken cancellation)
   at BTCPayServer.Payments.Bitcoin.NBXplorerListener.Listen(BTCPayWallet wallet) in /source/BTCPayServer/Payments/Bitcoin/NBXplorerListener.cs:line 144
2023-11-10 17:02:35.197 +00:00 [INF] Disconnected from WebSocket of NBXplorer (LTC)
2023-11-10 17:02:35.198 +00:00 [INF] Disconnected from WebSocket of NBXplorer (BTC)
2023-11-10 17:02:36.467 +00:00 [INF] SSH command executed with exit status 0. Output: 
2023-11-10 17:02:51.657 +00:00 [INF] BTC: Checking if any pending invoice got paid while offline...
2023-11-10 17:02:51.658 +00:00 [INF] LTC: Checking if any pending invoice got paid while offline...
2023-11-10 17:02:52.078 +00:00 [INF] LTC: 0 payments happened while offline
2023-11-10 17:02:52.079 +00:00 [INF] Connected to WebSocket of NBXplorer (LTC)
2023-11-10 17:02:54.089 +00:00 [INF] BTC: 0 payments happened while offline
2023-11-10 17:02:54.090 +00:00 [INF] Connected to WebSocket of NBXplorer (BTC)
```

### What browser do you use?

Brave - [Version 1.60.110 Chromium: 119.0.6045.105 (Official Build) (64-bit)](https://brave.com/latest/)

### Additional information

![$19](https://github.com/btcpayserver/btcpayserver/assets/37784226/1d10dbd0-d798-4694-b613-5bbd752d51ab)

![$15](https://github.com/btcpayserver/btcpayserver/assets/37784226/65210622-11c5-49d2-af85-c02622badbd7)

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by divinationstar** [comment]
I think I figured it out. The system is adding the network fees to the amount due if more than one payment on an invoice. But I do have a one payment invoice transaction where the system must be adding the network fee even though it's set to "Only if the customer makes more than one payment for the invoice". And the network fee does not show in the Invoice details page. There should be a message or icon, or something to notify the admin looking at the invoice page so they know the network fee is added in. Otherwise, the total amount due does not match the invoice amount and a person looking at this might think the calculation is wrong.

**Comment by petzsch** [comment]
As discussed with the @divinationstar yesterday on [Mattermost](https://chat.btcpayserver.org/btcpayserver/pl/4xq91b9utjdjzqmudq3wes57tw):

This is intended behavoiur. If a user pays in more then one transaction, the additional transactions result in higher fees for the merchant when forwarding from such payments. Hence the enduser is asked to pay the open due amount + network fees for an average 100 vB transaction. The reasons for this are explained in our [FAQ](https://docs.btcpayserver.org/FAQ/Stores/#add-network-fee-to-invoice-vary-with-mining-fees).

The observed case of a one payment transaction charging for network fees seems odd. But I couldn't reproduce it. Perhaps you can provide more details and screenshots on this specfiic case?

**Comment by divinationstar** [comment]
Hello,

Here is a recent one.

Invoice amount is $15. Total due X rate 0.00053692×36715.28 = $19.713168138. That's about $4 higher than invoice amount which must be because of the network fee. Yet, this is a one payment invoice. The user paid $13.562257279 but the system wants another 6.150910859 additional to equal the $4 above invoice cost.

[Screenshot from 2023-11-11 18-55-19.png]

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by divinationstar** [comment]
I looked at the most recent transaction and it's a one payment invoice and the total due matches the invoice amount. Why is this? Is it the way someone sends payment that determines if the system adds a network fee or not?

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by petzsch** [comment]
> [Screenshot from 2023-11-11 18-55-19.png]

Your screenshot didn't make it through. Could you post it via the github webinterface?

**Comment by divinationstar** [comment]
![Screenshot from 2023-11-12 19-50-32](https://github.com/btcpayserver/btcpayserver/assets/37784226/b96ab311-e233-48c6-8715-57361f49fa16)

**Comment by divinationstar** [comment]
Here's an interesting one. Two payments but a network fee on only one of them?

![Screenshot from 2023-11-12 19-57-11](https://github.com/btcpayserver/btcpayserver/assets/37784226/46fef2fd-9d86-4b2b-8972-5b37aaa8d6d9)

**Comment by divinationstar** [comment]
I thought Rate X Total due = Invoice amount.  "original invoice amount in BTC" should be the Total Due amount. It's calculated based on the Rate.

**Comment by NicolasDorier** [comment]
I think with 2.0, we can make the invoice details view clearer.
Especially, we could just show a table with the list of payments containing:

1. The time it was received
2. The payment method
3. The currency of the payment
4. The rate
5. The payment method fee.
6. The current status (Cancelled, Settled, Pending)
