### ISSUE TITLE
Payout with prism, interated continuously

### ISSUE THREAD

**Issue by massmux** [btcpayserver/btcpayserver#5525]
### Discussed in https://github.com/btcpayserver/btcpayserver/discussions/5524

<div type='discussions-op-text'>

<sup>Originally posted by **massmux** November 30, 2023</sup>
I have seen this issue arose. Here steps to reproduce:

Let's make a payout to an external LN address above 100 sats threshold. Go in payout, enable it, set  "Process approved payouts instantly " as true.

then in prism enable a catch all payout to a LN address, with 100% amount. save and enable the prism.

now send a (for example) 300 sats payment to the shop by POS.

the payment is immediately sent out to the LN address. but in payouts we still see the payout in "awaiting payment". This remains still. after the payout time, another payout of the same value is iterated. and this keeps going on without an end. for stopping it you shoud mark manually the payout as paid.

this issue was not present in previous versions apparently.</div>

**Comment by massmux** [comment]
```
2023-11-30T08:51:09.792435375Z info: LightningAutomatedPayoutSenderFactory:p4hD6n82vGEe2GAidvufA6PXbcEoWrqwFXoSSKZBrP3:BTC_LightningLike: 1 found to process. Starting (and after will sleep for 00:05:00)
2023-11-30T08:51:11.920748943Z fail: LightningAutomatedPayoutSenderFactory:p4hD6n82vGEe2GAidvufA6PXbcEoWrqwFXoSSKZBrP3:BTC_LightningLike: Could not process payout P8JXZZ89fEUZorUKZ4PzeWVhH19
2023-11-30T08:51:11.920785490Z System.ArgumentNullException: Value cannot be null. (Parameter 'left')
2023-11-30T08:51:11.920792293Z    at BTCPayServer.Lightning.LightMoney.op_Subtraction(LightMoney left, LightMoney right)
2023-11-30T08:51:11.920797122Z    at BTCPayServer.Lightning.LndHub.LndHubLightningClient.Pay(String bolt11, PayInvoiceParams payParams, CancellationToken cancellation)
2023-11-30T08:51:11.920802011Z    at BTCPayServer.Data.Payouts.LightningLike.UILightningLikePayoutController.TrypayBolt(ILightningClient lightningClient, PayoutBlob payoutBlob, PayoutData payoutData, BOLT11PaymentRequest bolt11PaymentRequest, PaymentMethodId pmi, CancellationToken cancellationToken) in /source/BTCPayServer/Data/Payouts/LightningLike/UILightningLikePayoutController.cs:line 348
2023-11-30T08:51:11.920806801Z    at BTCPayServer.PayoutProcessors.Lightning.LightningAutomatedPayoutProcessor.TrypayBolt(ILightningClient lightningClient, PayoutBlob payoutBlob, PayoutData payoutData, BOLT11PaymentRequest bolt11PaymentRequest) in /source/BTCPayServer/PayoutProcessors/Lightning/LightningAutomatedPayoutProcessor.cs:line 135
2023-11-30T08:51:11.920812040Z    at BTCPayServer.PayoutProcessors.Lightning.LightningAutomatedPayoutProcessor.Process(ISupportedPaymentMethod paymentMethod, List`1 payouts) in /source/BTCPayServer/PayoutProcessors/Lightning/LightningAutomatedPayoutProcessor.cs:line 91
```

**Comment by massmux** [comment]
doing more tests, it seems that this happens when there is a lightning LNDHUB funding source and not when using for example LNbank wallet

**Comment by Kukks** [comment]
> doing more tests, it seems that this happens when there is a lightning LNDHUB funding source and not when using for example LNbank wallet

It was an incompat issue with lnbits lndhub. 
Fixed in 
https://github.com/btcpayserver/BTCPayServer.Lightning/commit/838bda2eb10194877aabf642d8284453d32a58a0
and 
https://github.com/btcpayserver/BTCPayServer.Lightning/commit/8f242c3efe590b1a7fe5e5b995882540367f0fbb
