### ISSUE TITLE
[Bug]: 500 error on accessing dashboard (REGTEST) after creating a wallet

### ISSUE THREAD

**Issue by travishoglund** [btcpayserver/btcpayserver#5764]
### What is your BTCPay version?

I'm running BTC Pay 1.12.5

### How did you deploy BTCPay Server?

Docker

### What happened?

500 Internal error

### How did you encounter this bug?

Run locally using Docker on regtest.  After connecting a wallet to the store, the dashboard will 500.

### Relevant log output

```shell
2024-02-16 14:53:50 fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HN1F5QEJVE4K", Request id "0HN1F5QEJVE4K:00000001": An unhandled exception was thrown by the application.
2024-02-16 14:53:50 System.NotSupportedException: IMoney type not supported
2024-02-16 14:53:50    at BTCPayServer.MoneyExtensions.GetValue(IMoney m, BTCPayNetwork network) in /source/BTCPayServer/Extensions/MoneyExtensions.cs:line 30
2024-02-16 14:53:50    at BTCPayServer.Components.StoreWalletBalance.StoreWalletBalance.InvokeAsync(StoreData store) in /source/BTCPayServer/Components/StoreWalletBalance/StoreWalletBalance.cs:line 78
2024-02-16 14:53:50    at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsyncCore(ObjectMethodExecutor executor, Object component, ViewComponentContext context)
2024-02-16 14:53:50    at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsync(ViewComponentContext context)
2024-02-16 14:53:50    at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsync(ViewComponentContext context)
2024-02-16 14:53:50    at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper.InvokeCoreAsync(ViewComponentDescriptor descriptor, Object arguments)
2024-02-16 14:53:50    at AspNetCoreGeneratedDocument.Views_UIStores_Dashboard.__Generated__StoreWalletBalanceViewComponentTagHelper.ProcessAsync(TagHelperContext __context, TagHelperOutput __output)
2024-02-16 14:53:50    at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
2024-02-16 14:53:50    at AspNetCoreGeneratedDocument.Views_UIStores_Dashboard.ExecuteAsync() in /source/BTCPayServer/Views/UIStores/Dashboard.cshtml:line 57
2024-02-16 14:53:50    at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
2024-02-16 14:53:50    at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
2024-02-16 14:53:50    at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
2024-02-16 14:53:50    at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
2024-02-16 14:53:50    at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
2024-02-16 14:53:50    at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
2024-02-16 14:53:50    at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
2024-02-16 14:53:50    at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
2024-02-16 14:53:50    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-02-16 14:53:50    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
2024-02-16 14:53:50    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
2024-02-16 14:53:50    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|28_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-02-16 14:53:50    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-02-16 14:53:50    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
2024-02-16 14:53:50    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2024-02-16 14:53:50    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-02-16 14:53:50    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2024-02-16 14:53:50    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2024-02-16 14:53:50    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
2024-02-16 14:53:50    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
2024-02-16 14:53:50    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
2024-02-16 14:53:50    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
2024-02-16 14:53:50    at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 97
2024-02-16 14:53:50    at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 30
2024-02-16 14:53:50    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
2024-02-16 14:53:50    at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 29
```

### What browser do you use?

Chrome

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
What is `iMoney`?

**Comment by Kukks** [comment]
> What is `iMoney`? Seems like you're using plugins, try deactivating them

Imoney is our code, this is a valid bug

**Comment by travishoglund** [comment]
Any idea what might be causing this?  The dashboard route works before adding a wallet, but once linked it causes the issue.

**Comment by travishoglund** [comment]
> What is `iMoney`? Seems like you're using plugins, try deactivating them

I don't have any plugins activated, do you need more info?

**Comment by Kukks** [comment]
> > What is `iMoney`? Seems like you're using plugins, try deactivating them
> 
> I don't have any plugins activated, do you need more info?

Yes, are you using any altcoins?

**Comment by travishoglund** [comment]
No, I am not using any altcoins.  This is a base install, nothing customized other than adding a store, then adding a wallet.

**Comment by travishoglund** [comment]
@Kukks - It seems like it was a pretty simple fix - do you know why the issue was caused?  Is there a way for me to easily modify this code in my local docker image before you create an official docker image release for me to pull?
