### ISSUE TITLE
Error: Error while connecting to the API (Could not deserialize the response body.) 

### ISSUE THREAD

**Issue by Kixunil** [btcpayserver/btcpayserver#585]
I updated my LND to master in order to fix memory leak bug, but now btcpayserver can't connect to it. I did remove and re-create macaroons.

I also tried to pull newest btcpayserver and it didn't help.

**Comment by pavlenex** [comment]
You need to provide us with way more information in order to help you troubleshoot. Please see the [troubleshooting guide](https://docs.btcpayserver.org/support-and-community/troubleshooting), provide your setup, and exact steps, logs etc.

**Comment by whiteyhat** [comment]
I am having the same issue here by some reason my node is unavailable. 

`BTC Lightning Node - Unavailable`

**Comment by whiteyhat** [comment]
https://mainnet.satoshis.games/embed/9GeKnzxFVotU5r1vZrJkr7Ppuj8ECyAnq4LYdUfBtgRC/BTC/ln

**Comment by pavlenex** [comment]
@whiteyhat the first thing to try to do is restart your btcpay with 
`btcpay.restart.sh`

Try to get it back that way, we're trying to identify the issue, where did you deploy your BTCPay?

**Comment by whiteyhat** [comment]
Lunanode using one click deployment.

After restart nothing happened it is still unavailable

**Comment by whiteyhat** [comment]
Lunanode. After the restart it worked seamlessly

**Comment by pavlenex** [comment]
@NicolasDorier ^

**Comment by Kixunil** [comment]
I tried restarting again and it still isn't working. Is there at least some way to look at more detail what it's unable to parse? What data does it get and what's the error? That way, I could resolve it myself/contribute, but I'm unable to do so without it.

**Comment by pavlenex** [comment]
@Kixunil from what I understand you're using an external LND?
The only way to troubleshoot your issue is to[ provide LND logs.](https://docs.btcpayserver.org/support-and-community/troubleshooting#2-2-lightning-network-logs)
If you're using an external LND, I am afraid there's little we can do to help you anyway.

**Comment by janoside** [comment]
I'm having the same issue. I'm debugging and have identified more details about the failure to deserialize. It looks like the key part is: `Unexpected character encountered while parsing value: {. Path 'chains', line 1, position 546.` - it doesn't seem to like the `chains` element of the returned JSON. Don't know any more yet.

JSON response from my LND:

    {"identity_pubkey":"03c07a1f01a7a5c5ee6c6c63c27df976bc1fbaac09bbee047dad2e5c338c5abae8","alias":"lightning.chaintools.io","num_active_channels":6,"num_peers":18,"block_height":564053,"block_hash":"00000000000000000016b87e6a3456beca5a308736e835dfea45d6a999495f23","synced_to_chain":true,"uris":["03c07a1f01a7a5c5ee6c6c63c27df976bc1fbaac09bbee047dad2e5c338c5abae8@159.89.179.129:9735"],"best_header_timestamp":"1550776550","version":"0.5.1-beta commit=v0.5.1-beta-527-ge51c58e7221085fb36c3c30e98756212dde6b7f2","num_inactive_channels":1,"chains":[{"chain":"bitcoin","network":"mainnet"}]}

Exception details:

      BTCPayServer.Lightning.LND.SwaggerException: Could not deserialize the response body. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path 'chains', line 1, position 546.
         at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
         at Newtonsoft.Json.JsonTextReader.ReadAsString()
         at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
         at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
         at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
         at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
         at BTCPayServer.Lightning.LND.LndSwaggerClient.GetInfoAsync(CancellationToken cancellationToken)
         ...

**Comment by janoside** [comment]
A little more digging...There's a generated class `LndSwaggerClient` (I believe included via DLL from the related project [BTCPayServer.Lightning](https://github.com/btcpayserver/BTCPayServer.Lightning)) with a method signature `public Task<LnrpcGetInfoResponse> GetInfoAsync();`. The return type `LnrpcGetInfoResponse` is, I believe also generated code and includes a member `Chains` with the following definition:

    [JsonProperty("chains", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    public ObservableCollection<string> Chains { get; set; }

I believe this code needs to be re-generated to acknowledge that the "chains" element in the JSON response should be a list of sub-JSON objects rather than a list of strings. I don't know how to do this, but will continue digging (and learning as I go).

**Comment by rockstardev** [comment]
@janoside if LND Swagger changed then that class can be regenerated using NSwagStudio: https://github.com/RSuter/NSwag/wiki/NSwagStudio

**Comment by NicolasDorier** [comment]
nice catch, will fix that manually.

**Comment by NicolasDorier** [comment]
Maybe I will just remove it entirely so we support old and new versions.

**Comment by NicolasDorier** [comment]
@Kixunil @janoside can you confirm the error is now gone with 1.0.3.59?

**Comment by janoside** [comment]
@NicolasDorier Confirmed - error is gone. Thanks

**Comment by NicolasDorier** [comment]
@Kixunil reopen if that's not the case.

**Comment by NicolasDorier** [comment]
@Kixunil we have some people having memory leak issues (@Eskyee ) can you tell us which commit fixed it?  (ping @pavlenex )

**Comment by NicolasDorier** [comment]
(see https://github.com/btcpayserver/btcpayserver/issues/605)

**Comment by Eskyee** [comment]
https://github.com/Eskyee/btcpayjungle/commit/784d65424de188e8bcf9a156f425045da9caf183

**Comment by Kixunil** [comment]
It works, thanks a lot!

I tired it a while ago, but payments weren't working and it's only now that I concluded the problem is in lnd, not Btcpayserver.

Regarding memory issues: lnd went down again. I've upgraded to the latest version. It didn't crash so far, but there are some problems with payments.
