### ISSUE TITLE
[Bug]: BTCPayServer.Hosting.MigrationStartupTask: Error while running migration scripts

### ISSUE THREAD

**Issue by mariodian** [btcpayserver/btcpayserver#5958]
### What is your BTCPay version?

Running BTCPay from master d3277306cf88499eda03c96e4c3e03730fa8fcba

### How did you deploy BTCPay Server?

Manual deploy. Been running it for a while on Postgresql 16 with no issues. (Not sure whether 16.0 or 16.1)

### What happened?

I upgraded to the latest Ubuntu 24.04 LTS (with `do-release-upgrade -d`), 16.2 Postgresql, updated dotnet 8 and rebuilt BTCPay with shitcoins support. 

However, when I try running it, it throws a migration error (below). Building it without shitcoins via `./build.sh` and running it via `./run.sh` makes no difference. 

I suspect BTCPay isn't compatible with Postgresql 16.2. AFAIK, there's no easy way to downgrade from 16.2 to 16.[1,0] and `sudo apt install postgresql-16=16.0` has no packages available, so I can't really tell whether this is a 16.2 issue per se. 

I'm running NBxplorer on a different physical machine (it communicates to BTCPay over wireguard), BUT the exact same Ubuntu 24.04 LTS and the same postgresql/dotnet versions with no issues whatsoever. 

### How did you encounter this bug?

1. build with shitcoin support (or without, it doesn't matter):

```
dotnet publish --no-cache --configuration Altcoins-Release
```

2. run with shitcoin support (or without, doesn't matter again):

```
dotnet run --no-launch-profile --no-build -c Altcoins-Release --project "BTCPayServer/BTCPayServer.csproj" -- $@
```

3. get the migration error 

### Relevant log output

```shell
info: Configuration:  Network: Mainnet
info: BTCPayServer.Hosting.MigrationStartupTask: Running the migration scripts...
warn: BTCPayServer.Hosting.MigrationStartupTask: Error while running migration scripts, retrying...
Npgsql.PostgresException (0x80004005): 25001: VACUUM cannot be executed within a pipeline
   at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Migrations.Internal.NpgsqlMigrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
   at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
  Exception data:
    Severity: ERROR
    SqlState: 25001
    MessageText: VACUUM cannot be executed within a pipeline
    File: xact.c
    Line: 3507
    Routine: PreventInTransactionBlock
```
```


### What browser do you use?

N/A

### Additional information

psql (PostgreSQL) 16.2 (Ubuntu 16.2-2.pgdg24.04+1)
Ubuntu 24.04 LTS
dotnet 8.0.104

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by mariodian** [comment]
```
$ cat /var/log/postgresql/postgresql-16-main.log

2024-04-26 07:28:11.248 UTC [20276] btcpay@btcpayserver2 ERROR:  VACUUM cannot be executed within a pipeline
2024-04-26 07:28:11.248 UTC [20276] btcpay@btcpayserver2 STATEMENT:  VACUUM (FULL, ANALYZE) "InvoiceEvents"
2024-04-26 07:28:12.383 UTC [20276] btcpay@btcpayserver2 ERROR:  VACUUM cannot be executed within a pipeline
2024-04-26 07:28:12.383 UTC [20276] btcpay@btcpayserver2 STATEMENT:  VACUUM (FULL, ANALYZE) "InvoiceEvents"
```

And this is an earlier error related to LNBank plugin. I have removed the plugin and this error went away but the migration is still broken.

```
$ cat /var/log/syslog | grep btcpay

2024-04-26T06:07:49.907218+00:00 ip-172-26-7-217 systemd[1]: Started btcpayserver.service - BtcPayServer daemon.
2024-04-26T06:07:49.910939+00:00 ip-172-26-7-217 (dotnet)[6634]: btcpayserver.service: Invalid environment variable name evaluates to an empty string: @
2024-04-26T06:07:51.086270+00:00 ip-172-26-7-217 dotnet[6646]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Configuration:  Data Directory: /home/ubuntu/.btcpayserver/Main
2024-04-26T06:07:51.086447+00:00 ip-172-26-7-217 dotnet[6646]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: Configuration:  Configuration File: /home/ubuntu/.btcpayserver/Main/settings.config
2024-04-26T06:07:51.443399+00:00 ip-172-26-7-217 dotnet[6646]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: BTCPayServer.Plugins.PluginManager: Loading plugins from /home/ubuntu/.btcpayserver/Plugins
2024-04-26T06:07:52.191098+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Plugins.PluginManager.GetPluginInstancesFromAssembly(Assembly assembly) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Plugins/PluginManager.cs:line 261
2024-04-26T06:07:52.191125+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Plugins.PluginManager.GetPluginInstanceFromAssembly(String pluginIdentifier, Assembly assembly) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Plugins/PluginManager.cs:line 269
2024-04-26T06:07:52.191154+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Plugins.PluginManager.AddPlugins(IMvcBuilder mvcBuilder, IServiceCollection serviceCollection, IConfiguration config, ILoggerFactory loggerFactory, ServiceProvider bootstrapServiceProvider) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Plugins/PluginManager.cs:line 170
2024-04-26T06:07:54.386380+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:07:55.488297+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:07:56.668943+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:07:57.745279+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:07:58.834864+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:07:59.911339+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:08:01.039388+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:08:02.171711+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:08:03.314478+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:08:04.415952+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:08:05.532678+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:08:06.657571+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:08:07.760438+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:08:08.875141+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:08:10.005291+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:08:11.123456+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:08:12.215309+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:08:13.277560+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:08:14.385268+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:08:15.489896+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:08:16.599006+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:08:17.719674+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:08:18.837655+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:08:19.907904+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:08:20.993484+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:08:22.076702+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:08:23.151879+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:08:24.271101+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:08:25.364330+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:08:26.484258+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:08:27.734390+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:08:28.809313+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:08:29.901796+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:08:30.996526+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:08:32.061525+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
2024-04-26T06:08:33.175281+00:00 ip-172-26-7-217 dotnet[6646]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 897
```

**Comment by mariodian** [comment]
> Please, the master is very, VERY experimental right now, with stuff being built to ship v2 later this year. Use the tagged release commits

Yeah that was it. But now I have issues with the db as I deleted LNBank plugin only in the filesystem but not in the db. But I'll try to figure it out. Thanks!

```
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HN35OL5A1JEN", Request id "0HN35OL5A1JEN:00000001": An unhandled exception was thrown by the application.
Npgsql.PostgresException (0x80004005): 42P01: relation "CustodianAccount" does not exist

POSITION: 83
   at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass30_0`2.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToArrayAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at BTCPayServer.Services.Custodian.Client.CustodianAccountRepository.FindByStoreId(String storeId, CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Services/Custodian/CustodianAccountRepository.cs:line 56
   at BTCPayServer.Services.Custodian.Client.CustodianAccountRepository.FindByStoreId(String storeId, CancellationToken cancellationToken) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Services/Custodian/CustodianAccountRepository.cs:line 57
   at BTCPayServer.Components.MainNav.MainNav.InvokeAsync() in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Components/MainNav/MainNav.cs:line 95
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsyncCore(ObjectMethodExecutor executor, Object component, ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsync(ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsync(ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper.InvokeCoreAsync(ViewComponentDescriptor descriptor, Object arguments)
   at AspNetCoreGeneratedDocument.Views_Shared__Layout.__Generated__MainNavViewComponentTagHelper.ProcessAsync(TagHelperContext __context, TagHelperOutput __output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
   at AspNetCoreGeneratedDocument.Views_Shared__Layout.<>c__DisplayClass19_0.<<ExecuteAsync>b__1>d.MoveNext() in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Views/Shared/_Layout.cshtml:line 30
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
   at AspNetCoreGeneratedDocument.Views_Shared__Layout.ExecuteAsync() in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Views/Shared/_Layout.cshtml:line 16
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|28_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 97
   at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 30
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /home/ubuntu/source/Bitcoin/btcpayserver/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 29
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
  Exception data:
    Severity: ERROR
    SqlState: 42P01
    MessageText: relation "CustodianAccount" does not exist
    Position: 83
    File: parse_relation.c
    Line: 1449
    Routine: parserOpenTable
```

**Comment by k3tan172** [comment]
Thanks Mario!
Doing a fresh install on Ubuntu 24.04 and got this error as well. Not using master solved the issue.

With the manual deployment, I'm using postgres for nbxplorer and btcpayserver, but I'm still seeing "We would like to show you a chart of your balance. Please [migrate to the new NBXplorer backend](https://github.com/dgarage/NBXplorer/blob/master/docs/Postgres-Migration.md) for that data to become available." on the dashboard. 

Do you know how to solve this?

**Comment by mariodian** [comment]
Hey, it's unrelated to this issue.

You have to add the following line to `<your btcpay config dir>/Main/settings.conf`:

```
explorerpostgres=User ID=<nbxplorer postgres user>;Password=<nbxplorer postgres password>;Host=<nbxplorer host>;Port=5432;Database=<nbxplorer postgres db name>;
```

That is, if you use manual deployment. If not, you will have to do the similar but in the docker file.

**Comment by k3tan172** [comment]
Thanks that works now.
I know it's not related to this issue, I just didn't know how else to contact you.
Might be worth updating your freedomnode article on btcpayserver manual deployment when you get a chance, I still use it even after all these years! Appreciate your work!

**Comment by mariodian** [comment]
Thanks! Yeah great idea, just updated it.
