### ISSUE TITLE
[Bug]: InvalidOperationException:  Sequence contains more than one matching element

### ISSUE THREAD

**Issue by tuxpizza** [btcpayserver/btcpayserver#6077]
### What is your BTCPay version?

1.13.3-altcoins

### How did you deploy BTCPay Server?

Docker through official documentation

### What happened?

Updated docker which prompted a restart of BTCPayServer, next time it starts up the main container (generated_btcpayserver_1) is throwing an "InvalidOperationException:  Sequence contains more than one matching element" pertaining to some internal server error, and restarts every few seconds, preventing me from using it

Was on 1.13.0, updated to 1.13.3 but it did not fix the crashing.

### How did you encounter this bug?

Simply had BTCPayServer restarted, and now I just get a 502 when attempting to login as the main container keeps restarting itself, haven't changed anything else.

### Relevant log output

```shell
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
info: Configuration:  Data Directory: /datadir
info: Configuration:  Configuration File: /datadir/Main/settings.config
info: BTCPayServer.Plugins.PluginManager: Loading plugins from /root/.btcpayserver/Plugins
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer - 1.13.3
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Shopify - 1.13.3
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.PointOfSale - 1.13.3
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.PayButton - 1.13.3
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.NFC - 1.13.3
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Crowdfund - 1.13.3
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Bitcoin - 1.13.3
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Altcoins - 1.13.3
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Trocador - 1.2.4
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.AutoForward - 1.0.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Custodians.Kraken - 1.0.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Serilog - 1.0.1.0
info: Configuration:  Supported chains: BTC,XMR
info: Configuration:  BTC: Explorer url is http://nbxplorer:32838/
info: Configuration:  BTC: Cookie file is /root/.nbxplorer/Main/.cookie
info: Configuration:  Network: Mainnet
info: Configuration:  LogFile: /datadir/btcpay.log
info: Configuration:  Log Level: Debug
Unhandled exception. System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at BTCPayServer.Services.TransactionLinkProviders.RefreshTransactionLinkTemplates() in /source/BTCPayServer/Services/TransactionLinkProviders.cs:line 32
   at BTCPayServer.Hosting.BlockExplorerLinkStartupTask.ExecuteAsync(CancellationToken cancellationToken) in /source/BTCPayServer/Hosting/BlockExplorerLinkStartupTask.cs:line 36
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.StartWithTasksAsync(IWebHost webHost, CancellationToken cancellationToken) in /source/BTCPayServer/Extensions/WebHostExtensions.cs:line 19
   at BTCPayServer.Program.Main(String[] args) in /source/BTCPayServer/Program.cs:line 76
   at BTCPayServer.Program.Main(String[] args) in /source/BTCPayServer/Program.cs:line 103
   at BTCPayServer.Program.<Main>(String[] args)
```

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by NicolasDorier** [comment]
@tuxpizza we plan fixing it this week and release new release

**Comment by tuxpizza** [comment]
Hi, sorry to ask. I see everything is merged for this next release, will this release be going out tomorrow?
And thanks for prioritizing this issue, much appreciated as unfortunately it's caused quite the downtime for our service.

**Comment by NicolasDorier** [comment]
@tuxpizza sorry for the wait, this is released now!

**Comment by tuxpizza** [comment]
@NicolasDorier Not a problem, I  already had manually switched the tag to the rc1 version last week and it immediately fixed our issue!

Thanks guys! :raised_hands:

**Comment by Buganwigan** [comment]
Ax


Sent from Yahoo Mail for iPhone


On Monday, July 15, 2024, 11:38 AM, tuxsudo ***@***.***> wrote:




@NicolasDorier Not a problem, I already had manually switched the tag to the rc1 version last week and it immediately fixed our issue!

Thanks guys! 🙌
