### ISSUE TITLE
Error encountered migrating servers

### ISSUE THREAD

**Issue by justinmoon** [btcpayserver/btcpayserver#610]
I tried to migrate my data from an expensive azure instance to a cheaper Lunanode instance. [This is what I did to transfer the data](https://gist.github.com/justinmoon/183b59b6a441b6402347a4c12c78bb9c). After this succeeded and all my old azure invoices show up in the UI, I copied the xpub I was using on azure to this new server.

When I try to create a new invoice I get a 500 and this error shows up in `docker logs <container id>`:

```
Microsoft.AspNetCore.Server.Kestrel: Connection id "0HLKP3RJJRAD5", Request id "0HLKP3RJJRAD5:00000001": An unhandled exception was thrown by the application.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> Npgsql.PostgresException: 23505: duplicate key value violates unique constraint "PK_AddressInvoices"
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at BTCPayServer.Services.Invoices.InvoiceRepository.CreateInvoiceAsync(String storeId, InvoiceEntity invoice, InvoiceLogs creationLogs, BTCPayNetworkProvider networkProvider) in /source/Services/Invoices/InvoiceRepository.cs:line 169
   at BTCPayServer.Controllers.InvoiceController.CreateInvoiceCore(Invoice invoice, StoreData store, String serverUrl) in /source/Controllers/InvoiceController.cs:line 173
   at BTCPayServer.Controllers.PublicController.PayButtonHandle(PayButtonViewModel model) in /source/Controllers/PublicController.cs:line 48
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/Hosting/BTCpayMiddleware.cs:line 46
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

If I use a fresh xpub there is no such problem. It seems that BTCPay might be deriving addresses that have already been used -- leading to a violation of the uniqueness constraint on the Address table?

**Comment by NicolasDorier** [comment]
@justinmoon yes. It seems you did not backed up your NBXplorer, so you have this error.

You might be able to fix it by going into Wallets/Rescan and doing a rescan for your wallet.
After this, just create a bunch of dummy invoice until it stop crashing. (each invoice take the next address, so after a while, you will be at the end)

**Comment by justinmoon** [comment]
Rescan didn't work ...

Are there any instructions to backup NBXplorer?

**Comment by NicolasDorier** [comment]
Just create tons of invoice, it is not really a big deal. You will have ton of dummy invoice anyway with your service.

**Comment by NicolasDorier** [comment]
@justinmoon well it is in the docker volume.

`/var/docker/volumes/generate_nbxplorer_1/_data` or something like this.

**Comment by justinmoon** [comment]
True. I'll just do that. Thanks @NicolasDorier!

**Comment by ser** [comment]
IMHO this issue should not be closed without clear information in the docs that NBexplorer data must be backuped

**Comment by britttttk** [comment]
@ser thanks for mentioning. Yes, it would be good to add to docs if you also encountered this issue.

I'm happy to open the issue for you, but can you suggest more clearly which part of this issue you think should be added to the docs? Migrating server requires nbx backup? 

Feel free to open an issue in docs repo if you want to clarify there instead.

**Comment by 2ge** [comment]
same issue here, I used "official" backup guide, where this is totally omitted. Whats worse, the btcpayserever itself works, but creation of invoices doesnt.
