### ISSUE TITLE
[Bug]: `CancelPayoutAfterFaillures` setting is not used

### ISSUE THREAD

**Issue by jackstar12** [btcpayserver/btcpayserver#6131]
### What is your BTCPay version?

v1.13.5

### How did you deploy BTCPay Server?

Manually, regtest

### What happened?

While working on the new [boltz plugin](https://github.com/BoltzExchange/btcpayserver-boltz) I configured the automated lightning payout processor to 1 Max Failure attempt and it just keeps retrying even tough the attempts continuously fail. The setting seems to be used nowhere: https://github.com/search?q=repo%3Abtcpayserver%2Fbtcpayserver%20CancelPayoutAfterFailures&type=code

### How did you encounter this bug?

Configure automated lightning payout processor with 1 minute and 1 max failure attempt and initiate a pull payment which fails to be paid by the Lightning Node.

### Relevant log output

```shell
info: LightningAutomatedPayoutSenderFactory:2whLU64rMcunL7LCM5Q4M5YHtNEEfHV5L7FjK5UkBqc8:BTC_LightningLike: 1 found to process. Starting (and after will sleep for 00:01:00)
fail: LightningAutomatedPayoutSenderFactory:2whLU64rMcunL7LCM5Q4M5YHtNEEfHV5L7FjK5UkBqc8:BTC_LightningLike: Could not process payout 36PeJ12wAjFBcvqdQivbCunNJEri
Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="boltz error: 23424 is less than minimal of 50000")
   at BTCPayServer.Plugins.Boltz.BoltzClient.CreateSwap(CreateSwapRequest request) in /home/jacksn/dev/btcpayserver-boltz/BTCPayServer.Plugins.Boltz/BoltzClient.cs:line 238
   at BTCPayServer.Plugins.Boltz.BoltzLightningClient.Pay(String bolt11, PayInvoiceParams payParams, CancellationToken cancellation) in /home/jacksn/dev/btcpayserver-boltz/BTCPayServer.Plugins.Boltz/BoltzLightningClient.cs:line 222
   at BTCPayServer.Data.Payouts.LightningLike.UILightningLikePayoutController.TrypayBolt(ILightningClient lightningClient, PayoutBlob payoutBlob, PayoutData payoutData, BOLT11PaymentRequest bolt11PaymentRequest, PaymentMethodId pmi, CancellationToken cancellationToken) in /home/jacksn/dev/btcpayserver/BTCPayServer/Data/Payouts/LightningLike/UILightningLikePayoutController.cs:line 312
   at BTCPayServer.PayoutProcessors.Lightning.LightningAutomatedPayoutProcessor.TrypayBolt(ILightningClient lightningClient, PayoutBlob payoutBlob, PayoutData payoutData, BOLT11PaymentRequest bolt11PaymentRequest) in /home/jacksn/dev/btcpayserver/BTCPayServer/PayoutProcessors/Lightning/LightningAutomatedPayoutProcessor.cs:line 140
   at BTCPayServer.PayoutProcessors.Lightning.LightningAutomatedPayoutProcessor.HandlePayout(PayoutData payoutData, ILightningClient lightningClient) in /home/jacksn/dev/btcpayserver/BTCPayServer/PayoutProcessors/Lightning/LightningAutomatedPayoutProcessor.cs:line 94
info: LightningAutomatedPayoutSenderFactory:2whLU64rMcunL7LCM5Q4M5YHtNEEfHV5L7FjK5UkBqc8:BTC_LightningLike: 1 found to process. Starting (and after will sleep for 00:01:00)
fail: LightningAutomatedPayoutSenderFactory:2whLU64rMcunL7LCM5Q4M5YHtNEEfHV5L7FjK5UkBqc8:BTC_LightningLike: Could not process payout 36PeJ12wAjFBcvqdQivbCunNJEri
Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="boltz error: 23424 is less than minimal of 50000")
   at BTCPayServer.Plugins.Boltz.BoltzClient.CreateSwap(CreateSwapRequest request) in /home/jacksn/dev/btcpayserver-boltz/BTCPayServer.Plugins.Boltz/BoltzClient.cs:line 238
   at BTCPayServer.Plugins.Boltz.BoltzLightningClient.Pay(String bolt11, PayInvoiceParams payParams, CancellationToken cancellation) in /home/jacksn/dev/btcpayserver-boltz/BTCPayServer.Plugins.Boltz/BoltzLightningClient.cs:line 222
   at BTCPayServer.Data.Payouts.LightningLike.UILightningLikePayoutController.TrypayBolt(ILightningClient lightningClient, PayoutBlob payoutBlob, PayoutData payoutData, BOLT11PaymentRequest bolt11PaymentRequest, PaymentMethodId pmi, CancellationToken cancellationToken) in /home/jacksn/dev/btcpayserver/BTCPayServer/Data/Payouts/LightningLike/UILightningLikePayoutController.cs:line 312
   at BTCPayServer.PayoutProcessors.Lightning.LightningAutomatedPayoutProcessor.TrypayBolt(ILightningClient lightningClient, PayoutBlob payoutBlob, PayoutData payoutData, BOLT11PaymentRequest bolt11PaymentRequest) in /home/jacksn/dev/btcpayserver/BTCPayServer/PayoutProcessors/Lightning/LightningAutomatedPayoutProcessor.cs:line 140
   at BTCPayServer.PayoutProcessors.Lightning.LightningAutomatedPayoutProcessor.HandlePayout(PayoutData payoutData, ILightningClient lightningClient) in /home/jacksn/dev/btcpayserver/BTCPayServer/PayoutProcessors/Lightning/LightningAutomatedPayoutProcessor.cs:line 94
```

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by Alizby** [comment]
****

**Comment by Alizby** [comment]
info:%20LightningAutomatedPayoutSenderFactory%3A2whLU64rMcunL7LCM5Q4M5YHtNEEfHV5L7FjK5UkBqc8%3ABTC_LightningLike%3A%201%20found%20to%20process.%20Starting%20(and%20after%20will%20sleep%20for%2000%3A01%3A00)%0Afail%3A%20LightningAutomatedPayoutSenderFactory%3A2whLU64rMcunL7LCM5Q4M5YHtNEEfHV5L7FjK5UkBqc8%3ABTC_LightningLike%3A%20Could%20not%20process%20payout%2036PeJ12wAjFBcvqdQivbCunNJEri%0AGrpc.Core.RpcException%3A%20Status(StatusCode=%22Unknown%22,%20Detail=%22boltz%20error%3A%2023424%20is%20less%20than%20minimal%20of%2050000%22)%0A%20%20%20at%20BTCPayServer.Plugins.Boltz.BoltzClient.CreateSwap(CreateSwapRequest%20request)%20in%20/home/jacksn/dev/btcpayserver-boltz/BTCPayServer.Plugins.Boltz/BoltzClient.cs:line%20238%0A%20%20%20at%20BTCPayServer.Plugins.Boltz.BoltzLightningClient.Pay(String%20bolt11,%20PayInvoiceParams%20payParams,%20CancellationToken%20cancellation)%20in%20/home/jacksn/dev/btcpayserver-boltz/BTCPayServer.Plugins.Boltz/BoltzLightningClient.cs:line%20222%0A%20%20%20at%20BTCPayServer.Data.Payouts.LightningLike.UILightningLikePayoutController.TrypayBolt(ILightningClient%20lightningClient,%20PayoutBlob%20payoutBlob,%20PayoutData%20payoutData,%20BOLT11PaymentRequest%20bolt11PaymentRequest,%20PaymentMethodId%20pmi,%20CancellationToken%20cancellationToken)%20in%20/home/jacksn/dev/btcpayserver/BTCPayServer/Data/Payouts/LightningLike/UILightningLikePayoutController.cs:line%20312%0A%20%20%20at%20BTCPayServer.PayoutProcessors.Lightning.LightningAutomatedPayoutProcessor.TrypayBolt(ILightningClient%20lightningClient,%20PayoutBlob%20payoutBlob,%20PayoutData%20payoutData,%20BOLT11PaymentRequest%20bolt11PaymentRequest)%20in%20/home/jacksn/dev/btcpayserver/BTCPayServer/PayoutProcessors/Lightning/LightningAutomatedPayoutProcessor.cs:line%20140%0A%20%20%20at%20BTCPayServer.PayoutProcessors.Lightning.LightningAutomatedPayoutProcessor.HandlePayout(PayoutData%20payoutData,%20ILightningClient%20lightningClient)%20in%20/home/jacksn/dev/btcpayserver/BTCPayServer/PayoutProcessors/Lightning/LightningAutomatedPayoutProcessor.cs:line%2094%0Ainfo:%20LightningAutomatedPayoutSenderFactory:2whLU64rMcunL7LCM5Q4M5YHtNEEfHV5L7FjK5UkBqc8:BTC_LightningLike:%201%20found%20to%20process.%20Starting%20(and%20after%20will%20sleep%20for%2000:01:00)%0Afail:%20LightningAutomatedPayoutSenderFactory:2whLU64rMcunL7LCM5Q4M5YHtNEEfHV5L7FjK5UkBqc8:BTC_LightningLike:%20Could%20not%20process%20payout%2036PeJ12wAjFBcvqdQivbCunNJEri%0AGrpc.Core.RpcException:%20Status(StatusCode=%22Unknown%22,%20Detail=%22boltz%20error:%2023424%20is%20less%20than%20minimal%20of%2050000%22)%0A%20%20%20at%20BTCPayServer.Plugins.Boltz.BoltzClient.CreateSwap(CreateSwapRequest%20request)%20in%20/home/jacksn/dev/btcpayserver-boltz/BTCPayServer.Plugins.Boltz/BoltzClient.cs:line%20238%0A%20%20%20at%20BTCPayServer.Plugins.Boltz.BoltzLightningClient.Pay(String%20bolt11,%20PayInvoiceParams%20payParams,%20CancellationToken%20cancellation)%20in%20/home/jacksn/dev/btcpayserver-boltz/BTCPayServer.Plugins.Boltz/BoltzLightningClient.cs:line%20222%0A%20%20%20at%20BTCPayServer.Data.Payouts.LightningLike.UILightningLikePayoutController.TrypayBolt(ILightningClient%20lightningClient,%20PayoutBlob%20payoutBlob,%20PayoutData%20payoutData,%20BOLT11PaymentRequest%20bolt11PaymentRequest,%20PaymentMethodId%20pmi,%20CancellationToken%20cancellationToken)%20in%20/home/jacksn/dev/btcpayserver/BTCPayServer/Data/Payouts/LightningLike/UILightningLikePayoutController.cs:line%20312%0A%20%20%20at%20BTCPayServer.PayoutProcessors.Lightning.LightningAutomatedPayoutProcessor.TrypayBolt(ILightningClient%20lightningClient,%20PayoutBlob%20payoutBlob,%20PayoutData%20payoutData,%20BOLT11PaymentRequest%20bolt11PaymentRequest)%20in%20/home/jacksn/dev/btcpayserver/BTCPayServer/PayoutProcessors/Lightning/LightningAutomatedPayoutProcessor.cs:line%20140%0A%20%20%20at%20BTCPayServer.PayoutProcessors.Lightning.LightningAutomatedPayoutProcessor.HandlePayout(PayoutData%20payoutData,%20ILightningClient%20lightningClient)%20in%20/home/jacksn/dev/btcpayserver/BTCPayServer/PayoutProcessors/Lightning/LightningAutomatedPayoutProcessor.cs:line%2094

**Comment by Kukks** [comment]
@NicolasDorier DIdn't you intentionally remove this feature? I don't remember why because I remember it quite useful.

**Comment by pavlenex** [comment]
@NicolasDorier

**Comment by NicolasDorier** [comment]
So we removed from UI here https://github.com/btcpayserver/btcpayserver/commit/e4f79f046aa82bfbd6d76c933aeba5a978916dd0, but it was already not doing anything anymore.

Initially if I remember we removed it because we had a case of double payment, and there was no clear way to fix it.
That said, there seem to be a need for that, so I'll look into this more deeply.

**Comment by NicolasDorier** [comment]
In 2.x, the automated processor retry automatically up to 10 times if the transfer failed.
