### ISSUE TITLE
[Bug]: Boltcard payments get bolt11 invoice without memo when LNURL is Enabled

### ISSUE THREAD

**Issue by dsbaars** [btcpayserver/btcpayserver#6135]
### What is your BTCPay version?

v1.13.5

### How did you deploy BTCPay Server?

This is occured on both a self-hosted (docker) install and a Voltage BTCPay instance

### What happened?

I found a bug when paying with a boltcard while LNURL is enabled in your Lightning wallet (v1.13.5).
When this is enabled, a bolt11 without memo is sent (so the decription template is not applied). When disabling LNURL it does work.

### How did you encounter this bug?

I was testing boltcards (CoinCorner, Baltic Honeybadger with laser eyes, green BTCPay card I bought in Prague) and noticed that some BTCPay instances to honor the description template of the Lightning invoice and others not.

When LNURL is enabled (`Lightning -> Settings -> LNURL -> Enable LNURL`) I noticed that the bolt11 invoice sent to the callback URL is much shorter. When decoding it, it shows that BTCPayServer does not set a memo according to the template set in `Lightning -> Settings -> Description template of the lightning invoice`. When disabling the toggle "Enable LNURL" it does add a bolt11 memo according to the description template. 

### Relevant log output

```shell
btcpayserver-1  | fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: An unhandled exception has occurred while executing the request.
btcpayserver-1  | System.NullReferenceException: Object reference not set to an instance of an object.
btcpayserver-1  |    at BTCPayServer.Plugins.NFC.NFCController.SubmitLNURLWithdrawForInvoice(SubmitRequest request) in /source/BTCPayServer/Plugins/NFC/NFCController.cs:line 50
btcpayserver-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
btcpayserver-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
btcpayserver-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
btcpayserver-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
btcpayserver-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
btcpayserver-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
btcpayserver-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
btcpayserver-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
btcpayserver-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
btcpayserver-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
btcpayserver-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
btcpayserver-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
btcpayserver-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
btcpayserver-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
btcpayserver-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
btcpayserver-1  |    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
btcpayserver-1  |    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
btcpayserver-1  |    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
btcpayserver-1  |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
btcpayserver-1  |    at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 97
btcpayserver-1  |    at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 30
btcpayserver-1  |    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
btcpayserver-1  | fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HN5L7FR27LLS", Request id "0HN5L7FR27LLS:00000027": An unhandled exception was thrown by the application.
btcpayserver-1  | System.InvalidOperationException: The exception handler configured on ExceptionHandlerOptions produced a 404 status response. This InvalidOperationException containing the original exception was thrown since this is often due to a misconfigured Excepti
onHandlingPath. If the exception handler is expected to return 404 status responses then set AllowStatusCode404Response to true.
btcpayserver-1  |  ---> System.NullReferenceException: Object reference not set to an instance of an object.
btcpayserver-1  |    at BTCPayServer.Plugins.NFC.NFCController.SubmitLNURLWithdrawForInvoice(SubmitRequest request) in /source/BTCPayServer/Plugins/NFC/NFCController.cs:line 50
btcpayserver-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
btcpayserver-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
btcpayserver-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
btcpayserver-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
btcpayserver-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
btcpayserver-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
btcpayserver-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
btcpayserver-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
btcpayserver-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
btcpayserver-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
btcpayserver-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
btcpayserver-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
btcpayserver-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
btcpayserver-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
btcpayserver-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
btcpayserver-1  |    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
btcpayserver-1  |    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
btcpayserver-1  |    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
btcpayserver-1  |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
btcpayserver-1  |    at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 97
btcpayserver-1  |    at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 30
btcpayserver-1  |    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
btcpayserver-1  |    --- End of inner exception stack trace ---
```

### What browser do you use?

Chrome 127.0.6533.84 on Bitcoinize PoS (Android 12)

### Additional information

This occurred on a local instance of BTCPayServer connected to LND and via the Blink API connection, and on a Voltage BTCPayServer instance connected to LND.

"Use classic checkout" is disabled
"LNURL Classic Mode" is enabled
"Allow payee to pass a comment" is enabled

An invoice with LNURL enabled:
`lnbc220n1pntp42tpp5cr5qg6kkev7wsh8u9x6cc0vhgjfufvsddpt68ju9sgn5gh29cmcshp5dytw043gpxa5ecurcrqhrw659efa5e2szavr49mmspxtldu50rtqcqzpuxqz6gsp52tmnmp4pd9qfq57ka2ztkz63q7srcvcktmkysv3qlxl3m3n28e0s9qxpqysgq3kmh9hwmxch4n7f2yzv0qe6vpyskgl8q7xxne4ztzvsmlmsrkq95qd90sd3ewrke8y6fhfdguj9j8a4l2ztxad2xflfxz8nmrwqt97qpvgc6cc`

An invoice with LNURL disabled:
`lnbc220n1pntp4dcpp5vn5sa79lm8ff0ustqhsk49f05z4pvtlqhkjuefz8u0ffwzxgu3tsdzl2pskjepqw3hjqsnfw33k76twypgx75eqg3jk6meq9p8hyer9wgsyj3p6ypf5uu340fn4gdrpf4zrydmk2ajrxumfgap9w2gcqzpuxqz6gsp5vdtwp8ugdur45ts0q6dvc775hv7vlxy59vk06cgv30a3fnnmq6aq9qxpqysgqchd9c874fh9swl59ra28508x3lpq3kv0vmx505y8ua42wupxcuwjjj8zfvzku0c7pmhptn9ueckrd38evw72rphrf32x0vz4qkfvxrcp5npdg2`

Both invoices are generated with the same Point of Sale app (keypad, currency EUR, value of 0.01 EUR) for to a store using Blink as Lightning wallet.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by NicolasDorier** [comment]
Ok so I looked into it, and it doesn't seem to be a bug...

We are following the [LUD](https://github.com/lnurl/luds/blob/luds/06.md#notes-on-metadata-for-server-side-lnurl-pay) as expected.
The BOLT11 shouldn't contains the description, only the hash of it. This is the LNURL protocol.

So the issue lie down to wallets which do not properly parse the LNURL metadata to extract the description which is inside.
