### ISSUE TITLE
[Bug]: Pull payment stuck 

### ISSUE THREAD

**Issue by Bit2Cash** [btcpayserver/btcpayserver#6259]
### What is your BTCPay version?

BTCPay Server v1.13.5

### How did you deploy BTCPay Server?

Docker

### What happened?

A pull payment was initiated and now the system is stuck in a loop trying to finish the task. 

### How did you encounter this bug?

I have been testing the Pull payment functionality both with the admin user and another user and at some point the system couldn't finish the task nor cancel it, the logs keep showing the same thing for days. I tried restarting the btcpayserver docker, LND and the whole instance to no avail. 

### Relevant log output

```shell
This is the btcpayserver logs 

warn: BTCPayServer.Payments.Lightning.LightningPendingPayoutListener: InitializeTasks failed
BTCPayServer.Lightning.LND.LndException: payment isn't initiated
   at BTCPayServer.Lightning.LND.LndClient.LndPaymentClientSession.ListenLoop(HttpRequestMessage request)
   at BTCPayServer.Lightning.LND.LndClient.LndPaymentClientSession.WaitPayment(CancellationToken cancellation)
   at BTCPayServer.Lightning.LND.LndClient.GetPayment(String paymentHash, CancellationToken cancellation)
   at BTCPayServer.Lightning.LND.LndClient.BTCPayServer.Lightning.ILightningClient.GetPayment(String paymentHash, CancellationToken cancellation)
   at BTCPayServer.Payments.Lightning.LightningPendingPayoutListener.Act() in /source/BTCPayServer/Payments/Lightning/LightningPendingPayoutListener.cs:line 105
   at BTCPayServer.Payments.Lightning.LightningPendingPayoutListener.Act() in /source/BTCPayServer/Payments/Lightning/LightningPendingPayoutListener.cs:line 131
   at BTCPayServer.HostedServices.BaseAsyncService.CreateLoopTask(Func`1 act, String caller) in /source/BTCPayServer/HostedServices/BaseAsyncService.cs:line 55


This is the LND logs showing this error at regular intervals 

[ERR] RPCS: [/routerrpc.Router/TrackPaymentV2]: rpc error: code = NotFound desc = payment isn't initiated
```

### Are you sure this is a bug report?

- [ ] I confirm this is a bug report

**Comment by pavlenex** [comment]
@Kukks any idea what might be happening here? I think a few folks posted on Telegram by now about payouts being stuck unsure if you remember.

**Comment by NicolasDorier** [comment]
I could replicate. On it

**Comment by NicolasDorier** [comment]
https://github.com/btcpayserver/BTCPayServer.Lightning/commit/fc53710f565988c310fc841b4b20da79f49cd28b
