### ISSUE TITLE
[Bug]: NBX Connection Error with Fully Synced Bitcoin Node

### ISSUE THREAD

**Issue by ealvar13** [btcpayserver/btcpayserver#6269]
### What is your BTCPay version?

BTCPay Server v1.10.3+983b8c1f5

Pruning to 25 GB

### How did you deploy BTCPay Server?

Docker deployment on Akamai / Linode

<img width="224" alt="image" src="https://github.com/user-attachments/assets/0033d535-1947-4193-8c68-109453efc1b9">

### What happened?

I'm having trouble with another btcpay server's NBXplorer failing to index.

The bitcoin node is up to date.  Restarting btcpay using the btcpay-restart.sh script doesn't work.  My NBX is just stuck and this is the failure message from the docker container logs.

I have also tried rebooting the server.

This similar issue seems to be unresolved but is marked closed? https://github.com/btcpayserver/btcpayserver/issues/2722 

I recently had to wipe a testnet server for this same issue.  Any ideas? 

Any help would be very appreciated!

![image](https://github.com/user-attachments/assets/2074e5c2-9d28-41bb-9517-c2c9647e37cf)

The postgres logs look ok....but I don't see any hints that NBX is trying to connect

![image](https://github.com/user-attachments/assets/1eb3ea1d-c4dc-4b19-a979-386419c61159)

The front end shows that the blocks are not syncronizing, however I can tell from looking at the bitcoin docker container logs that they are in fact up to date:
<img width="322" alt="image" src="https://github.com/user-attachments/assets/9b2f42cd-d18e-4de9-910e-aa1ed2de7c04">

<img width="467" alt="image" src="https://github.com/user-attachments/assets/5995de5f-b34c-41c5-9b55-5b24db3f3e61">

### How did you encounter this bug?

This happens randomly. I haven't been able to fix it or notice a pattern to the occurences.  It also happened on a testnet node we were running and I had to erase it because I couldn't solve the issue.

### Relevant log output

```shell
fail: NBXplorer.Indexer.BTC: Unhandled exception in the indexer, retrying in 60 seconds
System.OperationCanceledException: The operation was canceled.
   at System.Threading.Channels.AsyncOperation`1.GetResult(Int16 token)
   at System.Threading.Channels.ChannelReader`1.ReadAllAsync(CancellationToken cancellationToken)+MoveNext()
   at System.Threading.Channels.ChannelReader`1.ReadAllAsync(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 104
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 104
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 166
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 78
   at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoop() in /source/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 56
info: NBXplorer.Events: BTC: Node state changed: NBXplorerSynching => NotStarted
info: NBXplorer.Indexer.BTC: TCP Connection succeed, handshaking...
info: NBXplorer.Indexer.BTC: Handshaked
info: NBXplorer.Indexer.BTC: Testing RPC connection to http://bitcoind:43782/
info: NBXplorer.Indexer.BTC: RPC connection successful
info: NBXplorer.Indexer.BTC: Full node version detected: 250000
info: NBXplorer.Indexer.BTC: NBXplorer is correctly whitelisted by the node
info: NBXplorer.Events: BTC: Node state changed: NotStarted => NBXplorerSynching
```

### What browser do you use?

Chrome

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
You're running a very old verison please update and try again. If you're still facing the issue re open the issue, thanks!

**Comment by ealvar13** [comment]
Thanks Pavlenex.  I updated to version but am still experiencing the same issue.

New BTCPay version: © BTCPay Server v1.13.5+30d91d0bd
New NBXplorer version: nbxplorer:2.5.7 

The bitcoin node seems to have restarted with no issues and is syncing according to the logs.

Any ideas what I can try next?

Error log from NBXplorer docker container:
<img width="1112" alt="image" src="https://github.com/user-attachments/assets/1d5596df-8890-4d94-8a83-f5ab8eb8fea8">

Error message:
fail: NBXplorer.Indexer.BTC: Unhandled exception in the indexer, retrying in 20 seconds
System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync(Socket socket)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP, CancellationToken cancellationToken)
   at NBitcoin.Protocol.Connectors.DefaultEndpointConnector.ConnectSocket(Socket socket, EndPoint endpoint, NodeConnectionParameters nodeConnectionParameters, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at NBitcoin.Protocol.DnsResolver.GetHostAddressesAsync(String hostNameOrAddress, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
--- End of stack trace from previous location ---
   at NBitcoin.Protocol.Connectors.DefaultEndpointConnector.ConnectSocket(Socket socket, EndPoint endpoint, NodeConnectionParameters nodeConnectionParameters, CancellationToken cancellationToken)
   at NBitcoin.Protocol.Node.ConnectAsync(Network network, EndPoint endpoint, NetworkAddress peer, NodeConnectionParameters parameters)
   at NBXplorer.Backend.Indexer.ConnectNode(CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 299
   at NBXplorer.Backend.Indexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 146
   at NBXplorer.Backend.Indexer.IndexerLoop() in /source/NBXplorer/Backend/Indexer.cs:line 95

**Comment by pavlenex** [comment]
@ealvar13 It looks like it needs time to sync, is it okay now, doesn't look stuck from the logs?

cc @NicolasDorier

**Comment by ealvar13** [comment]
Hi Pavlenex,

Thank you so much for all your help.  I really appreciate it.

NBXplorer is still stuck I believe.  I believe the bitcoin node is correctly working, which is why the total block height (currently 864,118 at the time of this is message) is updated.  However, NBXplorer is stuck on the same block: 847,519.  There is something, which is reflected in the logs but not in enough detail for me to understand, that is causing an exception in NBX.

I'm not sure what this issue is with NBX.  I've tried every combination of restart / update that I can think of.   

Any thoughts on what I could try would be very appreciated.   


<img width="360" alt="image" src="https://github.com/user-attachments/assets/4c8d5228-43e8-4e3e-9383-1e0cb9d828a4">

**Comment by pavlenex** [comment]
@ealvar13 Interesting, could you paste nbx container logs?

**Comment by ealvar13** [comment]
Hi @pavlenex for sure.  I really appreciate your help!  I hope this isn't something easy that I am missing.  

Here are the last 100 logs from the NBX container:

   at NBXplorer.Backend.Indexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 148
   at NBXplorer.Backend.Indexer.IndexerLoop() in /source/NBXplorer/Backend/Indexer.cs:line 95
info: NBXplorer.Indexer.BTC: TCP Connection succeed, handshaking...
info: NBXplorer.Indexer.BTC: Handshaked
info: NBXplorer.Indexer.BTC: Testing RPC connection to http://bitcoind:43782/
info: NBXplorer.Indexer.BTC: RPC connection successful
info: NBXplorer.Indexer.BTC: Full node version detected: 260000
info: NBXplorer.Indexer.BTC: NBXplorer is correctly whitelisted by the node
info: NBXplorer.Events: BTC: Node state changed: NotStarted => NBXplorerSynching
fail: NBXplorer.Indexer.BTC: Unhandled exception in the indexer, retrying in 60 seconds
System.OperationCanceledException: The peer has been disconnected
   at NBXplorer.Backend.Indexer.AskNextHeaders(Node node, CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 382
   at NBXplorer.Backend.Indexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 215
   at NBXplorer.Backend.Indexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 220
   at NBXplorer.Backend.Indexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 148
   at NBXplorer.Backend.Indexer.IndexerLoop() in /source/NBXplorer/Backend/Indexer.cs:line 95
info: NBXplorer.Events: BTC: Node state changed: NBXplorerSynching => NotStarted
info: NBXplorer.Indexer.BTC: TCP Connection succeed, handshaking...
info: NBXplorer.Indexer.BTC: Handshaked
info: NBXplorer.Indexer.BTC: Testing RPC connection to http://bitcoind:43782/
info: NBXplorer.Indexer.BTC: RPC connection successful
info: NBXplorer.Indexer.BTC: Full node version detected: 260000
info: NBXplorer.Indexer.BTC: NBXplorer is correctly whitelisted by the node
info: NBXplorer.Events: BTC: Node state changed: NotStarted => NBXplorerSynching
fail: NBXplorer.Indexer.BTC: Unhandled exception in the indexer, retrying in 60 seconds
System.OperationCanceledException: The peer has been disconnected
   at NBXplorer.Backend.Indexer.AskNextHeaders(Node node, CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 382
   at NBXplorer.Backend.Indexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 215
   at NBXplorer.Backend.Indexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 220
   at NBXplorer.Backend.Indexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 148
   at NBXplorer.Backend.Indexer.IndexerLoop() in /source/NBXplorer/Backend/Indexer.cs:line 95
info: NBXplorer.Events: BTC: Node state changed: NBXplorerSynching => NotStarted
info: NBXplorer.Indexer.BTC: TCP Connection succeed, handshaking...
info: NBXplorer.Indexer.BTC: Handshaked
info: NBXplorer.Indexer.BTC: Testing RPC connection to http://bitcoind:43782/
info: NBXplorer.Indexer.BTC: RPC connection successful
info: NBXplorer.Indexer.BTC: Full node version detected: 260000
info: NBXplorer.Indexer.BTC: NBXplorer is correctly whitelisted by the node
info: NBXplorer.Events: BTC: Node state changed: NotStarted => NBXplorerSynching
fail: NBXplorer.Indexer.BTC: Unhandled exception in the indexer, retrying in 60 seconds
System.OperationCanceledException: The peer has been disconnected
   at NBXplorer.Backend.Indexer.AskNextHeaders(Node node, CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 382
   at NBXplorer.Backend.Indexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 215
   at NBXplorer.Backend.Indexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 220
   at NBXplorer.Backend.Indexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 148
   at NBXplorer.Backend.Indexer.IndexerLoop() in /source/NBXplorer/Backend/Indexer.cs:line 95
info: NBXplorer.Events: BTC: Node state changed: NBXplorerSynching => NotStarted
info: NBXplorer.Indexer.BTC: TCP Connection succeed, handshaking...
info: NBXplorer.Indexer.BTC: Handshaked
info: NBXplorer.Indexer.BTC: Testing RPC connection to http://bitcoind:43782/
info: NBXplorer.Indexer.BTC: RPC connection successful
info: NBXplorer.Indexer.BTC: Full node version detected: 260000
info: NBXplorer.Indexer.BTC: NBXplorer is correctly whitelisted by the node
info: NBXplorer.Events: BTC: Node state changed: NotStarted => NBXplorerSynching
info: NBXplorer.Indexer.BTC: Node disconnected (Sync seems stuck after block 000000000000000000004d0af6ead9af9ef44d5ee71d13f706da8e7aa4053067 (000000000000000000004d0af6ead9af9ef44d5ee71d13f706da8e7aa4053067), restarting the connection.)
info: NBXplorer.Events: BTC: Node state changed: NBXplorerSynching => NotStarted
fail: NBXplorer.Indexer.BTC: Unhandled exception in the indexer, retrying in 60 seconds
System.OperationCanceledException: The peer has been disconnected
   at NBXplorer.Backend.Indexer.AskNextHeaders(Node node, CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 382
   at NBXplorer.Backend.Indexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 215
   at NBXplorer.Backend.Indexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 220
   at NBXplorer.Backend.Indexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 148
   at NBXplorer.Backend.Indexer.IndexerLoop() in /source/NBXplorer/Backend/Indexer.cs:line 95
info: NBXplorer.Indexer.BTC: TCP Connection succeed, handshaking...
info: NBXplorer.Indexer.BTC: Handshaked
info: NBXplorer.Indexer.BTC: Testing RPC connection to http://bitcoind:43782/
info: NBXplorer.Indexer.BTC: RPC connection successful
info: NBXplorer.Indexer.BTC: Full node version detected: 260000
info: NBXplorer.Indexer.BTC: NBXplorer is correctly whitelisted by the node
info: NBXplorer.Events: BTC: Node state changed: NotStarted => NBXplorerSynching
fail: NBXplorer.Indexer.BTC: Unhandled exception in the indexer, retrying in 60 seconds
System.OperationCanceledException: The peer has been disconnected
   at NBXplorer.Backend.Indexer.AskNextHeaders(Node node, CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 382
   at NBXplorer.Backend.Indexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 215
   at NBXplorer.Backend.Indexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 220
   at NBXplorer.Backend.Indexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 148
   at NBXplorer.Backend.Indexer.IndexerLoop() in /source/NBXplorer/Backend/Indexer.cs:line 95
info: NBXplorer.Events: BTC: Node state changed: NBXplorerSynching => NotStarted
info: NBXplorer.Indexer.BTC: TCP Connection succeed, handshaking...
info: NBXplorer.Indexer.BTC: Handshaked
info: NBXplorer.Indexer.BTC: Testing RPC connection to http://bitcoind:43782/
info: NBXplorer.Indexer.BTC: RPC connection successful
info: NBXplorer.Indexer.BTC: Full node version detected: 260000
info: NBXplorer.Indexer.BTC: NBXplorer is correctly whitelisted by the node
info: NBXplorer.Events: BTC: Node state changed: NotStarted => NBXplorerSynching
fail: NBXplorer.Indexer.BTC: Unhandled exception in the indexer, retrying in 60 seconds
System.OperationCanceledException: The peer has been disconnected
   at NBXplorer.Backend.Indexer.AskNextHeaders(Node node, CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 382
   at NBXplorer.Backend.Indexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 215
   at NBXplorer.Backend.Indexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 220
   at NBXplorer.Backend.Indexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 148
   at NBXplorer.Backend.Indexer.IndexerLoop() in /source/NBXplorer/Backend/Indexer.cs:line 95
info: NBXplorer.Events: BTC: Node state changed: NBXplorerSynching => NotStarted
info: NBXplorer.Indexer.BTC: TCP Connection succeed, handshaking...
info: NBXplorer.Indexer.BTC: Handshaked
info: NBXplorer.Indexer.BTC: Testing RPC connection to http://bitcoind:43782/
info: NBXplorer.Indexer.BTC: RPC connection successful
info: NBXplorer.Indexer.BTC: Full node version detected: 260000
info: NBXplorer.Indexer.BTC: NBXplorer is correctly whitelisted by the node
info: NBXplorer.Events: BTC: Node state changed: NotStarted => NBXplorerSynching

**Comment by NicolasDorier** [comment]
I fear that this error come from the fact that you node is pruned, and NBXplorer is asking for blocks from the time it dropped out... Blocks that have been pruned, and as such the node can't provide you anything.
