### ISSUE TITLE
[Bug]: Adding a CoinJoin Coordinator causes CPU core spike

### ISSUE THREAD

**Issue by benjaminchodroff** [btcpayserver/btcpayserver#6380]
### What is your BTCPay version?

BTCPay Server v2.0.2+b70c004f2

### How did you deploy BTCPay Server?

Docker on a 12 core/32GB/2TB NVME Intel i7 NUC. 

### What happened?

CoinJoin add coordinator causes a CPU core to spike to 100%

### How did you encounter this bug?

Not sure how long the problem has existed, and not able to reproduce on other setups.

1. Install CoinJoin plugin 1.0.103.0 
2. Add either a local coordinator (another bug - not possible to remove the local coordinator once added) or temporarily add a remote coordinator (mega.cash, for example - but all can reproduce the issue)
3. CPU spikes to 100% of one core caused by dotnet BTCPayServer.dll process, even when not mixing and CoinJoin plugin still not enabled "active"
4. Remove the remote coordinator and the CPU spike will stop 
5. It is not possible to remove the local coordinator - even disabling the local coordinator will not stop the CPU spike, must remove the plugin to stop the CPU spike
6. Pruning all past bitcoin coordinator transactions or removing the Bitcoin Wallet will not stop the CPU spike
7. No relevant logs found, not seeing any way to enable further debug or trace on CoinJoin plugin

### Relevant log output

```shell
2024-11-11 00:44:03.143 +00:00 [INF] A soft restart has been requested
2024-11-11 00:44:06.162 +00:00 [INF] DelayedTransactionBroadcasterHostedService successfully exited...
2024-11-11 00:44:06.167 +00:00 [INF] TorServices successfully exited...
2024-11-11 00:44:06.172 +00:00 [INF] CheckConfigurationHostedService successfully exited...
2024-11-11 00:44:06.177 +00:00 [INF] PullPaymentHostedService successfully exited...
2024-11-11 00:44:06.179 +00:00 [INF] Disconnected from WebSocket of NBXplorer (BTC)
2024-11-11 00:44:06.180 +00:00 [INF] NBXplorerListener successfully exited...
2024-11-11 00:44:06.181 +00:00 [INF] LightningListener successfully exited...
2024-11-11 00:44:06.182 +00:00 [INF] LightningPendingPayoutListener successfully exited...
2024-11-11 00:44:06.184 +00:00 [INF] Stop watching invoices
2024-11-11 00:44:06.199 +00:00 [INF] RatesHostedService successfully exited...
2024-11-11 00:44:06.216 +00:00 [INF] DynamicDnsHostedService successfully exited...
2024-11-11 00:44:06.221 +00:00 [INF] DbMigrationsHostedService successfully exited...
2024-11-11 00:44:08.956 +00:00 [INF] Running the migration scripts...
2024-11-11 00:44:09.048 +00:00 [INF] No migrations were applied. The database is already up to date.
2024-11-11 00:44:09.049 +00:00 [INF] All migration scripts ran successfully
2024-11-11 00:44:09.342 +00:00 [INF] Root Path: /
2024-11-11 00:44:09.979 +00:00 [INF] Connection to NBXplorer's database successful, dashboard and reporting features activated.
2024-11-11 00:44:09.980 +00:00 [INF] SSH settings detected, testing connection to root@host.docker.internal on port 22 ...
2024-11-11 00:44:10.021 +00:00 [INF] Checking if any payment arrived on lightning while the server was offline...
2024-11-11 00:44:10.049 +00:00 [INF] SSH connection succeeded
2024-11-11 00:44:10.075 +00:00 [INF] Processing lightning payments...
2024-11-11 00:44:10.114 +00:00 [INF] Starting listening NBXplorer (BTC)
2024-11-11 00:44:10.120 +00:00 [INF] Start watching invoices
2024-11-11 00:44:10.162 +00:00 [INF] Starting payment request expiration watcher
2024-11-11 00:44:10.175 +00:00 [INF] BTC: Checking if any pending invoice got paid while offline...
2024-11-11 00:44:10.180 +00:00 [INF] BTC: 0 payments happened while offline
2024-11-11 00:44:10.180 +00:00 [INF] Connected to WebSocket of NBXplorer (BTC)
2024-11-11 00:44:10.213 +00:00 [INF] 0 pending payment requests being checked since last run
2024-11-11 00:44:10.234 +00:00 [INF] Starting listening Monero-like daemons (XMR)
2024-11-11 00:44:10.240 +00:00 [INF] Starting listening TronUSDt-like daemons (USDT-TRON)
2024-11-11 00:44:10.254 +00:00 [INF] XMR just became available
2024-11-11 00:44:11.057 +00:00 [INF] Tracking state, current=66878736, latest=66878752
2024-11-11 00:44:11.259 +00:00 [INF] New block avoid from 66878736 to 66878752
2024-11-11 00:44:41.485 +00:00 [INF] New block avoid from 66878752 to 66878762
2024-11-11 00:45:11.682 +00:00 [INF] New block avoid from 66878762 to 66878772
2024-11-11 00:45:41.882 +00:00 [INF] New block avoid from 66878772 to 66878782
2024-11-11 00:46:12.087 +00:00 [INF] New block avoid from 66878782 to 66878792
2024-11-11 00:46:42.286 +00:00 [INF] New block avoid from 66878792 to 66878802
2024-11-11 00:47:12.497 +00:00 [INF] New block avoid from 66878802 to 66878813
2024-11-11 00:47:42.704 +00:00 [INF] New block avoid from 66878813 to 66878823
2024-11-11 00:47:52.616 +00:00 [INF] 2024-11-11 00:47:52.614 [26] INFO	HostedServices.StartAllAsync (61)	Started RoundStateUpdater.

2024-11-11 00:47:52.624 +00:00 [INF] 2024-11-11 00:47:52.624 [26] INFO	HostedServices.StartAllAsync (61)	Started WasabiCoordinatorStatusFetcher.

2024-11-11 00:47:52.626 +00:00 [INF] 2024-11-11 00:47:52.626 [28] INFO	HostedServices.StartAllAsync (61)	Started WasabiCoordinatorStatusFetcher.

2024-11-11 00:47:54.148 +00:00 [ERR] 2024-11-11 00:47:54.148 [30] ERROR	PeriodicRunner.ExecuteAsync (114)	System.Exception: Could not connect to the coordinator
 ---> System.Net.Http.HttpRequestException: Internal Server Error
{"type":"https://tools.ietf.org/html/rfc9110#section-15.6.1","title":"An error occurred while processing your request.","status":500,"traceId":"00-9a480c636eb498feabbb05c4bf3ad3db-661d17e7d1a19f95-00"}
   at WalletWasabi.Tor.Http.Extensions.HttpResponseMessageExtensions.ThrowRequestExceptionFromContentAsync(HttpResponseMessage me, CancellationToken cancellationToken)
   at WalletWasabi.Tor.Http.Extensions.HttpResponseMessageExtensions.ThrowUnwrapExceptionFromContentAsync(HttpResponseMessage me, CancellationToken cancellationToken)
   at WalletWasabi.WabiSabi.Client.WabiSabiHttpApiClient.SendWithRetriesAsync[TRequest](RemoteAction action, TRequest request, CancellationToken cancellationToken, Nullable`1 retryTimeout)
   at WalletWasabi.WabiSabi.Client.WabiSabiHttpApiClient.SendAndReceiveAsync[TRequest,TResponse](RemoteAction action, TRequest request, CancellationToken cancellationToken, Nullable`1 retryTimeout)
   at BTCPayServer.Plugins.Wabisabi.WasabiCoordinatorStatusFetcher.ActionAsync(CancellationToken cancel) in /build/Plugins/BTCPayServer.Plugins.Wabisabi/WasabiCoordinatorStatusFetcher.cs:line 36
   --- End of inner exception stack trace ---
   at BTCPayServer.Plugins.Wabisabi.WasabiCoordinatorStatusFetcher.ActionAsync(CancellationToken cancel) in /build/Plugins/BTCPayServer.Plugins.Wabisabi/WasabiCoordinatorStatusFetcher.cs:line 49
   at WalletWasabi.Bases.PeriodicRunner.ExecuteAsync(CancellationToken stoppingToken)

2024-11-11 00:48:12.907 +00:00 [INF] New block avoid from 66878823 to 66878833
2024-11-11 00:48:43.107 +00:00 [INF] New block avoid from 66878833 to 66878843
2024-11-11 00:48:56.799 +00:00 [INF] 2024-11-11 00:48:56.799 [5] INFO	HostedServices.StopAllAsync (89)	Stopped RoundStateUpdater.

2024-11-11 00:48:56.801 +00:00 [INF] 2024-11-11 00:48:56.801 [26] INFO	CoinJoinManager.WaitAndHandleResultOfTasksAsync (716)	Task 'walletsMonitoringTask' finished successfully.

2024-11-11 00:48:56.801 +00:00 [INF] 2024-11-11 00:48:56.801 [5] INFO	CoinJoinManager.WaitAndHandleResultOfTasksAsync (720)	Task 'commandsHandlingTask' finished successfully by cancellation.

2024-11-11 00:48:56.801 +00:00 [INF] 2024-11-11 00:48:56.801 [5] INFO	CoinJoinManager.WaitAndHandleResultOfTasksAsync (720)	Task 'monitorCoinJoinTask' finished successfully by cancellation.

2024-11-11 00:48:56.802 +00:00 [INF] 2024-11-11 00:48:56.802 [26] INFO	HostedServices.StopAllAsync (89)	Stopped WasabiCoordinatorStatusFetcher.

2024-11-11 00:48:56.802 +00:00 [INF] 2024-11-11 00:48:56.802 [5] INFO	CoinJoinManager.WaitAndHandleResultOfTasksAsync (716)	Task 'monitorAndHandleCoinjoinsTask' finished successfully.

2024-11-11 00:48:56.802 +00:00 [INF] 2024-11-11 00:48:56.802 [29] INFO	HostedServices.StopAllAsync (89)	Stopped WasabiCoordinatorStatusFetcher.

2024-11-11 00:49:13.309 +00:00 [INF] New block avoid from 66878843 to 66878853
```

### What browser do you use?

Chromium 130

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by pavlenex** [comment]
Hey since this is plugin related issue, you should log it in plugin authors repo https://github.com/Kukks/BTCPayServerPlugins/issues cc @Kukks
