### ISSUE TITLE
Web UI doesn't display sync progress - sometimes

### ISSUE THREAD

**Issue by Janaka-Steph** [btcpayserver/btcpayserver#700]
**Describe the problem/bug**
Even if my node is properly synching, the web UI says `NBXplorer headers height: 0
The node is starting...`, doesn't show the progress bar and I have an error in nbxplorer logs.
This happens sometimes, not sure how to reproduce. 

**Your environment**
* Version of BTCPay Server: v1.0.3.88
* Deployment method: docker
* Other relevant environment details: on single-board Odroid xu4, Ubuntu 18.04 image

**Logs (if applicable)**
docker logs generated_nbxplorer_1
```
fail: Configuration:  BTC: Unhandled in Waiter loop
System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException: Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at NBitcoin.RPC.RPCClient.SendCommandAsyncCore(RPCRequest request, Boolean throwIfRPCError)
   at NBitcoin.RPC.RPCClient.SendCommandAsync(RPCRequest request, Boolean throwIfRPCError)
   at NBitcoin.RPC.RPCClient.SetVersion(RPCCapabilities capabilities)
   at NBitcoin.RPC.RPCClient.ScanRPCCapabilitiesAsync()
   at NBXplorer.Configuration.RPCArgs.TestRPCAsync(NBXplorerNetwork networkInfo, RPCClient rpcClient, CancellationToken cancellation) in /source/NBXplorer/Configuration/RPCArgs.cs:line 135
   at NBXplorer.BitcoinDWaiter.StepAsync(CancellationToken token) in /source/NBXplorer/BitcoinDWaiter.cs:line 263
   at NBXplorer.BitcoinDWaiter.StartLoop(CancellationToken token, AutoResetEvent tick) in /source/NBXplorer/BitcoinDWaiter.cs:line 200
```

**Comment by Kukks** [comment]
`./btcpay-down.sh && ./btcpay-up.sh` Sometimes you just need to give it a restart

**Comment by Janaka-Steph** [comment]
Thank you for this comment but I already tried that.

**Comment by Janaka-Steph** [comment]
I add some NBxplorer logs
```
fail: Configuration:  BTC: Failed to connect to RPC
System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException: Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at NBitcoin.RPC.RPCClient.SendCommandAsyncCore(RPCRequest request, Boolean throwIfRPCError)
   at NBitcoin.RPC.RPCClient.SendCommandAsync(RPCRequest request, Boolean throwIfRPCError)
   at NBXplorer.RPCClientExtensions.GetBlockchainInfoAsyncEx(RPCClient client) in /source/NBXplorer/RPCClientExtensions.cs:line 69
   at NBXplorer.BitcoinDWaiter.StepAsync(CancellationToken token) in /source/NBXplorer/BitcoinDWaiter.cs:line 302
info: Events:         BTC: Node state changed: CoreSynching => NotStarted
info: Configuration:  BTC: Testing RPC connection to http://bitcoind:43782/
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HLLDUDFLT1QD", Request id "0HLLDUDFLT1QD:00000001": An unhandled exception was thrown by the application.
System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException: Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at NBitcoin.RPC.RPCClient.SendCommandAsyncCore(RPCRequest request, Boolean throwIfRPCError)
   at NBitcoin.RPC.RPCClient.SendCommandAsync(RPCRequest request, Boolean throwIfRPCError)
   at NBXplorer.RPCClientExtensions.GetBlockchainInfoAsyncEx(RPCClient client) in /source/NBXplorer/RPCClientExtensions.cs:line 69
   at NBXplorer.Controllers.MainController.GetStatus(String cryptoCode) in /source/NBXplorer/Controllers/MainController.cs:line 186
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ExceptionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
fail: Configuration:  BTC: Error connecting to RPC server The operation was canceled.
fail: Configuration:  BTC: Unhandled in Waiter loop
NBXplorer.Configuration.ConfigException
   at NBXplorer.Configuration.RPCArgs.TestRPCAsync(NBXplorerNetwork networkInfo, RPCClient rpcClient, CancellationToken cancellation) in /source/NBXplorer/Configuration/RPCArgs.cs:line 132
   at NBXplorer.BitcoinDWaiter.StepAsync(CancellationToken token) in /source/NBXplorer/BitcoinDWaiter.cs:line 263
   at NBXplorer.BitcoinDWaiter.StartLoop(CancellationToken token, AutoResetEvent tick) in /source/NBXplorer/BitcoinDWaiter.cs:line 200
info: Configuration:  BTC: Testing RPC connection to http://bitcoind:43782/
fail: Configuration:  BTC: Error connecting to RPC server The operation was canceled.
fail: Configuration:  BTC: Unhandled in Waiter loop
NBXplorer.Configuration.ConfigException
   at NBXplorer.Configuration.RPCArgs.TestRPCAsync(NBXplorerNetwork networkInfo, RPCClient rpcClient, CancellationToken cancellation) in /source/NBXplorer/Configuration/RPCArgs.cs:line 132
   at NBXplorer.BitcoinDWaiter.StepAsync(CancellationToken token) in /source/NBXplorer/BitcoinDWaiter.cs:line 263
   at NBXplorer.BitcoinDWaiter.StartLoop(CancellationToken token, AutoResetEvent tick) in /source/NBXplorer/BitcoinDWaiter.cs:line 200
info: Configuration:  BTC: Testing RPC connection to http://bitcoind:43782/
fail: Configuration:  BTC: Error connecting to RPC server The operation was canceled.
fail: Configuration:  BTC: Unhandled in Waiter loop
NBXplorer.Configuration.ConfigException
   at NBXplorer.Configuration.RPCArgs.TestRPCAsync(NBXplorerNetwork networkInfo, RPCClient rpcClient, CancellationToken cancellation) in /source/NBXplorer/Configuration/RPCArgs.cs:line 132
   at NBXplorer.BitcoinDWaiter.StepAsync(CancellationToken token) in /source/NBXplorer/BitcoinDWaiter.cs:line 263
   at NBXplorer.BitcoinDWaiter.StartLoop(CancellationToken token, AutoResetEvent tick) in /source/NBXplorer/BitcoinDWaiter.cs:line 200
info: Configuration:  BTC: Testing RPC connection to http://bitcoind:43782/
fail: Configuration:  BTC: Error connecting to RPC server The operation was canceled.
fail: Configuration:  BTC: Unhandled in Waiter loop
NBXplorer.Configuration.ConfigException
   at NBXplorer.Configuration.RPCArgs.TestRPCAsync(NBXplorerNetwork networkInfo, RPCClient rpcClient, CancellationToken cancellation) in /source/NBXplorer/Configuration/RPCArgs.cs:line 132
   at NBXplorer.BitcoinDWaiter.StepAsync(CancellationToken token) in /source/NBXplorer/BitcoinDWaiter.cs:line 263
   at NBXplorer.BitcoinDWaiter.StartLoop(CancellationToken token, AutoResetEvent tick) in /source/NBXplorer/BitcoinDWaiter.cs:line 200
info: Configuration:  BTC: Testing RPC connection to http://bitcoind:43782/
```

**Comment by Janaka-Steph** [comment]
Bitcoind logs at startup says Binding RPC failed

```
2019-03-23T12:04:03Z Using 16 MiB out of 32/2 requested for signature cache, able to store 524288 elements
2019-03-23T12:04:04Z Using 16 MiB out of 32/2 requested for script execution cache, able to store 524288 elements
2019-03-23T12:04:04Z Using 8 threads for script verification
2019-03-23T12:04:04Z scheduler thread start
2019-03-23T12:04:04Z libevent: getaddrinfo: address family for nodename not supported
**2019-03-23T12:04:04Z Binding RPC on address :: port 43782 failed.**
2019-03-23T12:04:04Z HTTP: creating work queue of depth 16
**2019-03-23T12:04:04Z No rpcpassword set - using random cookie authentication.**
2019-03-23T12:04:04Z Generated RPC authentication cookie /home/bitcoin/.bitcoin/.cookie
2019-03-23T12:04:04Z HTTP: starting 4 worker threads
2019-03-23T12:04:04Z Cache configuration:
2019-03-23T12:04:04Z * Using 2.0MiB for block index database
2019-03-23T12:04:04Z * Using 8.0MiB for chain state database
2019-03-23T12:04:04Z * Using 440.0MiB for in-memory UTXO set (plus up to 286.1MiB of unused mempool space)
```

**Comment by Kukks** [comment]
@Janaka-Steph  last log hits the spot
can you try adding `rpcbind=0.0.0.0` to the bitcoin.conf file  either directly or by editing the generated docker compose or the bitcoin docker fragment?

**Comment by Janaka-Steph** [comment]
I tried editing bitcoin.conf directly but `btcpay-up.sh` overwrite the file back to original. 

So I edited `/root/BTCPayServer/btcpayserver-docker/Generated/docker-compose.generated.yml`

`btcpay-down.sh` and `sudo reboot` just to be sure. 

This is what I have now:
```
bitcoind:
    restart: unless-stopped
    container_name: btcpayserver_bitcoind
    image: btcpayserver/bitcoin:0.17.0
    environment:
      BITCOIN_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      BITCOIN_EXTRA_ARGS: |
        rpcport=43782
        port=39388
        disablewallet=1
        whitelist=0.0.0.0/0
        rpcbind=0.0.0.0

        zmqpubrawblock=tcp://0.0.0.0:28332
        zmqpubrawtx=tcp://0.0.0.0:28333
    expose:
    - "43782"
    - "39388"
    - "28332"
    - "28333"
    volumes:
    - "bitcoin_datadir:/data"
```

And the new generated bitcoin.conf
```
mainnet=1
[main]
printtoconsole=1
rpcallowip=::/0
rpcport=43782
port=39388
disablewallet=1
whitelist=0.0.0.0/0
rpcbind=0.0.0.0

zmqpubrawblock=tcp://0.0.0.0:28332
zmqpubrawtx=tcp://0.0.0.0:28333
```

bitcoind logs doesn't show the binding error anymore.
Unfortunately the problem remains. Stats UI popup is buggy and everytime I refresh the page I will have this error log
```
root@odroid:~# docker logs generated_nbxplorer_1
info: Configuration:  Data Directory: /datadir
info: Configuration:  Configuration File: /datadir/Main/settings.config
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  BTC: Testing RPC connection to http://bitcoind:43782/
Hosting environment: Production
Content root path: /app/
Now listening on: http://0.0.0.0:32838
Application started. Press Ctrl+C to shut down.
info: Configuration:  BTC: Transient error 'Loading block index...', retrying soon...
info: Configuration:  BTC: Transient error 'Loading block index...', retrying soon...
info: Configuration:  BTC: Transient error 'Loading block index...', retrying soon...
info: Configuration:  BTC: Transient error 'Loading block index...', retrying soon...
info: Configuration:  BTC: Transient error 'Loading block index...', retrying soon...
info: Configuration:  BTC: Transient error 'Rewinding blocks...', retrying soon...
info: Configuration:  BTC: Transient error 'Verifying blocks...', retrying soon...
info: Configuration:  BTC: Transient error 'Verifying blocks...', retrying soon...
info: Configuration:  BTC: Transient error 'Verifying blocks...', retrying soon...
info: Configuration:  BTC: Transient error 'Verifying blocks...', retrying soon...
info: Configuration:  BTC: Transient error 'Verifying blocks...', retrying soon...
info: Configuration:  BTC: RPC connection successfull
info: Configuration:  BTC: Full node version detected: 170000
info: Configuration:  BTC: Node banlist loaded
info: Events:         BTC: Node state changed: NotStarted => CoreSynching
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HLLFHVOSLN9V", Request id "0HLLFHVOSLN9V:00000001": An unhandled exception was thrown by the application.
System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException: Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at NBitcoin.RPC.RPCClient.SendCommandAsyncCore(RPCRequest request, Boolean throwIfRPCError)
   at NBitcoin.RPC.RPCClient.SendCommandAsync(RPCRequest request, Boolean throwIfRPCError)
   at NBXplorer.RPCClientExtensions.GetBlockchainInfoAsyncEx(RPCClient client) in /source/NBXplorer/RPCClientExtensions.cs:line 69
   at NBXplorer.Controllers.MainController.GetStatus(String cryptoCode) in /source/NBXplorer/Controllers/MainController.cs:line 186
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ExceptionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

By the way, I am running on mainnet, I don't understand why zmq ports are 28332 and 28333 which I think are testnet ports.

**Comment by Janaka-Steph** [comment]
```
root@odroid:~# docker logs generated_btcpayserver_1
/app/docker-entrypoint.sh: 3: /app/docker-entrypoint.sh: /sbin/ip: not found
info: Configuration:  Data Directory: /datadir
info: Configuration:  Configuration File: /datadir/Main/settings.config
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  LogFile: btcpay.log
info: Configuration:  Log Level: Debug
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  LogFile: btcpay.log
info: Configuration:  Log Level: Debug
info: Configuration:  Root Path: /
info: Configuration:  Postgres DB used (User ID=postgres;Host=postgres;Port=5432;Database=btcpayservermainnet)
info: Configuration:  BTC: Explorer url is http://nbxplorer:32838/
info: Configuration:  BTC: Cookie file is /root/.nbxplorer/Main/.cookie
info: PayServer:      Starting listening NBXplorer (BTC)
info: PayServer:      Start watching invoices
/app/docker-entrypoint.sh: 3: /app/docker-entrypoint.sh: /sbin/ip: not found
info: Configuration:  Data Directory: /datadir
info: Configuration:  Configuration File: /datadir/Main/settings.config
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  LogFile: btcpay.log
info: Configuration:  Log Level: Debug
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  LogFile: btcpay.log
info: Configuration:  Log Level: Debug
info: Configuration:  Root Path: /
info: Configuration:  Postgres DB used (User ID=postgres;Host=postgres;Port=5432;Database=btcpayservermainnet)
info: Configuration:  BTC: Explorer url is http://nbxplorer:32838/
info: Configuration:  BTC: Cookie file is /root/.nbxplorer/Main/.cookie
info: PayServer:      Starting listening NBXplorer (BTC)
info: PayServer:      Start watching invoices
info: Events:         NBXplorer BTC: NotConnected => Synching
info: PayServer:      Starting payment request expiration watcher
info: Configuration:  Listening on http://0.0.0.0:49392
/app/docker-entrypoint.sh: 3: /app/docker-entrypoint.sh: /sbin/ip: not found
info: Configuration:  Data Directory: /datadir
info: Configuration:  Configuration File: /datadir/Main/settings.config
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  LogFile: btcpay.log
info: Configuration:  Log Level: Debug
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  LogFile: btcpay.log
info: Configuration:  Log Level: Debug
info: Configuration:  Root Path: /
info: Configuration:  Postgres DB used (User ID=postgres;Host=postgres;Port=5432;Database=btcpayservermainnet)
info: Configuration:  BTC: Explorer url is http://nbxplorer:32838/
info: Configuration:  BTC: Cookie file is /root/.nbxplorer/Main/.cookie
info: PayServer:      Starting listening NBXplorer (BTC)
info: PayServer:      Start watching invoices
/app/docker-entrypoint.sh: 3: /app/docker-entrypoint.sh: /sbin/ip: not found
info: Configuration:  Data Directory: /datadir
info: Configuration:  Configuration File: /datadir/Main/settings.config
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  LogFile: btcpay.log
info: Configuration:  Log Level: Debug
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  LogFile: btcpay.log
info: Configuration:  Log Level: Debug
info: Configuration:  Root Path: /
info: Configuration:  Postgres DB used (User ID=postgres;Host=postgres;Port=5432;Database=btcpayservermainnet)
info: Configuration:  BTC: Explorer url is http://nbxplorer:32838/
info: Configuration:  BTC: Cookie file is /root/.nbxplorer/Main/.cookie
info: PayServer:      Starting listening NBXplorer (BTC)
/app/docker-entrypoint.sh: 3: /app/docker-entrypoint.sh: /sbin/ip: not found
info: Configuration:  Data Directory: /datadir
info: Configuration:  Configuration File: /datadir/Main/settings.config
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  LogFile: btcpay.log
info: Configuration:  Log Level: Debug
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  LogFile: btcpay.log
info: Configuration:  Log Level: Debug
info: Configuration:  Root Path: /
info: Configuration:  Postgres DB used (User ID=postgres;Host=postgres;Port=5432;Database=btcpayservermainnet)
info: Configuration:  BTC: Explorer url is http://nbxplorer:32838/
info: Configuration:  BTC: Cookie file is /root/.nbxplorer/Main/.cookie
info: PayServer:      Starting listening NBXplorer (BTC)
info: PayServer:      Start watching invoices
info: Events:         NBXplorer BTC: NotConnected => Synching
info: PayServer:      Starting payment request expiration watcher
/app/docker-entrypoint.sh: 3: /app/docker-entrypoint.sh: /sbin/ip: not found
info: Configuration:  Data Directory: /datadir
info: Configuration:  Configuration File: /datadir/Main/settings.config
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  LogFile: btcpay.log
info: Configuration:  Log Level: Debug
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  LogFile: btcpay.log
info: Configuration:  Log Level: Debug
info: Configuration:  Root Path: /
info: Configuration:  Postgres DB used (User ID=postgres;Host=postgres;Port=5432;Database=btcpayservermainnet)
info: Configuration:  BTC: Explorer url is http://nbxplorer:32838/
info: Configuration:  BTC: Cookie file is /root/.nbxplorer/Main/.cookie
info: PayServer:      Starting listening NBXplorer (BTC)
info: PayServer:      Start watching invoices
warn: PayServer:      Error while contacting bittrex: The SSL connection could not be established, see inner exception. Object reference not set to an instance of an object.
info: PayServer:      Starting payment request expiration watcher
warn: PayServer:      Error while contacting poloniex: Object reference not set to an instance of an object.
info: Configuration:  Listening on http://0.0.0.0:49392
info: PayServer:      0 pending payment requests being checked since last run
info: PayServer:      User logged in.
fail: PayServer:      BTC: NBXplorer error `The operation was canceled.`
info: PayServer:      User logged in.
info: Events:         NBXplorer BTC: NotConnected => Synching
fail: PayServer:      BTC: NBXplorer error `The operation was canceled.`
info: Events:         NBXplorer BTC: Synching => NotConnected
info: Events:         NBXplorer BTC: NotConnected => Synching
fail: PayServer:      BTC: NBXplorer error `The operation was canceled.`
info: Events:         NBXplorer BTC: Synching => NotConnected
fail: PayServer:      BTC: NBXplorer error `The operation was canceled.`
info: Events:         NBXplorer BTC: NotConnected => Synching
fail: PayServer:      BTC: NBXplorer error `The operation was canceled.`
info: Events:         NBXplorer BTC: Synching => NotConnected
info: Events:         NBXplorer BTC: NotConnected => Synching
fail: PayServer:      BTC: NBXplorer error `The operation was canceled.`
info: Events:         NBXplorer BTC: Synching => NotConnected
fail: PayServer:      BTC: NBXplorer error `The operation was canceled.`
```

**Comment by NicolasDorier** [comment]
Those timeout are because your node is busy spending too much CPU trying to sync.

**Comment by NicolasDorier** [comment]
Nothing really you can do, unless fast sync.

**Comment by Janaka-Steph** [comment]
Ok, fast sync doesn't work for me. I tried twice and each time the data directory is corrupted.

**Comment by NicolasDorier** [comment]
@Janaka-Steph can you update, normally the errors of NBXplorer should be gone.

**Comment by NicolasDorier** [comment]
At least in the logs of nbxplorer

**Comment by Janaka-Steph** [comment]
My BTCpay is synced now so I don't have the progress bar anymore and can't tell if this bug still exist. I  close the issue, someone else can reopen it if necessary.

**Comment by pantunes** [comment]
> My BTCpay is synced now so I don't have the progress bar anymore and can't tell if this bug still exist. I close the issue, someone else can reopen it if necessary.

Hi Janaka,

What what the solution then?

**Comment by bolatovumar** [comment]
@pantunes normally the solution on this case tends to be "restart your BTCPay".

**Comment by pantunes** [comment]
@bolatovumar 

As adviced before I've done ```./btcpay-down.sh && ./btcpay-up.sh``` with a server reboot and its still the same.

**Comment by pantunes** [comment]
If looking at logs ```docker logs -f btcpayserver_bitcoind``` looks ok though:

so my question is if this is just a UI/service glitch or indeed there is a problem with the sync?


![Screenshot 2020-01-27 at 20 03 56](https://user-images.githubusercontent.com/6731272/73204922-2bfdff00-4140-11ea-8d06-13cb8c477973.png)

**Comment by bolatovumar** [comment]
@pantunes I'm not sure what the underlying issue is. The sync speed depends on how powerful the machine you are running the sync on is and how fast the connection is. @NicolasDorier might have more to say about this.

**Comment by pantunes** [comment]
@bolatovumar and it seems to be working now...haven't change anything just waited some time.

It seems this issue is not consistent.

@bolatovumar thanks for the feedback and help!

**Comment by golyalpha** [comment]
It would seem that it's likely caused by *some* load issue, especially if the issue disappears after the sync is complete.

I have hit the same issue, it looks to show up for the first time somewhere after block 300000 (idk when exactly, I noticed the issue this morning, and it's currently in the 350000's), was there some change in validation rules in that range that would cause an increased load on the node (or maybe just higher average block size)?

Either way, I guess I'll wait for the sync to finish and see if the other components of BTCPay can finally reach the bitcoin node again.
