### ISSUE TITLE
System.Exception: Unable to load bundles (HTTP 500 on initial load web UI)

### ISSUE THREAD

**Issue by aantonop** [btcpayserver/btcpayserver#710]
After successful installation and startup of BTCPay server, an error occurs the first time I try to access the web UI on port 23001. HTTP 500 is returned to the web client and a System Exception occurs in the btcpay logs (logs at the end of this issue)

* Version of BTCPay Server:  v1.0.3.88 (also failing for several other 1.0.3.xx versions tested)
* Deployment method: Manual Build
* Other relevant environment details: Ubuntu 16.04 

**To Reproduce**
- Build and run BTCPay from systemctl startup script 
- BTCPay uccessfully connects to NBXplorer and sees new blocks
- BTCPay starts HTTP server on 23001
- On initial HTTP get of localhost:23001, HTTP500 is returned.
- Logs show system exception in LoadBundles()

Additional details:
- BTCPay server is running as a non-administrative user. 
- daemon user and group have full access to the btcpayserver build and launch directory
- It worked before "bundles"
- Crash happens even when bundlejscss is set to false
- Additional logging added to the code shows that bundlejscss is correctly read as "false" in the daemon execution.
- Daemon user has full file access to bundleconfig.json
- Even when setting 777 permisions on bundleconfig.json, it still crashes

```
 System.Exception: Unable to load bundles.
    at Meziantou.AspNetCore.BundleTagHelpers.BundleProvider.LoadBundles()
    at Meziantou.AspNetCore.BundleTagHelpers.BundleProvider.GetBundle(String name)
    at Meziantou.AspNetCore.BundleTagHelpers.BundleTagHelper.Process(TagHelperContext context, TagHelperOutput output)
    at Microsoft.AspNetCore.Razor.TagHelpers.TagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
    at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.RunAsync(TagHelperExecutionContext executionContext)
    at AspNetCore.Views_Shared__Layout.<ExecuteAsync>b__44_0() in /usr/local/src/BTCPayServer/btcpayserver/BTCPayServer/Views/Shared/_Layout.cshtml:line 27
    at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
    at AspNetCore.Views_Shared__Layout.ExecuteAsync()
    at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
    at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
    at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
    at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
    at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
    at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
    at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
    at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
    at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /usr/local/src/BTCPayServer/btcpayserver/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 55
    at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by rockstardev** [comment]
Seems we need 777 (or at least 664) on all referenced files under `wwwroot`.

This is relevant method that eventually gets called, all I see there is `File.ReadAllText` operations:

https://github.com/meziantou/Meziantou.AspNetCore.BundleTagHelpers/blob/1e2cbc001826bd584abf682b5c1c92e9e3dae8ab/Meziantou.AspNetCore.BundleTagHelpers/BundlerMinifier/Bundle/BundleHandler.cs#L56

**Comment by Kukks** [comment]
@rockstardev  I am just wondering if this is because there is no write permissions to create the actual bundle file?

**Comment by NicolasDorier** [comment]
I think the problem is actually read permission, if the read fails, this is typically what you would have see 

https://github.com/meziantou/Meziantou.AspNetCore.BundleTagHelpers/blob/1e2cbc001826bd584abf682b5c1c92e9e3dae8ab/Meziantou.AspNetCore.BundleTagHelpers/BundlerMinifier/Bundle/BundleHandler.cs#L57

**Comment by NicolasDorier** [comment]
@aantonop I think the problem is that you build with root priviledge, and that the bundle file in `bin/Release` (bundle.config) does not have read permission for other users. (or one of the folder in the hierachy don't have the right permissions)

You can easily fix this problem by building btcpayserver from the non administrative user.

That said, if @rockstardev can fix it, it is fixable by instead of having a bundle.config file expected in the output of btcpay, instead you include it in the assembly as a resource.

**Comment by NicolasDorier** [comment]
Trying to fix it on the repo there

**Comment by NicolasDorier** [comment]
Ok actually I can solve it without changing upstream repo. Working on a fix.

**Comment by NicolasDorier** [comment]
@aantonop can you try to run on master, with the commit I just did? It should fix it if `bundlejscss` is set to `true`.

**Comment by rockstardev** [comment]
@Kukks the core problem is that Bundler needs to read that `bundleconfig.json` so that it can figure out what files are referenced. The in [`_Layout.cshtml`, line 29](https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Views/Shared/_Layout.cshtml#L29) we have:

`<bundle name="wwwroot/bundles/main-bundle.min.css" />`

And if bundling is turned on, it will spit out one reference (to generated file... for this we need write access to that directory - this happens during `dotnet build`). If bundling is off - it'll transform this one element into all the `script/link` references to individual fields.

I think @NicolasDorier is on exactly the right path here with those permissions and how `dotnet build` with non-administrative user will produce different results. And yes, @madskristensen gave me admin access to Bundler repository, so if you need something merged - lemme know @NicolasDorier.

**Comment by rockstardev** [comment]
OK, missing reference to `BundlerMinifier.Core` was what was causing the problem in some cases I guess:

https://github.com/btcpayserver/btcpayserver/commit/0578a692db119a4297ff168009fb46a77664382b#diff-6a9de8749b532027dc48bb5be3e83b03R39

If you pull and build with this latest commit @aantonop - it should work. Plus with fix @NicolasDorier has provided, we are now good with upgrading to .NET Core 2.2 when it's time. <3

**Comment by NicolasDorier** [comment]
Yep, I confirm it works for me now. :)
@aantonop if you use `bundlejscss` to `true` (as it should be normally), you won't have permission issue as I read the bundle.config directly from the resources of the assembly.

**Comment by aantonop** [comment]
It appears my setup is cursed by the "you should've used docker" daemons. 

Per https://github.com/btcpayserver/btcpayserver/issues/710#issuecomment-475865887
I built everything using the non-admin user, who also owns the datadir and the cloned code dir. Before starting, to make sure, I chown -R all the directories to the non-admin user. Still... no luck.

I pulled the latest master which included 

https://github.com/btcpayserver/btcpayserver/commit/f74f06338adaf6fe760a7fd2d9d86d0e558180ae

I cleaned the directory, pulled and built again (all using the non-admin user). All good. Run via systemctl, watch journal. Now I'm getting

a) with bundlejscss false, I get the same error
b) with bundlejscss true, I get a different error:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at BundlerMinifier.FileHelpers.NormalizePath(String path)
   at BundlerMinifier.FileHelpers.TrimTrailingPathSeparatorChar(String path)
   at BundlerMinifier.FileHelpers.DemandTrailingPathSeparatorChar(String path)
   at BundlerMinifier.TagHelpers.BundleTagHelper.GetSrc(String path)
   at BundlerMinifier.TagHelpers.BundleTagHelper.Process(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.TagHelpers.TagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.RunAsync(TagHelperExecutionContext executionContext)
   at AspNetCore.Views_Shared__Layout.<ExecuteAsync>b__44_0() in /usr/local/src/BTCPayServer/btcpayserver/BTCPayServer/Views/Shared/_Layout.cshtml:line 27
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
   at AspNetCore.Views_Shared__Layout.ExecuteAsync()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /usr/local/src/BTCPayServer/btcpayserver/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 55
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

```

**Comment by NicolasDorier** [comment]
So there is some progress! :)
@rockstardev any idea? The second error could come from my `ResourceBundleProvider`?

**Comment by NicolasDorier** [comment]
It comes from this

```FileHelpers.NormalizePath(_hostingEnvironment.WebRootPath.DemandTrailingPathSeparatorChar());```
Which mean `WebRootPath` is null which is very surprising.

**Comment by NicolasDorier** [comment]
@aantonop I need to manage to replicate this bug, can you tell me the output of

```
dotnet --version
```
as well as the version of your operating system?

**Comment by aantonop** [comment]
```
$ dotnet --version
2.1.505
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"

```

All packages up to date

**Comment by NicolasDorier** [comment]
dotnet version does not seems to show the sdk version. Well I will try to replicate with this.

**Comment by aantonop** [comment]
dotnet-sdk-2.1/xenial,now 2.1.505-1 amd64 [installed]
  Microsoft .NET Core SDK 2.1.505

**Comment by NicolasDorier** [comment]
@aantonop I tried brand new VM, manual install and it just worked.


Install Bitcoin Core 0.17.0

```bash
BITCOIN_VERSION="0.17.0"
BITCOIN_URL="https://bitcoincore.org/bin/bitcoin-core-0.17.0/bitcoin-0.17.0-x86_64-linux-gnu.tar.gz"
BITCOIN_SHA256="9d6b472dc2aceedb1a974b93a3003a81b7e0265963bd2aa0acdcb17598215a4f"

# install bitcoin binaries
cd /tmp
wget -O bitcoin.tar.gz "$BITCOIN_URL"
echo "$BITCOIN_SHA256 bitcoin.tar.gz" | sha256sum -c - && \
mkdir bin && \
sudo tar -xzvf bitcoin.tar.gz -C /usr/local/bin --strip-components=2 "bitcoin-$BITCOIN_VERSION/bin/bitcoin-cli" "bitcoin-$BITCOIN_VERSION/bin/bitcoind"
rm bitcoin.tar.gz
```

Install .NET Core SDK 2.1:
On my ubuntu 16.04: (See [those instructions](https://dotnet.microsoft.com/download/linux-package-manager/ubuntu16-04/sdk-2.1.505) for different OS).

```bash
wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo apt-get install apt-transport-https
sudo apt-get update
sudo apt-get install -y dotnet-sdk-2.1
```

Install NBXplorer

```bash
cd ~
git clone https://github.com/dgarage/NBXplorer
cd NBXplorer
git checkout latest
./build.sh
```

Install BTCPayServer

```bash
cd ~
git clone https://github.com/btcpayserver/btcpayserver
cd btcpayserver
git checkout latest
./build.sh
```


Run bitcoind:

```bash
nohup bitcoind &
```

Run nbxplorer:

```bash
cd ~/NBXplorer
nohup ./run.sh &
```

Run BTCPayServer:

```bash
cd ~/btcpayserver
nohup ./run.sh --port 8080 --bind 0.0.0.0 &
```

Now you can browse your server on port 8080.

Can you repro this?

**Comment by NicolasDorier** [comment]
PS: I tried with a non root user.

**Comment by aantonop** [comment]
I managed to isolate the problem to the systemd start script. I copied from the run.sh contents and this command line worked:
```
ExecStart=/usr/bin/dotnet run --no-launch-profile --no-build -c Release -p "BTCPayServer/BTCPayServer.csproj" --conf /data/btcpayserver/btcpayserver.conf --datadir /data/btcpayserver/

```

The problem was all in how I launched BTCPay from systemd. I had copied the systemd from one of the tutorials, and it didn't work.

**Comment by Kukks** [comment]
So are you now: https://media.giphy.com/media/Ae7SI3LoPYj8Q/giphy.gif ?

**Comment by NicolasDorier** [comment]
@aantonop can you tell us which tutorial you followed so we can fix the tutorial?

That said, I need to investigate why you got the problem at all.

**Comment by chill117** [comment]
I had a similar issue as @aantonop:
* Internal server error with a blank white screen
* In the logs on the server: `System.NullReferenceException: Object reference not set to an instance of an object.` with a very similar stack trace as above.

My setup includes a custom Dockerfile to build the btcpayserver image with docker-compose. The important bits in the first attempt Dockerfile:
```
...

# Build btcpayserver from source:
RUN cd ./BTCPayServer \
	&& dotnet publish --output /app/ --configuration Release

...

CMD ["dotnet", "/app/BTCPayServer.dll"]
```

And the important bits from the final Dockerfile that worked:
```
...

# Build btcpayserver from source:
RUN cd ./BTCPayServer \
	&& dotnet publish --output /app/ --configuration Release

...

# !! IMPORTANT !!
# Required to prevent internal server errors caused by file path problems in app:
WORKDIR /app

CMD ["dotnet", "BTCPayServer.dll"]
```
Note the `WORKDIR` directive and the path change in the CMD directive.
