### ISSUE TITLE
[v1.0.3.93] Error writing frame - The WebSocket is in an invalid state ('Aborted')

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver#761]
**Describe the problem/bug**
I have not noticed anything unusual happening but BTCPay logs are throwing a weird error.

**Your environment**
* Version of BTCPay Server:  v1.0.3.93
* Deployment method:  Docker, LunaNode
* Other relevant environment details:

**Logs (if applicable)**
```
019-04-13 10:34:13.822 +00:00 [ERR] Error writing frame.
System.Net.WebSockets.WebSocketException (0x80004005): The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Open, CloseReceived'
   at System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, Boolean isDisposed, WebSocketState[] validStates)
   at System.Net.WebSockets.ManagedWebSocket.SendPrivateAsync(ReadOnlyMemory`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.WebSockets.WebSocketExtensions.SendMultiSegmentAsync(WebSocket webSocket, ReadOnlySequence`1 buffer, WebSocketMessageType webSocketMessageType, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport.StartSending(WebSocket socket)
```

```
fail: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Error writing frame.
System.Net.WebSockets.WebSocketException (0x848A5400): The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Open, CloseReceived'
   at System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, Boolean isDisposed, WebSocketState[] validStates)
   at System.Net.WebSockets.ManagedWebSocket.SendPrivateAsync(ReadOnlyMemory`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.WebSockets.WebSocketExtensions.SendMultiSegmentAsync(WebSocket webSocket, ReadOnlySequence`1 buffer, WebSocketMessageType webSocketMessageType, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport.StartSending(WebSocket socket)
info: Events:         Invoice 2gnGUH7nEpBw2FcLdFxntp new event: invoice_created (1001)
info: Events:         Invoice DsbBhJ3Zu4mf5Lbf3zPrBn new event: invoice_created (1001)
fail: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Error writing frame.
System.Net.WebSockets.WebSocketException (0x80004005): The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Open, CloseReceived'
   at System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, Boolean isDisposed, WebSocketState[] validStates)
   at System.Net.WebSockets.ManagedWebSocket.SendPrivateAsync(ReadOnlyMemory`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.WebSockets.WebSocketExtensions.SendMultiSegmentAsync(WebSocket webSocket, ReadOnlySequence`1 buffer, WebSocketMessageType webSocketMessageType, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport.StartSending(WebSocket socket)
info: Events:         Invoice DNo8LXShoEd8jqA3x9a1YW new event: invoice_created (1001)
info: Events:         Invoice 8joAuxidjd7oQhhuNLpmtA new event: invoice_created (1001)
fail: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Error writing frame.
System.Net.WebSockets.WebSocketException (0x80004005): The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Open, CloseReceived'
   at System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, Boolean isDisposed, WebSocketState[] validStates)
   at System.Net.WebSockets.ManagedWebSocket.SendPrivateAsync(ReadOnlyMemory`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.WebSockets.WebSocketExtensions.SendMultiSegmentAsync(WebSocket webSocket, ReadOnlySequence`1 buffer, WebSocketMessageType webSocketMessageType, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport.StartSending(WebSocket socket)
```

**Comment by pavlenex** [comment]
A bit more follow up
![Screen Shot 2019-04-15 at 12 18 56](https://user-images.githubusercontent.com/36959754/56125300-df628200-5f78-11e9-9977-ea06d9a8d51f.png)
![Screen Shot 2019-04-15 at 12 19 08](https://user-images.githubusercontent.com/36959754/56125301-dffb1880-5f78-11e9-97be-17a36a5fd9bf.png)
![Screen Shot 2019-04-15 at 12 19 23](https://user-images.githubusercontent.com/36959754/56125326-f1442500-5f78-11e9-8dbc-3b0dcf162895.png)

**Comment by pavlenex** [comment]
According to @Kukks

> it looks like a user on the crowdfund had a connection issue and couldn't get the live updates from crowdfund

Also, he says it's nothing to worry about, so if someone experiences the same problem, complain to @Kukks here and we'll re-open the issue.

The issue is related to #762
