### ISSUE TITLE
Crowdfund animations and sounds not playing

### ISSUE THREAD

**Issue by radWorx** [btcpayserver/btcpayserver#902]
**Describe the problem/bug**
CF App animations and sounds are broken. No fireworks and no sounds when payment received. 

**Your environment**
* Version of BTCPay Server: 1.0.3.116/118
* Deployment method: Local Regtest
* Other relevant environment details: Dev Env
*Also Tested on mainnet.demo and testnet.demo: https://mainnet.demo.btcpayserver.org/apps/3Zb3uaudAVN51EBern6iXEgbqmHH/crowdfund
https://testnet.demo.btcpayserver.org/apps/4KLG2xcZxc1CqGiEvapCNHeFbYH3/crowdfund

**Logs (if applicable)**
warn: PayServer:      Unhandled exception in AppHubStreamer
System.ArgumentException: The value passed in must be an enum base or an underlying type for an enum, such as an Int32.
Parameter name: value
   at System.RuntimeType.GetEnumName(Object value)
   at BTCPayServer.Services.Apps.AppHubStreamer.ProcessEvent(Object evt, CancellationToken cancellationToken) in T:\btcpayserver-1.0.3.116\btcpayserver-1.0.3.116\BTCPayServer\Services\Apps\AppHubStreamer.cs:line 55
   at BTCPayServer.HostedServices.EventHostedServiceBase.ProcessEvents(CancellationToken cancellationToken) in T:\btcpayserver-1.0.3.116\btcpayserver-1.0.3.116\BTCPayServer\HostedServices\EventHostedServiceBase.cs:line 33

**To Reproduce**
1.Make donation to Crowdfund
2.Payment succeeds, no animation nor sounds

**Expected behavior**
Fireworks animations and sounds should play.

**Actual behavior**
Modal shows Invoice is paid, but no animations or sound.

**Comment by britttttk** [comment]
I'm able to reproduce this issue also

**Comment by radWorx** [comment]
Getting same errors logged with Point of Sale.
